### ISSUE TITLE
GPT4-V

### ISSUE THREAD

**Issue by rakesh-purohit9** [mckaywrigley/chatbot-ui#1001]
Any plan to add GPT 4 vision support to upload images?

**Comment by nirbenda** [comment]
Upvoting, after Open AI Dev Day, it is now possible using the API, and rather simple to implement.

**Comment by rakesh-purohit9** [comment]
@mckaywrigley

**Comment by Reza-Kabiri** [comment]
Dear @mckaywrigley please add GPT-4 Vision. I'm already using your amazing code on a personal Vercel deploy. And now I need to use it for GPT-4V API as well. Thanks in advance

**Comment by Nymbo** [comment]
+1 BIG fan of chatbotUI, pls add support for GPT-4-V

**Comment by jeffgyf** [comment]
I have implemented it
![Screenshot 2023-12-13 183236](https://github.com/mckaywrigley/chatbot-ui/assets/16674327/1e27ef6f-2fa1-46a3-8681-54c84be57995)
![Screenshot 2023-12-13 183245](https://github.com/mckaywrigley/chatbot-ui/assets/16674327/0f6cefa1-5818-4d4d-bf36-192af8ded60d)
