### ISSUE TITLE
Will Code Interpreter be available in the future?

### ISSUE THREAD

**Issue by o-mo-ty** [mckaywrigley/chatbot-ui#1009]
Will Code Interpreter be available in the future?

**Comment by davidmoore-io** [comment]
Integration of Open Interpreter would be possible I guess - https://github.com/KillianLucas/open-interpreter - which would give broadly the same capability.

I don't see OpenAI ever open sourcing their plugins, which is probably unwise but 🤷

**Comment by fkesheh** [comment]
There are some forks that have it already.

Em dom., 5 de nov. de 2023 07:11, David Moore ***@***.***>
escreveu:

**Comment by GEMTechnologies** [comment]
@fkesheh can u give me any link to such a fork
