### ISSUE TITLE
Automatically naming convesation title

### ISSUE THREAD

**Issue by khairulhaaziq** [mckaywrigley/chatbot-ui#101]
Hi @mckaywrigley have you considered making this, any idea how would you do it? If it's not in the works, I want to try making it

**Comment by mckaywrigley** [comment]
I've considered it but want to keep user API requests down for now. I may revisit it soon.

**Comment by khairulhaaziq** [comment]
> I've considered it but want to keep user API requests down for now. I may revisit it soon.

I like the current method where it picks the last prompt, I think is is better though than what openAI does, I think we always somehow run off topic from the first prompt(where it generates the title) and cant remember what is it about.
