### ISSUE TITLE
implemented GPT-4 Vision support

### ISSUE THREAD

**Issue by jeffgyf** [mckaywrigley/chatbot-ui#1035]
I have implemented the support of GPT-4 Vision and submitted the PR https://github.com/mckaywrigley/chatbot-ui/pull/1034.
You can preview it in my forked repo before the PR is merged https://github.com/jeffgyf/chatbot-ui/tree/main
![Screenshot 2023-12-13 183236](https://github.com/mckaywrigley/chatbot-ui/assets/16674327/1e27ef6f-2fa1-46a3-8681-54c84be57995)
![Screenshot 2023-12-13 183245](https://github.com/mckaywrigley/chatbot-ui/assets/16674327/0f6cefa1-5818-4d4d-bf36-192af8ded60d)

**Comment by Bortus-AI** [comment]
Fantastic!

**Comment by hikafeng** [comment]
A version that can be successfully deployed https://github.com/HikaFeng/HikaGPT

**Comment by Manojbhat09** [comment]
Has this been merged?

**Comment by Dreaming-Codes** [comment]
> Has this been merged?

Vision support will be a thing with 2.0

**Comment by nguyenvulong** [comment]
edited: not sure why but after I restarted the `npm run chat` several times then the vision model showed up. Thanks.
---
it's not merged right? I couldn't find the option for GPT 4 vision in the self-hosted chatbot-ui.
