### ISSUE TITLE
Using the google search feature

### ISSUE THREAD

**Issue by arksenu** [mckaywrigley/chatbot-ui#1041]
During runtime on the app, whenever trying to use the google search feature, I get hit with a page showing me

Unhandled Runtime Error
TypeError: undefined is not an object (evaluating 'selectedConversation.messages.length')
Call Stack
dispatchEvent

[native code]

That's it though. Theres no other information and the console doesn't seem to output any error messages. I definitely have GOOGLE_CSE_ID and GOOGLE_API_KEY set in the env.local.

**Comment by arksenu** [comment]
not completed but ok

**Comment by Fakamoto** [comment]
@arksenu is there a google search feature? where?
