### ISSUE TITLE
Waiting for v2 😄

### ISSUE THREAD

**Issue by 0-hero** [mckaywrigley/chatbot-ui#1044]

**Comment by cd-yang** [comment]
Waiting

**Comment by mgsotelo** [comment]
Waiting

**Comment by secondtruth** [comment]
see https://github.com/mckaywrigley/chatbot-ui/commit/403d2b71ca8eba4184503287558de67b0e97ae02

**Comment by 0-hero** [comment]
yes saw that

**Comment by tim-brand** [comment]
*keeps refresing for launch*

**Comment by mgsotelo** [comment]
still waiting

**Comment by Nymbo** [comment]
keep refreshing boys

**Comment by mindcont** [comment]
waiting

**Comment by slopesweb** [comment]
😄

**Comment by nicekate** [comment]
waiting

**Comment by cloud-on-prem** [comment]
Folks, I understand the enthusiasm. I am eagerly awaiting the release as well. 
But as we all can appreciate, juggling open-source commitments with other priorities can be challenging. Let's be respectful to the author's time here. 

By commenting on the issue, all we are doing is spamming the author. (which ironically, this comment does as well)

If you want to show your support, may I respectfully ask you to star the repo or react with an emoji on the issue (which BTW is also not a real "issue" to begin with 😛)

🙏 ❤️

**Comment by 0-hero** [comment]
https://x.com/mckaywrigley/status/1742750780023779532?s=46&t=ZC6wgu7iLucRMVlNeDgmYQ
