### ISSUE TITLE
Don't wait any longer; the project release has been postponed again. It's really frustrating; I've been waiting for a whole week already.

### ISSUE THREAD

**Issue by hikafeng** [mckaywrigley/chatbot-ui#1047]
![image](https://github.com/mckaywrigley/chatbot-ui/assets/76583915/02627c7a-9c53-4e62-bfdc-ec5810b947c9)
A little under the weather and would like to be 100% for launch as it’ll be fairly demanding, so pushing back a couple days. Friday or Monday - probably the latter. Everything is done though.

**Comment by xiaos911** [comment]
Very regrettable

**Comment by maddes8cht** [comment]
Well, it's ready when it's ready.
However, for the waiting people it's really frustrating to HAVE something like a "deadline" that gets postponed several times at the very moment when the release was scheduled.
If possible, postpone earlier.
Make more reliable anouncements.
And maybe, if people are waiting for it:
Make an alpha release or a beta release so people have  at least ANYTHING.
Things can always be improved.
There is no such thing as a "perfect" release.

**Comment by vmldude** [comment]
Well said maddes8cht

**Comment by twf-nikhila** [comment]
The fact that this project is open source & free is truly remarkable. I think instead of criticising we should respect @mckaywrigley for making it open-source

**Comment by maddes8cht** [comment]
@twf-nikhila I fully agree, and i forgot to mention that.
Yes, always, i should have also added a BIG and LOUD "Thank you" for the great work !

Anyways, there is always room for improvements, and exposing oneself with a project like this always includes the option to give constructive criticism.
Given that:
At this point, i would have loved to get an alpha- or beta release mentioning the current problems that still needs to be resolved.

Again:
Love this project.
Thanks for the great Work.
I'm caring for it, so i'm eagerly waiting for the rlease.

**Comment by enricoros** [comment]
You should check out other projects as well, such as https://github.com/enricoros/big-agi :)

**Comment by MrBenzWorld** [comment]
> You should check out other projects as well, such as https://github.com/enricoros/big-agi :)

Thank you, it is great . I was using llama models for months and I used all which are mentioned  by #thebloke,but I did not know about it. This is the best chat ui with a clean and clear interface. 
@enricoros

**Comment by twf-nikhila** [comment]
This looks amazing, thanks for sharing it @enricoros

**Comment by jonschlinkert** [comment]
Lol, @mckaywrigley I hope you know how much you are loved by the community. You don't get issues like this unless people love what you're doing. The sentiment in this thread is excitement, not anger. Like a kid waiting to open presents. 

You're doing an amazing job, please keep doing what you do.

**Comment by MrBenzWorld** [comment]
> Lol, @mckaywrigley I hope you know how much you are loved by the community. You don't get issues like this unless people love what you're doing. The sentiment in this thread is excitement, not anger. Like a kid waiting to open presents. 
> 
> You're doing an amazing job, please keep doing what you do. 

It's true, it is the excitement and in  @mckaywrigley great work. 

There are a number of alternatives but this is important and fills all the gaps.

**Comment by AndrewsPanda** [comment]
Looking forwards to the release! Is there an update on when it's likely to roll out now?

**Comment by Bortus-AI** [comment]
> Looking forwards to the release! Is there an update on when it's likely to roll out now?

6pm Pacific Time

**Comment by Jdban** [comment]
Well he just force pushed to main, so I think it's live...

**Comment by JohanVonFiedler** [comment]
Thanks for waiting to get this thing right before launching @mckaywrigley.  For real - all your work is much appreciated.

**Comment by JohanVonFiedler** [comment]
![920e2ffe2bf5254897c49ab6dff13861](https://github.com/mckaywrigley/chatbot-ui/assets/128096011/e0f0d657-2707-4508-8acd-a9af7ecfc6de)

**Comment by Elijas** [comment]
Wait, so the whole old v1 project history was deleted?

**Comment by Jdban** [comment]
LOL when he force pushed to main he deleted the entire history of the original... jesus christ...

**Comment by Elijas** [comment]
@Jdban 
Yeah, I think the better approach would be to at least just create a commit with all files deleted and replaced with new files
Really no need to delete history

**Comment by Jdban** [comment]
> Yeah, I think the better approach would be to at least just create a commit with all files deleted and replaced with new files
> Really no need to delete history

The guy running this repo has repeatedly proven that he has no idea how to work with others. He releases something, abandons it for months, refuses to add any maintainers, then comes in and blasts away all the old history

**Comment by knoopx** [comment]
@Jdban the readme said he will move the old codebase into a new repo and replace this one with the latest.

**Comment by mckaywrigley** [comment]
> Well, it's ready when it's ready. However, for the waiting people it's really frustrating to HAVE something like a "deadline" that gets postponed several times at the very moment when the release was scheduled. If possible, postpone earlier. Make more reliable anouncements. And maybe, if people are waiting for it: Make an alpha release or a beta release so people have at least ANYTHING. Things can always be improved. There is no such thing as a "perfect" release.

This is valid criticism, and I agree that I botched the delay stuff.

In hindsight I wish I would've just not said anything and dropped it - people got excited and the delays got annoying.

Lesson learned, and thanks for your patience!

**Comment by Elijas** [comment]
Does anybody have the old source code? v2 is not working yet (as docker) and v1 has been deleted 👀

**Comment by Elijas** [comment]
> > Well, it's ready when it's ready. However, for the waiting people it's really frustrating to HAVE something like a "deadline" that gets postponed several times at the very moment when the release was scheduled. If possible, postpone earlier. Make more reliable anouncements. And maybe, if people are waiting for it: Make an alpha release or a beta release so people have at least ANYTHING. Things can always be improved. There is no such thing as a "perfect" release.
> 
> This is valid criticism, and I agree that I botched the delay stuff.
> 
> In hindsight I wish I would've just not said anything and dropped it - people got excited and the delays got annoying.
> 
> Lesson learned, and thanks for your patience!

@mckaywrigley Thanks for everything, we appreciate it! We all understand that software release timelines can be tricky sometimes.

Could you share a bit on what's the reasoning behind force-push wiping old history instead of it the v2 being a commit on top? I.e. one big commit that "deletes everything and adds all v2 code as initial starting point"

**Comment by briankelley** [comment]
The amount of entitlement and complaining in this thread for FOSS is staggering. I'm just happy to have the new version available and grateful for @mckaywrigley's work.

**Comment by Jdban** [comment]
> The amount of entitlement and complaining in this thread for FOSS is staggering. I'm just happy to have the new version available and grateful for @mckaywrigley's work.

All I've want is the guy to offload some work to the willing community and stop ignoring everyone.
And not do stupid shit like force push away the main branch of a repo that has 6000 forks.

**Comment by enricoros** [comment]
> force push away the main branch of a repo that has 6000 forks

LOL :D
