### ISSUE TITLE
Toaster message UI

### ISSUE THREAD

**Issue by nayansinghal23** [mckaywrigley/chatbot-ui#1048]
Video URL -> https://screenpal.com/watch/cZV1iYVHmBP

The UI of error thrown on sending data to Chatbot is incorrect. Basically, the width of error thrown by Toaster is small compared to the data present inside it.
![toaster-ui](https://github.com/mckaywrigley/chatbot-ui/assets/96867955/2c24eda2-517b-42b2-b7ba-a0f92e7f97bc)

**Comment by tanish-malekar** [comment]
If a PR for this has been closed, why is this issue still open?
