### ISSUE TITLE
UI asks for api key even when one is set on the server side

### ISSUE THREAD

**Issue by thomasleveil** [mckaywrigley/chatbot-ui#105]
There is a regression since https://github.com/mckaywrigley/chatbot-ui/commit/83217c6d83e65b4400f5ab408d0cef9ccfc3c8c5, It is now impossible to use the UI wihtout setting an API on the UI, even if an API key is set on the server side.

(or did I miss something ?)

**Comment by mckaywrigley** [comment]
Shoot a branch must've gotten messed up. Thought that was pushed. I'll get that fixed!

**Comment by mckaywrigley** [comment]
This should be fixed now. Will wait for confirmation.

**Comment by thomasleveil** [comment]
using ad2e1f0, and providing the key with the `OPENAI_API_KEY` environment variable, I have the following error : 
![image](https://user-images.githubusercontent.com/42300/227456580-854bbf6f-db38-4330-9ffd-680f76853cc9.png)
![image](https://user-images.githubusercontent.com/42300/227456614-30871f04-bd55-4f2a-ac4b-548df800b629.png)

**Comment by VincentChou1995** [comment]
I have encountered the same issue as well，when I open localhost:3000
![image](https://user-images.githubusercontent.com/34445274/227690908-90a28da0-9b92-4deb-90ff-75feaae230cd.png)
