### ISSUE TITLE
Error: Invalid Server Actions request.

### ISSUE THREAD

**Issue by 0smboy** [mckaywrigley/chatbot-ui#1052]
after login the chatbot ui, i meet this error:
<img width="1037" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/91452062/e772bb28-06b0-40fe-a7c4-46592ac004ca">

**Comment by greagain** [comment]
What's the default user/pass, or if there is any? I get exactly the same error after input random user/pass

**Comment by wrapss** [comment]
try clear ur cookie

**Comment by wrapss** [comment]
> What's the default user/pass, or if there is any? I get exactly the same error after input random user/pass

try clear website cookies

**Comment by greagain** [comment]
Just update: after update next.js, the error message said the version 14.0.2 is outdated, I am able to pass the login step, though there are still other problems.
