### ISSUE TITLE
can we use cloud Supabase service?

### ISSUE THREAD

**Issue by xycjscs** [mckaywrigley/chatbot-ui#1055]
It is easy to create a free Supabase project.
URL, KEY, ROLE KEY are available from the supabase.com.

I am using RHEL8 system. Docker desktop is not available, which is essential by Supabase. 

failed to inspect database container: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/supabase_db_chatbotui/json": dial unix /var/run/docker.sock: connect: permission denied

**Comment by ApiskeyC** [comment]
A version that can be deployed to Vercel and supabase.com in the cloud is available for trial on the web. don't need a local machine. From https://github.com/ApiskeyC/chatbot-ui

**Comment by mckaywrigley** [comment]
We will have a tutorial on this soon, but yes!
