### ISSUE TITLE
Error: Invalid Server Actions Request due to Header Mismatch (x-forwarded-host and origin)

### ISSUE THREAD

**Issue by jony4** [mckaywrigley/chatbot-ui#1057]
✓ Compiled /login in 4.9s (1265 modules)
 ✓ Compiled in 516ms (716 modules)
`x-forwarded-host` header with value `localhost:3000` does not match `origin` header with value `10.151.157.27:3000` from a forwarded Server Actions request. Aborting the action.
 ⨯ Error: Invalid Server Actions request.
    at AsyncLocalStorage.run (node:async_hooks:345:14)
    at AsyncLocalStorage.run (node:async_hooks:345:14)

**Comment by Guerdal** [comment]
Same here

The machine where chatbot-ui is deployed is a server with my GPUs.

I access from another machine.

I think that the default configuration only authorize an access to localhost

But where change that ?

**Comment by wrapss** [comment]
supabase is installed on which machine? the address set in the .env evolves accordingly.

**Comment by Guerdal** [comment]
For my part, supabase is installed in a docker on the same machine that runs Chatbot-ui.

**Comment by wrapss** [comment]
so in your environment file NEXT_PUBLIC_SUPABASE_URL is the ipv4 of the machine on which supabase is installed, not localhost?

**Comment by Guerdal** [comment]
Content of my .env.local

```
# Supabase Public
NEXT_PUBLIC_SUPABASE_URL=http://192.168.42.173:8000
NEXT_PUBLIC_SUPABASE_ANON_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# Supabase Private
SUPABASE_SERVICE_ROLE_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# Ollama
NEXT_PUBLIC_OLLAMA_URL=http://192.168.42.173:11434 # Default


```
192.168.42.173 is the IP of my GPUs Server (AI specific machine)

I connect to it from another machine :-)

If I connect via a ssh tunnel,

`ssh -f user_ai_server@192.168.42.173 -L 3000:localhost:3000 -N
`
the server accept my connexion via http://localhost:3000 (on my machine)

**Comment by wrapss** [comment]
and if you try to launch chatbot-ui with the command npx next dev -H 0.0.0.0 and access it without ssh tunnel?

**Comment by Guerdal** [comment]
:-(

```
npx next dev -H 0.0.0.0
   ▲ Next.js 14.0.2
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000
   - Environments: .env.local, .env

 ✓ Ready in 2.4s
 ✓ Compiled /middleware in 130ms (124 modules)
 ○ Compiling / ...
request to https://fonts.gstatic.com/s/inter/v13/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2pL7W0Q5n-wU.woff2 failed, reason: 

Retrying 1/3...
request to https://fonts.gstatic.com/s/inter/v13/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2pL7W0Q5n-wU.woff2 failed, reason: 

Retrying 2/3...
 ✓ Compiled / in 4.8s (1226 modules)
 ✓ Compiled in 327ms (714 modules)
 ○ Compiling /chat ...
 ✓ Compiled /chat in 4.6s npx next dev -H 0.0.0.0
   ▲ Next.js 14.0.2
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000
   - Environments: .env.local, .env

 ✓ Ready in 2.4s
 ✓ Compiled /middleware in 130ms (124 modules)
 ○ Compiling / ...
request to https://fonts.gstatic.com/s/inter/v13/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2pL7W0Q5n-wU.woff2 failed, reason: 

Retrying 1/3...
request to https://fonts.gstatic.com/s/inter/v13/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2pL7W0Q5n-wU.woff2 failed, reason: 

Retrying 2/3...
 ✓ Compiled / in 4.8s (1226 modules)
 ✓ Compiled in 327ms (714 modules)
 ○ Compiling /chat ...
 ✓ Compiled /chat in 4.6s (3612 modules)
 ○ Compiling /login ...
 ✓ Compiled /login in 1326ms (3637 modules)
`x-forwarded-host` header with value `0.0.0.0:3000` does not match `origin` header with value `192.168.42.173:3000` from a forwarded Server Actions request. Aborting the action.
 ⨯ Error: Invalid Server Actions request.
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at AsyncLocalStorage.run (node:async_hooks:346:14)(3612 modules)
 ○ Compiling /login ...
 ✓ Compiled /login in 1326ms (3637 modules)
`x-forwarded-host` header with value `0.0.0.0:3000` does not match `origin` header with value `192.168.42.173:3000` from a forwarded Server Actions request. Aborting the action.
 ⨯ Error: Invalid Server Actions request.
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at AsyncLocalStorage.run (node:async_hooks:346:14)

```

**Comment by tirthpatell** [comment]
@jony4 @Guerdal Follow this [example](https://github.com/mckaywrigley/chatbot-ui/issues/1117#issuecomment-1887920236).

I had the same issue. Add the URLs you want access from in the `next.config.js` file. Though you must make sure the client device/IP has access to the device/IP supabase is hosted on. Else it will throw different error when you first try to signup/login. I use it outside the network using proxy, so I also had to proxy the DB and provide that DB url in env for `NEXT_PUBLIC_SUPABASE_URL`.

See my image as example

***next.config.js***
![CleanShot 2024-01-16 at 20 21 38@2x](https://github.com/mckaywrigley/chatbot-ui/assets/32465104/fdd5e272-492f-40fc-829b-86253e3aa903)

***.env.local***
![CleanShot 2024-01-16 at 20 25 07@2x](https://github.com/mckaywrigley/chatbot-ui/assets/32465104/6b375a9e-ce7d-4e5c-9d3b-918ef4158080)

**Comment by jony4** [comment]
@tirthpatell Thanks for your message, let me give it a try.

**Comment by Somnus1437** [comment]
This new version is too difficult to set up and runs with too many lags compared to the ui1.0 version.
