### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by ghost** [mckaywrigley/chatbot-ui#1058]
A version that can be deployed to Vercel and supabase.com in the cloud is available for trial on the web. don't need a local machine.
From https://github.com/ApiskeyC/chatbot-ui

**Comment by ghost** [comment]
[apiskey.com](https://apiskey.com/)

**Comment by Bortus-AI** [comment]
How do we use Ollama with apiskey.com or with your fork? I tried adding the env in vercel for ollama but models do not show up

**Comment by ghost** [comment]
Because ollama is a local model that requires a GPU server for deployment, and considering that Vercel does not provide GPUs and due to cost issues, apiskey has removed ollama. If you want to use it, you can fork the original chatbotui 2.0 and deploy it locally.

**Comment by Bortus-AI** [comment]
I have a dedicated server with a gpu in a data center so I was hoping to point to it from vercel. Thanks for the quick reply

**Comment by ghost** [comment]
"You can fork the original chatbotui 2.0 and replace its package.json file with my package.json file. Additionally, add the environment variable, NEXT_PUBLIC_OLLAMA_URL, on Vercel. Don't forget to override the npm install and integrate Supabase into Vercel. For this step, you can refer to the readme section of my repository."

**Comment by Bortus-AI** [comment]
I tried that but still not able to show the ollama models. I'll see if anything shows in the logs

**Comment by Bortus-AI** [comment]
Nothing in the logs and ollama server is detecting a curl or any type of attempt from the vercel deployment. Maybe not fully implemented or working yet with chatbot 2.0

**Comment by ghost** [comment]
Thirty minutes ago, the original version was fixed for the Ollama route on hosted services. You can try the latest version now. Good luck. It's time for me to sleep, as it's 23:58.

**Comment by Bortus-AI** [comment]
Yeah I saw that and no change but will keep working on it. Sleep well!

**Comment by Bortus-AI** [comment]
#1062 Fixed it
