### ISSUE TITLE
How integrated is Supabase? How difficult would it be to replace it with RDS?

### ISSUE THREAD

**Issue by Bermpje** [mckaywrigley/chatbot-ui#1059]
As the title states. How integrated is all this with Supabase? Because I really liked the previous version it runs lean and mean in AWS. I like the new functional features, but I don't want to deploy Supabase into AWS. It is just to much management hassle. 

I'd like to instead use RDS, but it's unclear to me how much work it would take to migrate away from Supasebase to AWS RDS for the database. Can anybody provide some insights.

**Comment by mckaywrigley** [comment]
Shouldn't be that difficult. We will likely support Amazon RDS and Google Cloud SQL relatively soon.

At its core it's just Postgres.

Focus right now is just getting things working locally.

FWIW hosting on Supabase is extremely straightforward (we will have a guide soon), but I totally understand wanting to use your preferred cloud provider.

**Comment by Bermpje** [comment]
For your understanding, I am willing to do the work to make it run on RDS. But wanted an idea upfront of how feasible it is.

**Comment by mckaywrigley** [comment]
Got it. I don't have a great answer for you yet other than we'll support it hopefully by the end of the month.

**Comment by cocktailpeanut** [comment]
> Focus right now is just getting things working locally.

@mckaywrigley thank you for your work. Since you said you had plans to do other DBs like RDS AND also mentioned your focus is on getting it to work locally, just wanted to share my quick thought about local.

IMO, while hosted databases like supabase (powered by postgresql) or RDS as backend are powerful, I think it's too heavy for a "local first AI" stack.

Any plans to implement this in SQLite or DuckDB, or any of the file base database systems instead?

If you do it that way, not only is it significantly lighter than postgres, but also should even be able to deploy the DBs directly to the edge even when hosting remotely with no hosted database systems. There are sites with hundreds of thousands of users running on a single SQLite database file. I think SQLite/DuckDB are more than enough for private local LLM.

Just wanted to throw it out there because I've been waiting for your release because I've been primarily interested in running this 100% locally, but postgres + docker + etc. feels too heavy for a regular person, not just in terms of difficulty but also in terms of efficiency.

**Comment by AI-egroup-bwaite** [comment]
+1 for RDS! I'll do my best to find some free time this weekend to test this.

**Comment by Bermpje** [comment]
@AI-egroup-bwaite if you need help or need another tester, feel free to hit me up!

I am in the CET timezone.

**Comment by mallapraveen** [comment]
> > Focus right now is just getting things working locally.
> 
> @mckaywrigley thank you for your work. Since you said you had plans to do other DBs like RDS AND also mentioned your focus is on getting it to work locally, just wanted to share my quick thought about local.
> 
> IMO, while hosted databases like supabase (powered by postgresql) or RDS as backend are powerful, I think it's too heavy for a "local first AI" stack.
> 
> Any plans to implement this in SQLite or DuckDB, or any of the file base database systems instead?
> 
> If you do it that way, not only is it significantly lighter than postgres, but also should even be able to deploy the DBs directly to the edge even when hosting remotely with no hosted database systems. There are sites with hundreds of thousands of users running on a single SQLite database file. I think SQLite/DuckDB are more than enough for private local LLM.
> 
> Just wanted to throw it out there because I've been waiting for your release because I've been primarily interested in running this 100% locally, but postgres + docker + etc. feels too heavy for a regular person, not just in terms of difficulty but also in terms of efficiency.

+ 1 it would be better if we have lighter db than going thru docker and stuff.

**Comment by dsprahul** [comment]
> > Focus right now is just getting things working locally.
> 
> @mckaywrigley thank you for your work. Since you said you had plans to do other DBs like RDS AND also mentioned your focus is on getting it to work locally, just wanted to share my quick thought about local.
> 
> IMO, while hosted databases like supabase (powered by postgresql) or RDS as backend are powerful, I think it's too heavy for a "local first AI" stack.
> 
> Any plans to implement this in SQLite or DuckDB, or any of the file base database systems instead?
> 
> If you do it that way, not only is it significantly lighter than postgres, but also should even be able to deploy the DBs directly to the edge even when hosting remotely with no hosted database systems. There are sites with hundreds of thousands of users running on a single SQLite database file. I think SQLite/DuckDB are more than enough for private local LLM.
> 
> Just wanted to throw it out there because I've been waiting for your release because I've been primarily interested in running this 100% locally, but postgres + docker + etc. feels too heavy for a regular person, not just in terms of difficulty but also in terms of efficiency.

I will get started on implementing the `SQLite` backend over the weekend. I am not sure if that's the best flat-file DB choice and it depends on the rest of the stack being used.

**Comment by jackgofff** [comment]
How hard would it be to shift to **_noSQL (e.g. MongoDB)?_** 
Curious why you chose SQL and/or if you think a specific combo of the two can be useful.
