### ISSUE TITLE
Docker deployment

### ISSUE THREAD

**Issue by henrywithu** [mckaywrigley/chatbot-ui#1060]
Thanks for the open source project. The v1 did inspire me a lot.
It will be appreciated if you can provide a Dockerfile for v2 asap.

**Comment by Elijas** [comment]
Does anybody have the old source code?

**Comment by kaaboaye** [comment]
https://github.com/mckaywrigley/chatbot-ui/forks

**Comment by dm3n** [comment]
we need a docker run !!!!!!

**Comment by mckaywrigley** [comment]
Working on this at the moment. Be live soon.

**Comment by henrywithu** [comment]
> Working on this at the moment. Be live soon.

Thanks bro.
Just wanna say that there is no "perfect release". You already are one of the pioneers of Web-UI by open source v1. Don't push yourself too hard, as currently there are tons of similar projects. Feel free to take some rest and develop what you think is the best. 😉

**Comment by skorokithakis** [comment]
A Compose file for v2 would be appreciated as well, but that's something I can submit a PR for if an official Docker image is uploaded.

**Comment by Digital39999** [comment]
Would be neat if you include Supabase in the docker-compose as a service too, so it's nice to quickly deploy.

**Comment by skorokithakis** [comment]
Of course, I'll make it run the whole stack.

**Comment by eliavm** [comment]
Is there a fork that already implemented Docker support?

**Comment by Funkelfetisch** [comment]
following

**Comment by DaanIhomer** [comment]
this would be awesome! we have been using the v1 for a while and love it. Would be awesome if it gets updated :)

**Comment by arduilex** [comment]
I'm not a TypeScript developer so I'd love to have a docker for v2!

**Comment by Digital39999** [comment]
Why this got closed? I don't see it being finished anywhere..

**Comment by arduilex** [comment]
This PR just work fine :)
https://github.com/mckaywrigley/chatbot-ui/pull/1193

**Comment by Digital39999** [comment]
Was hoping it could get merged tbh
