### ISSUE TITLE
npm run chat - Missing script: "chat"

### ISSUE THREAD

**Issue by bartholomewbartkowski** [mckaywrigley/chatbot-ui#1065]
I'm trying to set up a local version of ChatBotUI. After running npm run chat, I get the following error:
npm ERR! Missing script: "chat"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

**Comment by fitchmultz** [comment]
Follow the instructions closely. After cloning the repo make sure you cd into the chatbot-ui directory by running `cd chatbot-ui`
