### ISSUE TITLE
Feature Request | API Key via env variable

### ISSUE THREAD

**Issue by kyleroberts-ai** [mckaywrigley/chatbot-ui#1066]
Hi,

Thank you for the amazing work.

I was wondering if instead of individual users uploading an API key, instead could we have a method to add via an env variable? 

Thanks,

**Comment by mckaywrigley** [comment]
Now that the database is secure (not local storage) we really want to encourage people to use the UI as it's a bit more simple for non-technical users. Highly encourage you to clone the repo and implement it for yourself though. We want to encourage people to experiment with their own features :)
