### ISSUE TITLE
email password, what's it, and how to set?

### ISSUE THREAD

**Issue by greagain** [mckaywrigley/chatbot-ui#1068]
Sorry for being newbie, can not find how to setup email/password to access the chat ui, I think might need to sign up? But when do that, I get the following error:
Unhandled Runtime Error
Error: Invalid Server Actions request.

Or am I doing something wrong for some settings? Like what should be the project_url in the sql thing? I suppose it's the API url?

**Comment by greagain** [comment]
BTW, using mac/m1. It might be something wrong with the supabase thing, such that new email/password can not be created?

**Comment by fitchmultz** [comment]
I had the same issue. "Could not authenticate user" when trying to "Sign up."

First, clear your browser cache and site data for localhost:3000.

Next, make sure in your .env.local you have the port specified in `NEXT_PUBLIC_SUPABASE_URL` like this `NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321`

Also make sure you have both `NEXT_PUBLIC_SUPABASE_ANON_KEY` and `SUPABASE_SERVICE_ROLE_KEY` set.

After this restart everything and try again. I was able to put a username and password in and click log in, which created my account. Good luck.

I am on M1 Mc as well. Node ver 21.5.0

**Comment by murillocamargo** [comment]
> I had the same issue. "Could not authenticate user" when trying to "Sign up."
> 
> First, clear your browser cache and site data for localhost:3000.
> 
> Next, make sure in your .env.local you have the port specified in `NEXT_PUBLIC_SUPABASE_URL` like this `NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321`
> 
> Also make sure you have both `NEXT_PUBLIC_SUPABASE_ANON_KEY` and `SUPABASE_SERVICE_ROLE_KEY` set.
> 
> After this restart everything and try again. I was able to put a username and password in and click log in, which created my account. Good luck.
> 
> I am on M1 Mc as well. Node ver 21.5.0

Thank you very much, this solved the issue for me.
The NEXT_PUBLIC_SUPABASE_URL did the trick.

**Comment by greagain** [comment]
Unfortunately, this didn't solve my problem, I get the same error as described here:
https://github.com/mckaywrigley/chatbot-ui/issues/1052

**Comment by greagain** [comment]
after update next.js to 14.0.5-canary.45, I was able to proceed, but in the chat window I get an error:
Unhandled Runtime Error
Error: TypeError: Failed to fetch

Source
db/profile.ts (12:10) @ getProfileByUserId

  10 |
  11 | if (!profile) {
> 12 |   throw new Error(error.message)
     |        ^
  13 | }
  14 |
  15 | return profile

**Comment by AI-egroup-bwaite** [comment]
<img width="963" alt="Screenshot 2024-01-09 at 2 59 15 PM" src="https://github.com/mckaywrigley/chatbot-ui/assets/139197083/69298e61-c701-42f7-b9f8-b8217346fae0">

Same issue. It seems like the setup process fails to create everything for the user. Running in aws on a t2.medium. 

If it helps anyone else, this is everything I have done to get it working this far. This is on amazon linux 2 ami. 

###############

sudo su -
passwd ec2-user
sudo yum install git -y
git clone https://github.com/mckaywrigley/chatbot-ui.git
sudo yum install npm
cd chatbot-ui
npm install
sudo yum install docker
sudo systemctl enable docker
sudo systemctl start docker
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
(echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/ubuntu/.bashrc
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
sudo yum groupinstall 'Development Tools'
brew install gcc
sudo usermod -aG docker ec2-user
export DOCKER_HOST=unix:///$HOME/.docker/run/docker.sock
reboot
brew install supabase/tap/supabase
npm i next@latest
supabase start
Copy env files with new values
npm run chat

##################################

I see the user account get created in supabase , but i'm new to supabase so I dont know everything to check just yet.

**Comment by greagain** [comment]
BTW, I get exactly the same anon key as the original code? Is that normal, or means something wrong?

**Comment by AI-egroup-bwaite** [comment]
I'm guessing its normal on a default install. You should have a command in the supabase docs to generate a new one but you will need to update it in the files per the readme.

**Comment by greagain** [comment]
Tried on local wsl2 distribution, same error.

**Comment by duanshuaimin** [comment]
the same error

**Comment by gabe314** [comment]
If you have the app running on a remote server, but you are attempting to access it from your local device (say, over an SSH tunnel), you need to forward local port 54321 to the remote port 54321 (in addition to port 3000, for web access to the interface, and port 54323, for web access to supabase):

`ssh -L 3000:localhost:3000 -L 54323:localhost:54323 -L 54321:localhost:54321 [remote-hostname]`

This will resolve the getProfileByUserId issue noted above by AI-egroup-bwaite.

**Comment by mosas** [comment]
exactly same issue happened. still looking for solution.

**Comment by Somnus1437** [comment]
意思就是现在的UI2.0直接安装在服务器上，没有办法通过域名访问，只能架设本地吗？

**Comment by sheena16202** [comment]
> <img alt="Screenshot 2024-01-09 at 2 59 15 PM" width="963" src="https://private-user-images.githubusercontent.com/139197083/295323586-69298e61-c701-42f7-b9f8-b8217346fae0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NDExNTYsIm5iZiI6MTcwOTg0MDg1NiwicGF0aCI6Ii8xMzkxOTcwODMvMjk1MzIzNTg2LTY5Mjk4ZTYxLWM3MDEtNDJmNy1iOWY4LWI4MjE3MzQ2ZmFlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxOTQ3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTkyNmMxMzYzMTAyNWZiOWU0YTQzNzQ3OTU5Nzc5OWRmZjI0NDI0MzY5ZmY1MDNkYjBiMmIwMmRhZTI5Zjk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1Etrf2fT0XRpOpm5ji9qux6yFnpVp_xO1QyfmoiqX94">
> Same issue. It seems like the setup process fails to create everything for the user. Running in aws on a t2.medium.
> 
> If it helps anyone else, this is everything I have done to get it working this far. This is on amazon linux 2 ami.
> 
> ###############
> 
> sudo su - passwd ec2-user sudo yum install git -y git clone https://github.com/mckaywrigley/chatbot-ui.git sudo yum install npm cd chatbot-ui npm install sudo yum install docker sudo systemctl enable docker sudo systemctl start docker /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/ubuntu/.bashrc eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" sudo yum groupinstall 'Development Tools' brew install gcc sudo usermod -aG docker ec2-user export DOCKER_HOST=unix:///$HOME/.docker/run/docker.sock reboot brew install supabase/tap/supabase npm i next@latest supabase start Copy env files with new values npm run chat
> 
> ##################################
> 
> I see the user account get created in supabase , but i'm new to supabase so I dont know everything to check just yet.

**Comment by sheena16202** [comment]
I am facing the same issue did you fixed it
