### ISSUE TITLE
Feature Request: Allow multiple conversations at once

### ISSUE THREAD

**Issue by dillchen** [mckaywrigley/chatbot-ui#107]
Right now, the UI follows the same OpenAI pattern, wondering if we could open this up a bit more

**Comment by mckaywrigley** [comment]
Like a side-view type thing? Could do that pretty easily.

**Comment by dillchen** [comment]
yea 100%

**Comment by fmaclen** [comment]
Having multiple conversations on the screen at once would be great.

But I'd suggest that before you implement such a big UI change it'd be nice if you could navigate through different conversations while one is actively receiving a completion (I noticed you get a `not-allowed` cursor if you try to click on another conversation while a completion is taking place).

ChatGPT stops the current completion if you switch to a different conversation, which is actually worse UX.

Eventually, it'd be nice if conversations could send simultaneous completion requests, though I guess you run the risk of hitting an API rate limit or something like that.

**Comment by dillchen** [comment]
I fully agree with @fmaclen actually
