### ISSUE TITLE
Perplexity models not working

### ISSUE THREAD

**Issue by murillocamargo** [mckaywrigley/chatbot-ui#1074]
After saving my profile's Perplexity API keys I'm getting the following error while trying to chat.
The models are unlocked correctly.

![image](https://github.com/mckaywrigley/chatbot-ui/assets/7115912/9e1932f4-3835-42e0-ab4b-b439385ca432)

**Comment by mckaywrigley** [comment]
Will investigate!

**Comment by greagain** [comment]
Not sure if this will help, I think perplexity api need to be inferenced in this way:
def perplexity_chat(prompt):
url = 'https://api.perplexity.ai/chat/completions'
headers = {'Authorization': 'Bearer pplx-api'}
data = {
'model': 'mixtral-8x7b-instruct',
'messages': [
{'role': 'system', 'content': 'You are a helpful assistant.'},
{'role': 'user', 'content': prompt}
]
}
response = requests.post(url, headers=headers, json=data)
return response.json()['choices'][0]['message']['content']

**Comment by greagain** [comment]
The above is the python code way that works for me, basically the:
https://api.perplexity.ai/v1/mixtral-8x7b-instruct/completions
endpoint did not work, will give 404 errror. Has to put the model name into 'data'.

**Comment by mckaywrigley** [comment]
Perplexity issues should be ironed out now. Just made a change.
