### ISSUE TITLE
Vercel Runtime Error

### ISSUE THREAD

**Issue by vmldude** [mckaywrigley/chatbot-ui#1075]
I tried to fork the project on vercel after  the update.  Now I get the below error upon launching the project

Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 735498021

Can anyone suggest what additional steps are required before forking it onto vercel?

**Comment by Bortus-AI** [comment]
This fork and guide worked for me on vercel
https://github.com/ApiskeyC/chatbot-ui

**Comment by vmldude** [comment]
Thanks the detailed instructions worked for me!
