### ISSUE TITLE
What is the project_url? This seems the only thing I don't know how to 'follow' in the Readme

### ISSUE THREAD

**Issue by greagain** [mckaywrigley/chatbot-ui#1077]
sql
In the 1st migration file 20240108234540_setup.sql you will need to replace 2 values:

project_url (line 53): This can remain unchanged if you don't change your config.toml file.
service_role_key (line 54): You got this value from running supabase status in step 5.1.
You will also need to to fill in the values for project_url

**Comment by vmldude** [comment]
it is on the suprabase dashboard for the project

look right next to this:

Connecting to your new project
Interact with your database through the [Supabase client libraries](https://supabase.com/docs/reference) with your API keys.

More information about your project's keys can be found in your project's API settings.

**Comment by greagain** [comment]
run:
supabase status
give me this:
Stopped services: [supabase_analytics_chatbotui]
supabase local development setup is running.

         API URL: http://127.0.0.1:54321
     GraphQL URL: http://127.0.0.1:54321/graphql/v1
          DB URL: postgresql://postgres:postgres@127.0.0.1:54322/postgres
      Studio URL: http://127.0.0.1:54323
    Inbucket URL: http://127.0.0.1:54324
      JWT secret: super-secret-jwt-token-with-at-least-32-characters-long
        anon key: 
        service_role key: 
        
   So I suppose it should be:http://127.0.0.1:54321
   but the 20240108234540_setup.sql
   have: project_url TEXT := 'http://supabase_kong_chatbotui:8000'

**Comment by greagain** [comment]
Checked the docker desktop, there are several container server running, not sure if http://supabase_kong_chatbotui:8000 should be 'the one'.

**Comment by wrapss** [comment]
it's written that you shouldn't touch it unless you've modified it in config.toml file, so you shouldn't touch it at all? I haven't touched this parameter and my application works correctly.

**Comment by mckaywrigley** [comment]
My fault on poor documentation.

I have updated the docs to hopefully clear this up a bit.

Basically - you shouldn’t need to change this.
