### ISSUE TITLE
Unhandled Runtime Error Error: TypeError: Failed to fetch

### ISSUE THREAD

**Issue by duanshuaimin** [mckaywrigley/chatbot-ui#1078]
chatbot-ui:the newest version

**Comment by duanshuaimin** [comment]
<img width="1420" alt="截屏2024-01-10 11 38 30" src="https://github.com/mckaywrigley/chatbot-ui/assets/535940/1fd3bb2c-1399-42c8-bed0-7e859181bf1f">

**Comment by wrapss** [comment]
have you correctly configured your environment file? (to try to create an account again, please clear the site's cookies)

**Comment by mckaywrigley** [comment]
@duanshuaimin Try clearing cookies for the site. Have seen this a few times and that might fix it.

**Comment by greagain** [comment]
Tried as hard as I can to start afresh, still have this error---account is created again.

**Comment by greagain** [comment]
manged to make it work from a fresh install on wsl2, and have to use firefox and private browsing, then is able to get to the create profile part and working. Clear browing data seems not work for Chrome.

**Comment by duanshuaimin** [comment]
> have you correctly configured your environment file? (to try to create an account again, please clear the site's cookies)

thanks,environment file is correctly configured,but cookies not cleared

**Comment by duanshuaimin** [comment]
> @duanshuaimin Try clearing cookies for the site. Have seen this a few times and that might fix it.

it works,thanks

**Comment by Bortus-AI** [comment]
Having this issue on a new install as well. Clearing cookies does not work. After I click sign up I get this error. My env.local is correct. I never get the email after registering and I can login but get the 
db/profile.ts (12:10) @ getProfileByUserId

  10 |
  11 | if (!profile) {
> 12 |   throw new Error(error.message)
     |        ^
  13 | }
  14 |
  15 | return profile

**Comment by wrapss** [comment]
u see a line in profile table ? http://localhost:54323/project/default/editor/17494

**Comment by Bortus-AI** [comment]
> u see a line in profile table ? http://localhost:54323/project/default/editor/17494

@wrapss Yes I do

**Comment by wrapss** [comment]
can you add a console.log(user.id) in the components/utility/global-state.tsx file around line 170, retrieve it from the console and compare it with the userid in the profile table and in the authentication tab. if it's the same i don't see where the problem comes from 
![screen](https://github.com/mckaywrigley/chatbot-ui/assets/7548882/e5d1789b-e8aa-4cb2-9278-f1c883ba9016)

**Comment by Bortus-AI** [comment]
Thanks for the reply. I just did that and the user id matches in the console and the public/profiles user id and the aut/users tables user id

**Comment by wrapss** [comment]
there's literally only one function left, so check it out. see your supabase configuration in the .env or elsewhere.
![image](https://github.com/mckaywrigley/chatbot-ui/assets/7548882/4b8107ae-0a03-4103-bcbe-f2ac06b4b72b)
