### ISSUE TITLE
database dependency

### ISSUE THREAD

**Issue by ehartford** [mckaywrigley/chatbot-ui#1079]
the reason I used this instead of huggingface/chat-ui is because it don't require a database dependency

Now that it does require a database dependency, I will prefer to use the old version with no database dependency

Can you please document a way to use it without a database dependency?  (ie using the browser's local storage instead)

**Comment by mckaywrigley** [comment]
@ehartford Local browser storage can only hold 5MB of storage, has a lot of security issues, and doesn’t allow for any multimodality or file storage. 

I realize it’s not as convenient, but chat has gone beyond the needs of small storage for text-only, hence the decision.

**Comment by ehartford** [comment]
You can store more than 5mb locally and also database is not a necessary feature for chat UI.

https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API

But, it's your decision to make.
I will figure out something.

But thank you for your excellent contribution to open source AI!

**Comment by ehartford** [comment]
@mckaywrigley I saw that you squashed the old pre-database version - do you still have a copy of it somewhere?

**Comment by ehartford** [comment]
never mind, I found it

https://github.com/ehartford/dolphin-web
