### ISSUE TITLE
Could not authenticate user

### ISSUE THREAD

**Issue by iamianM** [mckaywrigley/chatbot-ui#1080]
I get "Could not authenticate user" error anytime I try to login or signup. I even get it on the main site https://apiskey.com/. Is this an error from a recent merge? This is my first time trying to deploy with vercel.

**Comment by Nymbo** [comment]
Check your email! It sends you a confirmation email when you sign up.

Clicking the link in the email still takes me to localhost:3000 but it should let you in after you reload the page.

**Comment by mckaywrigley** [comment]
While we encourage forks, we do not endorse this 3rd party sites as we can’t vouch for security.

We are unaffiliated with this site.
