### ISSUE TITLE
Using Supabase Docker already deployed

### ISSUE THREAD

**Issue by Guerdal** [mckaywrigley/chatbot-ui#1087]
I have alrready a supabase docker deployed for another project.

Can I use it with Chatbot-ui ?

At this moment, if I start chatbot-ui, i received this :

```
npm run chat

> chatbot-ui@2.0.0 chat
> supabase start && npm run db-types && npm run dev

sh: 1: supabase: not found
```
May be I don't understand something :-)

**Comment by wrapss** [comment]
u need supabase-cli for run npm run db-types

**Comment by Guerdal** [comment]
It's not possible to manually initialize the database ?

**Comment by wrapss** [comment]
the command generates a types.ts file which is used in the application so I don't think so :/ but you just need the cli for that your docker installation won't change

**Comment by wrapss** [comment]
or try npm run dev directly, but I think the above command is necessary

**Comment by Guerdal** [comment]
Ok I will try that

**Comment by Guerdal** [comment]
Alright, I tried a few things.

Firstly, through the Supabase SQL editor interface, I ran the content of the migration scripts.

Next, I launched the service using the command "npm run dev" => I have access to the Chatbot-UI interface.

However, I cannot go further as I encounter another bug, that of accessing chatbot-ui from a remote machine.

**Comment by dawoodjee** [comment]
Why not use a dockerized Supabase so everything runs in containers

**Comment by wrapss** [comment]
@dawoodjee [see](https://github.com/mckaywrigley/chatbot-ui/pull/1193)
