### ISSUE TITLE
Error when uploading PDF. setUseRetrieval is not a function

### ISSUE THREAD

**Issue by amir-ghasemi** [mckaywrigley/chatbot-ui#1089]
![Screenshot 2024-01-10 at 16-13-12 Screenshot](https://github.com/mckaywrigley/chatbot-ui/assets/19309204/e1024d4a-4cec-49ea-be71-af022a76af0d)

**Comment by imanpatelb** [comment]
I think setUseRetrieval is not properly enclosed within ChatbotUIContext.Provider. This could happen if the component is rendered outside the provider's tree in your application's component hierarchy.
What do you think?
