### ISSUE TITLE
Override API keys globally for users

### ISSUE THREAD

**Issue by jsweetzer-ea** [mckaywrigley/chatbot-ui#1091]
I would like to be able to override the API key for each provider by environment variable, such that all users are forced to use the provided API key. It would also be beneficial to then disable bring-your-own-key for any providers not enabled at env level. 

Is this something you would support adding in the short term?

**Comment by housser-apply** [comment]
Agreed, we'd love to be able to deploy this for an internal team, and want all users to be using our centrally managed API keys without having to provision and distribute separate keys to all users.

**Comment by sebiweise** [comment]
It would be nice to share a workspace and then define api keys for that workspace so every user that is working in that workspace will use the specific api key

**Comment by mckaywrigley** [comment]
We’ll add support for this soon!

**Comment by jsweetzer-ea** [comment]
Great, thank you!

**Comment by tomasmcm** [comment]
Plus one on this. We use chatbot-ui with azure openai to provide a private instance of gpt-4 for internal use within the company and would like to abstract API keys like in V1
