### ISSUE TITLE
Supabase SSO login

### ISSUE THREAD

**Issue by jsweetzer-ea** [mckaywrigley/chatbot-ui#1092]
Supabase Pro enables SAML SSO - https://supabase.com/docs/reference/javascript/auth-signinwithsso

Ideal behaviour would be to default login to SSO instead of username/password if SSO is enabled (perhaps specify the allowed domain(s) in env).  

An extension of this could be to then fill the profile with SSO-provided details (e.g username, chat name) and disable editing the profile for SSO-created users. 

Is this something you would support adding in the short term?

**Comment by jollytoad** [comment]
I've been experimenting with this, as eventually we want Okta SSO, but I've started simple with Google OAuth, and pre-populating profile data from the raw user JSON data. Username as email, and pulling in display name and user image URL.

Had to modify the `create_profile_and_workspace` trigger fn in the db to pre-populate and adjust the setup page a little to display the pre-populated data.

Experimental branch can be found here... https://github.com/jollytoad/chatbot-ui/tree/oauth

**Comment by jsweetzer-ea** [comment]
Thanks a lot - do you mind pushing your trigger + setup page changes to the branch please? 

I managed to get Azure working with your changes otherwise.

**Comment by DanielLaberge** [comment]
I am also very interested in SSO with Azure and Google Workspace. Could you let me know when support for it is merged in main?

**Comment by jsweetzer-ea** [comment]
Had some slight issues so far with the WIP branch.

Setup of a new profile using email as username failed validation for two reasons - the field in the table is checking for max 25 characters and the UI won’t allow for validating a prepopulated username greater than this either. 

Edit: I realise I overlooked the modification to the email in the trigger and removed it, as I wanted to use full email. 

On callback success the app should redirect to setup the first time, and chat thereafter - I am kicked back to the index page after a successful callback as it stands. Lastly I think the inputs should be disabled on the setup page if pre-filled. 

Are you intending to polish your implementation further or should we explore separately? Cheers

**Comment by mckaywrigley** [comment]
This won't be a focus short term.

**Comment by jollytoad** [comment]
@jsweetzer-ea I'm not planning to polish to the point where it could be merged back, as I expect to have some very specific configuration for our use-case, but more than happy to share and continue discussion. From Mckay's last comment looks like such effort wouldn't get merge at this time anyway, which is fair enough.

At present I'm exploring the possibility of using Auth.js to work-around the limitations of Supabase auth (which doesn't support Okta via OIDC!)

**Comment by jsweetzer-ea** [comment]
No problem - thank you for the reply. Likewise have taken our fork private as it will be customised beyond this for enterprise use. Cheers!

**Comment by aalev** [comment]
> I've been experimenting with this, as eventually we want Okta SSO, but I've started simple with Google OAuth, and pre-populating profile data from the raw user JSON data. Username as email, and pulling in display name and user image URL.
> 
> Had to modify the `create_profile_and_workspace` trigger fn in the db to pre-populate and adjust the setup page a little to display the pre-populated data.
> 
> Experimental branch can be found here... https://github.com/jollytoad/chatbot-ui/tree/oauth

hello, I'm eager to get or implement SSO with Azure Entra ID (aka Azure Active Directory) as it is THE feature required to deploy after the proof of value !

@jollytoad: this branch doesn't exist anymore, could you restablish it or share -part of- the code ?
@jsweetzer-ea : did you get your private fork to work ?

best regards

**Comment by jollytoad** [comment]
@aalev hi, yes, the branch is now 'org', it's my default branch, there is a brief readme documenting the changes from 'main'... https://github.com/jollytoad/chatbot-ui/blob/org/README_FORK.md ... it's currently relying on Google OAuth still atm, we're waiting for Supabase to implement generic OAuth/OIDC support, which allegedly is coming soon!

It's not production ready, still trying to get my head around next.js weirdness, like env vars getting inlined!
