### ISSUE TITLE
Trying llama via ollama yields Reader error

### ISSUE THREAD

**Issue by BartlomiejLewandowski** [mckaywrigley/chatbot-ui#1094]
Just checked out the repository yday, managed to get the UI running, but choosing a local backend yields the following error when trying to interface with the model:

```
Unhandled Runtime Error
TypeError: Failed to execute 'getReader' on 'ReadableStream': ReadableStreamDefaultReader constructor can only accept readable streams that are not yet locked to a reader

 signal: AbortSignal
  5 | ) => {
> 6 | const reader = stream?.getReader()
    |                       ^
  7 | const decoder = new TextDecoder()
  8 |
  9 | if (reader) {
```

Any ideas what the root cause is?

**Comment by amir-ghasemi** [comment]
I have been getting that error on and off. Are you able to access the Ollama server directly? Restarting the server might help.

**Comment by BartlomiejLewandowski** [comment]
Looks like an error reading the same body twice - the error handler uses .json() when status is not ok, then proceeds to try and read the body once again in the happy path. 

I found that ollama api returns a 500 in my case caused by a wrong model files due to a recent version change

**Comment by taype** [comment]
I have the same error, and don't know how to handle it. anyone know how to solve it?
