### ISSUE TITLE
any hosted website can use out of box?

### ISSUE THREAD

**Issue by luohao123** [mckaywrigley/chatbot-ui#1098]
github description's website are down

**Comment by ApiskeyC** [comment]
> github description's website are down

Try apiskey.com

**Comment by mckaywrigley** [comment]
> > github description's website are down
> 
> Try [apiskey.com](https://apiskey.com)

Please stop promoting your service. I've tried to make this clear in other issues. We do NOT endorse this site in any way and cannot vouch for its security. Do not use it.

**Comment by luohao123** [comment]
@mckaywrigley  can u make chatbotui.com avaiable?
