### ISSUE TITLE
Unhandled Runtime Error TypeError: Failed to execute 'getReader' on 'ReadableStream': ReadableStreamDefaultReader constructor can only accept readable streams that are not yet locked to a reader

### ISSUE THREAD

**Issue by duanshuaimin** [mckaywrigley/chatbot-ui#1099]
<img width="1436" alt="截屏2024-01-11 10 45 05" src="https://github.com/mckaywrigley/chatbot-ui/assets/535940/8d5096a1-8316-4eea-937a-866dfa137237">
<img width="778" alt="截屏2024-01-11 10 45 28" src="https://github.com/mckaywrigley/chatbot-ui/assets/535940/26a29645-4cd5-4f50-aba0-cbaa6d6cb36a">

**Comment by amir-ghasemi** [comment]
Seems to be same as #1094.

**Comment by tisfeng** [comment]
I'm also experiencing this problem, operating exactly as the installation instructions, does anyone know how to fix this?
