### ISSUE TITLE
i18n and l10n please

### ISSUE THREAD

**Issue by boxoft-ai** [mckaywrigley/chatbot-ui#110]
Kindly consider incorporating internationalization (i18n) and localization (l10n) features into your app, as this would greatly enhance its accessibility and enjoyment for users around the world.

**Comment by Chanzhaoyu** [comment]
> Might be a great opportunity for someone to make a PR.
> 
> I'm unfamiliar, but I'm all ears if you can help educate me on what that entails!

I'd be happy to contribute XD

**Comment by mckaywrigley** [comment]
Will look for it!

**Comment by Jungley8** [comment]
#142
