### ISSUE TITLE
Not really an issue, just some questions about chatbot-ui

### ISSUE THREAD

**Issue by mgsotelo** [mckaywrigley/chatbot-ui#1100]
I'm relatively new into the project, and btw it's one of the coolest projects I've ever seen. 

I have a couple of questions about the project, and how to use it in the most optimal way possible. So my questions are the following:

- What are presets? 
- What is the difference between prompts and presets? 
- Do you have any examples of how do instructions in different scopes work between each other? I mean, I can set instructions in the workspace, into my profile, into presets, into prompts, and so on, but I don't know exactly how they interact between each other, if any scope can override other (e.g. idk if prompt instructions can override workspace instructions, or vice-versa)
- How do you work with files? Do you just upload files and then you create a new chat and query your pdf file?
- Do you have any documentation? 

If you're interested, I can write some functional docs, how-to guides and maybe tutorials about chatbot-ui (probably using docusaurus or something similar). Let me know if I can help.

**Comment by mckaywrigley** [comment]
Hoping to add docs next week that should cover everything in-depth.

I'd check back later next week and we should have good guides for everything!
