### ISSUE TITLE
PDF upload error on Mac with M1

### ISSUE THREAD

**Issue by OliverTalentship** [mckaywrigley/chatbot-ui#1104]
Import trace for requested module:
./node_modules/@xenova/transformers/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node
./node_modules/@xenova/transformers/node_modules/sharp/build/Release/ sync ^\.\/sharp\-.*\.node$
./node_modules/@xenova/transformers/node_modules/sharp/lib/sharp.js
./node_modules/@xenova/transformers/node_modules/sharp/lib/constructor.js
./node_modules/@xenova/transformers/node_modules/sharp/lib/index.js
./node_modules/@xenova/transformers/src/utils/image.js
./node_modules/@xenova/transformers/src/transformers.js
./lib/generate-local-embedding.ts
./app/api/retrieval/process/route.ts
 ⨯ ./node_modules/@xenova/transformers/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

Resolution is to add the following to the next.config.js

 // Override the default webpack configuration
  webpack: (config) => {
      // See https://webpack.js.org/configuration/resolve/#resolvealias
      config.resolve.alias = {
          ...config.resolve.alias,
          "sharp$": false,
          "onnxruntime-node$": false,
      }
      return config;
  },

**Comment by sanbaideng** [comment]
I am using windows11,  and I get this error too,
Did you solve this allready？

**Comment by OliverTalentship** [comment]
I made the following change – then it worked.
// Override the default webpack configuration
webpack: (config) => {
// See https://webpack.js.org/configuration/resolve/#resolvealias
config.resolve.alias = {
...config.resolve.alias,
"sharp$": false,
"onnxruntime-node$": false,
}
return config;
},


Von: YangYang ***@***.***>
Datum: Samstag, 22. Juni 2024 um 04:16
An: mckaywrigley/chatbot-ui ***@***.***>
Cc: Oliver Trabert ***@***.***>, Author ***@***.***>
Betreff: Re: [mckaywrigley/chatbot-ui] PDF upload error on Mac with M1 (Issue #1104)
CAUTION: External Sender. Please do not click on links or open attachments from senders you do not trust.


I am using windows11, and I get this error too,
Did you solve this allready？
