### ISSUE TITLE
Concerns About API Key Exposure

### ISSUE THREAD

**Issue by Mingzefei** [mckaywrigley/chatbot-ui#1105]
Hello, I have been exploring this repository and noticed several issues related to API key exposure. As a user who is keenly interested in the security aspects of this project, I am quite concerned about this issue.

Has this issue been resolved? If so, could you please explain how it was addressed?

Thanks!

**Comment by mckaywrigley** [comment]
We’ve moved away from local storage which were the cause of those issues.
