### ISSUE TITLE
Support for  proxy  api endpoint for open api

### ISSUE THREAD

**Issue by divyam234** [mckaywrigley/chatbot-ui#1107]
New version looks good but its lacks certain features like customproxy api endpoint for openapi and ui is not compatible for mobile . I can raise a pr for this

**Comment by Bortus-AI** [comment]
Yes please, I enjoy using the cloudflare AI relay so it would be great to have custom api endpoint integrated

**Comment by mckaywrigley** [comment]
If you added a proxy endpoint option we'd certainly merge. I can tackle this as well.

**Comment by tisfeng** [comment]
I didn't understand. Does it currently support custom endpoints? I couldn't find this setting.

Why was this issue closed? Is it already supported, or is there no plan to support it?

**Comment by spammenotinoz** [comment]
I took a manual approach, as discussed here, but in theory a minor code update to read a system variable is viable.
https://github.com/mckaywrigley/chatbot-ui/discussions/1527
