### ISSUE TITLE
Supabase start is failing with below message.

### ISSUE THREAD

**Issue by mallapraveen** [mckaywrigley/chatbot-ui#1108]
![image](https://github.com/mckaywrigley/chatbot-ui/assets/28497715/cc8e7425-c23e-4002-a0b9-65b2bbea2486)

Applying migration 20240108234540_setup.sql...
Applying migration 20240108234541_add_profiles.sql...
Applying migration 20240108234542_add_workspaces.sql...
Applying migration 20240108234543_add_folders.sql...
Applying migration 20240108234544_add_files.sql...
Applying migration 20240108234545_add_file_items.sql...
Applying migration 20240108234546_add_presets.sql...
Applying migration 20240108234547_add_assistants.sql...
Applying migration 20240108234548_add_chats.sql...
Applying migration 20240108234549_add_messages.sql...
Applying migration 20240108234550_add_prompts.sql...
Applying migration 20240108234551_add_collections.sql...
supabase_edge_runtime_chatbotui container logs:
Download https://deno.land/std@0.182.0/http/server.ts
Download https://deno.land/x/jose@v4.13.1/index.ts
failed to load 'https://deno.land/std@0.182.0/http/server.ts': Import 'https://deno.land/std@0.182.0/http/server.ts' failed: error sending request for url (https://deno.land/std@0.182.0/http/server.ts): error trying to connect: invalid peer certificate: UnknownIssuer
Error: main worker boot error: worker boot error
service not healthy: [supabase_edge_runtime_chatbotui]
Try rerunning the command with --debug to troubleshoot the error.

**Comment by joseverav** [comment]
What was the fix for this? I have the exact same problem.

**Comment by emptytank** [comment]
I have this same problem. Can someone please provide some guidance on how to fix?
