### ISSUE TITLE
How to upload pdf file

### ISSUE THREAD

**Issue by Stan370** [mckaywrigley/chatbot-ui#1109]
Hi, I'm just wondering how to upload pdf file.

**Comment by grabani** [comment]
![image](https://github.com/mckaywrigley/chatbot-ui/assets/25469154/cfc70f2a-2220-470d-aafa-1d3e5d958317)

Did you have something else in mind?

**Comment by mckaywrigley** [comment]
You can use the plus icon in the message input or the file tab in the sidebar :)
