### ISSUE TITLE
Text Generation Inference

### ISSUE THREAD

**Issue by NicolasDrapier** [mckaywrigley/chatbot-ui#1112]
Hello, 

Thank you so much for your work, it's incredible. 

Are there any plans to support Text Generation Inference for local models?

**Comment by amir-ghasemi** [comment]
Not sure about TGI but it's rather easy to extend the code to work with other inference engines which provide an OpenAI compatible server. I have tested it with vLLM and it works as expected.

![image](https://github.com/mckaywrigley/chatbot-ui/assets/19309204/928d3576-7c8d-4173-9739-24b7c53edab5)

**Comment by mckaywrigley** [comment]
I just added it to my list to explore. Not opposed at all - would be nice for hosted versions being able to use more models.

As @amir-ghasemi mentioned it's fairly extensible if you want to add until we get around to it.
