### ISSUE TITLE
Adding OPENAI_API_HOST not working

### ISSUE THREAD

**Issue by MohdSaleh** [mckaywrigley/chatbot-ui#1114]
OPENAI_API_HOST from ENV is not reading, How to manage adding external API (Same OpenAI Response).
//Added inside ENV
OPENAI_API_HOST=https://abc.com

**Comment by MohdSaleh** [comment]
BaseURL settings added to settings,  
https://github.com/mckaywrigley/chatbot-ui/pull/1127
Please check this @mckaywrigley

**Comment by mckaywrigley** [comment]
This isn't something we're going to support for the time being. Majority of users will get confused by it.

**Comment by Bortus-AI** [comment]
Thats really lame. Never heard of this setting being confusing on any other chat repo. Cloudflare AI relay for example is really nice, not only to track usage but also it can cache the responses and save you money by using less tokens.

**Comment by spammenotinoz** [comment]
If interested https://github.com/mckaywrigley/chatbot-ui/discussions/1527
In theory, a quick code update to use an environment variable is possible, but for now this is the approach I use.
