### ISSUE TITLE
Chat Search Doesn't Seem to Work

### ISSUE THREAD

**Issue by grabani** [mckaywrigley/chatbot-ui#1115]
The chat search doesn't seem to work.

I have the following chat:

![image](https://github.com/mckaywrigley/chatbot-ui/assets/25469154/95b81b07-84de-4f3c-86a3-21141eeb3e93)

when I search for the string "london" or "London" I get no matches 😔:

![image](https://github.com/mckaywrigley/chatbot-ui/assets/25469154/326b91ff-0c9d-48fc-93f5-34119589b93f)

**Comment by amir-ghasemi** [comment]
Chat search is working. It only uses the chat title for search though, not the contents.

**Comment by grabani** [comment]
That is a LOSS of functionality compared to v1; which searched title and body 😔

**Comment by mckaywrigley** [comment]
We used to be able to search every message you had because it capped out at 5MB of text. Things are a bit more complex now so we don't support it, though we are adding in-chat search soon for long chats.
