### ISSUE TITLE
Add allowed domains/url

### ISSUE THREAD

**Issue by tirthpatell** [mckaywrigley/chatbot-ui#1117]
So I am running it locally, and trying to access it from one of my domains by using the cloudflared. I am getting the error that the given domain/url is not allowed origin. I don't have much experience with next.js, how do I change the allowed domains?

![CleanShot 2024-01-11 at 12 16 53@2x](https://github.com/mckaywrigley/chatbot-ui/assets/32465104/adf08aa0-6860-4137-8925-448d45629e85)

**Comment by robtec** [comment]
if you update `next.config.js`

```
experimental: {
    	serverComponentsExternalPackages: ["sharp", "onnxruntime-node"],
	serverActions: {
		allowedOrigins: ["localhost:3001", "mycooldomain.com"],
			}
  }
```

**Comment by mckaywrigley** [comment]
Update your next.config.js like @robtec mentioned. Next.js has great docs for the config if you need.

**Comment by Bortus-AI** [comment]
> Update your next.config.js like @robtec mentioned. Next.js has great docs for the config if you need.

@mckaywrigley Can we do something like NEXTAUTH_URL=https://yourdomain.com in the .env.local instead?
