### ISSUE TITLE
Presets not being listed?

### ISSUE THREAD

**Issue by murillocamargo** [mckaywrigley/chatbot-ui#1118]
After creating a Preset where does it goes? 
I'm thinking it would be listed on the new chat modal along with other models.

Is this a bug or Presets work in a different way?

![image](https://github.com/mckaywrigley/chatbot-ui/assets/7115912/5784c3a1-a4e3-400d-87be-505de1e05ae7)

![image](https://github.com/mckaywrigley/chatbot-ui/assets/7115912/9da41656-687c-41b4-9da9-eb704b8b9a2a)

Thanks.

---

I noticed that the Provider options is not being saved correctly, sometimes it opens empty.

![image](https://github.com/mckaywrigley/chatbot-ui/assets/7115912/9efab432-10b6-4cf6-9abd-1d09777e7ad0)

**Comment by wrapss** [comment]
Click on "Quick settings"

**Comment by mckaywrigley** [comment]
In quick settings :)

**Comment by murillocamargo** [comment]
> In quick settings :)

dear god
