### ISSUE TITLE
Support for user feedback/rating

### ISSUE THREAD

**Issue by amir-ghasemi** [mckaywrigley/chatbot-ui#1122]
Would be nice to have a feedback (thumbs up/down) option for every generated response similar to ChatGPT. Feedback could be stored in supabase and mined to improve performance.

**Comment by kyleroberts-ai** [comment]
+1 for this feature

**Comment by mckaywrigley** [comment]
Just to check...

You mean for your own data, or you want *us* to fine-tune your responses?

Totally get the former, but the latter goes a bit beyond the scope of what we're trying to do.

**Comment by amir-ghasemi** [comment]
@mckaywrigley I meant the former, ie just allowing users to rate responses and storing them in the db.

**Comment by mckaywrigley** [comment]
Got it. Probably won't implement that as I don't particularly like the extra complexity for users. Researchers could implement that though and it would be fairly straightforward.
