### ISSUE TITLE
Hook for a preprocessed vector database

### ISSUE THREAD

**Issue by amir-ghasemi** [mckaywrigley/chatbot-ui#1124]
Is the current RAG support limited to files uploaded via the UI? If I have a large number of preprocessed files, already chunked and embedded in a vector database, where would be the best place to integrate it in the code so the users have access via RAG by default.

**Comment by mckaywrigley** [comment]
You'd want to use a seed.sql file in the supabase dir. Check their docs for more.

**Comment by raul-bermejo** [comment]
@amir-ghasemi were you able to address the issue? This doesn't seem to be implemented or any documentation available yet
