### ISSUE TITLE
disable signup doesn't work

### ISSUE THREAD

**Issue by munterwexi** [mckaywrigley/chatbot-ui#1128]
i deployed an own instance via the guideline, but wanted to disable signups since we will be able to give access to selected users only. 

in the file supabase/config.toml there is line 68 stating one can disable signups by setting this to false: 

```
# Allow/disallow new user signups to your project.
enable_signup = true
```

error description:  this doesn't have the expected effect. after redeployment the signup button and process still works. 

expected behaviour: no signup button there and possible after setting this to false

**Comment by Bortus-AI** [comment]
confirmed same issue here. I would like to disable it as well

**Comment by mckaywrigley** [comment]
If it's for hosted version you can disable in the Supabase UI.
