### ISSUE TITLE
Error: relation "public.profiles" does not exist

### ISSUE THREAD

**Issue by Neogepeto** [mckaywrigley/chatbot-ui#1129]
db/profile.ts (12:10) @ getProfileByUserId

  10 |
  11 | if (!profile) {
> 12 |   throw new Error(error.message)
     |        ^
  13 | }
  14 |
  15 | return profile
  
  i have this error and it seem to block everything what should i do ?

**Comment by harshvitra** [comment]
Can you check if your Supabase URL and Key is used from supabase status ?

**Comment by Neogepeto** [comment]
> Can you check if your Supabase URL and Key is used from supabase status ?

its not the key i had refferenced in env.local how do i change them ?

**Comment by Onat-T** [comment]
Why is this closed @Neogepeto ? How did you solve it?
