### ISSUE TITLE
【docx process failed】FileReader onloadend event executes after handling .docx files

### ISSUE THREAD

**Issue by ghost** [mckaywrigley/chatbot-ui#1131]
**Problem**:
The `return` statement in the code block that handles `.docx` files is not preventing the `FileReader.onloadend` event from being executed. This leads to unnecessary code execution even after the `.docx` file has been processed.

**Expected Behavior**:
After handling a `.docx` file, the function should terminate and not execute any further code, especially not the `FileReader.onloadend` event.

**Current Behavior**:
The `FileReader.onloadend` event is being executed even after the `.docx` file has been processed and a `return` statement has been reached.

**Steps to Reproduce**:
1. Select a `.docx` file to be processed.
2. The code correctly identifies and processes the `.docx` file.
3. Despite the `return` statement, the `FileReader.onloadend` event is still executed.

**Proposed Solutions**:
1. Remove the `FileReader.onloadend` event listener after processing the `.docx` file:

```javascript
if (file.type === "application/vnd.openxmlformats-officedocument.wordprocessingml.document") {
  // ...handle .docx file...

  // Remove the onloadend event listener
  reader.onloadend = null;

  return;
}
```

2. Use a flag to indicate whether the file has been handled and check this flag in the `FileReader.onloadend` event:

```javascript
let isFileHandled = false; // Initialize a flag to indicate file handling status

// Handle docx files
if (file.type === "application/vnd.openxmlformats-officedocument.wordprocessingml.document") {
  // ...handle .docx file...

  isFileHandled = true; // Set the flag to true as the file is handled
  return;
}

reader.onloadend = async function () {
  if (isFileHandled) {
    // If the file has been handled, do not execute further actions
    return;
  }

  // ...rest of the onloadend event code...
};
```

Either of these solutions should prevent the `FileReader.onloadend` event from executing after a `.docx` file has been processed, ensuring that the program behaves as expected.

**Comment by ghost** [comment]
But problem not be solved. hhhhhhhhh

**Comment by mckaywrigley** [comment]
Patched!
