### ISSUE TITLE
feature request: support sqlite?

### ISSUE THREAD

**Issue by rumisle** [mckaywrigley/chatbot-ui#1135]
reasons:

1. no need to install gigabytes of docker to use supabase (now it has ate >10gb of my disk, and it is still pulling more images, i'm scared). feels bloated for a simple local instance, and imo sqlite could easily handle a little chat app.
2. one less daemon running on the background for local instance.
3. more convenient initialization, no need to fill `project_url` and `service_role_key`
4. for the hosted version, the readme suggested using the hosted version of supabase, maybe the user want to store their private chat data on the same server they are serving the frontend, rather than a thrid-party database provider.

downside:

maybe some auth work has to be done manually? but i don't think people care about auth for local instance anyways.

day-dreaming:

sqlite wasm in the browser backed by local database so that this whole chatbot-ui can once again be served as a nice static site? no `npm install` needed, zipped archives are distributed via github releases. i don't know whether it's possible though.

**Comment by mckaywrigley** [comment]
So here's the issue...

I'm going to continue to use postgres in prod, and this project is essentially just open-sourcing that work.

A sqllite version would be something I'd have to support at every turn, and they differ enough that it would become a bit of a pain.

I think this is a really good case for a community fork called "chatbot-ui-sqllite" or something.

**Comment by rumisle** [comment]
Got it, thank you! Closing the issue

**Comment by emsi** [comment]
> I'm going to continue to use postgres in prod, and this project is essentially just open-sourcing that work.
> 
> A sqllite version would be something I'd have to support at every turn, and they differ enough that it would become a bit of a pain.

I'm slightly confused because at https://github.com/mckaywrigley/chatbot-ui/issues/1148#issuecomment-1890424951 you wrote: "Have to get sqllite working 1:1 with our postgres stuff and then package the whole thing". 
Does that mean that there actually is  sqllite compatibility work in progress?
