### ISSUE TITLE
clicking on the shortcut help doesn't do anything

### ISSUE THREAD

**Issue by rumisle** [mckaywrigley/chatbot-ui#1138]
for example when i clicked on the open presets (cmd + shift + p), i thought it would open presets... maybe it's my problem. and on firefox `cmd + shift + p` is the shortcut for private tab so unfortunately i can't use that shortcut.

**Comment by mckaywrigley** [comment]
Apologies that shortcuts don't work properly on firefox. I've been using Chrome, but shortcuts can be tough as other apps conflict. That command in particular opens up the quick settings, and I'll rename that one to make it more clear. You can still open up quick settings manually in the top left :)
