### ISSUE TITLE
Line breaks <br> are not regognised within tables?

### ISSUE THREAD

**Issue by schihei** [mckaywrigley/chatbot-ui#114]
![CleanShot 2023-03-24 at 08 18 36](https://user-images.githubusercontent.com/6663322/227451791-4ec43e25-57de-44c2-a123-7b4b9d9e5f52.png)

**Comment by mckaywrigley** [comment]
Unfortunately that's going to be a problem with the library we use for Markdown.

**Comment by schihei** [comment]
Understand. Thank you very much for your quick response. I really like the project.
