### ISSUE TITLE
feature request: i18n / i10n support

### ISSUE THREAD

**Issue by vOwl** [mckaywrigley/chatbot-ui#1140]
Hi there, 
awesome work for v2.0 - congrats.
Localized UI like in v1.0 would be great.
You like to support.

**Comment by mckaywrigley** [comment]
I have this on my list to basically port over what we had on V1 over to V2 for this.

Really want to make sure we support many languages.

I'll see if I can get the groundwork done on this over the weekend and then people can submit PRs in for specific locales.

**Comment by mckaywrigley** [comment]
Just to circle back on this it is coming as part of our big sqlite update coming later this week.

**Comment by mckaywrigley** [comment]
Groundwork has been completed. I will begin translations this weekend.
