### ISSUE TITLE
Reverse proxy issue - How to expose localhost:3000 internal IP to LAN? (e.g., 192.168.1.x:3000)

### ISSUE THREAD

**Issue by mysterium-coniunctionis** [mckaywrigley/chatbot-ui#1143]
Trying to access Chatbot-UI from my reverse proxy that is on 192.168.1.4 (ports 80/443 forwarded to this address). My laptop is on 192.168.1.17. When I am attempting to reverse proxy chatbot.website.url from http://192.168.1.17:3000, I am able to pull up the Chatbot-UI front-end, but I receive all sorts of odd errors related to CORS and other security issues in the browser. Chatbot-UI hosted locally @ http://localhost:3000 works perfectly. I want to be able to access this from my phone and other computers which I am currently unable to do. I want to host locally, not cloud based. Strangely, I can access the Supabase front-end locally hosted via the same reverse proxy without issue, works perfectly.

Does my question make sense and is this the correct place to ask about it?

Thank you for any help.

**Comment by SinanAkkoyun** [comment]
I use Caddy as a reverse proxy and it works like a charm

**Comment by Bortus-AI** [comment]
#1117
Add 192.168.1.17:3000 to the allowed list per this comment

**Comment by mysterium-coniunctionis** [comment]
Thank you for sharing this. This fix allows me to use my reverse proxy on a desktop computer, but for some reason, my local-llm's through Ollama (m1 macbook pro) only work on localhost:3000, but not through the reverse proxy. iPhone/iOS still comes up with the same errors even after applying this. Feeling grateful for some progress and will come back to this tomorrow once I've had some sleep.

**Comment by Bortus-AI** [comment]
Welcome. I have the same issue. Still looking for a fix

**Comment by mysterium-coniunctionis** [comment]
@Bortus-AI Thank you for the welcome, though, I definitely hear some ominous music playing in the background as you say it related to this issue. Are you saying that accessing local-LLMs (Ollama) via locally hosted through reverse proxy is at present a known yet unresolved issue or something else? I am not a professional developer (actually, at present, studying for my psychologist license but an enthusiastic tinkerer with all things AI/LLM, religiously writing down my ideas until my technical know-how can catch up with them 😆), so I don't want to pull out my hair trying to resolve something that is apparently not resolved if that is what you are saying. Currently, my solution for using my Ollama LLMs via my reverse-proxy is the Ollama-web-ui project, but Chatbot-UI is just so goddamn beautiful in terms of the attention to front-end aesthetics that it has entranced me enough to want to use this exclusively as soon as possible.

**Comment by mysterium-coniunctionis** [comment]
@Bortus-AI Might this have anything to do with it?

http://host.docker.internal:11434
vs
http://localhost:11434

???
