### ISSUE TITLE
Autoscroll gets interrupted each time markdown is being used

### ISSUE THREAD

**Issue by SinanAkkoyun** [mckaywrigley/chatbot-ui#1145]
As soon as `text like this gets printed`, the autoscroll feature resets on mobile, how can one fix that?

**Comment by mckaywrigley** [comment]
I'll raise my hand right now and say I'm super guilty of mobile support being absolutely terrible (right now).

I want to make an effort to fix this, but for the short term we'll definitely focus on desktop layouts.

**Comment by mysterium-coniunctionis** [comment]
@mckaywrigley Is it a safer bet to wait until you make an announcement of improved mobile support before pulling my hair out trying to sort out how to get my mobile reverse proxy working? 🙃
