### ISSUE TITLE
【Bug】Uploading a docx file failed and when using Chinese dialogue, occasionally there are '��' in the answers.

### ISSUE THREAD

**Issue by ghost** [mckaywrigley/chatbot-ui#1147]
Uploading a docx file failed 
![image](https://github.com/mckaywrigley/chatbot-ui/assets/154501119/3d289f13-26a8-470f-bbe3-f39a8c51daa4)
![image](https://github.com/mckaywrigley/chatbot-ui/assets/154501119/195d553a-99d2-4a4e-bfa2-71944295b58e)

there are '��' in the answers.
![image](https://github.com/mckaywrigley/chatbot-ui/assets/154501119/726b38ae-8aa8-4767-8774-98d6b48b0595)

**Comment by mckaywrigley** [comment]
I suspect that the Docx document loading method is decently buggy. It's admittedly a tougher file format to work with for RAG.

If anyone sees and has ideas PRs here would be awesome.

**Comment by ghost** [comment]
According to the test, processing docx files actually calls \app\api\retrieval\process\route.ts and does not use \app\api\retrieval\process\docx\route.ts

**Comment by mckaywrigley** [comment]
Try pulling? Should work. Made a type check change just in case that was the bug.

**Comment by Subhahdip** [comment]
Hi guys!! just move into web dev recently. can you guys help me get my first contribution in chatbot-ui? really excited :)

**Comment by hikafeng** [comment]
> Try pulling? Should work. Made a type check change just in case that was the bug.

[Fix Process Docx Bug](https://github.com/HikaFeng/chatbot-ui/commit/420dffc30349e14445fe1ac3db59684a2e20c4ac)

and  can you guys help me get my first contribution in chatbot-ui? really excited!!!!!!!!!!!!
