### ISSUE TITLE
Question: any timeline for the desktop app ?

### ISSUE THREAD

**Issue by younes-io** [mckaywrigley/chatbot-ui#1148]
Two questions actually:

1 - What is the timeline for the release of a desktop app ?
2 - Any discussions section in the repo to ask questions instead of opening issues?

Thank you

**Comment by mckaywrigley** [comment]
End of next week. Have to get sqllite working 1:1 with our postgres stuff and then package the whole thing into (likely) a Tauri app.

Just enabled discussion on the repo - should be a good place for people!

**Comment by younes-io** [comment]
Thank you for your feedback @mckaywrigley
