### ISSUE TITLE
bug?: using .env.local

### ISSUE THREAD

**Issue by saliksik** [mckaywrigley/chatbot-ui#115]
I have deployed a web application on Vercel and utilized the .env.local file. However, upon visiting my site and clicking on the button "click if using a .env.local file", it keeps loading without displaying anything (Loading...), although the chat function is operational. A hard refresh of the site is necessary for the model and system prompt to appear.

![Web capture_24-3-2023_172223_llegomark0018976 vercel app](https://user-images.githubusercontent.com/122975898/227478225-933a1ff0-5b1f-499a-863b-8d10665c97ad.jpeg)
![Web capture_24-3-2023_172159_llegomark0018976 vercel app](https://user-images.githubusercontent.com/122975898/227478230-6d446f5e-ca1d-44ca-b1b5-8305159b248c.jpeg)
![Web capture_24-3-2023_172145_llegomark0018976 vercel app](https://user-images.githubusercontent.com/122975898/227478236-fc2e3c8a-e9d1-4ead-b996-93893b430f28.jpeg)

**Comment by saliksik** [comment]
Can the web app automatically detects if the .env.local is present and directs the user to chat without clicking anything?

**Comment by thomasleveil** [comment]
_related to #105_

**Comment by mckaywrigley** [comment]
fixed!
