### ISSUE TITLE
 I don't even know where I went wrong

### ISSUE THREAD

**Issue by Somnus1437** [mckaywrigley/chatbot-ui#1151]
![7B557F45F4-F166-402c-9813-369E23CC45B](https://github.com/mckaywrigley/chatbot-ui/assets/144725707/b8ecadd6-04bd-4e7c-918d-9503783e65ed)
![7BDFF6E576-D740-428c-925D-AF9FC5A16B32](https://github.com/mckaywrigley/chatbot-ui/assets/144725707/377d7ece-3581-4d6c-99f5-0f2629eabb1c)
I couldn't get in at all. chatbot-ui.aiptl.com

**Comment by mckaywrigley** [comment]
Trying to keep issues to code. For setup questions the discussions tab may be more suitable.
