### ISSUE TITLE
"Could not authenticate user"

### ISSUE THREAD

**Issue by Success2014** [mckaywrigley/chatbot-ui#1154]
I was following the steps till step 4 and was able to visit the localhost:3000.
However, it asked me to login. No matter what email and password I used, I'm unable to login. 
It says "Could not authenticate user".
I was unable to sign up either.

**Comment by instrido** [comment]
This isn't documented but for a supabase newbie, the steps are to go to your local supabase dashboard and create a user under the authentication tab on the extreme left side sidebar/navbar/whatevbar. Once you have created a user, you should be able to login.

**Comment by SaqibSyed1014** [comment]
@instrido I tried adding a new user in supabase dashboard and tried to login in local chatbot-ui instance but it still returned could not authenticate user. I checked api url in network tab & it is http://localhost:3000 is it correct or I missed some steps?

**Comment by mckaywrigley** [comment]
> I was following the steps till step 4 and was able to visit the localhost:3000. However, it asked me to login. No matter what email and password I used, I'm unable to login. It says "Could not authenticate user". I was unable to sign up either.

Try test@test.com and "password" just to do one last check. That should work as both are valid inputs.

**Comment by GrannyProgramming** [comment]
> This isn't documented but for a supabase newbie, the steps are to go to your local supabase dashboard and create a user under the authentication tab on the extreme left side sidebar/navbar/whatevbar. Once you have created a user, you should be able to login.

This resolved the issue for me, to find the local dashboard just navigate to your local Dashboard at http://localhost:54323/, and access the database directly.

Below image shows where to navigate to add user 

![image](https://github.com/mckaywrigley/chatbot-ui/assets/53883501/e3b1ef42-848f-498d-8119-21e08f695aec)
