### ISSUE TITLE
Bug: File upload using german umlaute as "name" doesn't work

### ISSUE THREAD

**Issue by vOwl** [mckaywrigley/chatbot-ui#1156]
Uploading a pdf file and giving a name containing german umlaute like "ö" doesnt work.
Using "oe" instead of "ö" works.

- ❌ works NOT: "ChatGPT_im_PM_MOVR_ManagementCircle_Köln" 

<img width="460" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/10940689/3eaf297b-848d-4559-a01f-ce9c65e4c36b">

- ✅ WORKS: "ChatGPT_im_PM_MOVR_ManagementCircle_Koeln"

<img width="459" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/10940689/c02ff246-104a-44d5-97ce-f3236e472e99">

**Comment by siavashvj** [comment]
This is true for all non-english standard chararacters, such as åäö for us here in Sweden.
