### ISSUE TITLE
Bug: Ollama model context is incorrect

### ISSUE THREAD

**Issue by peperunas** [mckaywrigley/chatbot-ui#1157]
First of all, great work!

Second: I primarily use Ollama and have found out that the UI does not update the context correctly according to the selected model. AFAIK, Ollama provides this information in the API.

Thank you!

**Comment by mckaywrigley** [comment]
Apologies - can you elaborate just a bit on what you mean by the UI isn't updating the context correctly?

**Comment by peperunas** [comment]
My bad!

For example, I am using `mistral` that supports a `32k` context. The UI uses up to ~`3k` tokens, instead:

<img width="607" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/6033387/5a2137f8-0f63-4384-b8ca-253ab5ead3c4">

**Comment by mckaywrigley** [comment]
Ah I see. Do we know if context length for each model is accessible via Ollama API?
