### ISSUE TITLE
Feature Request: Option for users to update password and add forgot password link on login page.

### ISSUE THREAD

**Issue by masonjames** [mckaywrigley/chatbot-ui#1160]
Ask me how I discovered this was missing... 🤦‍♂️

**Comment by mckaywrigley** [comment]
I can get "forgot password" done today.

**Comment by masonjames** [comment]
Thanks so much! I was manually sending password requests and magic links from within supabase admin, but the email links always just refreshed on the /login page.

**Comment by mckaywrigley** [comment]
@masonjames Added!

For email running locally you can access the email server on `http://localhost:54324`.
