### ISSUE TITLE
Feature request: Conversation tokens' calculation

### ISSUE THREAD

**Issue by peperunas** [mckaywrigley/chatbot-ui#1165]
It would be great to have a calculation of the token used in the conversation and the unsent message, such that the user can adjust accordingly.

Ideally, this should also take in account the files in the conversation. If the files' tokens exceed the model's capability, the user should be informed / the message should not be sent.

**Comment by mckaywrigley** [comment]
Better and more visible token handling is something I'd love to support.

The tricky part is mostly UX.

I don't want things to be too overwhelming for everyday users, but I'd like to give more granular control to power users.

**Comment by peperunas** [comment]
That's a good point. I have been using this project (https://big-agi.com/) for a while and they do a great job of showing this.

**Comment by mckaywrigley** [comment]
I'm playing around with a "power user" mode that toggles on features like this. Not 100% sure if it'll be fully supported yet. Need to finish assistants & tools and then I'll probably circle back on things like this.
