### ISSUE TITLE
Build does not complete

### ISSUE THREAD

**Issue by ghost** [mckaywrigley/chatbot-ui#1168]
**Describe the bug**
NPM getting stuck.

**To Reproduce**
1.  Follow local install steps for Chatbot-UI
2.  using Ubuntu 23.10.1 Mantic LXC in Proxmox 8.1
3.  Node.js 22.11.0 via Voltra

**Expected behavior**
Chatbot-ui will build and launch to localhost.

**Additional context**
NPM gets hung up here:

```
> chatbot-ui@2.0.0 dev
> next dev

   ▲ Next.js 14.0.2
   - Local:        http://localhost:3000
   - Environments: .env.local

 ✓ Ready in 2.1s
```

Sometimes it will progress slightly further but then installs indefinitely. Restarting LXC, re-creating LXC, etc. does not solve the issue.

**Comment by adoolaard** [comment]
Same here!

**Comment by im-calvin** [comment]
Bump! I got it running on Windows + WSL, but I tried deploying to both Debian and Ubuntu server and it didn't work for me. Having some weird Webpack bug or other similar stuff. Will keep you guys updated if I find a fix

**Comment by im-calvin** [comment]
I forgot to install Ollama, that fixed the build bug for me.
