### ISSUE TITLE
Feature requests: code interpreter assistant

### ISSUE THREAD

**Issue by xycjscs** [mckaywrigley/chatbot-ui#1169]
Thanks for your work!

I believe assistants with code interpreter will bring this project to a higher level. 

Not only users can create their own assistants, I also hope users can use OpenAI hosted assistants via only assistant ID. Those assistants will be created by us on the OpenAI websites to protect information used in the assistants. Thanks a lot.

**Comment by xycjscs** [comment]
Btw to give assistant ID to all users. We also need a tool to add same presets/prompts/assistants to all users. Maybe it will be done by creating public presets/prompts/assistants at database.

**Comment by mckaywrigley** [comment]
Here's what we have on the short term roadmap that you mentioned as I understood it:
- Code Interpreter
- Use your OpenAI assistants
- Easy sharing of assistants/prompts/etc

Expect that within the next 2 weeks!
