### ISSUE TITLE
"Error consuming stream: TypeError: Error in input stream" with Mistral Small/Medium code answers

### ISSUE THREAD

**Issue by vnguyen42** [mckaywrigley/chatbot-ui#1170]
When using Mistral Medium or Small, completions are often stopped in the middle of the answer when it include code, with error in the console :
"Error consuming stream: TypeError: Error in input stream"

Steps to reproduce : 
1. Ask to improve a piece of code that's 700 tokens long
2. Completion of code get stopped out after ~300 tokens in my case

![test_2](https://github.com/mckaywrigley/chatbot-ui/assets/16151212/84bc5ba0-073e-422d-899b-5cbae6c0f752)
![test_1](https://github.com/mckaywrigley/chatbot-ui/assets/16151212/1acfc721-36b6-4295-8231-d666c2f1dcbb)

**Comment by mckaywrigley** [comment]
There appear to be errors in how Mistral and Perplexity are parsed on their ends.

This is a high priority bug.

If anyones sees this and wants to dig in great PR opportunity.

**Comment by mckaywrigley** [comment]
Perplexity is fixed.

I haven't been able to replicate the Mistral issue but the code for this is still ambiguous.

Eyeing this.

**Comment by mckaywrigley** [comment]
Fixed.
