### ISSUE TITLE
[Bug] '��' in responses for Chinese/Japanese/Korean requests

### ISSUE THREAD

**Issue by haotian-liu** [mckaywrigley/chatbot-ui#1171]
Related to #1147, but it happens to pure chat queries as well. Solving this may solve #1147 as well.

> Reference prompts to reproduce (Chinese/Japanese/Korean)
> 写一篇1000字关于人类与AI的议论文
> 人間とAIに関する1000字の論文を書いてください。
> 인간과 AI에 관한 1000자 논의 글을 쓰세요.

<img width="723" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/6631389/453c0988-f56e-4faa-93a1-15e375d28c26">
<img width="731" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/6631389/7f54655c-b26a-46e0-a326-1635b80e1253">

**Comment by gijigae** [comment]
Thanks for raising the issue! What is your setup for Chatbot UI? I have two environments; one is hosted in Vercel and the other is deployed locally. For me, the issue you reported only occurs in former.

**Comment by haotian-liu** [comment]
@gijigae nice catch! it's on vercel (and with the online supabase). not sure which one is the cause.

**Comment by gijigae** [comment]
My local environment is connected to the Supabase web service. Thus, the issue would be something to do with the way Vercel is hosted. I will try to deploy Chatbot UI into another hosting service and will report back in case the issue persists.

**Comment by xycjscs** [comment]
Same problem on the Vercel. No idea how to debug.

**Comment by Pirogiran** [comment]
On Netlify everything works fine, compared to Vercel.

**Comment by xycjscs** [comment]
Moved project to Netlify, this problem avoided. 
I will keep looking on this issue, hope it could be solved.
some reference  https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/507

**Comment by mckaywrigley** [comment]
Combo of an OpenAI/Vercel issue.

**Comment by xycjscs** [comment]
brothers, it is a bug. Problem has been solved. I will make a pull request quickly. 
Chinese/Japanese/Korean can keep following this project with Vercel deployment and avoid compatible problems at Netlify.
