### ISSUE TITLE
[Bug] Files tab only displays folders when (at least one) file is uploaded

### ISSUE THREAD

**Issue by 0-hero** [mckaywrigley/chatbot-ui#1173]
GIF Below
![Bug](https://github.com/mckaywrigley/chatbot-ui/assets/9160496/aad269dd-0253-4006-a107-9ee677a9ba4b)

Once a file is uploaded and moved into the folder, then folders are displayed

**Comment by mckaywrigley** [comment]
Changed the UX to fix this issue.
