### ISSUE TITLE
Error: Invalid Server Actions request.

### ISSUE THREAD

**Issue by taype** [mckaywrigley/chatbot-ui#1174]
**`x-forwarded-host` header with value `localhost:3000` does not match `origin` header with value `192.168.100.111:3000` from a forwarded Server Actions request. Aborting the action.
 ⨯ Error: Invalid Server Actions request.
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
**
![微信截图_20240115152941](https://github.com/mckaywrigley/chatbot-ui/assets/117689950/03a52457-40d2-4d7f-bdbe-fbbc260831ba)

**Comment by im-calvin** [comment]
I'm seeing this potential fix: https://github.com/vercel/next.js/issues/58295. Basically boils down to upgrading Next to 14.0.3 or downgrading to 14.0.0

**Comment by A8IO** [comment]
I had this issue whilst getting this to work on a non-localhost IP, might be worth a try using the settings described in [1113](https://github.com/mckaywrigley/chatbot-ui/issues/1113)

**Comment by taype** [comment]
> I'm seeing this potential fix: [vercel/next.js#58295](https://github.com/vercel/next.js/issues/58295). Basically boils down to upgrading Next to 14.0.3 or downgrading to 14.0.0

Thank you very much, I upgrade Next to 14.0.3 ,and it worked for me .
