### ISSUE TITLE
idk how to name stuff im new to this, stuff aint work

### ISSUE THREAD

**Issue by BananPrzydawka** [mckaywrigley/chatbot-ui#1176]
shit dont work. every time i start it up, it takes me to the default page, and then after clicking start chatting skips login goes straight to chat, and proceeds to not work. throws error:

Unhandled Runtime Error

Error: JSON object requested, multiple (or no) rows returned
Source

db/profile.ts (12:10) @ getProfileByUserId

  10 |
  11 | if (!profile) {
> 12 |   throw new Error(error.message)
     |        ^
  13 | }
  14 |
  15 | return profile

im gonna try to learn the project myself and fix this, but ive never worked on anything even remotely this big

**Comment by Jkallus** [comment]
I'm also seeing this sometimes. On my main computer it works and I can make accounts and login. When I access it from any other computer it skips login and shows this error if I already have a cookie. If I try in incognito mode it does bring me to the login page but regardless of putting in valid credentials or making a new account after logging in it has this error.

**Comment by mckaywrigley** [comment]
In a few days we'll be adding a sqlite version without auth that should just work out of the box.

Hang tight and we'll have a much easier version to run!

**Comment by rahulvrane** [comment]
Hi, thanks for this. Just checking - is the sqlite version already out? I keep getting this same error - even on fresh installs..
