### ISSUE TITLE
Token is different

### ISSUE THREAD

**Issue by neosfm** [mckaywrigley/chatbot-ui#1179]
Hello, I'm new into this. I sent a message saying:
"Hello!"
and it replied:
"Hello! How can I assist you today?"

The prompt is: "You are a friendly, helpful AI assistant."

I'm using GPT-4 Turbo. Using "https://tiktokenizer.vercel.app/" i should only have used 35 Tokens, but when i look it up in my OpenAI Platform, i have used 42 Tokens. How is this possible?, can you help me?
<img width="893" alt="Untitled" src="https://github.com/mckaywrigley/chatbot-ui/assets/76944576/ff286e41-e200-4313-8796-fa6c58a571fe">

**Comment by mckaywrigley** [comment]
Check `build-prompt.ts`. We add a few tokens behind the scenes.

**Comment by neosfm** [comment]
okay thank you!
