### ISSUE TITLE
[Bug] Removing the default Ollama model makes impossible to change model

### ISSUE THREAD

**Issue by peperunas** [mckaywrigley/chatbot-ui#1184]
Hello!

I removed the default model I setup in the UI. After that, I could not choose a different model.

<img width="353" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/6033387/45010b97-6600-46bf-aea6-6459fc6ef5fd">

<img width="631" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/6033387/4d6d8b06-00cf-49b3-b342-ce537b7ee541">

(Where `dolphin-mistral` is the model that has been removed server-side)

**Comment by mckaywrigley** [comment]
Where did you remove the default model?

**Comment by davidamacey** [comment]
Second this issue.

### Issue

If I remove a model or Ollama from the system, AFTER I have already created a user with a specified model, the UI does not respond properly.  I get the same images as display.

### Remedy Attempts

I logged out and logged back in as the same user.  I get the same result

If I log out and create a new user the UI returns to normal, I can see the current models served by ollama

### Unknown solution

It seems the database keeps track of the models used by the user, so if the model is removed from the system there is a conflict in the validation?

### Interim Solutions

1. Log out and create a new user.
2. Redeploy stack to reset users
3. Delete users from Supabase web GUI

I hope this helps shed light on the situation.  Thanks for the hard work!

**Comment by mckaywrigley** [comment]
@davidamacey I think I understand. So you're removing models from Ollama that have been previously used in your UI, and that issue causes the model selector to break?

**Comment by davidamacey** [comment]
@mckaywrigley Correct if I reset or change ollama in Docker or cli, then it seems that the frontend doesn't know where to go to get the model it previously was assigned, that now does not exist.

I only found this when I was iterating on the different deployment methods, and it hard broke like @peperunas commented as well.

**Comment by mckaywrigley** [comment]
Just pushed a change that will fix the model select disappearing when you remove an ollama model from your system.
