### ISSUE TITLE
"Your account is not active" using OpenAI API, although there is no issue (screenshot included) 

### ISSUE THREAD

**Issue by aodrasa** [mckaywrigley/chatbot-ui#1187]
Having a stranger issue (followed the YouTube tutorial to make sure everything was correct), where when trying to use an OpenAI model, no matter if I set the default key in .env.local or in the chat session, I get an error "Your account is not active, please check your billing details on our website."

Tested my OpenRouter models and they work fine, and also tested multiple OpenAI API keys, as well as confirming they work in MacGPT.

Any suggestions?

![Screenshot 2024-01-16 at 12 20 18 pm](https://github.com/mckaywrigley/chatbot-ui/assets/121209163/00d2b3ac-3c5b-4c68-8407-a6712045990d)
![Screenshot 2024-01-16 at 12 22 48 pm](https://github.com/mckaywrigley/chatbot-ui/assets/121209163/c72112ba-8fe6-48af-b390-26e881d6b545)
![Screenshot 2024-01-16 at 12 23 43 pm](https://github.com/mckaywrigley/chatbot-ui/assets/121209163/3608241b-9bff-4677-92ea-6ee658e92890)

**Comment by hikafeng** [comment]
You should check your OpenAI account settings to see if there are any unpaid bills. Make sure that a payment method for settling bills is set up.

**Comment by mckaywrigley** [comment]
Check OpenAI Account via their site. That's an issue with their billing.
