### ISSUE TITLE
How hard would it be to shift to noSQL (e.g. MongoDB)? 

### ISSUE THREAD

**Issue by jackgofff** [mckaywrigley/chatbot-ui#1188]
How hard would it be to shift to noSQL (e.g. MongoDB)?
Curious why you chose SQL and/or if you think a specific combo of the two can be useful.

**Comment by mckaywrigley** [comment]
We're adding a Sqlite option but I have zero interest in no-SQL DBs, so I won't be supporting it.

The schema is pretty clear in the migration files, so if you wanted to port on your own it should be fairly straightforward.
