### ISSUE TITLE
Switching Users Does Not Work Properly

### ISSUE THREAD

**Issue by davidamacey** [mckaywrigley/chatbot-ui#1189]
### Issue

Logging in with User 1 I have a few chats.  Log in as User 2 I still see the previous login chats.  If I refresh the page, then it loads the User 2 chat history.  Log out and log in as User 1, I see User 2 chat history, once I refresh it updates.

This issue seems to be related to a cookie.  If I clear the browser history/cookies it wipes the information.

### Potential Solution 

I am not a front-end dev, but I speculate it has to do with the session and state between users.

Is there a check that can verify profile name of logged in user?

It would be great to have multiple users logging into the application.

Thank you!

**Comment by mckaywrigley** [comment]
Ah - this is an issue with global state not getting reset upon logout.

This will only occur when signing in on the same browser session.

I'll fix this!

**Comment by mckaywrigley** [comment]
@davidamacey This should be fixed now, but just checking in if you found a condition we didn't cover.

**Comment by davidamacey** [comment]
Sounds great, thank you!

Not at the moment, thanks for providing such quick updates!

**Comment by mckaywrigley** [comment]
Awesome. If it pops back up just let me know and I'll investigate further!
