### ISSUE TITLE
suggest adding username and password login

### ISSUE THREAD

**Issue by luckfu** [mckaywrigley/chatbot-ui#119]
suggest adding username and password login

**Comment by Pharrcyde** [comment]
I would love this. If possible, something akin to what [cogentapps/chat-with-gpt](https://github.com/cogentapps/chat-with-gpt) does. You're able to login to view and search previous conversations.

**Comment by mckaywrigley** [comment]
I’ve considered a hosted version with auth and synced storage (while keeping it open source of course) but it’s quite an undertaking.

I’m a bit spread thin at the moment.

**Comment by michael7908** [comment]
thank you for your amazing project and I will explore how to add login page with help of ChatGPT itself:-)

**Comment by jralduaveuthey** [comment]
@michael7908 did you manage to add a login? I would be interested on this for personal use

**Comment by jralduaveuthey** [comment]
I just saw this pull request that looks quite good https://github.com/mckaywrigley/chatbot-ui/pull/215
