### ISSUE TITLE
Feature Request: Developer mode / prompt engineering mode

### ISSUE THREAD

**Issue by MatthewScholefield** [mckaywrigley/chatbot-ui#1190]
First of all, super awesome work with the latest version! So basically, the current feature set seems to cover CUJs for interacting directly with these LLMs. However, as a developer a common CUJ is to work on prompt templates for prototyping LLM related apps and scripts. Would this be something you'd be interested in adding? I'm considering implementing the feature locally since the stack looks pretty nice to work with and I really am interested in the feature.

At the simplest stage it would be like a "chat" but each chat also shows the system prompt in visible part of the UI and chat messages would be editable by default. Ideally though it could even have support for basic templating with something like mustache and the templates could be exported to some JSON or something for easy use in code.

Let me know your thoughts on this.

**Comment by mckaywrigley** [comment]
I've played around with versions of this in the past, and I think this should mostly just be its own application.

The complexity goes a bit beyond what I want to support, though I do think it's a worthy addition that may be better suited for a dev-heavy fork of this.
