### ISSUE TITLE
[request] Add litellm support

### ISSUE THREAD

**Issue by Trapper4888** [mckaywrigley/chatbot-ui#1198]
[Litellm](https://github.com/BerriAI/litellm) is an open source proxy/router/load balancer to expose multiple LLM api (openai, mistral, together, openrouter, TGI, locally served, ...) through [one openai api endpoint](https://docs.litellm.ai/docs/simple_proxy).
It also have a /model route to load the list of available models.[(here is the swagger)
](https://litellm-api.up.railway.app/#/)

If we could add one custom openai endpoint to chatbot-ui, through litellm we could add any endpoints.

**Comment by mckaywrigley** [comment]
This looks interesting. I certainly feel the pain of trying to make all APIs compatible with the code. I'll look into it.

**Comment by ishaan-jaff** [comment]
@Trapper4888 I'm the litellm maintainer - can we hop on a call to learn how you use litellm ? 
Link to my [calendar](https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-02) for your convenience: 

Also I can make a PR to this repo for using litellm cc @mckaywrigley
