### ISSUE TITLE
[BUG] Advanced Settings Sync Across Different Models Instead of Being Model-Specific

### ISSUE THREAD

**Issue by AdventistVirtual** [mckaywrigley/chatbot-ui#1199]
[BUG] Advanced Settings Sync Across Different Models Instead of Being Model-Specific

### Introduction:
Hey McKay, I appreciate the great work you've been doing. I've noticed a few bugs during my usage and wanted to contribute by detailing them here for further investigation and resolution.

### Description:
I've encountered an issue where the advanced settings in our system are not linked individually to each AI model. Instead, they are synchronized across all models. This becomes problematic when switching between different models, such as GPT-3.5 and GPT-4 Turbo, as the context window and other settings that were optimal for one model are not necessarily suitable for another.

### Steps to Reproduce:
- Select GPT-3.5 and adjust advanced settings to a specific configuration.
- Switch to GPT-4 Turbo.
- Observe that the advanced settings remain the same as they were set for GPT-3.5.

### Expected Behavior:
I would expect the advanced settings to be model-specific, allowing for customization that aligns with the capabilities and requirements of each individual model.

### Actual Behavior:
The advanced settings remain constant across different models, leading to potential inefficiencies and confusion, especially when the settings suitable for one model are not applicable for another.

### Impact:
This issue impacts the usability and efficiency of model switching, particularly for users who frequently alternate between different AI models and require tailored settings for each.

### Suggested Solution:
Implementing model-specific advanced settings would greatly enhance user experience. This way, users can set up optimal configurations for each model independently, ensuring the settings are always aligned with the selected model's capabilities and limitations.

### Attachment:
![Advanced Settings](https://github.com/mckaywrigley/chatbot-ui/assets/128757363/bac1f0a7-e831-424b-9f98-f08b9448f08c)

**Comment by jsweetzer-ea** [comment]
I believe your use-case is what Presets are for, applied via Quick Settings when creating a new chat. The Workspace default is just a default for any new chat created. 

On a related note @mckaywrigley - it would be very helpful to be able to see the Preset / other settings applied to a chat after it is created, assuming that it does persist for the entire chat context?

**Comment by mckaywrigley** [comment]
Workspace defaults are the settings that you workspace boots up with when it is selected.

@jsweetzer-ea is correct - the functionality that you're looking for is what the "Presets" feature is for. You can create infinite combinations of settings that you can reuse at any time via the "Quick Settings" selector in new chats.

I agree that setting visibility would be nice after creation. I will add that tonight.

**Comment by xycjscs** [comment]
I found context length is not settled as preset settings.
for instance, when i start with gpt-3 and apply gpt-4 presets, only modified gpt-4 preset is used (modified because the context length is not following gpt-4 preset). If i apply the same preset twice, then context will follow the preset.
How to fix this problem?
