### ISSUE TITLE
Dialog Context gets stuck

### ISSUE THREAD

**Issue by markusstrasser** [mckaywrigley/chatbot-ui#12]
After chatting back and forth a few times, the dialog context seems to freeze and the responses to an new query stay the same. 

Seems there is an issue with the dialogue state?
(GPT3.5 default).

**Comment by mckaywrigley** [comment]
If possible can you provide a screenshot and device? Having a tough time reproducing the bug. Thanks!

**Comment by thomasleveil** [comment]
same thing here, I can see the vertical scroll bar updating as more text in included in the page, but the page does not automatically scroll down and the page is frozen (cannot use the mouse wheel or arrow keys to scroll down).

Once the response is finished to be included in the page, the freeze disappears and we can scroll down to see the newly added text

**Comment by mckaywrigley** [comment]
@markusstrasser Is this your issue as well, or is it actually affecting responses? Trying to clarify the different between these descriptions.

**Comment by thomasleveil** [comment]
ChatGPT suggests this fix : 

This code is blocking the browser main thread because it is using a while loop to read data from a stream. To fix this, you can use the ReadableStreamDefaultReader API to read the stream in chunks asynchronously. Here's an example of how you can modify the code to use the ReadableStreamDefaultReader API:

```js
const reader = data.getReader();
const decoder = new TextDecoder();
let isFirst = true;
let text = "";

async function readStream() {
  const { value, done } = await reader.read();
  if (done) {
    return;
  }

  const chunkValue = decoder.decode(value);
  text += chunkValue;

  if (isFirst) {
    isFirst = false;
    const updatedMessages: Message[] = [...updatedConversation.messages, { role: "assistant", content: chunkValue }];

    updatedConversation = {
      ...updatedConversation,
      messages: updatedMessages
    };

    setSelectedConversation(updatedConversation);
  } else {
    const updatedMessages: Message[] = updatedConversation.messages.map((message, index) => {
      if (index === updatedConversation.messages.length - 1) {
        return {
          ...message,
          content: text
        };
      }

      return message;
    });

    updatedConversation = {
      ...updatedConversation,
      messages: updatedMessages
    };

    setSelectedConversation(updatedConversation);
  }

  await readStream();
}

readStream();
```

In this modified code, we use an async function readStream to read the stream in chunks asynchronously. We call this function recursively until the stream is done. This way, the browser main thread is not blocked while waiting for the stream to be read.

**Comment by mckaywrigley** [comment]
I changed scroll to "auto" from "smooth" which fixed the scroll issue (I think). @thomasleveil Let me know if that fixes the issue you had.

It sounds like @markusstrasser may have a different one so I'll keep this open until I confirm all issues are fixed!

**Comment by markusstrasser** [comment]
Sure. Screenshots attached. I'm on macOS venture. MBP M1. 

My best guesses are that either

a) the **temperature being set at 0** which might push to model to give deterministic responses after a while
or
b) **the conversational context** where the model is not receiving enough context from the conversation history. In the code (charLimit) clips the messages sent to the API.

I'll experiment a bit but it's probably closer to b) since I would assume openAI would mention the temperature thing in their docs or disincentivize setting it to 0.

In the code 

` const charLimit = 12000;
    let charCount = 0;
    let messagesToSend = [];

    for (let i = 0; i < messages.length; i++) {
      const message = messages[i];
      if (charCount + message.content.length > charLimit) {
        break;
      }
      charCount += message.content.length;
      messagesToSend.push(message);
    }`

It seems that after a while you'd always send the first few messages to the API and break before the new messages are added. If the charLimit needs to be 12000 -- maybe loop over the list in reverse? So older instead of newer messages get clipped?

Also, do we know the default params that OpenAI uses for their  3.5 turbo chatGPT web UI? I'd love to set them as defaults as to compare behavior


<img width="786" alt="Screenshot 2023-03-19 at 9 47 10 AM" src="https://user-images.githubusercontent.com/3579138/226164084-2f2bac68-d8f5-4eb1-9e9b-5149f31a922a.png">
<img width="605" alt="Screenshot 2023-03-19 at 9 47 25 AM" src="https://user-images.githubusercontent.com/3579138/226164081-5a363a75-0cd1-4f17-8c00-f0c338c9f0eb.png">
<img width="535" alt="Screenshot 2023-03-19 at 9 47 30 AM" src="https://user-images.githubusercontent.com/3579138/226164079-327fe6f9-b140-427d-b148-0cee3dd3346f.png">
<img width="620" alt="Screenshot 2023-03-19 at 9 47 35 AM" src="https://user-images.githubusercontent.com/3579138/226164077-2c22e66d-5694-49a8-b0c0-7c5e2ffd27b9.png">
<img width="589" alt="Screenshot 2023-03-19 at 9 47 42 AM" src="https://user-images.githubusercontent.com/3579138/226164075-91ead16f-d840-4d93-9cdb-aead077578e0.png">
<img width="618" alt="Screenshot 2023-03-19 at 9 47 47 AM" src="https://user-images.githubusercontent.com/3579138/226164074-29cc0411-bdab-4361-b5ed-c2d14a9b0d05.png">

**Comment by mckaywrigley** [comment]
Thanks so much for this! We fixed the bug that was incorrectly setting the context. The new messages were being removed instead of added. If you pull you should see that fixed for you.

I'll be adding the ability to replace the default prompt with your own in the next 2 days, so you'll be able to play around with that.

Let me know if the bug fix we patched in fixes this.

**Comment by markusstrasser** [comment]
Thanks for the fix! Btw, is there a reason for the 4000 messageLimit or 12000 charLimit? I'm trying to find the settings so that the behavior is as close as possible to the one at chat.openai.com as to use the client as my main UI to chatGPT.

**Comment by mckaywrigley** [comment]
API limit is 4K tokens total. It’s about 1k tokens for the message, and 2-3k for context. Stretches it out as much as possible. I will have options for configuration this week. You’ll be able to customize it.
