### ISSUE TITLE
[BUG] Spinning Wheel on Saving Workspace Advanced Settings Changes

### ISSUE THREAD

**Issue by AdventistVirtual** [mckaywrigley/chatbot-ui#1200]
[BUG] Spinning Wheel on Saving Workspace Advanced Settings Changes

### Introduction:
Hi McKay, I've identified a bug that needs your attention. It's related to the behavior of the interface when saving changes to the workspace advanced settings.

### Description:
The problem occurs when attempting to save changes made to the advanced settings of a workspace. After making adjustments to these settings and clicking 'Save', the page transitions to a spinning wheel, indicating a loading process. However, this spinning wheel persists indefinitely, suggesting a failure in the save process or a backend issue.

### Steps to Reproduce:
- Go to the workspace advanced settings.
- Make any change to the settings.
- Click the 'Save' button.
- Observe that the page shows a spinning wheel that does not resolve.

### Attachment:
![Screenshot 2024-01-17 134853](https://github.com/mckaywrigley/chatbot-ui/assets/128757363/38abac24-e08b-4966-85f5-78c98ba9df52)

**Comment by mckaywrigley** [comment]
Which setting did you change?

I'm unable to reproduce the bug.

**Comment by AdventistVirtual** [comment]
It happens when I change the temperature or context window.

**Comment by mckaywrigley** [comment]
Still unable to reproduce.

Try restarting both Supabase and the frontend and see if that helps.
