### ISSUE TITLE
service not healthy:

### ISSUE THREAD

**Issue by saurav75068** [mckaywrigley/chatbot-ui#1201]
I keep getting this error 

![image](https://github.com/mckaywrigley/chatbot-ui/assets/127246728/07f7e1bb-4456-4c82-b26b-c60ac82a4d2d)

Steps Taken:

Downloaded the Github repository as instructed. 
Docker was pre installed. 
supabase was installed using command prompt
 - got error of service not healthy: [supabase_edge_runtime_ChatUI2.0]
 - ran supabase start --debug // next command entered.
 again got the error of "   at #serveHttp (https://deno.land/std@0.182.0/http/server.ts:258:20)

   at eventLoopTick (ext:core/01_core.js:183:11)
service not healthy: [supabase_edge_runtime_ChatUI2.0]"

Docker version I am using is 
C:\AI-Platform\ChatUI2.0>docker --version
Docker version 24.0.7, build afdd53b

**Comment by mleonard9** [comment]
Try this: https://github.com/supabase/cli/issues/1083#issuecomment-1691431279

**Comment by Onat-T** [comment]
Why is this closed? Same exact issue and the shared comment does not help. It isn't even applicable; the app does not work and `supabase start` command does not execute properly. (Pruned everything on the computer and still does not work.) 

(Thanks for your hard work by the way @mckaywrigley !)

**Comment by joseverav** [comment]
I found a similar problem. The fix mentioned above may work for mac, but not for windows.
