### ISSUE TITLE
Supabase JWT secret key, where to set?

### ISSUE THREAD

**Issue by DiamondGlassDrill** [mckaywrigley/chatbot-ui#1204]
Since 1h I try to figure out how to set my JWT secret key in chatbot ui using Supabase.

         API URL: http://127.0.0.1:54321
     GraphQL URL: http://127.0.0.1:54321/graphql/v1
          DB URL: postgresql://postgres:postgres@127.0.0.1:54322/postgres
      Studio URL: http://127.0.0.1:54323
    Inbucket URL: http://127.0.0.1:54324
      **JWT secret: super-secret-jwt-token-with-at-least-32-characters-long <<---**

Could u please tell me where in chatbot ui .env.local I can set it ?

# Supabase Public
NEXT_PUBLIC_SUPABASE_URL = 
NEXT_PUBLIC_SUPABASE_ANON_KEY=
# Supabase Private
SUPABASE_SERVICE_ROLE_KEY=

So there is no JWT secret key I can setup nor in the Supabase configs

Thanks in advance for solving this issue.

**Comment by mckaywrigley** [comment]
For this setup you do not need that value.
