### ISSUE TITLE
How do I integrate other APIs (CustomGPT)

### ISSUE THREAD

**Issue by d4ndr4d3** [mckaywrigley/chatbot-ui#1205]
I have been using CustomGPT. Not a LLM but they provide an API Key for custom apps. And, they use OpenAI and Pinecone. It is not possible for me/us to move everything from Pinecone to Supabase right now.

Api Documentation: https://docs.customgpt.ai/reference/i-api-homepage

I could build something around CustomGPT. I thought of embedchain.

But I thought of some more interesting use for Chatbot UI where there is a core public documentation in CustomGPT and many not so public documentation in Chatbot UI.

I am running Chatbot UI and studying the code right now. 

Is it too crazy? Won't work?

Any suggestions?

**Comment by edmcquinn** [comment]
I am also intrested in this! It would be really cool to be able to just make an API call to whatever service we wanted and have it display the results in the UI.

**Comment by mckaywrigley** [comment]
You can now set up tools with an OpenAPI schema (like in OpenAI's GPTs) where you can accomplish this.

**Comment by edmcquinn** [comment]
@mckaywrigley Hey. Do you have any docs on how to do this? When I setup the tool it doesn't do anything.
