### ISSUE TITLE
Show error message for login (email, password) 

### ISSUE THREAD

**Issue by im-calvin** [mckaywrigley/chatbot-ui#1206]
I've been working on a fix for showing correct error messages for incorrect email / incorrect password / password reset.

Not sure if I've seen any issues about this, but it seems like a major UI/UX fix.

I'll push it to my fork soon, but it requires some database changes, namely showing the users.email

**Comment by mckaywrigley** [comment]
We'd welcome better error messages for the user, but warning ahead of time we won't merge anything that changes the user schema here.

**Comment by im-calvin** [comment]
> user schema 

Would something like a new table called `public.users` with two fields: `id, email` be okay? I'm not sure what you mean by user schema

**Comment by mckaywrigley** [comment]
Check the login page now.

I just added better error messages by passing in the `error.message`.

Covers correct messaging for invalid emails/passwords.

**Comment by im-calvin** [comment]
I feel like it's a good step, but it still doesn't differentiate between email incorrect vs password incorrect on signup, as well as some other edge cases. Check out #1209

**Comment by mckaywrigley** [comment]
Signup errors include:
- User already exists
- Invalid email
- Invalid password

Unless I'm mistaken all should be handled as-is.

**Comment by im-calvin** [comment]
I've tried your commit, all I'm seeing from `error.message` is `Invalid login credentials`. On the backend side it's able to differentiate between the different error messages but the frontend only seems to show `Invalid login credentials`

**Comment by mckaywrigley** [comment]
Ah I see what you mean now.

I don't want to get too cute with adding new tables for the login message to be slightly more clear, though I get why you'd want it for your own deployment.
