### ISSUE TITLE
Azure API Deployment Error - Resource Does Not Exist

### ISSUE THREAD

**Issue by vv01sam** [mckaywrigley/chatbot-ui#1207]
![1](https://github.com/mckaywrigley/chatbot-ui/assets/143489008/b1998c46-c515-40de-b839-9649b2aff5dd)
Hello everyone,

I've encountered an issue after attempting to deploy an API on Azure. I'm presented with the following error message when trying to access the resource:

```
The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.
```

It's been well over a few minutes since I initiated the deployment, and I've double-checked both my resource configuration and deployment process without any luck in resolving the issue. Everything appears to be correctly set up in the Azure portal as far as I can see.

Could anyone suggest possible causes for this error and steps I might take to resolve it?

- The deployment is showing as completed in the portal.
- I have verified the resource group and service settings, and all seems to be in order.

Are there any logs or settings I should be checking? Or could this be a transient issue with Azure?

Any advice or guidance would be greatly appreciated. Thank you in advance.

**Comment by horizonchasers** [comment]
Having the same issue.  To be honest I am not sure what value we should be putting here.  
Azure OpenAI GPT-4.5 Turbo ID

Willing to build an Azure guide if I can get it working

**Comment by othmanelhoufi** [comment]
@horizonchasers  It refers to the Deployment ID of the model, for example it could be named `gpt-45-turbo` or `gpt-4-turbo` or other, it depends on deployment in your Azure OpenAI.

**Comment by mckaywrigley** [comment]
I just changed "Deployment IDs" to "Deployment Names" in the UI.

Should be more clear now as Azure uses "Deployment Names" in their dashboard.

Sorry for the confusion.

**Comment by horizonchasers** [comment]
Working now. Really appreciate the help.  Having this interface is amazing, been using GPT4 32k in the Microsoft playground was brutal.  Might I suggest not hiding the Endpoint and the Deployment Names.  I have several I am using and would be nice to see which one I have configured.  Great work and thank you.

**Comment by vv01sam** [comment]
everything is running smoothly now. really appreciate it!
