### ISSUE TITLE
Consecutive queries using GPT-4-Vision produces error

### ISSUE THREAD

**Issue by tim13246879** [mckaywrigley/chatbot-ui#1210]
It appears that image urls are not correctly added to the collection of messages after an image-attached query. When using the gpt 4 vision model, any query that follows a query with an image produces the error "Invalid image URL". Here is what it looks like:

![image](https://github.com/mckaywrigley/chatbot-ui/assets/114123946/12a7a550-1edc-4b7a-b2db-1663d4684fe5)

To reproduce the error:
1. Select OpenAI gpt-4-vision model.
2. Send a query with an image attached.
3. Send another query with, or without, an image attached in the same chat.
4. "Invalid image URL" error occurs.
5. (If the page is refreshed at this point, and the same chat is accessed, then further queries DO NOT produce the error). 

Looking at the messages print to the console, the error occurs when image_url is an empty string when it should be a base64 representation of the image. The problem may exist in the buildFinalMessages function in lib/build-prompts.ts, where the messages are constructed. I wasn't able to fix the error, but hopefully this issue helps someone else fix it.

**Comment by mckaywrigley** [comment]
There's some serious spaghetti code throughout the entire chat process. Working over the next 2 days to completely refactor that and it should completely clear up this issue!

**Comment by mckaywrigley** [comment]
Fixed.
