### ISSUE TITLE
Error creating assistant. Error creating public.assistant_collections does not exist

### ISSUE THREAD

**Issue by vOwl** [mckaywrigley/chatbot-ui#1212]
Hi, 
I tried to create a new assistant and get the following error when submitting the form:
`Error creating assistant. Error creating public.assistant_collections does not exist`

I ran "npm run update" before. 
Anything else i have to do to fix this?

update: supabase/types.ts was modified after "npm run update" and table "assistant_collections" was removed from file.
(the table doesn't exist in supabase)

<img width="843" alt="assistant_error" src="https://github.com/mckaywrigley/chatbot-ui/assets/10940689/f3fbf877-5c4a-4ac4-b87a-90a6bb7e5fc1">

Kind regards

**Comment by gijigae** [comment]
You can run SQLs in the `supabase/migrations/20240115171510_add_assistant_files.sql` file. There is a section for, "ASSISTANT COLLECTIONS". Hope it helps.
![image](https://github.com/mckaywrigley/chatbot-ui/assets/81459/9f74b693-2bfc-4f2f-9f84-d0a2c6aab84c)

**Comment by vOwl** [comment]
running the query as mentioned above, fixed it. thanks @gijigae 
Any idea why it wasn't applied automatically?

**Comment by mckaywrigley** [comment]
There was a typo in the `npm run update` script that I just patched and I wonder if this is why the migration didn't work correctly on the 1st go.
