### ISSUE TITLE
OpenAI Assistants within Tool/Assitants

### ISSUE THREAD

**Issue by jsweetzer-ea** [mckaywrigley/chatbot-ui#1213]
I see the fetch for this is currently commented out (and uncommenting doesn't enable) - is there an ETA for this feature as part of the overall Tools/Assistants? 

On a related point, the addApiKeysToProfile function in server-chat-helpers should be adjusted to include the OpenAI org ID so that the env var can also be applied to users for this purpose. 

Thanks again!

**Comment by mckaywrigley** [comment]
Hoping to have that by the end of the month. Mostly a UX issue. Started writing the code for it during the assistants update and realized we needed a separate area for those bc of threads, etc.

I'll fix the Org Id issue today!

**Comment by jsweetzer-ea** [comment]
Makes sense, thanks for the update. 

RE threads - do you intend to replicate this kind of functionality within the app in some form? Or will Assistants in Chatbot UI effectively be Collections + Tools + Chat? 

I ask because the persistence of context over time helps the Assistance use-case ("learning"), but equally the OpenAI implementation can become quite expensive token-wise for unoptimized use.

**Comment by mckaywrigley** [comment]
Our assistants are modeled after how OpenAI does GPTs as opposed to trying to mimic the Assistants API.

I'm open to expanding it. Just not sure yet how that'll play out.

**Comment by jsweetzer-ea** [comment]
Understood. If you're working on an Assistants API integration then probably no need short-term. 

FWIW, I would only like/expect to be able to interact with the OpenAI Assistant, and ideally have some way to limit which OpenAI Assistants are exposed to certain users (even if this is entirely done manually in the DB). OpenAI Assistant creation/management, even file association, could/should all be done in the OpenAI Platform.

**Comment by mckaywrigley** [comment]
Yeah I think first step is just making so that, at the very least, people have a straightforward way to use their OpenAI assistants in the UI even if all of the "management" part of it is done natively over on OpenAI's playground.
