### ISSUE TITLE
[FEATURE REQUEST] Important Features for a better UX & more

### ISSUE THREAD

**Issue by othmanelhoufi** [mckaywrigley/chatbot-ui#1215]
Hello,

Thanks again for this amazing UI and for the effort you put into it!

I have used this app for sometime now and I would love to share some ideas that can enhance the overall user experience:

- **Chat Editing** : during the chat we can only edit the user prompt, sometimes we need to edit also the model's result, for example to correct a fact or to improve the follow-up results in that same chat.
- **System Prompt & Params Editing** : we can do this when initiating a new chat, but it would be great to have the capability to edit those params even after, during a chat, instead of starting a new one. Sometimes the results of the model are good, but we just need to increase the token window, or enhance the System prompt without leaving the conversation.
- **Clone a conversation** : sometimes we want to experiment with different params but without corrupting the conversation, it would be good to just have a button to clone a chat and from there do the experimentation but we keep the original conversation intact.
- **Download a conversation** : for each conversation, we can have a button to download the current conversation with the params as an Image (like a screenshot) or PDF or JSON. Sharing conversations and model results it's a really important feature.
- **Export/Import the entire app configs & chats** : switching through devices will result on a data loss (unless of course we transfer manually the database tables), it would be great to have an Export/Import functionality that saves and loads all our conversations and configurations in a JSON file.
- **Documentation & Wiki** : fortunately, the app is boosted with great features, but sometimes users don't know where to start, how it works or even if a feature exists in the app because of a lack of documentation. A specific Tab could be added where a simple doc is written, containing all features descriptions with a quick GIF Demo. Also with a changelog for updates.

Improvements outside the UX scope:

-  **Admin user cockpit** : what if we had a super user account with some high order functionalities like user management, data and rights management, model management ... this can be so useful for teams and organisations.
- **Feeback logic** : this is so important, models are being improved through feedback, so how about a voting mechanism where the user can give a feedback for each output (like thumbs up or down), and everything is stored for finetuning models mainly Llama or other light weight model.
- **Image generation** : integrate the same API logic for image generation models like DALLE-3.

That being said, it would be so good to have a roadmap for futur integrations clearly expressed, this can attract more contributors to join you and help you build a Super Chatbot UI. Hopefully I can be one of them.
Please let me know what you think, and thanks again :) 

Best,

**Comment by mckaywrigley** [comment]
Pretty much everything on this list except for feedback logic will be added during Q1 2024! :)

**Comment by tobalsan** [comment]
@mckaywrigley any updates on the Q1 updates?

Particularly the DALL-E support.

Thanks.
