### ISSUE TITLE
Not clear how to add local, non ollama run local models, on different ports

### ISSUE THREAD

**Issue by tonykay** [mckaywrigley/chatbot-ui#1216]
So, in my use case, I want to run various local models, and using `ollama` is straightforward as long as I execute, `ollama run phi` before starting chatbot-ui. I am assuming it scans default port 11434 and then detects the model?

However, I also make use of lm-studio on different ports, like, for example, its default 1234 - how do I get Chatbot-ui to also detect that?

**Comment by tonykay** [comment]
So I have tried tweaking (from .env.local.example as an export) `NEXT_PUBLIC_OLLAMA_URL=http://localhost:11434` to point to `http://localhost:1234` but this seems to fail. I assume because ollama's endpoint is expected and lm-studio is presenting itself as an openai endpoint (irrespective of the model, in this case Mixtral)

**Comment by mckaywrigley** [comment]
@tonykay [This](https://github.com/jmorganca/ollama/blob/main/docs/faq.md) covers switching the port that ollama runs on.

**Comment by tonykay** [comment]
Thanks for that, useful doc. Slightly different, though, than my problem. What I'm looking for is a way to **also** point chatbot-ui at a local openai endpoint. IE In addition to being able to run local models via ollama I want to be able to use a local model being run via lm-studio for example.)

**Comment by mckaywrigley** [comment]
Difficult to say because every service is going to have its own api. You'd have to write the code for it.

For now, we're only supporting ollama as our official local model provider.
