### ISSUE TITLE
Unable to use local models with ollama

### ISSUE THREAD

**Issue by PrakrutR** [mckaywrigley/chatbot-ui#1225]
I am running a local llama server with `./ollama serve`, which runs on port 11434. Then, in another shell, I have a model running with  `./ollama run llama2-uncensored`. Here is what my .env.local looks like
```
# Supabase Public
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxj>
# Supabase Private
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZ>
# Ollama
NEXT_PUBLIC_OLLAMA_URL=http://localhost:11434
# API Keys (Optional: Entering an API key here overrides the API keys globally for all users)
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
GOOGLE_GEMINI_API_KEY=
MISTRAL_API_KEY=
PERPLEXITY_API_KEY=
OPENROUTER_API_KEY=

# OpenAI API Information
NEXT_PUBLIC_OPENAI_ORGANIZATION_ID=

# Azure API Information
AZURE_OPENAI_API_KEY=
NEXT_PUBLIC_AZURE_OPENAI_ENDPOINT=
NEXT_PUBLIC_AZURE_GPT_35_TURBO_ID=
NEXT_PUBLIC_AZURE_GPT_45_VISION_ID=
NEXT_PUBLIC_AZURE_GPT_45_TURBO_ID=
#Extras
REACT_EDITOR=code
```
When I run `npm run chat` I get the following error 
```
(node:78610) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
Now the ui loads correctly but I am unable to send messages/receive responses
The following error appears in the ui
```
Unhandled Runtime Error
Error: TypeError: Failed to fetch
```
```
  10 |
  11 | if (!profile) {
> 12 |   throw new Error(error.message)
     |        ^
  13 | }
  14 |
  15 | return profile
```
```
Call Stack
async fetchStartingData
components/utility/global-state.tsx (170:22)
```
Please help

**Comment by wrapss** [comment]
warining is not an error, and you don't need to run a model for it to be usable from the ollama api. For the error seems to be an account problem, not an ollama one.

**Comment by wrapss** [comment]
http://localhost:54323/project/default/auth/users look here if u see an user

**Comment by PrakrutR** [comment]
@wrapss I restarted everything without running a model still no luck and I checked http://localhost:54323/project/default/auth/users there is a user listed with the email i used to test
still unable to send any message I can type into the box but cannot send

**Comment by PrakrutR** [comment]
I also tested the ollama api to make sure its working with
```
curl http://localhost:11434/api/generate -d '{
  "model": "llama2-uncensored",
  "prompt":"Why is the sky blue?"
}'
```
It works as intended

**Comment by wrapss** [comment]
you get the error related to the profile when you type a message? please be precise

**Comment by wrapss** [comment]
Do you see the profile icon in the bottom left corner?

**Comment by wrapss** [comment]
what version of ollama do you have? v0.1.14 is required
try this request for check : 
curl http://localhost:11434/api/chat -d '{
  "model": "llama2-uncensored",
  "messages": [
    { "role": "system", "content": "You are a helpful assistant that answers concisely." },
    { "role": "user", "content": "why is the sky blue?" }
  ]
}'

**Comment by PrakrutR** [comment]
> you get the error related to the profile when you type a message? please be precise

No the error pops up on the bottom left corner as soon as the UI loads

> Do you see the profile icon in the bottom left corner?

No I do not

> what version of ollama do you have? v0.1.14 is required try this request for check : curl http://localhost:11434/api/chat -d '{ "model": "llama2-uncensored", "messages": [ { "role": "system", "content": "You are a helpful assistant that answers concisely." }, { "role": "user", "content": "why is the sky blue?" } ] }'

Works perfectly repose below-
```
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:28.914668982Z","message":{"role":"assistant","content":"The"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:29.105050915Z","message":{"role":"assistant","content":" sky"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:29.288647982Z","message":{"role":"assistant","content":" appears"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:29.497007569Z","message":{"role":"assistant","content":" blue"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:29.675832943Z","message":{"role":"assistant","content":" because"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:29.883213972Z","message":{"role":"assistant","content":" the"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:30.037603269Z","message":{"role":"assistant","content":" air"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:30.20696632Z","message":{"role":"assistant","content":" mole"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:30.403519511Z","message":{"role":"assistant","content":"cules"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:30.622470602Z","message":{"role":"assistant","content":" in"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:30.82784807Z","message":{"role":"assistant","content":" Earth"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:31.014603151Z","message":{"role":"assistant","content":"'"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:31.199900989Z","message":{"role":"assistant","content":"s"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:31.400349694Z","message":{"role":"assistant","content":" atmosphere"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:31.554062794Z","message":{"role":"assistant","content":" scatter"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:31.734748944Z","message":{"role":"assistant","content":" the"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:31.914480821Z","message":{"role":"assistant","content":" sun"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:32.103455475Z","message":{"role":"assistant","content":"light"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:32.30884549Z","message":{"role":"assistant","content":" that"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:32.503019283Z","message":{"role":"assistant","content":" reaches"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:32.703166746Z","message":{"role":"assistant","content":" them"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:32.869124364Z","message":{"role":"assistant","content":","},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:33.075085867Z","message":{"role":"assistant","content":" allowing"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:33.259654233Z","message":{"role":"assistant","content":" shorter"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:33.484047904Z","message":{"role":"assistant","content":" w"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:33.651021459Z","message":{"role":"assistant","content":"avel"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:33.819481813Z","message":{"role":"assistant","content":"ength"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:33.989786979Z","message":{"role":"assistant","content":" colors"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:34.176107756Z","message":{"role":"assistant","content":" such"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:34.351725334Z","message":{"role":"assistant","content":" as"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:34.545319027Z","message":{"role":"assistant","content":" blue"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:34.724989293Z","message":{"role":"assistant","content":" to"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:34.909247648Z","message":{"role":"assistant","content":" pass"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:35.093301414Z","message":{"role":"assistant","content":" through"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:35.270426292Z","message":{"role":"assistant","content":" more"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:35.484654243Z","message":{"role":"assistant","content":" easily"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:35.640871752Z","message":{"role":"assistant","content":" than"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:35.848182878Z","message":{"role":"assistant","content":" longer"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:35.990402542Z","message":{"role":"assistant","content":" w"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:36.151532042Z","message":{"role":"assistant","content":"avel"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:36.320312113Z","message":{"role":"assistant","content":"ength"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:36.502042065Z","message":{"role":"assistant","content":" colors"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:36.695123002Z","message":{"role":"assistant","content":" like"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:36.910703114Z","message":{"role":"assistant","content":" red"},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:37.11855139Z","message":{"role":"assistant","content":"."},"done":false}
{"model":"llama2-uncensored","created_at":"2024-01-21T19:13:37.310841441Z","message":{"role":"assistant","content":""},"done":true,"total_duration":19644627402,"load_duration":8208578028,"prompt_eval_count":38,"prompt_eval_duration":3039127000,"eval_count":46,"eval_duration":8396233000}
```

**Comment by wrapss** [comment]
do you see the profile setting icon on the bottom left?

**Comment by PrakrutR** [comment]
> do you see the profile setting icon on the bottom left?

No I do not
Heres a screenshot of the page as it appears for me
![image](https://github.com/mckaywrigley/chatbot-ui/assets/76415988/5cba4d33-6560-44e0-8860-b2fbed5250e7)

**Comment by wrapss** [comment]
so it's an account problem, try clearing chatbot-ui's cookies and try logging in again?

**Comment by michel-numan** [comment]
Im getting the same error however running on Caddy via CloudFlare tunnels

**Comment by wrapss** [comment]
please try with the latest version

**Comment by mysterium-coniunctionis** [comment]
**_Same_ error - completely deleted everything and started from scratch. Unable to my profile context ("What would you like the AI to know about you to provide better responses?"), however supabase admin login is created.**

```
chatbot-ui % npm run chat

> chatbot-ui@2.0.0 chat
> supabase start && npm run db-types && npm run dev

supabase start is already running.
Run supabase status to show status of local Supabase containers.

> chatbot-ui@2.0.0 db-types
> supabase gen types typescript --local > supabase/types.ts

(node:1) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time

> chatbot-ui@2.0.0 dev
> next dev

   ▲ Next.js 14.1.0
   - Local:        http://localhost:3000
   - Environments: .env.local

 ✓ Ready in 2.8s
 ✓ Compiled /middleware in 276ms (156 modules)
No valid locales in accept-language header: *
Reverting to using defaultLocale: en
 ○ Compiling /[locale] ...
 ✓ Compiled /[locale] in 8.8s (1593 modules)
No valid locales in accept-language header: *
Reverting to using defaultLocale: en
 ✓ Compiled in 934ms (692 modules)
 ✓ Compiled in 149ms (678 modules)
```

### **Screenshots of error when trying to save profile context ("What would you like the AI to know about you to provide better responses?") and does not save (have tried clearing cookies, completely new reinstall of chatbotui):**

<img width="254" alt="Screenshot 2024-01-22 at 3 02 44 PM" src="https://github.com/mckaywrigley/chatbot-ui/assets/3911621/c2230f4e-edb9-4c64-9a75-0fe4f19a494a">

<img width="990" alt="Screenshot 2024-01-22 at 2 57 51 PM" src="https://github.com/mckaywrigley/chatbot-ui/assets/3911621/d4ac2f89-f6da-4c18-ac0c-c888a1446d06">

**Comment by wrapss** [comment]
try supabase db push ?

**Comment by mysterium-coniunctionis** [comment]
> try supabase db push ?

I have a local install as instructed per the installation instructions here with no fancy changes to any part of the code. The only thing I have done is enter my API information in the env.local file but otherwise no changes to the code. I am using an m1 MacBook Pro. Multiple Supabase containers are visible inside of Docker Desktop. How do I do the **supabase db push** given a default Chatbot-UI installation?

**Comment by wrapss** [comment]
from the root of chatbot-ui folder, in the same way as you would use the supabase status command?

**Comment by mysterium-coniunctionis** [comment]
> from the root of chatbot-ui folder, in the same way as you would use the supabase status command?

I see. Thank you. It seems like there is some intermediary step to be able to do this and that particular error seems to have been resolved by running "npm run update" from the chatbot root. None the less, this is the response I get when I run "supabase db push":

```
chatbot-ui % supabase db push
Cannot find project ref. Have you run supabase link?
```

**Comment by wrapss** [comment]
How did you get the supabase credentials if you can't run supabase status?

**Comment by wrapss** [comment]
in your .env you added NEXT_PUBLIC_SUPABASE_ANON_KEY and SUPABASE_SERVICE_ROLE_KEY? how did you get them?

**Comment by mysterium-coniunctionis** [comment]
> in your .env you added NEXT_PUBLIC_SUPABASE_ANON_KEY and SUPABASE_SERVICE_ROLE_KEY? how did you get them?

`supabase status` works and provides me keys. Keys are correctly entered in `~/chatbot-ui/env.local`. 

For whatever reason, the command `supabase db push` returns the error `Cannot find project ref. Have you run supabase link?`.

I am using a local install on an M1 MacBook Pro and receive this error message in Terminal. This is my first time working with supabase so I apologize that I cannot be more helpful.  Please let me know if there is anything else specifically that I can do that might be helpful. Doing my best to contribute how I can.

**Comment by PrakrutR** [comment]
@mysterium-coniunctionis 

Ah exactly the errors I am getting. Thanks for the screenshot.
I tried clearing cookies and even a new deleting the repo and repluuing with a clean install of everything no luck

**On supabase**
`supabase db push` returns `Cannot find project ref. Have you run supabase link?`
`supabse link` returns `2024/01/23 17:50:13 Access token not provided. Supply an access token by running supabase login or setting the SUPABASE_ACCESS_TOKEN environment variable.`

Should I need a supabase login for a local run?

_Info_ everything is running locally on a Ubuntu machine if relevant I can provide more info about the machine set-up

**Comment by mysterium-coniunctionis** [comment]
> @mysterium-coniunctionis
> 
> Ah exactly the errors I am getting. Thanks for the screenshot. I tried clearing cookies and even a new deleting the repo and repluuing with a clean install of everything no luck

The update pushed yesterday fixed the profile context bug for me. I am now able to save my profile context via localhost:3000. I ran the update using `npm run update`.

**Comment by PrakrutR** [comment]
@mysterium-coniunctionis I tried that now and I also tried redowloading the repo and starting from scratch and deleting the user I had createdI still get this error
![image](https://github.com/mckaywrigley/chatbot-ui/assets/76415988/2e5f50fe-c738-4cdc-a960-ba2d32d41a8b)

However this is on `http://localhost:3000/setup` and there now a completely black screen and no ui at all
Going to `http://localhost:3000/chat` bring back the ui but there's still no profile no list of models and I cannot send prompts

Also I just noticed that in the backend gui at `http://localhost:54323/project/default/logs/auth-logs` I get the following error 
```
{
  "code": 500,
  "message": "An error has occurred: fetch failed",
  "requestId": "b5f71df6-f50d-4209-ba29-260943a3df83"
}
```
The same error on these log tabs too-
![image](https://github.com/mckaywrigley/chatbot-ui/assets/76415988/25107cbb-c5c2-4a67-a348-e55c6f8a0c38)

I dont know if this is relevant I am just reporting it incase it is connected

**Comment by wrapss** [comment]
@PrakrutR have you started supabase with 'supabase start' and entered the supabase information obtained with 'supabase status' in your .env.local file?

**Comment by PrakrutR** [comment]
I am pretty sure I have heres the .env.local
```
# Supabase Public
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0

# Supabase Private
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN8>
# Ollama
NEXT_PUBLIC_OLLAMA_URL=http://localhost:11434
# API Keys (Optional: Entering an API key here overrides the API keys globally for all users)
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
GOOGLE_GEMINI_API_KEY=
MISTRAL_API_KEY=
PERPLEXITY_API_KEY=
OPENROUTER_API_KEY=

# OpenAI API Information
NEXT_PUBLIC_OPENAI_ORGANIZATION_ID=

# Azure API Information
AZURE_OPENAI_API_KEY=
NEXT_PUBLIC_AZURE_OPENAI_ENDPOINT=
NEXT_PUBLIC_AZURE_GPT_35_TURBO_ID=
NEXT_PUBLIC_AZURE_GPT_45_VISION_ID=
NEXT_PUBLIC_AZURE_GPT_45_TURBO_ID=
```

 and heres what `supabase status` returns
 ```
Stopped services: [supabase_analytics_chatbotui]
supabase local development setup is running.

         API URL: http://127.0.0.1:54321
     GraphQL URL: http://127.0.0.1:54321/graphql/v1
          DB URL: postgresql://postgres:postgres@127.0.0.1:54322/postgres
      Studio URL: http://127.0.0.1:54323
    Inbucket URL: http://127.0.0.1:54324
      JWT secret: super-secret-jwt-token-with-at-least-32-characters-long
        anon key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
service_role key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
```
Have I made some mistake

 I tried to create a user using the backend GUI and got the error `failed to fetch`
 Can I debug by running the UI without accounts and see if it works?
 
![image](https://github.com/mckaywrigley/chatbot-ui/assets/76415988/9230b996-ce43-4778-857d-502c5c42d536)

**Comment by PrakrutR** [comment]
Tried a full update/reinstall again still had the same problem in creating a user
![image](https://github.com/mckaywrigley/chatbot-ui/assets/76415988/71f19b04-0f41-4c26-bb07-dfa5dec9a035)
```
Call Stack
async fetchStartingData
components/utility/global-state.tsx (192:22)
async fetchData
components/utility/global-state.tsx (134:22)
```

**Comment by mckaywrigley** [comment]
@PrakrutR 

You accidentally entered your role key incorrectly.

> SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN8>

This should be `SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU`

**Comment by PrakrutR** [comment]
@mckaywrigley I Just double-checked. Sorry, it was a mistake in copying my `.env.local` file
I think I have it correct I still have the same issue
Here is the proper set of environmental variables I am using I am still having the same 
[envvar.txt](https://github.com/mckaywrigley/chatbot-ui/files/14046984/envvar.txt)
I am still having the same issue please dont close the topic

Even with the corrected and triple checked keys I hve the following errors
![image](https://github.com/mckaywrigley/chatbot-ui/assets/76415988/0ef2edf6-93a5-4041-b901-0b42945f48ce)
![image](https://github.com/mckaywrigley/chatbot-ui/assets/76415988/a0a16083-73fb-4471-94f2-a1744aadbc61)

**Comment by jordicor** [comment]
I'm having exactly the same error, when accessing local it works fine, everything, but when accessing from a different computer then I have that error.

http://localhost:3000 -- works fine
http://192.168.50.209:3000 -- I get that error that the profile doesn't exists

I'm sure that .env.local it's right because in local works fine.

**Comment by wrapss** [comment]
the ip of supabase in env file must be the private ipv4 of your machine, not localhost or 127.0.0.1

**Comment by PrakrutR** [comment]
How do I change the IP of supabase?

**Comment by wrapss** [comment]
the ip of supabase is the ip of your machine, I don't understand the question?

**Comment by wrapss** [comment]
![image](https://github.com/mckaywrigley/chatbot-ui/assets/7548882/7a4a2835-1604-4305-bc24-a802d98ab882)

**Comment by jordicor** [comment]
Thank you @wrapss  , changing just the URL of SUPABASE_URL , the problem persists, changing both URLs (Supabase URL and Ollama URL) fixed the problem.

Now I can access the Chatbot UI from a different PC from my LAN.

Thanks!

**Comment by PrakrutR** [comment]
Wonderful thanks that fixed my error!
Thank you so much!

**Comment by jordicor** [comment]
By the way, sorry for this new reply but I think that could be useful for someone using Chatbot UI in Windows with WSL and Ollama.

After being able to access using a different PC from my LAN, I noticed that local LLMs (LLama, etc.) were not showing up, the problem was changing the URL, that WSL needs to open some ports and route the traffic.

Following this steps fixed it and now I can use Local LLMs too: https://github.com/ollama/ollama/issues/1431
