### ISSUE TITLE
Truncation of Chat Responses due to Exceeding Token Limit in Long Conversations

### ISSUE THREAD

**Issue by cablackmon** [mckaywrigley/chatbot-ui#1226]
In lengthy conversations, the chatbot UI appears to encounter issues where new responses from the model are truncated or cut off. This behavior suggests that the token limit for the model's responses might be exceeded. It appears that the entire chat message chain is being submitted to the model for each new response, potentially leading to the exhaustion of the model's token limit.

#### Files Involved
The issue seems to be related to the way chat messages are handled and submitted in the routes for various AI models. Specifically, the following files are involved:

- `openai/route.ts`
- `google/route.ts`
- `mistral/route.ts`
- (Other AI service routes if applicable)

Additionally, the front-end components managing the chat UI might also play a role in this issue:

- `chat-ui.tsx`
- `chat-messages.tsx`
- `chat-input.tsx`

#### Problematic Behavior
In each of the route files mentioned above, the entire `messages` array received from the request is being sent to the AI models without any truncation or context management. This means that as the conversation grows longer, more tokens are consumed for the chat history, leaving fewer tokens available for generating new responses.

This behavior is observed in the following code snippets from the route files:

```javascript
// Example from openai/route.ts
const response = await openai.chat.completions.create({
  model: chatSettings.model as ChatCompletionCreateParamsBase["model"],
  messages: messages as ChatCompletionCreateParamsBase["messages"],
  ...
})
```

#### Suggested Solution
To mitigate this issue, it is recommended to implement a context truncation strategy. This strategy should ensure that only the most recent and relevant messages (or a limited number of tokens) are included in the `messages` array before it's sent to the AI model. This can help prevent the exhaustion of the token limit and ensure that new responses from the model are not truncated.

#### Potential Impact
Implementing this change could significantly improve the user experience in long conversations by ensuring that responses from the model are complete and informative. It could also optimize the use of tokens, potentially reducing the cost and increasing the efficiency of the model.

**Comment by mckaywrigley** [comment]
Working on better chat trunctation!

**Comment by cablackmon** [comment]
Thank you!
