### ISSUE TITLE
Strange behavior after the latest assistant and tools changes

### ISSUE THREAD

**Issue by sebiweise** [mckaywrigley/chatbot-ui#1228]
![image](https://github.com/mckaywrigley/chatbot-ui/assets/22999200/85bb745b-6cec-4238-a4a4-7f7ba87df576)
Anybody know what this is about? This screenshot is from an empty new conversation.

**Comment by sixlive** [comment]
Fair amount of `test` console logs too...

**Comment by sebiweise** [comment]
Found the issue and will create a pull request for that. Removed one debug console.log and fixed some labels
