### ISSUE TITLE
Add support for XLSX

### ISSUE THREAD

**Issue by jsweetzer-ea** [mckaywrigley/chatbot-ui#1229]
Do you plan to extend File support to XLSX? 

XLSX has advantages for retrieval when using OpenAI directly; my understanding is that it can work with the data structure as opposed to a flat parsed file like json/csv/etc. 

Cheers!

**Comment by mckaywrigley** [comment]
Working down the list of core things and then improved RAG will be high on the list.

Really good RAG is just *incredibly* difficult.

**Comment by inzomiac** [comment]
was this already implemented?
