### ISSUE TITLE
Discussion: Should we support plugins?

### ISSUE THREAD

**Issue by alanpog** [mckaywrigley/chatbot-ui#123]
OpenAI announced ChatGPT [plugins](https://openai.com/blog/chatgpt-plugins). Should we support them here before the general release?

**Comment by alanpog** [comment]
I mean the UI part here. The heavy lifting is [advancing fast at langchain and already usable](https://hwchase17.github.io/langchainjs/docs/modules/agents/aiplugin-tool/).

**Comment by mckaywrigley** [comment]
I am planning on supporting this soon.
