### ISSUE TITLE
More advanced workspace featrues

### ISSUE THREAD

**Issue by sebiweise** [mckaywrigley/chatbot-ui#1233]
- Option to add/invite users to a workspace
- Option to save settings/apikeys to a workspace so that every user can use this when the workspace is selected

Add a table workspace_user for the 1 to n relation to be able to add multiple users to one workspace.
Columns should be something like id, userid, workspaceId, role (Admin and User so users cannot delete a workspace)

**Comment by mckaywrigley** [comment]
These are on the way!
