### ISSUE TITLE
Ollama local models don't have icon/logo anymore in UI

### ISSUE THREAD

**Issue by othmanelhoufi** [mckaywrigley/chatbot-ui#1238]
Hello,

A small bug. The local models don't have icon/logo anymore

<img width="487" alt="Screenshot 2024-01-23 at 13 57 14" src="https://github.com/mckaywrigley/chatbot-ui/assets/40344016/272b8861-4c76-4fb5-93cc-73a229699fa7">

**Comment by mckaywrigley** [comment]
This was removed due to branding concerns.
