### ISSUE TITLE
Unhandled Runtime Error - Button don't work

### ISSUE THREAD

**Issue by coav** [mckaywrigley/chatbot-ui#1239]
Hello, It's giving me this error after I run chat on http://localhost:3000/chat

<img width="722" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/1080185/fbb8c480-5b72-49f8-9e7c-a942b94e70a7">

The buttons don't work, therefore I can't send the prompt.

Thanks,
Matej

**Comment by PrakrutR** [comment]
I have the same problem see this #1225

**Comment by mckaywrigley** [comment]
Your configuration is almost certainly incorrect.

Double check that you entered the supabase info correctly.
