### ISSUE TITLE
Docker Environment Variables Not Working (OPENAI_ORGANIZATION= DEFAULT_TEMPERATURE= DEFAULT_SYSTEM_PROMPT=)

### ISSUE THREAD

**Issue by Kryszn0** [mckaywrigley/chatbot-ui#1240]
I've searched previous issues and found comments stating the environment variables needed to have "NEXT_PUBLIC_" placed in front. However, also saw those older issues were marked as completed a few weeks ago. I've tried both, with & without "NEXT_PUBLIC_" but they do not seem to be read correctly in the docker environment

OPENAI_ORGANIZATION=
DEFAULT_TEMPERATURE=
DEFAULT_SYSTEM_PROMPT=

**Comment by mckaywrigley** [comment]
Unfortunately we no longer support the legacy version and recommend migrating to V2 (current README).
