### ISSUE TITLE
Unable to create an Assistant. Error message reads: "Error creating assistant. Error: relation "public.assistant_collections" does not exist."

### ISSUE THREAD

**Issue by mysterium-coniunctionis** [mckaywrigley/chatbot-ui#1242]
As the title says, I am getting an error message when attempting to save my created assistant. This error message is displayed via the Chatbot-UI web portal via localhost:3000 using an Ollama LLM that otherwise is compatible with local access.

Error message reads:
`! Error creating assistant. Error: relation "public.assistant_collections" does not exist.`

<img width="319" alt="Screenshot 2024-01-23 at 8 43 20 AM" src="https://github.com/mckaywrigley/chatbot-ui/assets/3911621/9b4d1877-17f7-44bd-9fe6-2b53ef96f8e1">

EDIT>>>
Same error when using (non-local) GPT-4-Turbo / OpenAI API.

**Comment by im-calvin** [comment]
I'm investigating the same issue at the moment

**Comment by im-calvin** [comment]
Quick update, the crux of the issue is that the database seems to be missing the assistant_collections table.

I'm not sure where to edit for this, whether it be in `supabase/types.ts` or somewhere else. Also not sure what fields are in the table.

**Comment by im-calvin** [comment]
Okay, I've got a pseudo-fix. I think the issue is with the way that you run `git pull`. As mentioned in the `README`, you have to run `npm run update`, although if you just go into the script it runs 3 commands separately:

1. `git pull origin main` - for me, my origin was set up to track a different remote so I had to specify it myself
2. `npm run db-migrate` - make sure that you ran `supabase start` to begin with, or else this command will fail
3. `npm run db-types` - this adds `public.assistant_collections` back into the database

If you want a quicker fix, here's a dump of what you should add to `supabase/types.ts`, although this _might_ not be scalable (for future commits). Add the following to `L37:supabase/types.ts`, so that it is inside the `public.tables.[assistant_collections]` table

```
      assistant_collections: {
        Row: {
          assistant_id: string
          collection_id: string
          created_at: string
          updated_at: string | null
          user_id: string
        }
        Insert: {
          assistant_id: string
          collection_id: string
          created_at?: string
          updated_at?: string | null
          user_id: string
        }
        Update: {
          assistant_id?: string
          collection_id?: string
          created_at?: string
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "assistant_collections_assistant_id_fkey"
            columns: ["assistant_id"]
            isOneToOne: false
            referencedRelation: "assistants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "assistant_collections_collection_id_fkey"
            columns: ["collection_id"]
            isOneToOne: false
            referencedRelation: "collections"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "assistant_collections_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
```

**Comment by mckaywrigley** [comment]
You'll need to pull from this repo, run `npm run db-migrate` and `npm run db-types`.

Then restart the app and it should work.

**Comment by mysterium-coniunctionis** [comment]
> 1. `git pull origin main` - for me, my origin was set up to track a different remote so I had to specify it myself
> 2. `npm run db-migrate` - make sure that you ran `supabase start` to begin with, or else this command will fail
> 3. `npm run db-types` - this adds `public.assistant_collections` back into the database

That fixed it! In fact, after applying the update per your instructions, clearing my cookies, and re-logging back in, my nine previous attempts at saving the Assistant came up as multiple assistants. I deleted those and then re-added one and it worked. Thanks for the rapid fix! @im-calvin & @mckaywrigley
