### ISSUE TITLE
Repeatedly getting this error message in terminal every few seconds: "[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead. (Use `node --trace-deprecation ...` to show where the warning was created) No valid locales in accept-language header: * Reverting to using defaultLocale: en"

### ISSUE THREAD

**Issue by mysterium-coniunctionis** [mckaywrigley/chatbot-ui#1243]
As stated, I am repeatedly (many many many times >100) getting this error message every few seconds in terminal on a macOS silicon based MacBook Pro:

`[DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead. (Use node --trace-deprecation ... to show where the warning was created) No valid locales in accept-language header: * Reverting to using defaultLocale: en`

<img width="1103" alt="Screenshot 2024-01-23 at 8 50 53 AM" src="https://github.com/mckaywrigley/chatbot-ui/assets/3911621/42136b97-dfa1-47b2-ade5-2f74dbf423bd">

**Comment by Bortus-AI** [comment]
You can ignore those
