### ISSUE TITLE
Unhandled Runtime Error Error: TypeError: Failed to fetch

### ISSUE THREAD

**Issue by danec** [mckaywrigley/chatbot-ui#1244]
On starting up the first time (after configuring everything), I'm getting a Unhandled Runtime Error
Error: TypeError: Failed to fetch.

![Screenshot 2024-01-23 at 13 47 11](https://github.com/mckaywrigley/chatbot-ui/assets/6599262/40eb1f09-517c-4700-b91e-77c1bb183d01)

**Comment by Bortus-AI** [comment]
ensure that your .env.local file is configured correctly. Once that's verified, the next to consider is the access point. Are you attempting to access it from the same local machine, or are you trying to connect from a different computer or over the internet?

If you're accessing it locally, the typical URL would be http://127.0.0.1:54321. However, for remote access - either from another computer or over the internet - your browser needs to be able to reach the NEXT_PUBLIC_SUPABASE_URL. In this case, you must use an address that's reachable from your browser. This could be the actual IP address of the machine hosting the service or a domain name if you have set one up.

For example, your URL might look like one of the following:

https://supabase.bortus.com
http://[Local IP Address]:54321
http://[WAN IP Address]:54321

As a diagnostic step, try loading http://127.0.0.1:54321 from your browser. If this fails, then try http://[Local IP Address]:54321 and http://[WAN IP Address]:54321

**Comment by Bortus-AI** [comment]
I had this very issue yesterday and then realized I needed to use the public/wan IP for the NEXT_PUBLIC_SUPABASE_URL when accessing chatbot-ui from another device than the one running the server.

**Comment by danec** [comment]
> However, for remote access - either from another computer or over the internet - your browser needs to be able to reach the NEXT_PUBLIC_SUPABASE_URL. In this case, you must use an address that's reachable from your browser. This could be the actual IP address of the machine hosting the service or a domain name if you have set one up.

Thanks - this was it exactly! Fixed this and everything is working perfectly now.

**Comment by mckaywrigley** [comment]
Looks like issue was solved - thanks everyone :)

**Comment by Bortus-AI** [comment]
@mckaywrigley Can we add something to the Readme about this? Its a pretty easy thing to overlook

**Comment by Bortus-AI** [comment]
> > However, for remote access - either from another computer or over the internet - your browser needs to be able to reach the NEXT_PUBLIC_SUPABASE_URL. In this case, you must use an address that's reachable from your browser. This could be the actual IP address of the machine hosting the service or a domain name if you have set one up.
> 
> Thanks - this was it exactly! Fixed this and everything is working perfectly now.

Welcome!

**Comment by decolygs** [comment]
> > > However, for remote access - either from another computer or over the internet - your browser needs to be able to reach the NEXT_PUBLIC_SUPABASE_URL. In this case, you must use an address that's reachable from your browser. This could be the actual IP address of the machine hosting the service or a domain name if you have set one up.
> > 
> > 
> > Thanks - this was it exactly! Fixed this and everything is working perfectly now.
> 
> Welcome!



Tell us about it. Please.

I am trying to access from another device, but I get an Unhandled Runtime Error
Error: Invalid Server Actions request.

The 54321 port is blocked by the firewall, so I have acquired a new domain and am using Nginx to reverse it.
The configuration is as follows
server {
    listen 80;
    server_name get DOMAIN;

    location / {
        proxy_pass http://127.0.0.1:54321;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme; }
    }

NEXT_PUBLIC_SUPABASE_URL=get DOMAIN
The getDOMAIN described in NEXT_PUBLIC_SUPABASE_URL can be accessed from browsers on other devices.
The browser will display {"message": "no Route matched with those values"}.

However, when I try to login with chatbot-ui, I get an Unhandled Runtime Error.

Is there a problem with the Nginx description?　Or is it the description in env.local?

<img width="957" alt="スクリーンショット 2024-03-02 21 17 43" src="https://github.com/mckaywrigley/chatbot-ui/assets/134048989/05d02b5d-67d5-45d0-b7c1-4d318cdb41c3">
