### ISSUE TITLE
Azure deployment set in environment variable 

### ISSUE THREAD

**Issue by im-calvin** [mckaywrigley/chatbot-ui#1245]
in `.env.local`, I set the `AZURE_GPT_45_VISION_NAME` to some value, but when I try and chat, `/api/chat/azure` throws an error: `Azure resource not found`. I see that `DEPLOYMENT_ID` in `/api/chat/azure/route.ts` is an empty string, and that `profile.azure_openai_45_turbo_id` is an empty string. 

I wonder if it's due to some variables being named `_name` and `_id` in the `.env` and `profile` 
#1207 might be relevant

**Comment by im-calvin** [comment]
I noticed that there are some variables named `profile.azure_openai_45_turbo_id` and some `azure_openai_gpt_45_turbo_id`, I think that's the problem.

In the profile, the one registered **has "GPT"** in it, but in the route, it tries to retrieve from the wrong key name

**Comment by mckaywrigley** [comment]
Merged.
