### ISSUE TITLE
Using Ollama/local models from another source 

### ISSUE THREAD

**Issue by kmsrockz** [mckaywrigley/chatbot-ui#1249]
Hello everyone, 
I have installed chatbot ui locally with Ollama. 
When I using 127.0.0.1 local models and file uploads works without problems. 

But when I access the chatbot from my iPhone or other computer using the local ip for example 192.168.1.100. 
Local models and file uploads no longer work. 
Normal chat with Azure OpenAi works fine.

Ollama runs in Docker container, I can also access ollama via the URL:192.168.1.100:11434. (Ollama Service is running) 
But i have no local models shows in Browser, only AzureOpenAi and other API´s.

It must still be possible to access the local models. 
Maybe someone has an idea or has already made it work? 

Very grateful for any advices 🙏 
![Bildschirmfoto 2024-01-24 um 11 33 05](https://github.com/mckaywrigley/chatbot-ui/assets/101411581/8cacc16a-542a-4eed-9fd0-23495afe4b3d)
![Bildschirmfoto 2024-01-24 um 11 32 29](https://github.com/mckaywrigley/chatbot-ui/assets/101411581/4cf0ce19-f09d-41a9-98ba-6827af7c0a07)
<img width="899" alt="Screen 2024-01-24 um 11 36 21" src="https://github.com/mckaywrigley/chatbot-ui/assets/101411581/7998ae10-61f5-4534-822e-a9040a097178">

**Comment by wrapss** [comment]
go in the network tabs of ur navigator and search 'tags' request

**Comment by kmsrockz** [comment]
Thanks for Reply ! 🙏

ive get this 2 errors.... 


Access to fetch at 'http://192.168.1.100:11434/api/tags' from origin 'http://192.168.1.100:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
global-state.tsx:273 
        
       

GET http://192.168.1.100:11434/api/tags net::ERR_FAILED 403 (Forbidden)

**Comment by wrapss** [comment]
look [this](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-allow-additional-web-origins-to-access-ollama)

**Comment by kmsrockz** [comment]
Thx, add local IP Adress by OLLAMA_ORIGIN but still not work 🤔

**Comment by Bortus-AI** [comment]
@kmsrockz #1255 See if the suggestions here fix it.

**Comment by kmsrockz** [comment]
yeah works now ! THX Everybody 🙏
