### ISSUE TITLE
Local Models not showing up

### ISSUE THREAD

**Issue by Alex-Walston** [mckaywrigley/chatbot-ui#1255]
I think I followed everything correctly but the local models are still not showing up on the UI

![image](https://github.com/mckaywrigley/chatbot-ui/assets/68715024/4b4aa42a-5b20-4ae8-86c4-01714276df7a)
![image](https://github.com/mckaywrigley/chatbot-ui/assets/68715024/a7b9f649-6ba5-4d18-a9d8-3a6586ba185d)
![image](https://github.com/mckaywrigley/chatbot-ui/assets/68715024/44980d77-8917-4af1-98fb-6029a7dbab48)

**Comment by Bortus-AI** [comment]
are you accessing the chat on the same computer as the ollama server? If not you need to stop ollama and then start uit via OLLAMA_HOST=0.0.0.0 OLLAMA_ORIGINS=* ollama serve so that ollama can be reached from another computer

**Comment by Alex-Walston** [comment]
I am accessing it from a different computer from the server.

I tried what you recommended and I am still getting the same issue

![image](https://github.com/mckaywrigley/chatbot-ui/assets/68715024/d882c486-7f4e-41f2-995b-7aba6230972f)

**Comment by Bortus-AI** [comment]
Okay try this. 
Change the ollama_url to the lan or wan IP not local host. 
NEXT_PUBLIC_OLLAMA_URL=http://IPADRESS:11434

**Comment by Bortus-AI** [comment]
Since you're accessing via another computer the chatbot ui in your browser is trying to access localhost but that isn't on that computer. Its on the remote so you need to change it to point to the actual IP.

**Comment by Alex-Walston** [comment]
Still nothing, although after making that change I got a hit on the ollama when I launched the Chatbot

![image](https://github.com/mckaywrigley/chatbot-ui/assets/68715024/f5974091-ed63-4eb5-9111-4c7405ac8a7c)

**Comment by Bortus-AI** [comment]
I'm assuming if you run ollama list you see the downloaded models on the server? I only say that as it happened once where I had models downloaded but ollama list was blank until i restarted it. Also make sure you're running the latest ollama

**Comment by Alex-Walston** [comment]
That was it

Thank you!

**Comment by Bortus-AI** [comment]
> That was it
> 
> Thank you!

Welcome!
