### ISSUE TITLE
Mistral still not working in Vercel

### ISSUE THREAD

**Issue by viraniaman94** [mckaywrigley/chatbot-ui#1258]
Thank you for addressing my previous related issue. I am getting a new error while using Mistral on Vercel:

```
 Error: 400 status code (no body)
    at (node_modules/openai/error.mjs:40:19)
    at (node_modules/openai/core.mjs:248:24)
    at (node_modules/openai/core.mjs:287:29)
    at (app/api/chat/mistral/route.ts:27:21)
    at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:189:36)
    at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:128:25)
    at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:251:29)
    at (node_modules/next/dist/esm/server/web/edge-route-module-wrapper.js:81:20)
    at (node_modules/next/dist/esm/server/web/adapter.js:157:15) {
  status: 400,
  headers: {
  access-control-allow-origin: '*',
  cf-as-number: '16509',
  cf-cache-status: 'DYNAMIC',
  cf-ray: '84a27c9e07ea13cf-ORD',
  connection: 'keep-alive',
  content-length: '135',
  content-type: 'application/json',
  date: 'Tue, 23 Jan 2024 19:36:39 GMT',
  ratelimitbysize-limit: '2000000',
  ratelimitbysize-query-cost: '279',
  ratelimitbysize-remaining: '1999721',
  ratelimitbysize-reset: '21',
  server: 'cloudflare',
  x-kong-proxy-latency: '6',
  x-kong-request-id: '64be951a3b11464c35151500df299478',
  x-kong-upstream-latency: '10',
  x-ratelimitbysize-limit-minute: '2000000',
  x-ratelimitbysize-limit-month: '10000000000',
  x-ratelimitbysize-remaining-minute: '1999721',
  x-ratelimitbysize-remaining-month: '9999422542'
},
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined
}
```

_Originally posted by @viraniaman94 in https://github.com/mckaywrigley/chatbot-ui/issues/1231#issuecomment-1906798692_

**Comment by mckaywrigley** [comment]
Double check that you have pulled and deployed the latest code updates.

I've confirmed that all models now work in Vercel with the latest api changes.

**Comment by viraniaman94** [comment]
Apologies. I tested the Tiny and Small models, and they work fine on Vercel now. Thank you for fixing them. 

However, the Medium still doesn't work. Now there is no error from the chat endpoint but I still don't see any messages. Tried running in Incognito mode to bypass any caches as well. Screenshot:

<img width="2485" alt="Screenshot 2024-01-24 at 5 45 46 PM" src="https://github.com/mckaywrigley/chatbot-ui/assets/89636334/aa038ec0-9545-4890-a777-7f48cfe11723">

Also I tried to build and release the latest commit `62aeb88` to Vercel and seeing the following error:

<img width="1203" alt="Screenshot 2024-01-24 at 5 49 48 PM" src="https://github.com/mckaywrigley/chatbot-ui/assets/89636334/5758fc8e-c494-4d9b-ace8-52d1dacfa119">

I am on `f5a06cd` which was the latest as of yesterday.

**Comment by mckaywrigley** [comment]
Totally my fault. I pushed a breaking change to the types files. That has now been reverted!

We merged a PR that fixes the medium bug after the commit you're on.

So pull the change I just made and that should be fixed now :)

**Comment by viraniaman94** [comment]
Works perfectly! Thank you so much for the quick turnaround, and also an excellent product :D

**Comment by mckaywrigley** [comment]
Awesome! Thanks for you patience. Glad we got that fixed.
