### ISSUE TITLE
Feature Request: Make Chatbot-ui Multiplayer

### ISSUE THREAD

**Issue by dillchen** [mckaywrigley/chatbot-ui#126]
1. Add Auth (firebase)
2. Hook up to a server / allow people to join channels 
3. Unclear on handle how to handle requests (I.e if multiple users post into one channel) 
-> if #107 is implemented -> GPT would be able to respond in threads / in a sideview (requires product thinking)

----
Use Case: Would be great to have a hosted / company specific instance of Chatbot-UI - that we all share an API key for -> would be incredibly useful to have many people be able to prompt

**Comment by mckaywrigley** [comment]
This will be added eventually!
