### ISSUE TITLE
Unable to login after fresh install and user creation

### ISSUE THREAD

**Issue by jppaolim** [mckaywrigley/chatbot-ui#1261]
Followed the install instructions. 
Created a first user. 
Then it blocks. 
Node output  + error screenshot  
To be noted in supabase there is a user correctly created. 

Mac OS M1 Sonoma fresh install... 

> chatbot-ui@2.0.0 dev
> next dev

   ▲ Next.js 14.1.0
   - Local:        http://localhost:3000
   - Environments: .env.local

 ✓ Ready in 1450ms
 ✓ Compiled /middleware in 143ms (156 modules)
 ○ Compiling /[locale] ...
 ✓ Compiled /[locale] in 1241ms (1592 modules)
(node:18470) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:18461) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 ✓ Compiled in 1142ms (699 modules)

![Capture d’écran 2024-01-25 à 00 25 37](https://github.com/mckaywrigley/chatbot-ui/assets/73477568/f51c99b3-b357-4687-ac50-7b63bc5ec92c)

**Comment by mckaywrigley** [comment]
Move to the "Help" category in "Discussions"
