### ISSUE TITLE
ERR_SSL_WRONG_VERSION_NUMBER - Login or Signup Issue in GitHub Codespaces

### ISSUE THREAD

**Issue by parthiban-subramani** [mckaywrigley/chatbot-ui#1266]
**_I'm trying to run this app in GitHub Codespaces and got the below issue. Any idea how to fix this issue..?_**

<img width="1160" alt="Screenshot 2024-01-25 at 5 00 18 PM" src="https://github.com/mckaywrigley/chatbot-ui/assets/70690705/da7b7dc0-10d9-4c97-aeaa-6514421bbcde">

<img width="1184" alt="Screenshot 2024-01-25 at 5 01 34 PM" src="https://github.com/mckaywrigley/chatbot-ui/assets/70690705/6ff0d479-f397-4f5d-a1e9-5430d0b30132">

**Comment by mckaywrigley** [comment]
Move to the "Help" category in "Discussions"
