### ISSUE TITLE
Add the ability for global assistants/importing assistants

### ISSUE THREAD

**Issue by skorokithakis** [mckaywrigley/chatbot-ui#1267]
I have created a few assistants with the API that I'd like to use, and they're scoped to the API key that I use for the Chatbot UI installation. Unfortunately, there doesn't seem to be a way to add those assistants to the installation globally.

It would be great if I could specify, somewhere in the configuration, the IDs of a few assistants that I wanted included globally in the UI, and those would be added for every user.

**Comment by mckaywrigley** [comment]
Move to "Discussions"
