### ISSUE TITLE
Issue with a custom tool 

### ISSUE THREAD

**Issue by mrgizmo212** [mckaywrigley/chatbot-ui#1273]
I wrote a schema for a custom tool that pulls real time financial data. The system recognizes it and even seems to try and work but then fails. The code is below:

Custom Headers:

{
  "Authorization": "Bearer token <my token>"
}

Schema

{
  "openapi": "3.1.0",
  "info": {
    "title": "Polygon.io Stock and Crypto Data API",
    "description": "API schema for accessing stock and crypto data from Polygon.io.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://api.polygon.io"
    }
  ],
  "paths": {
    "/v1/open-close/{stocksTicker}/{date}": {
      "get": {
        "summary": "Get Stock Daily Open and Close",
        "description": "Get the daily open and close for a specific stock.",
        "operationId": "getStockDailyOpenClose",
        "parameters": [
          {
            "name": "stocksTicker",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "date",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "date"
            }
          }
        ]
      }
    },
    "/v2/aggs/ticker/{stocksTicker}/prev": {
      "get": {
        "summary": "Get Stock Previous Close",
        "description": "Get the previous closing data for a specific stock.",
        "operationId": "getStockPreviousClose",
        "parameters": [
          {
            "name": "stocksTicker",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ]
      }
    },
    "/v3/trades/{stockTicker}": {
      "get": {
        "summary": "Get Stock Trades",
        "description": "Retrieve trades for a specific stock.",
        "operationId": "getStockTrades",
        "parameters": [
          {
            "name": "stockTicker",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ]
      }
    },
    "/v3/trades/{optionsTicker}": {
      "get": {
        "summary": "Get Options Trades",
        "description": "Retrieve trades for a specific options ticker.",
        "operationId": "getOptionsTrades",
        "parameters": [
          {
            "name": "optionsTicker",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ]
      }
    },
    "/v2/last/trade/{optionsTicker}": {
      "get": {
        "summary": "Get Last Options Trade",
        "description": "Get the last trade for a specific options ticker.",
        "operationId": "getLastOptionsTrade",
        "parameters": [
          {
            "name": "optionsTicker",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ]
      }
    },
    "/v1/open-close/crypto/{from}/{to}/{date}": {
      "get": {
        "summary": "Get Crypto Daily Open and Close",
        "description": "Get daily open and close data for a specific cryptocurrency.",
        "operationId": "getCryptoDailyOpenClose",
        "parameters": [
          {
            "name": "from",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "to",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "date",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "date"
            }
          }
        ]
      }
    },
    "/v2/aggs/ticker/{cryptoTicker}/prev": {
      "get": {
        "summary": "Get Crypto Previous Close",
        "description": "Get the previous closing data for a specific cryptocurrency.",
        "operationId": "getCryptoPreviousClose",
        "parameters": [
          {
            "name": "cryptoTicker",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "API Key"
      }
    }
  },
  "security": [
    {
      "BearerAuth": []
    }
  ]
}

**Comment by mckaywrigley** [comment]
@mrgizmo212 We just pushed a huge update to fix a ton of issues with tools.

I suspect that it should work now.

Keep me updated and I'll continue testing.

**Comment by sameraw** [comment]
@mckaywrigley i am working with @mrgizmo212 in resolving this, we are now getting a response from the BOT simply saying that it was not able to access the data due to permission issues, however the API is valid. I am going to show below an example of the schema we have and will opmit the API. Was wondering if there is anything we are doing wrong:

`{
	"openapi": "3.1.0",
	"info": {
		"title": "Polygon live market data API",
		"description": "Get live quote and trade data.",
		"version": "v1.0.0"
	},
	"servers": [
		{
			"url": "https://api.polygon.io"
		}
	],
	"paths": {
		"/v2/snapshot/locale/us/markets/stocks/tickers/{ticker}?apiKey=API_KEY": {
			"get": {
				"description": "Get the most up-to-date market data for a specific ticker.",
				"operationId": "GetAaplSnapshot",
				"parameters": [
          {
            "name": "ticker",
            "in": "query",
            "description": "Ticker symbol of the request.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
				"deprecated": false
			}
		}
	},
	"components": {
		"schemas": {}
	}
}
`

Its essentially a simple get request with API passed in the URL.

**Comment by sameraw** [comment]
@mckaywrigley  Example response: No errors just a response stating auth issues. 
![Screenshot 2024-01-26 at 1 42 40 PM](https://github.com/mckaywrigley/chatbot-ui/assets/7453708/8eb323cb-03e2-4744-832a-480a3f8d2f17)

**Comment by mckaywrigley** [comment]
Do you set auth headers in your request?

That may be the issue on our end if so.

**Comment by sameraw** [comment]
Setting auth header like so: `{"Authorization": "Bearer API_KEY"}`

**Comment by sameraw** [comment]
Setting auth header returns the same.

**Comment by mckaywrigley** [comment]
Got it. Let me investigate if there are errors with how we set the authorization headers in the code.

**Comment by mckaywrigley** [comment]
Just pushed a change that fixes a bug that didn't set the authorization header on URL requests.

I think it should work now.

**Comment by sameraw** [comment]
Great @mckaywrigley ! Let me try that and get back to you!

**Comment by sameraw** [comment]
Outstanding, i think we are good for now :) Thanks @mckaywrigley !
![Screenshot 2024-01-26 at 2 13 02 PM](https://github.com/mckaywrigley/chatbot-ui/assets/7453708/c1ee39e1-e0e6-4d28-8278-b0e3064e2a60)

**Comment by mckaywrigley** [comment]
@sameraw Awesome!

In the next week or so we should have better validation and whatnot to make it easier to figure out possible issues with your tools, etc.

Thanks for the help!
