### ISSUE TITLE
User Account Creation Hiccups

### ISSUE THREAD

**Issue by masonjames** [mckaywrigley/chatbot-ui#1278]
1. When a new user is created, the setup process doesn't load fully. The URL changes to setup, but only shows the spinner icon until a manual browser refresh. 

On refresh, the setup process begins but on step 3, clicking next produces no result. I had to clear browser cache/cookies to be logged out, and the process repeats. I've tested this with 2 users and in 2 browsers, but if you have additional troubleshooting steps, I'm happy to do further testing.

2. Password reset email sends a link, but seems to only direct to the login URL, not a password reset screen. I'm using a hosted suprabase setup with emails directly through their service.

**Comment by 24601** [comment]
I had a similar issue to what you are describing in your first problem, but was related to migrations not running against supabase in my case. YMMV, of course, but an existing user did not have an issue. Probably depends what rev you are coming from on how it manifests, but I found a few migraitons not run and that addressed it.

**Comment by masonjames** [comment]
I believe the migration was successful - but only because I've done it about 30 times learning as much as I can. I did manually export some users from a previous install and imported them here. I think I did that correctly, but now I wonder if something there is throwing the newly created ones off.

**Comment by mckaywrigley** [comment]
Double check migrations. That's the issue.
