### ISSUE TITLE
Feature Request: preview token count before submitting

### ISSUE THREAD

**Issue by gadenbuie** [mckaywrigley/chatbot-ui#128]
First, thanks for this awesome open source project!

Because we're using our own API token, it'd be really helpful to show a preview of the number of tokens that a prompt will require before hitting send. 

I noticed that chatblade (a cli tool) has a similar feature. I've been watching my API usage panel but it'd be easier to have a little inline preview.

**Comment by mckaywrigley** [comment]
Looking into adding this soon. Some of the more popular tokenizers don't work directly in the browser so just need to make a custom solution.

**Comment by Chanzhaoyu** [comment]
but the Token calculation for Chinese and other languages is not accurate.

**Comment by Jungley8** [comment]
https://github.com/botisan-ai/gpt3-tokenizer:  maybe a better choice.
This is a isomorphic TypeScript tokenizer for OpenAI's GPT-3 model. Including support for gpt3 and codex tokenization. It should work in both NodeJS and Browser environments.
