### ISSUE TITLE
db-reset error

### ISSUE THREAD

**Issue by aotsukiqx** [mckaywrigley/chatbot-ui#1280]
> chatbot-ui@2.0.0 db-reset
> supabase db reset && npm run db-types

Resetting local database...
Recreating database...
Setting up initial schema...
Applying migration 20240108234540_setup.sql...
unexpected EOF                              
At statement 0: -- Enable HTTP extension    
create extension http with schema extensions

every time npm run db-reset will run into this error.

**Comment by mckaywrigley** [comment]
Please move to "Help" in "Discussions" above
