### ISSUE TITLE
with env. api keys, fresh signup will show Unlock models by entering API keys in your profile settings.

### ISSUE THREAD

**Issue by xycjscs** [mckaywrigley/chatbot-ui#1282]
I have settled several env. api keys. But, new users first time accesss the chat page, all model are unavailable, unless they fresh the page. model selection shows: "Unlock models by entering API keys in your profile settings."

refresh page can solve the problem, but users will not give sites a chance to refresh. They will believe, all models are not available.

**Comment by mckaywrigley** [comment]
Please move to "Help" in "Discussions"
