### ISSUE TITLE
file uploading failed on Netlify deployments

### ISSUE THREAD

**Issue by xycjscs** [mckaywrigley/chatbot-ui#1283]
I deploy the project on the Netlify. I can not upload files for embedding anymore. 
Local deployments are fine.

Anyone has clues?

**Comment by xycjscs** [comment]
vercel is okay. However chinese\japaness\koreans sentence will be garbled.

**Comment by Pirogiran** [comment]
Same issue here.
Edit: On Vercel not only Chinese (and others) will be corrupted, but also Russian, for example.

**Comment by mckaywrigley** [comment]
Please move to "Help" in "Discussions" above
