### ISSUE TITLE
Migration script exposes hardcoded secrets

### ISSUE THREAD

**Issue by leonardsellem** [mckaywrigley/chatbot-ui#1284]
_This issue concerns the codebase, but I don't know whether it belongs here or into the Discussions._

With deployment on Vercel, the documentation prompts to replace the Supabase service_role_key in the `20240108234540_setup.sql` file (and possibly the Supabase project_url).
How to prevent those secrets to be exposed in public forks repositories on Github?

**Comment by mckaywrigley** [comment]
if people deploy their own hosted versions they should only commit the testing values for dev purposes.

Then they should run their production migration setup file separately so it doesn't get committed to their codebase.
