### ISSUE TITLE
Global / Default Variables

### ISSUE THREAD

**Issue by mrgizmo212** [mckaywrigley/chatbot-ui#1285]
Using vercel, is there a way to set global variables for all users that log in & perhaps set 1 main admin account?

Within the .env file we set all the variables but it still prompts every user. to enter them. For clarity I am talking about LLM API Keys.

**Comment by kyleroberts-ai** [comment]
Need to raise this in discussions. 

Read the latest read me update.

**Comment by mckaywrigley** [comment]
In your Vercel project go to the Settings tab and look for Environment Variables in the sidebar.
