### ISSUE TITLE
Bug: files are not referenced when using `text-embedding-3-large`

### ISSUE THREAD

**Issue by peperunas** [mckaywrigley/chatbot-ui#1288]
As the title states, attaching a file to a conversation does not work. The file is correctly uploaded and embeddings generated, but the assistant (in my case GPT 4) states there is no added context.

<img width="751" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/6033387/b986c966-0270-4a8f-a974-58f38f453090">

**Comment by mckaywrigley** [comment]
Just tested on latest version and am not having issues.

Any more details you can share?

**Comment by peperunas** [comment]
This might be due to my modification of the embedding model, as I switched to the `-large` model. I don't see how this can break everything, though.

https://github.com/peperunas/chatbot-ui/commit/9e3d043e9596674148aa23d33f2785e6eb2f0d69

**Comment by mckaywrigley** [comment]
Large by default uses a different amount of dimensions so the search will break.

If you want to modify that you'll need to make db modifications on how large embeddings are stored and searched.

**Comment by ShravanSunder** [comment]
@mckaywrigley i'm trying to use the new dimensions and embedding combo
i've changed:
- 20240108234545_add_file_items the `match_file_items_openai` and `openai_embedding` to 512
- and changed app/api/retrieval/process/route.ts by adding `dimensions: 512` to the embedding call
- updated the open ai package to 4.26

i'm getting an internal server error when i try to use a file in a chat.  `POST /api/retrieval/retrieve`

Did i miss anything?

**Comment by TimchaStudio** [comment]
@ShravanSunder @peperunas @mckaywrigley 

Has your issue been resolved? I have encountered the same error as well.

"I haven't modified any code. Simply following the [official Supabase Docker tutorial](https://supabase.com/docs/guides/self-hosting/docker) for local installation results in the same error." 

ERROR
```
172.21.0.3 - - [12/Mar/2024:13:00:47 +0000] "POST /rest/v1/rpc/match_file_items_openai HTTP/1.1" 404 226 "-" "node"
```

**Comment by peperunas** [comment]
Nope, I switched project alltogether.
