### ISSUE TITLE
API keys in environment variables not used for new users

### ISSUE THREAD

**Issue by viraniaman94** [mckaywrigley/chatbot-ui#1290]
Thanks again for the fantastic tool!

I tried to create a new account on my hosted instance, but was asked to add API keys for the models for which I have already set environment variables in Vercel. Screenshots for reference:

Env variables in vercel:
<img width="947" alt="Screenshot 2024-01-26 at 9 05 53 PM" src="https://github.com/mckaywrigley/chatbot-ui/assets/89636334/0e328a75-329f-4537-aff5-b533313c55bd">

Screenshots of various UI elements where I expected an API key to already be present, but was not:
<img width="375" alt="Screenshot 2024-01-26 at 8 41 42 PM" src="https://github.com/mckaywrigley/chatbot-ui/assets/89636334/4a6910d6-eac7-48db-8af2-c77d5dde3fe1">
<img width="1228" alt="Screenshot 2024-01-26 at 8 41 32 PM" src="https://github.com/mckaywrigley/chatbot-ui/assets/89636334/76dc6335-ef63-4973-af32-5ba7a6883d1b">
<img width="613" alt="Screenshot 2024-01-26 at 8 41 13 PM" src="https://github.com/mckaywrigley/chatbot-ui/assets/89636334/d4b6e1f0-c845-450b-9197-56c8a4885540">

To be clear, I don't see the same issue with the first user I created. I can see that Admin has set the API keys for the models I use with the very first user I created, and can access both Mistral and OpenAI models.

**Comment by mckaywrigley** [comment]
Make sure to redeploy after you've set your env vars.

Can confirm it works as intended.

**Comment by viraniaman94** [comment]
The env vars have not been changed after setting. There have been many deployments after setting the env vars.
