### ISSUE TITLE
ChatbotUI stuck on loading screen: Supabase API call error

### ISSUE THREAD

**Issue by viraniaman94** [mckaywrigley/chatbot-ui#1291]
As of [82b9180](https://github.com/mckaywrigley/chatbot-ui/commit/82b9180c24ab8e898939513779fcfcd85c89d504), Chatbot-UI fails to load in Vercel, due to a 400 from Supabase. Here's the error that I see:

<img width="1584" alt="Screenshot 2024-01-26 at 9 18 15 PM" src="https://github.com/mckaywrigley/chatbot-ui/assets/89636334/192903ff-be4b-4feb-a865-e5d19727c71b">

**Comment by mckaywrigley** [comment]
You need to apply the latest migrations to your hosted DB.

**Comment by mxn2020** [comment]
Do you have a solution for this workspace issue?
Restarting, re installing and anything else did not work for me.
