### ISSUE TITLE
Fresh install - first time login, user cretated in DB but unable to move forward

### ISSUE THREAD

**Issue by macin** [mckaywrigley/chatbot-ui#1293]
I get this once I click create user.  Complete fresh installation on linux...
NAME="CentOS Stream"
VERSION="9"

Unhandled Runtime Error
Error: TypeError: Failed to fetch

Source
db/profile.ts (12:10) @ getProfileByUserId

```
  10 |
  11 | if (!profile) {
> 12 |   throw new Error(error.message)
     |        ^
  13 | }
  14 |
  15 | return profile
```
Call Stack
async fetchStartingData
components/utility/global-state.tsx (198:22)
async fetchData
components/utility/global-state.tsx (137:22)

**Comment by macin** [comment]
@mckaywrigley could you please give a hint what to do? I searched through all issues and no luck finding this problem. Db up to date.
Or maybe this is something for the discussions tab?

**Comment by zerolivesleft** [comment]
I'm having the same issue. Did you find a solution?

**Comment by PrakrutR** [comment]
See #1225
