### ISSUE TITLE
Using files fails to work and in doing so damages profile and all subsequent chats

### ISSUE THREAD

**Issue by J-Light** [mckaywrigley/chatbot-ui#1294]
The app work fine and as expected on start. When I upload a simple text file that has a sample data (I have tried a couple of different files). I get an error (code 500). 

When I then start a new chat I only get gibberish, logging out and back in or creating an new workspace or clearing site date and cookies does not work. Here is an example:

![image](https://github.com/mckaywrigley/chatbot-ui/assets/2544660/649b88f9-2498-41d7-9f76-1ecb8d3e8ea6)

The only way I am able to recover is to reset the database and re-create my account.

**Comment by J-Light** [comment]
Creating a new account without resetting the database also gives expected results.

**Comment by mckaywrigley** [comment]
What's your temperature for the model? 2.0 on the OpenAI models can lead to weird things like this.

**Comment by J-Light** [comment]
I think that may be the issue here. Files still not working, will investigate more. Closing this for now.
