### ISSUE TITLE
I'm sorry but the issue you and alanjustalan closed...

### ISSUE THREAD

**Issue by kevinlyliu** [mckaywrigley/chatbot-ui#13]
Sorry there's really python beginner like me😅

10 hours ago you told Alanjustalan to "

Ah I see! Get rid of the < and >. Sorry for the confusion there. That should fix it!"

The same error, while I don't understand. You means a special character in my openai API key?

![捕获](https://user-images.githubusercontent.com/26814056/226145823-1b09a131-f3af-49d8-98a4-bdaa5bf7f1aa.PNG)
![捕获2](https://user-images.githubusercontent.com/26814056/226145826-d6830d31-be88-47b1-9f51-9b6840c526ad.PNG)

**Comment by mckaywrigley** [comment]
I will modify the README to get rid of those.

It's a standard practice, but I'm sure it's confusing to those unfamiliar. Will remove.
