### ISSUE TITLE
Bug: Cannot change OpenAI models unless save is clicked on the profile window 

### ISSUE THREAD

**Issue by 0-hero** [mckaywrigley/chatbot-ui#1301]
Steps to reproduce 
1. OpenAI API key is provided during initial setup
2. Model defaults to GPT-4 Turbo. Chat works. Settings are locked (asks to provide API key again)
3. Open profile (OpenAI key is already present from setup). Click save
4. Model settings unlock

**Comment by mckaywrigley** [comment]
Just pushed a fix for this.
