### ISSUE TITLE
GPT-4 model is not supported

### ISSUE THREAD

**Issue by biswaz** [mckaywrigley/chatbot-ui#1306]
<img width="637" alt="Screenshot 2024-01-29 at 10 30 33 AM" src="https://github.com/mckaywrigley/chatbot-ui/assets/12367632/f0ed402a-e8df-4418-b3fc-5b27ed5a1311">

Only these 3 models are supported. It would be nice to have the older GPT4 model here too. Since the working of GPT4.5T and GPT4 are very different and model output is also different. GPT4 is less lazy than 4.5T IMO.

**Comment by mckaywrigley** [comment]
Added this back in!
