### ISSUE TITLE
Installing chatbot-ui on a Linux VM

### ISSUE THREAD

**Issue by evgeni-semenov** [mckaywrigley/chatbot-ui#1308]
Hello,

First of all thank you for the great application!

I tried to follow the instructions on Debian Linux VM and failed miserably. 
`brew` is not officially included on any Linux distro afaik, and installing it might not be so straghtforward.

I would highly appreciate a more detailed step by step instructions on Linux installation. Or even better, an all-in-one docker container that could be used as self-hosted in the homelab or cloud environment.

**Comment by Bortus-AI** [comment]
Brew is easy to install on debian 

`sudo apt-get install build-essential procps curl file git`

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

`$(/home/linuxbrew/.linuxbrew/bin/brew`

`eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"`

**Comment by Bortus-AI** [comment]
https://gist.github.com/fardjad/2e38d4dbdd42b28ec8bbe0b725e67f37

https://brew.sh/

https://linux.how2shout.com/2-ways-to-install-homebrew-on-debian-11-bullseye-linux/
