### ISSUE TITLE
Context length bug with chatGPT 3.5

### ISSUE THREAD

**Issue by NousFuturons** [mckaywrigley/chatbot-ui#1315]
I updated to the last version of the repo. I get the following error message each time I start a **new chat** with ChatGPT 3.5 (having set the chats to NOT include profile context or workspace instructions) : « 400 this model’s maximum context length is 4097 tokens. However you requested 4198 tokens (102 in messages, 4096 in the completion) »
Can’t figure out what could possibly be wrong.
Any clues?
Thx
![Capture d’écran 2024-01-29 à 19 23 36](https://github.com/mckaywrigley/chatbot-ui/assets/151826013/d3d65a82-7840-4055-9fe4-c012aa3a2df9)

**Comment by mckaywrigley** [comment]
I suspect some part of our prompt builder isn't tokenizing the message correctly.

I'll investigate.

**Comment by mckaywrigley** [comment]
Just pushed a fix for this if you pull the latest changes!
