### ISSUE TITLE
Profile pic synchronization

### ISSUE THREAD

**Issue by gtentillier** [mckaywrigley/chatbot-ui#1317]
### Profile pic synchronisation

Hello, 
Thank you very much for your efforts on this project! 
I've encountered a problem regarding profile picture synchronization: when uploading a new file, it often occurs that the profile picture in the lower left corner of the interface fails to synchronize. Similarly, the user's profile picture in conversation messages faces synchronization issues, although less frequently than the one in the lower left corner. 
Could you please address this issue?

**Comment by mckaywrigley** [comment]
Great timing - literally just fixed this within a minute of you making this!

Issue was that images uploaded with the same url, so the cache never reset.

If you pull this should be fixed as we changed how image urls upload.

**Comment by gtentillier** [comment]
Great thanks !
Keep up the good work ;)
