### ISSUE TITLE
Context Limits

### ISSUE THREAD

**Issue by daveycodez** [mckaywrigley/chatbot-ui#1318]
Hey, just wanted to let you know that the first thing I did was remove the 1500 character limit on the system prompts. I'm pasting my entire projects into it. I set the limits to 15,000,000 on Supabase. Should probably remove arbitrary context limits when we are getting 128k windows. Other than that, awesome project. I was about to build this but I'm glad you already did lol thank you.

I'm working on a new project for Stuffing context, I'm going to automate synchronizing a codebase with the system prompt so it can assist in realtime with coding tasks inside of your project, with full context. I'll be building it on top of your Chat UI, I'll let you know when it's working

**Comment by mckaywrigley** [comment]
The 1,500 limit only applies to workspaces instructions. That can of course be removed.

The reasoning for this is that most workspace instructions are copy and pasted from ChatGPT's custom instructions which enforce the same limit. So mostly just keep consistent with that.

For system prompts in each chat you can have prompts longer than that (100k char limit).
