### ISSUE TITLE
Update supabase/config.toml when running on Vercel?

### ISSUE THREAD

**Issue by Itangalo** [mckaywrigley/chatbot-ui#1321]
Thanks again for this project.

After spending some time trying to deploy chatbot-ui on Vercel, I believe that supabase/config.toml will need to be updated to make things work. (I haven't made things work, so I'm very open to the idea that I'm wrong.)

Anyway, I suspect something like this would be a good addition to the "hosted quickstart" section in the Readme:

```
In the supabase/config.toml make the following changes:

* project_id (line 3): Set to the project ID as provided by Supabase
* api_url (line 38): Set to the project url
* site_url (line 57): Set to a persistent url for the deployed site on Vercel (not one that changes with each new deploy). Getting this url requires deploying the app first.
```

**Comment by mckaywrigley** [comment]
This file only applies to local instances. For hosted only the ENV values matter.

**Comment by Itangalo** [comment]
Thanks! I'm impressed by your quick responses.
