### ISSUE TITLE
context length exceeded message for GPT-3.5-turbo even for for few tokens

### ISSUE THREAD

**Issue by gkiri** [mckaywrigley/chatbot-ui#1324]
When GPT-3.5-turbo model is configured , below message is seen even though query is one or two tokens.Irrespective of token length below message is seen for all queries.

Note: GPT4 model works fine

![image](https://github.com/mckaywrigley/chatbot-ui/assets/25444878/31fd880c-cf83-453f-a1aa-36ad4be73c33)

**Comment by mckaywrigley** [comment]
Just pushed a fix for this.

Max Tokens was being set when it shouldn't have been.
