### ISSUE TITLE
The nodev16.19.1 I used has been deployed, but it is very slow to open, and it takes several minutes. Why?

### ISSUE THREAD

**Issue by HaiwangTT** [mckaywrigley/chatbot-ui#133]

**Comment by mckaywrigley** [comment]
Perhaps a local node issue. I would suggest reinstalling.

**Comment by HaiwangTT** [comment]
The computer room node is located in singapore, and the operating environment is CentOS 7.9.2 Node 16.19.1，I've redeployed and it's still very slow
