### ISSUE TITLE
Error: Column 'azure_openai_embeddings_id' of relation 'profiles' does not exist

### ISSUE THREAD

**Issue by the3rdWorlder** [mckaywrigley/chatbot-ui#1330]
![Screenshot 2024-01-30 112856](https://github.com/mckaywrigley/chatbot-ui/assets/99656250/01485643-c907-4882-aff2-d42d81a52c47)

it been three days and i never seem to get pass this error... 

in a previous question deleting the browser cache was suggested but i did not work for me.

i put the openai API key in the env.local file where it supposed to overriding any api keys users may enter, is that the issue ??

**Comment by mckaywrigley** [comment]
Need to run the latest migrations

**Comment by ochen1** [comment]
For example, you might need to run the command `sudo supabase migration up` or `sudo npm run db-push` manually.

One potential cause of this issue is #1095 where you'll need to correct the migration file using the method proposed by @kkartunov first.

**Comment by the3rdWorlder** [comment]
> For example, you might need to run the command `sudo supabase migration up` or `sudo npm run db-push` manually.
> 
> One potential cause of this issue is #1095 where you'll need to correct the migration file using the method proposed by @kkartunov first.

this #1095 worked. thank u, ochen
