### ISSUE TITLE
Custom models: "Cannot read properties of undefined (reading 'MAX_TOKEN_OUTPUT_LENGTH')" 

### ISSUE THREAD

**Issue by vOwl** [mckaywrigley/chatbot-ui#1331]
Hi,

Using custom models produces the error "Cannot read properties of undefined (reading 'MAX_TOKEN_OUTPUT_LENGTH')".

I guess the fix of
https://github.com/mckaywrigley/chatbot-ui/commit/bdf725a4c16cf83e8a3ee3cfeceaf58de4f406cc

needs to be applied to
`app/api/chat/custom/route.ts`

Kind regards
M.

**Comment by mckaywrigley** [comment]
@vOwl I suspect you're right. Made the change!

**Comment by vOwl** [comment]
I'm curious - why is the property removed in general?
And why is "max token" selection within "model selection panel" in the upper right corner limits to 4096? (even when model support more)

**Comment by mckaywrigley** [comment]
We should probably add max tokens to custom models to help fix that. Good catch.

**Comment by mckaywrigley** [comment]
Added
