### ISSUE TITLE
Assistant issues: description not configurable / assistant profile pictures won't be saved

### ISSUE THREAD

**Issue by vOwl** [mckaywrigley/chatbot-ui#1332]
Hi,

the **description** of an assistant can't be defined in the edit form, but is shown in the pulldown:
<img width="246" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/10940689/090409ec-900b-49f9-9413-553942ba2d69">

After setup 3 assistants, only for one assistant the the profile image is updated after choosing a picture. The two other ones do not save the picture, even the UI claims the "assistant updated succesfully".

Kind regards
M.

**Comment by Pirogiran** [comment]
Same issue.
![image](https://github.com/mckaywrigley/chatbot-ui/assets/99805468/d251dda4-9c4e-456a-b460-6c73f62779d6)

**Comment by mckaywrigley** [comment]
Fixed!
