### ISSUE TITLE
Impossible to choose a model when using only Azure Ai Keys

### ISSUE THREAD

**Issue by weltonrodrigo** [mckaywrigley/chatbot-ui#1337]
The model selection widget says that I need to provide api keys to choose models.

Workaround is to put anything "afasfsdfasdf" as the open ai key.

**Comment by mckaywrigley** [comment]
Fix on the way.

**Comment by mckaywrigley** [comment]
Should be patched!

**Comment by dannykorpan** [comment]
The problem still persists. When a new user signs up, they must first log out and log back in again for all keys to be set by the system.

**Comment by spammenotinoz** [comment]
F5 seems to do the trick
