### ISSUE TITLE
History Import not work / Request / Improved UI

### ISSUE THREAD

**Issue by jordon31** [mckaywrigley/chatbot-ui#134]
I like this project but could you add SQL? to archive the histories

each history has a UUID must be saved on SQL and the url is generated as on gpt chat

for SQL

save conversations via SQL

if a user wants to export it he can do it (always via .json file) the conversations must be taken from the SQL database

and if one wants to import them automatically they are saved in the SQL database

Add GPT-4 32K TOK model

Add a button Regenerate response like on chatgpt

Add the option to edit the previous message

Improving UI for phone like chat gpt please check yourself it's bad

Thanks
Jordon

**Comment by mckaywrigley** [comment]
Please try and keep issues to 1 item at a time.

**Comment by jordon31** [comment]
so for SQL what do you think?
