### ISSUE TITLE
Could not find a relationship between 'workspaces' and 'models' in the schema cache

### ISSUE THREAD

**Issue by ryanlua** [mckaywrigley/chatbot-ui#1342]
For some reason my hosted version of Chatbot UI started producing errors when I updated my fork. When a would login to the website, it would infinitely load.

This only happened when I updated my fork and redeployed on Vercel. I'm using Supabase for backend.

## Browser console errors
```
Failed to load resource: the server responded with a status of 400 ()
710-c70754b0ced44bdc.js:1  Uncaught (in promise) Error: Could not find a relationship between 'workspaces' and 'models' in the schema cache
    at s (710-c70754b0ced44bdc.js:1:4050)
    at async en (layout-c49fbd18a0ef982d.js:1:5471)
```
![image](https://github.com/mckaywrigley/chatbot-ui/assets/80087248/56a9dcdb-a29a-4c22-b72c-8464c3d68813)

## Supabase reports
![image](https://github.com/mckaywrigley/chatbot-ui/assets/80087248/ef6a7395-beec-420c-8f66-e5331bdd0b57)

## First console error
![image](https://github.com/mckaywrigley/chatbot-ui/assets/80087248/b3a02200-21d9-42f5-945a-5c04bba7d335)
```
{
    "message": "No API key found in request",
    "hint": "No `apikey` request header or url param was found."
}
```

## Second console error
![image](https://github.com/mckaywrigley/chatbot-ui/assets/80087248/4986da46-8cb2-4fb9-bf33-d5f9abeea984)

**Comment by MchLrnX** [comment]
I just ran into this again today. Was there a workaround?

**Comment by danmo** [comment]
after pulling the latest and updating/migrating by the book I'm getting something similar: 
"Error: Could not find a relationship between 'workspaces' and 'tools' in the schema cache"

**Comment by danmo** [comment]
Fixed it by doing a db restart 😅

**Comment by mxn2020** [comment]
I have the same problem and can't fix it.
I keep getting various errors such as:
"Error: Could not find a relationship between 'workspaces' and 'tools' in the schema cache"
or user_id issues. it does not get any workspace.

Anyone with a solution?

**Comment by ryanlua** [comment]
I was able to able to find another similar issue with the same error. Apparently, you need to update the DB but I'm not sure how to do that since I'm quite new to Supabase.

> ```
> You need to apply the latest migrations to your hosted DB.
> ```
> 
> _Originally posted by @mckaywrigley in https://github.com/mckaywrigley/chatbot-ui/issues/1291#issuecomment-1912939482_

I was able to find docs on how to migrate projects for Supabase but it seems awfully complex with needing to back everything up and so you can move to another organization?

> Migrating projects can be achieved using the Supabase CLI. This is particularly useful for older projects (e.g. to use a newer Postgres version).
> 
> https://supabase.com/docs/guides/platform/migrating-and-upgrading-projects#migrate-your-project
