### ISSUE TITLE
GPT 4 Vision responses limited at 16 tokens

### ISSUE THREAD

**Issue by siavashvj** [mckaywrigley/chatbot-ui#1344]
Responses from GPT 4 Vision seems to be hard limited at 16 tokens.

**Comment by mckaywrigley** [comment]
Can confirm. Fixing shortly.

**Comment by mckaywrigley** [comment]
Fixed! Appears OpenAI defaults Vision responses to 16 tokens as you mentioned. Weird default setting on their end lol
