### ISSUE TITLE
GPT-4 Vision model output breaks off after a few words every time

### ISSUE THREAD

**Issue by ByteMirror** [mckaywrigley/chatbot-ui#1347]
Whenever I try to use the GPT-4 Vision Model in ChatBotUI I get a few words of response and then it justs breaks off in the middle of the sentence. 
Does anyone know where this might come from or how I could fix this?
<img width="788" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/96124427/cad9dec3-5c06-4b7a-b517-4e26adb6668f">

**Comment by weltonrodrigo** [comment]
I'm experience this too with both azure vision and openai vision

**Comment by mckaywrigley** [comment]
Have you pulled the latest changes?

A fix went out for this earlier today so I think it *should* be okay now.

**Comment by siavashvj** [comment]
Reported and potentially fixed yesterday: https://github.com/mckaywrigley/chatbot-ui/issues/1344
