### ISSUE TITLE
v2 Docker Compose

### ISSUE THREAD

**Issue by brmassa** [mckaywrigley/chatbot-ui#1349]
hi Mckay,

great work! I wonder about having a docker compose yml to organize the whole package, including Supabase, for a tight delivery solution.

it also would be easy to deploy next to other container stuff in servers.

regards
Bruno Massa

**Comment by mckaywrigley** [comment]
There's currently a community PR being worked on for this!

Keeping my eye on it. Could probably use some extra people contributing to it to speed things up if the demand is there.

**Comment by blablazzz** [comment]
any updates on it?
