### ISSUE TITLE
Using ollama models on a vercel deployment

### ISSUE THREAD

**Issue by PrakrutR** [mckaywrigley/chatbot-ui#1350]
I want to allow the use of locally running ollama models onto my vercel deployment, I tried forwarding the port into a public URL using ngrok but no local models are even shown I cannot seem to fix it any suggestions?

**Comment by Bortus-AI** [comment]
you need to stop ollama and then start it via OLLAMA_HOST=0.0.0.0 OLLAMA_ORIGINS=* ollama serve so that ollama can be reached from another computer

**Comment by PrakrutR** [comment]
This works for the local build and not for the vercel deployment unfortunately my issue is still not resolved

**Comment by PrakrutR** [comment]
@Bortus-AI @mckaywrigley 
using
```
curl http://184.105.157.65:11434/api/generate  -d '{
  "model": "llama2",
  "prompt":"Why is the sky blue?"
}'
```
on a different computer generates a resposnce so ollama works but no models how up on vercel

**Comment by Bortus-AI** [comment]
In my experience vercel like the IP address for ollama to be a domain. Try setting that up and see if it works

**Comment by PrakrutR** [comment]
@Bortus-AI I tried setting that up by forwarding the port through ngrok but that doesn't work do you have any suggestions?

**Comment by humanainer** [comment]
Any sugestions? I Have the same problem...
