### ISSUE TITLE
Tools seems to be appending variables at the end of the URL causing endpoint/formatting errors.

### ISSUE THREAD

**Issue by sameraw** [mckaywrigley/chatbot-ui#1357]
Hi, we are integrating Polygon into some of the tools functions in order to access real-time market data. However Polygon only accepts GET request for their endpoints which is fine however this means we cannot use the body option of the tools since it defaults to POST as seen here:
![Screenshot 2024-02-01 at 10 30 09 AM](https://github.com/mckaywrigley/chatbot-ui/assets/7453708/1918438a-2b36-4835-bf70-bfb38f196577)

Instead we have to use the Query URL option for tools but the URL was being misformatted because the Ticker variable is not passed into the URL as a query param. For Example:

**Correct URL:** https://api.polygon.io/v1/indicators/ema/SPY?timespan=day&adjusted=true&window=50&series_type=close&order=desc

**Incorrect URL:** https://api.polygon.io/v1/indicators/ema/SPY?timespan=day&adjusted=true&window=50&series_type=close&order=desc?ticker=SPY&timespan=day&window=50

For us to fix this we had to change the following lines inside /api/chat/tools/route.ts
![Screenshot 2024-02-01 at 10 32 45 AM](https://github.com/mckaywrigley/chatbot-ui/assets/7453708/02d2aa27-3e20-4be8-99f4-a9d9c6cc3ccb)

**I recommend having the user format the path themselves inside their schema and simply pass in the variables in for example:**
![Screenshot 2024-02-01 at 10 35 31 AM](https://github.com/mckaywrigley/chatbot-ui/assets/7453708/e2b7dce4-20bf-4121-8f41-11e9db1eb74b)
this way the user has more flexibility in formatting their path.

**Comment by jhchundev** [comment]
This issue may relate `jest` failed
```
● extractOpenapiData for body 2 › should parse a valid OpenAPI body schema for body 2

    expect(received).toHaveProperty(path)

    Expected path: "stocksTicker"
    Received path: []

    Received value: {"parameters": {"properties": {"date": {"format": "date", "type": "string"}, "stocksTicker": {"type": "string"}}, "type": "object"}}

      335 |     expect(routes[0].operationId).toBe("getStockDailyOpenClose")
      336 |
    > 337 |     expect(functions[0].function.parameters.properties).toHaveProperty(
          |                                                         ^
      338 |       "stocksTicker"
      339 |     )
      340 |     expect(functions[0].function.parameters.properties.stocksTicker.type).toBe(

      at Object.<anonymous> (__tests__/lib/openapi-conversion.test.ts:337:57)

```

**Comment by mckaywrigley** [comment]
Have a ton of tool fixes coming in the next 24hrs!

**Comment by mckaywrigley** [comment]
Sorry got swamped with some unexpected stuff. Working on this tonight and tomorrow.

**Comment by mckaywrigley** [comment]
Should be fixed. If not open a new PR with whatever the error is an I'll prioritize as this is very critical!
