### ISSUE TITLE
Multiple PDFs in the `Sources ` Tab

### ISSUE THREAD

**Issue by JinL0** [mckaywrigley/chatbot-ui#1366]
I am testing the PDF RAG processes, I uploaded one PDF but multiple PDF files appeared in the `source` tab. 
<img width="1409" alt="Screenshot 2024-02-02 at 6 41 25 PM" src="https://github.com/mckaywrigley/chatbot-ui/assets/29108275/3b048429-25cb-47fe-9ae1-cc3fcf11e123">

**Comment by mckaywrigley** [comment]
Those are various "chunks" from the same pdf. UI can probably cleaned up a bit there where we make it more obvious that they're part of the same file.
