### ISSUE TITLE
Check your Supabase project's API settings to find these values

### ISSUE THREAD

**Issue by YifuDeng** [mckaywrigley/chatbot-ui#1367]
https://supabase.com/dashboard/project/_/settings/api
    at RootLayout (./app/[locale]/layout.tsx:75:87)
    at stringify (<anonymous>)
 ⨯ Error: Your project's URL and Key are required to create a Supabase client!

Check your Supabase project's API settings to find these values

https://supabase.com/dashboard/project/_/settings/api
    at RootLayout (./app/[locale]/layout.tsx:75:87)
    at stringify (<anonymous>)
digest: "2816365943"

**Comment by wozniakpawel** [comment]
Getting the same error, not sure why the issue was closed. Yes, I have populated the `.env.local` file.

**Comment by noodleyness** [comment]
To fix this, I copied the anon key from `supabase status` to .env.local as `NEXT_PUBLIC_SUPABASE_ANON_KEY`

**Comment by wozniakpawel** [comment]
Ah yes, that worked. I am a donkey and only added the `SUPABASE_SERVICE_ROLE_KEY` and `NEXT_PUBLIC_SUPABASE_URL` for whatever reason.

That being said, I imagine more people might run into this issue sooner or later. It might be worth updating this part of the docs to list the three required variables (`NEXT_PUBLIC_SUPABASE_URL`, `SUPABASE_SERVICE_ROLE_KEY`, and `NEXT_PUBLIC_SUPABASE_ANON_KEY`) specifically. It's not crystal clear:

> Note: Use API URL from supabase status for NEXT_PUBLIC_SUPABASE_URL
> Now go to your .env.local file and fill in the values.
> If the environment variable is set, it will disable the input in the user settings.

**Comment by MurphyYue** [comment]
Thanks a lot, it works !

**Comment by kirtanchandak** [comment]
thanks!

**Comment by blexo** [comment]
...AND after you've set these environment variables - make sure and redeploy the project.  My project did not pick them up without redeploying...

**Comment by ghost** [comment]
install simple `npx nuxi dev --dotenv .env.local` and work 😵

**Comment by devp4** [comment]
> Ah yes, that worked. I am a donkey and only added the `SUPABASE_SERVICE_ROLE_KEY` and `NEXT_PUBLIC_SUPABASE_URL` for whatever reason.
> 
> That being said, I imagine more people might run into this issue sooner or later. It might be worth updating this part of the docs to list the three required variables (`NEXT_PUBLIC_SUPABASE_URL`, `SUPABASE_SERVICE_ROLE_KEY`, and `NEXT_PUBLIC_SUPABASE_ANON_KEY`) specifically. It's not crystal clear:
> 
> > Note: Use API URL from supabase status for NEXT_PUBLIC_SUPABASE_URL
> > Now go to your .env.local file and fill in the values.
> > If the environment variable is set, it will disable the input in the user settings.

Correct me if I'm wrong, but you shouldn't need SUPABASE_SERVICE_ROLE_KEY to do the basic operations, right? This should also NOT be exposed to the browser. I would just use the NEXT_PUBLIC ones with RLS and only use SUPABASE_SERVICE_ROLE_KEY in 
edge functions if necessary. Just want to clarify so people don't accidentally use it in the browser.

More info: https://supabase.com/docs/guides/functions/secrets
