### ISSUE TITLE
Support for image generation

### ISSUE THREAD

**Issue by PrakrutR** [mckaywrigley/chatbot-ui#1370]
Gemini Pro generates images but they appear as 
![image001](https://github.com/mckaywrigley/chatbot-ui/assets/76415988/0b851aac-aef9-443a-8154-8cb59ad7fcd6)

Is image generation not supported?

**Comment by MartianInGreen** [comment]
No it is not supported by default, you could add a tool under the tool section. But no LMM model support generating images by default currently, it's just hallucination.

**Comment by PrakrutR** [comment]
Ah that's what I thought thanks!
Is there anyway to make sure a tool/custom llm is available to all users?

**Comment by mckaywrigley** [comment]
Unfortunately just a hallucination
