### ISSUE TITLE
Request: Docker Image

### ISSUE THREAD

**Issue by yesbhautik** [mckaywrigley/chatbot-ui#1376]
Please give support to deploy with docker-compose or docker file, it will be easier to deploy locally as well as in the cloud.

**Comment by mckaywrigley** [comment]
There's a version with sqlite and simplified auth in the works that'll ship with this.

Expect that within 2-3 weeks. A bit swamped but it's in progress.

**Comment by Aj7Ay** [comment]
> There's a version with sqlite and simplified auth in the works that'll ship with this.
> 
> Expect that within 2-3 weeks. A bit swamped but it's in progress.

Sir When can we expect the docker-compose file
