### ISSUE TITLE
Using assistants defined in OpenAI's API

### ISSUE THREAD

**Issue by PrakrutR** [mckaywrigley/chatbot-ui#1398]
I saw the fetch function in app/API/assistants\openai, but it does not seem to fetch assistants created on the open console. Am I missing something? As an aside, is there any way I can create assistants/tools/presets etc, and make them available globally to every user?

**Comment by princemuichkine** [comment]
Please, @mckaywrigley, could you update us on how to build a global assistant? I mean, how can we integrate an assistant built on the OpenAI platform as a "model" in my chatbot UI app?

I would appreciate it if someone who has succeeded in doing this could explain how they did it.
