### ISSUE TITLE
Email signup goes to localhost on vercel deployment

### ISSUE THREAD

**Issue by PrakrutR** [mckaywrigley/chatbot-ui#1400]
Turned on email confirmation for signup but the link that is generated to confirm the email is linked to localhost:3000 rather than a valid url. Any suggestions?

**Comment by yesbhautik** [comment]
Go to: https://supabase.com/dashboard/project/{PROJECT_ID}/auth/url-configuration & change localhost to your website url.

![chrome_6qKapvUM0L](https://github.com/mckaywrigley/chatbot-ui/assets/63995315/ba92316b-36a0-4522-9abf-4c7647f938d9)

**Comment by PrakrutR** [comment]
Thanks that fixed it!
Also it it worth uncommenting ` emailRedirectTo: ${origin}/auth/callback` and ` return redirect("/login?message=Check email to continue sign in process")`
In app/[locale]/login/page.tsx?

**Comment by yesbhautik** [comment]
what

**Comment by PrakrutR** [comment]
in app/[locale]/login/page.tsx there are these two comments
```
// USE IF YOU WANT TO SEND EMAIL VERIFICATION, ALSO CHANGE TOML FILE
// emailRedirectTo: `${origin}/auth/callback`
```
```
// USE IF YOU WANT TO SEND EMAIL VERIFICATION, ALSO CHANGE TOML FILE
// return redirect("/login?message=Check email to continue sign in process")
```
