### ISSUE TITLE
Authentication is limited to Email/Password

### ISSUE THREAD

**Issue by BEEFF** [mckaywrigley/chatbot-ui#1402]
Hellooo,

Absolutely love the UI, how everything works with Supabase but authentication is limited to email/password auth. 

For people who want to set the app up as an enterprise app, i.e use SAML/SSO, we would need to change the login / supabase client code to allow this. 

All references to user_id would need to be changed to lookup values inside the JWT instead of auth.uid() 

Is there a way in supabase to modify how the auth.uid() is generated so SAML providers / and other providers could be used?

**Comment by BEEFF** [comment]
I dont want to make a fork and just hack the living crap out of it, because when a new release comes out, it would be better if everything "just worked"

**Comment by mckaywrigley** [comment]
We'll get around to this eventually. Good PR opportunity.
