### ISSUE TITLE
Can we customize the Gemini API server address？

### ISSUE THREAD

**Issue by zhanghxiao** [mckaywrigley/chatbot-ui#1409]
Can this project customize the Gemini API server address? For example, set an environment variable: Google_URL = Self Proxy Google Gemini Pro API URL.

**Comment by swiftdev29** [comment]
Yes that would be great (if possible)

**Comment by swiftdev29** [comment]
For own models too, maybe some default model, or some default API URL like in v1 can be set up

**Comment by zhanghxiao** [comment]
> 对于自己的模型，也许可以设置一些默认模型，或者一些默认的 API URL，如 v1 中

In fact, this idea should be very convenient after implementation. I think it should only be defined directly in the source code or database.As long as the calling logic of the custom model we need to call follows OpenAI or Google,
