### ISSUE TITLE
Supabase service not healthy error

### ISSUE THREAD

**Issue by jaimejim** [mckaywrigley/chatbot-ui#1424]
I am getting this pesky error
`service not healthy: [supabase_pg_meta_chatbotui supabase_studio_chatbotui] `

I can only think of reinitializing the db but I would like to know if someone else has faced it too.

**Comment by ochen1** [comment]
Run `supabase start` or `sudo supabase start` again. This will start the database.

However, I'm somewhat confident that you are experiencing a migration issue and need to follow the instructions in the referenced comment: https://github.com/mckaywrigley/chatbot-ui/issues/1095#issuecomment-1886900526

And then, run migration again by running a command here: https://github.com/mckaywrigley/chatbot-ui/issues/1330#issuecomment-1937105817

**Comment by jaimejim** [comment]
Thanks!!  The error is actually form the `supabase start` cli command. `--debug` does not provide more clues and using `sudo` still yields the same error. 

I did a clean `git clone` installation, with no migration from the chat-ui legacy and I still get the same error, here are more details:

```sh
supabase_pg_meta_chatbotui container logs:

> @supabase/postgres-meta@0.0.0-automated start
> node dist/server/server.js

Segmentation fault

> @supabase/postgres-meta@0.0.0-automated start
> node dist/server/server.js

Segmentation fault

> @supabase/postgres-meta@0.0.0-automated start
> node dist/server/server.js

Segmentation fault

> @supabase/postgres-meta@0.0.0-automated start
> node dist/server/server.js

Segmentation fault

> @supabase/postgres-meta@0.0.0-automated start
> node dist/server/server.js

Segmentation fault

> @supabase/postgres-meta@0.0.0-automated start
> node dist/server/server.js

Segmentation fault

> @supabase/postgres-meta@0.0.0-automated start
> node dist/server/server.js

Segmentation fault

> @supabase/postgres-meta@0.0.0-automated start
> node dist/server/server.js

(node:19) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
Segmentation fault
supabase_studio_chatbotui container logs:
  ▲ Next.js 13.5.6
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000

 ✓ Ready in 763ms
  ▲ Next.js 13.5.6
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000

 ✓ Ready in 408ms
  ▲ Next.js 13.5.6
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000

 ✓ Ready in 454ms
  ▲ Next.js 13.5.6
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000

 ✓ Ready in 385ms
  ▲ Next.js 13.5.6
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000

 ✓ Ready in 369ms
service not healthy: [supabase_pg_meta_chatbotui supabase_studio_chatbotui]
Try rerunning the command with --debug to troubleshoot the error.
```

**Comment by jaimejim** [comment]
So, disabling "Use Virtualization framework" (as described [here](https://github.com/supabase/cli/issues/1083#issuecomment-1691431279) ) in Docker allowed me to start it but now I get another login bug.  Also documented for intel macbooks on the [supabase website](https://supabase.com/docs/guides/cli/getting-started#running-supabase-locally). 

```js
 ⚠ metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
 ⨯ app/[locale]/login/page.tsx (45:12) @ Login
 ⨯ Error: JSON object requested, multiple (or no) rows returned
    at Login (./app/[locale]/login/page.tsx:51:19)
  43 |
  44 |     if (!homeWorkspace) {
> 45 |       throw new Error(error.message)
     |            ^
  46 |     }
  47 |
  48 |     return redirect(`/${homeWorkspace.id}/chat`)
```

Seems that this new issue is reported here too: https://github.com/mckaywrigley/chatbot-ui/issues/1377
Will attempt to fix based on instructions there and close this issue in the meanwhile.
