### ISSUE TITLE
After trying to loging, I get a Workspace Error

### ISSUE THREAD

**Issue by grahama1970** [mckaywrigley/chatbot-ui#1427]
After I login with a user/pass on my macbook, I get the error below
Is there some credential it needs? I also deleted/disabled browser cache. Any idea what it could be?

```Unhandled Runtime Error
Error: relation "public.profiles" does not exist

Source
db/profile.ts (12:10) @ getProfileByUserId

  10 |
  11 | if (!profile) {
> 12 |   throw new Error(error.message)
     |        ^
  13 | }
  14 |
  15 | return profile
```
<img width="1029" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/152222635/f26a6fe3-6a7f-40c8-b8bd-278bb6d2409d">

**Comment by yesbhautik** [comment]
sir, no need to open issue with same topics. #1377

Vercel will never work with current release. you can use another method, i have given solution. Also, you need help with servers/hosting of this, please let me know.

You can close the issue. 😄
