### ISSUE TITLE
Custom Models default to 10 tokens out

### ISSUE THREAD

**Issue by nivibilla** [mckaywrigley/chatbot-ui#1428]
Hi,

Im using a mistral 7b model hosted by sglang. I cant find any setting to set max tokens out to more than 10. Even though the ui caps at 4096. The actual model itself doesn't return more than 10 tokens.

I have set the tokens to 32k in the workspace settings but it still doesn't do it.

**Comment by nivibilla** [comment]
As a temporary workaround, I've manually set the limit myself by adding this line in `app/api/chat/custom/route.ts`
`max_tokens: 32384`

**Comment by mckaywrigley** [comment]
Specifying max tokens is now possible in custom models
