### ISSUE TITLE
用docker部署的，为啥问问题都是小爱先回答，然后gpt得不到问题，只有个问好。。

### ISSUE THREAD

**Issue by ydlmxl** [mckaywrigley/chatbot-ui#143]
![image](https://user-images.githubusercontent.com/51391646/227723234-c1d760e5-fb4c-4dcb-af53-52fbd4c65fc4.png)

**Comment by Jungley8** [comment]
提错了 项目？

**Comment by ydlmxl** [comment]
没有啊

**Comment by ydlmxl** [comment]
sorry，搞错了
