### ISSUE TITLE
ChatHistory is no longer available for new chat, since "Add chat history navigation functionality #1403"

### ISSUE THREAD

**Issue by spammenotinoz** [mckaywrigley/chatbot-ui#1440]
Hi using current release, [28d47c1](https://github.com/mckaywrigley/chatbot-ui/commit/28d47c19341df117a4e829b756f4a96eb72b9747) ChatHistory response is no longer available for new Chats.
Older Chat History remains available, just new history is not saved \ presented correctly.

**Comment by fkesheh** [comment]
Can you explain that better. The chat history function was about using ctrl-shift up and down to navigate through the messages in the currently opened chat. I also didn't see any change on the sidebar chat, it looks to be working fine

What exactly do you mean with "Older Chat History remains available, just new history is not saved \ presented correctly."?

**Comment by evannaderi** [comment]
I am having the same problem. When I create a new chat, I cannot see the chat history when I return to it.

**Comment by spammenotinoz** [comment]
Fixed: I failed to understand deployment instructions correctly.
How I fixed: 
Set project_url TEXT := 'http://supabase_kong_chatbotui:8000'; within 20240108234540_setup.sql, formerly had the URL from hosted supabase (API screen).   On the front-end I use an environment variable to set project_url as the hosted superbase URL (from API screen).
supabase link
supabase db push
Hope this helps.
