### ISSUE TITLE
Feature request: Global APIs for OpenAI Compatible Models

### ISSUE THREAD

**Issue by spammenotinoz** [mckaywrigley/chatbot-ui#1447]
Excellent project with great support for OpenAI Compatible Models.
The new hosted version is great, like how you simplified the interface and it's a great price point.
A desirable feature for the OpenSource version would be to support the addition global models\via Environment Variables
1_ModelName=
1_ModelID=
1_BaseURL=
1_ModelKey=
1_ContextLength=
Secondly for the pre-defined providers, please add variables to define the BaseURL.
Thankyou for consideration.

**Comment by KastanDay** [comment]
Custom BaseURL support for OpenAI is all I need. Huge unlock. Thanks Mckay.

**Comment by spammenotinoz** [comment]
Closing: thanks to this project have discovered OpenRouter.AI more models than I need/want at a great price.
