### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by yasukionozaki120** [mckaywrigley/chatbot-ui#1449]
The following error occurs

-------------------------
Unhandled Runtime Error
Error: TypeError: Failed to fetch

components\utility\global-state.tsx (170:22)

<img width="960" alt="2024-02-16 11 18 30" src="https://github.com/mckaywrigley/chatbot-ui/assets/56671436/8edc0e12-7d44-43f5-aba9-eff6c7bb4124">

**Comment by mckaywrigley** [comment]
Make sure the backend is running and all migrations have run
