### ISSUE TITLE
feat: parse user's message as Markdown

### ISSUE THREAD

**Issue by fmaclen** [mckaywrigley/chatbot-ui#146]
In this dumb example, it'd be nice if all my messages are also parsed as markdown:

![image](https://user-images.githubusercontent.com/1434675/227725894-41896cbc-79a4-45a5-a1c4-eaab8c303696.png)

**Comment by mckaywrigley** [comment]
I’m going to make this an option. Interestingly it’s about a 50/50 split on who is for and against this.

Options should be rolling out by mid next week.
