### ISSUE TITLE
Request -- Possible saving History via SQL for cpanel server

### ISSUE THREAD

**Issue by jordon31** [mckaywrigley/chatbot-ui#147]
Could you please add SQL to store chat histories? Each conversation must be assigned a UUID and saved in the SQL database. The URL for the chat should be generated as it does on GPT chat. Chat conversations must be stored in the SQL database and if a user wants to export them, he can do so via a .json file. Also, if a user wants to import conversations, they can be automatically saved in the SQL database.

Thanks.
Jordon

**Comment by masonjames** [comment]
There is a JOSN file export option now. Is there anything else needed for your use case?

**Comment by jordon31** [comment]
add a chat sync system

add an AUTH like this project that uses "https://next-auth.js.org/ "

https://github.com/SashenJayathilaka/ChatGPT-Clone

add this feature ASAP which is important and don't save things locally

Thanks
