### ISSUE TITLE
File Uploads with HTML mark-up produce error: Error creating file. Error:. Could not resolve host: supabase_kong_chatbotui

### ISSUE THREAD

**Issue by spammenotinoz** [mckaywrigley/chatbot-ui#1481]
![image](https://github.com/mckaywrigley/chatbot-ui/assets/29272432/b606bb85-7a15-4633-b102-6d82d434eb33)

Highly possible I broke my database, as my initial deployment has the project URL as my supabase url, but updated back to http://supabase_kong_chatbotui:8000 as per the clarified instructions.

Uploading other types of files\pictures is fine.

Issues occurs uploading HTML content and some source code with SCRIPTING markup.

**Comment by spammenotinoz** [comment]
To clarify the issue only occurs when uploading files with HTML content.

**Comment by spammenotinoz** [comment]
Don't prioritise this too much, I tried uploading the HTML code to the official UI of all the key services and broke them all.
So maybe just some improved error handling.
Gemini I get "sorry something went wrong it was you and not us"
ChatGPT "can I help you with something?"
and similar for the other services.

**Comment by deanrie** [comment]
Hi, this problem is globally 

https://github.com/mckaywrigley/chatbot-ui/issues/1472

**Comment by spammenotinoz** [comment]
Closing as duplicate

**Comment by spammenotinoz** [comment]
Duplicate
