### ISSUE TITLE
Backend URL and optional OpenAI key

### ISSUE THREAD

**Issue by guiramos** [mckaywrigley/chatbot-ui#149]
Hello.

I think this could be a great improvement. 

Would not make more sense to, instead reaching out to Openai directly, to send the messages to a backend that will handle conversation, extract specific data and eventually interact more with openai api, fetch memory build more context and then send the message(answer) back to the frontend(chatbot-ui).

I think allowing this out-of-the-box is a great feature. I am trying to do that in my fork but I truly believe that if you provide that built-in would make much more sense.

Also, the backend api url would have to be handle per-environment (I am struggling with that by the way).

Keep up the great work anyway.
This project is a success. Look at the amount of forks and stars.

**Comment by thomasleveil** [comment]
Have you looked at [langChain](https://github.com/hwchase17/langchain) ? If langChain were integrated in chatbot-ui, it would make the heavy lifting

**Comment by mckaywrigley** [comment]
We will be providing LangChain powered apps and plugins. Added your feedback to my list for this!
