### ISSUE TITLE
Add Groq client support

### ISSUE THREAD

**Issue by mmahmad** [mckaywrigley/chatbot-ui#1495]
I have a Groq API key that I'd like to be able to use for the models they support (see [here](https://console.groq.com/docs/models)).

Seems like their chat completion API interface is the same as OpenAI's (https://console.groq.com/docs/quickstart), with some [exceptions](https://console.groq.com/docs/openai).

**Comment by spammenotinoz** [comment]
Wow, thanks [mmahmad](https://github.com/mmahmad) these are super fast.
How can I make this the default model for users?
Do I need to run a SQL migration or front-end code that can be changed.  I'll take a look myself also.

**Comment by mmahmad** [comment]
Thanks to fkesheh@ for the fast turnaround!

For changing the default model in the home and all other workspaces, I think you'd need to change at least the following 2 places:

- defaults: https://github.com/mckaywrigley/chatbot-ui/blob/a18409e2c4fe6338c8af69bdc38d8098f7b9cff7/app/%5Blocale%5D/%5Bworkspaceid%5D/layout.tsx#L159
- adjust the sql migration here: https://github.com/mckaywrigley/chatbot-ui/blob/a18409e2c4fe6338c8af69bdc38d8098f7b9cff7/supabase/migrations/20240125192042_upgrade_openai_models.sql#L4
