### ISSUE TITLE
Sidebar scrollbar appears when you add a folder even if there is only one saved chat

### ISSUE THREAD

**Issue by tomredf** [mckaywrigley/chatbot-ui#151]
Sidebar scrollbar appears when you add a folder even if there is only one saved chat

**Comment by tomredf** [comment]
I see this has been fixed so closing

**Comment by masonjames** [comment]
Yeah, technically this exists across all browsers sizes in my testing... screenshot below is chrome on a 13" macbook pro
<img width="344" alt="Valet Health ChatGPT 2023-04-01 23-21-37" src="https://user-images.githubusercontent.com/297610/229329456-d422811d-8aa7-4bf7-bc95-b6173aa04e54.png">
