### ISSUE TITLE
Not saving new API keys

### ISSUE THREAD

**Issue by evannaderi** [mckaywrigley/chatbot-ui#1528]
I tried adding new API keys and the save button does not work, in the console it says: Error: Column 'groq_api_key' of relation 'profiles' does not exist

**Comment by vnktsh** [comment]
You need to apply latest migrations, run:
`git pull origin main` (or merge changes from main if you're in a different branch)
`supabase migration up`

**Comment by evannaderi** [comment]
> You need to apply latest migrations, run: `git pull origin main` (or merge changes from main if you're in a different branch) `supabase migration up`
 
I am hosting it though, so I get this error:
"Connecting to local database...
failed to connect to postgres: failed to connect to `host=127.0.0.1 user=postgres database=postgres`: dial error (dial tcp 127.0.0.1:54322: connect: connection refused)"
