### ISSUE TITLE
 Error: Column 'groq_api_key' of relation 'profiles' does not exist

### ISSUE THREAD

**Issue by xiaoshuai22334455** [mckaywrigley/chatbot-ui#1530]
358-540004ef67bc4adc.js:1 Uncaught (in promise) Error: Column 'groq_api_key' of relation 'profiles' does not exist

**Comment by vnktsh** [comment]
You need to apply latest migrations, run:
`git pull origin main` (or merge changes from main if you're in a different branch)
`supabase migration up`
