### ISSUE TITLE
Make clear what you store in Supabase?

### ISSUE THREAD

**Issue by cggaurav** [mckaywrigley/chatbot-ui#1531]
For the non technically inclined, not storing data on the browser and in Supabase, raises eyes, especially if it not clear what you exactly store there? 

Could we make that explicit in the README?

**Comment by bleriot14** [comment]
.

**Comment by codsec** [comment]
> For the non technically inclined, not storing data on the browser and in Supabase, raises eyes, especially if it not clear what you exactly store there?
> 
> Could we make that explicit in the README?

If im not wrong, they store users and chats

**Comment by Jonneal3** [comment]
@cggaurav Hey there! So the 2 groups of files responsible for whats getting stored in cache vs. supabase are as follows: Supabase > Types -- This tells you pretty much all of the items and their relationsips with SB and they connect to the DB folders for each table. thats pretty much is for supabase.... AS for the cache, thats the CONTEXT file. The items in the context file (im to believe are cached), and the items get updated as we use the app... BUT also, there is a file called global-state that updates those items upload loading the app.... Hopefully that gives you a starting point
