### ISSUE TITLE
Vercel Deployment Issues

### ISSUE THREAD

**Issue by Jonneal3** [mckaywrigley/chatbot-ui#1537]
<img width="428" alt="Screenshot 2024-03-06 at 8 52 10 PM" src="https://github.com/mckaywrigley/chatbot-ui/assets/92951162/25d123cd-d9af-438d-a2e5-95fb7347d4d4">

Main "start chatting" page when clicked, changes URL to login, however, will NOT actuall hide the start chatting page once deployed to vercel. 

The locally hosted version works great but a deployed version will not. Anyone have any idea?

**Comment by djuillard** [comment]
Same issue on my side.

Moreover, when following the instruction on the Readme, it appears that I actually pushed onto my github fork project the service role key.... which is of course not acceptable. I had to revoke the supabase project to erase the key. How to modify the migration file into Github without creating a security issue ?

**Comment by Jonneal3** [comment]
Better yet, can we just remove that "start chatting page"????... im not sure it is really very useful

**Comment by spammenotinoz** [comment]
> Same issue on my side.
> 
> Moreover, when following the instruction on the Readme, it appears that I actually pushed onto my github fork project the service role key.... which is of course not acceptable. I had to revoke the supabase project to erase the key. How to modify the migration file into Github without creating a security issue ?

According to the doco you don’t use the .env.local file with Vercel or even locally.  Just set the environment variables in Vercel.  I do the same for self hosted.  That is the correct secure approach for Vercel.

**Comment by djuillard** [comment]
> > Same issue on my side.
> > Moreover, when following the instruction on the Readme, it appears that I actually pushed onto my github fork project the service role key.... which is of course not acceptable. I had to revoke the supabase project to erase the key. How to modify the migration file into Github without creating a security issue ?
> 
> According to the doco you don’t use the .env.local file with Vercel or even locally. Just set the environment variables in Vercel. I do the same for self hosted. That is the correct secure approach for Vercel.

Sure, I know about the env.local to be filled in within the Vercel portal. But my concern is about the migration file for which two lines must be modified (see the Readme). If I am not mistaken, the project url and the service role need to be kind of « hard coded » into that file… that is being pushed and synced with the GitHub remote repository…

**Comment by spammenotinoz** [comment]
> > > Same issue on my side.
> > > Moreover, when following the instruction on the Readme, it appears that I actually pushed onto my github fork project the service role key.... which is of course not acceptable. I had to revoke the supabase project to erase the key. How to modify the migration file into Github without creating a security issue ?
> > 
> > 
> > According to the doco you don’t use the .env.local file with Vercel or even locally. Just set the environment variables in Vercel. I do the same for self hosted. That is the correct secure approach for Vercel.
> 
> Sure, I know about the env.local to be filled in within the Vercel portal. But my concern is about the migration file for which two lines must be modified (see the Readme). If I am not mistaken, the project url and the service role need to be kind of « hard coded » into that file… that is being pushed and synced with the GitHub remote repository…

Your "Git" code for Vercel or your hosted front-end can just keep the original unmodified migration scripts.  They are not referenced at all during the front-end deployment \ build, just the environment variables.

The migration file is for the once-off DB build, you just modify the local file and not push back.
If super parandoid, even when you build the DB you can keep the original code, and run that specific migration sql afterwards to update the service role key ad project url.  Reminder though, the migration file is just run once on the original backend\database build.
It's absolutely not used when you deploy the front-end via Vercel.

**Comment by Jonneal3** [comment]
@djuillard yeah as far as I know, the migration files are only used for the supabase setup so you dont need to reference them after that occurs on your initialization of the app :) -- I would be cognizant of the RLS though

**Comment by Jonneal3** [comment]
Tried troubleshooting for 3 hours tonight and nothing. Anyone have any ideas? Ive tried:

Altering the page.tsx code > did NOT work. It would jsut refresh the screen constantly. 
Altering the .env variables file etc as mentioned before to no avail

Anyone have any solutions> I think the bet idea is to remove the start chatting page.... Can we get some votes on that?

**Comment by spammenotinoz** [comment]
Sorry do you actually have an issue\problem?   Or just want to hide the "Start Chatting Page".
If so please explain the problem\issue, I could not work it out from the history.
I actually like the "Start Chatting Landing Page"

**Comment by djuillard** [comment]
> en when you build the DB you can keep the original code, and run that specific migration sql a

OK, very clear, thank you, I didn't know that!

**Comment by Jonneal3** [comment]
@spammenotinoz Ok well we dont have to remove that page, it was just a secondary thought. Yes i do have an issue. Same thing I had said earlier. Running the program locally works fine, on vercel, I cannot get past the starting page. 

When i click the "start chatting" button, it changes the url to the /login route, but then "something" happens. When i check the console logs, there are no errors. So either the when that button gets clicked, its hitting an error when rendering the login page (or its not), but either way it just shows the start chatting page and no way to click past it.

I have opened up a Vercel issue as well. Im not sure if its something to do with the transition of server to client side rendering or something like this. 

I see @mckaywrigley commended in a "use client" tag at the top but i'm not sure its purpose, as there are no reference imports.

<img width="761" alt="Screenshot 2024-03-08 at 11 00 25 AM" src="https://github.com/mckaywrigley/chatbot-ui/assets/92951162/6e84daaf-6c39-4d37-9af5-70ef6c3b75a6">


Anyways.. Any Thoughts? I'd love to fix this for future users... thanks

**Comment by Jonneal3** [comment]
Ok now ive confirmed Im not going crazy. I decided to completely re-fork the newest branch and deploy right to vercel and theres an error - will not show up on newly deployed vercel at all . 

We should look at the updates made last few weeks and make sure that the app can be deployed.

<img width="1909" alt="Screenshot 2024-03-08 at 12 38 36 PM" src="https://github.com/mckaywrigley/chatbot-ui/assets/92951162/09e98c05-e265-405b-a47f-891ebd7e9735">

EDIT: I "think" i found the issue. It surely does involve environment variables as @spammenotinoz in vercel for deployment as well! I was just entering random variables there for deployment as Ive never had a site deploy but show a screen like that. So, i tried deploying WITH the correct variables and it worked. SO, if you are deploying quickly, you MUST always have the correct variables for supabase (at least), CORRECT when you deploy. Just a warning lol.

**Comment by djuillard** [comment]
Hi @Jonneal3 , can you re-explain how you did to make it work ? I did enter the correct variables in the Vercel setting page, but I got stuck at the "login / sign up" page like you. Did I miss something ? Which are the mandatory environment variables ? Only the ones related to supabase ?

**Comment by Jonneal3** [comment]
@djuillard Yes exactly.  With Next.js, you need the supabase environment variables in there exactly correctly (in the vercel environment), for deployment. So just make sure you have those in there exactly like this and redeploy. That worked for me.

<img width="911" alt="Screenshot 2024-03-11 at 11 00 18 AM" src="https://github.com/mckaywrigley/chatbot-ui/assets/92951162/3613922e-618e-4174-abb4-78c43ef9f417">
