### ISSUE TITLE
Claude 3 Opus | Chat with Images

### ISSUE THREAD

**Issue by gamingflexer** [mckaywrigley/chatbot-ui#1548]
Using **Claude 3 Opus** for Vision fails with the following message.

![image](https://github.com/mckaywrigley/chatbot-ui/assets/50608241/6224a3c5-9cf6-45cf-8e5e-21b1a82b75e3)

Thanks ! a lot appreciate the project & effort

**Comment by NousFuturons** [comment]
And I get the following error in the console : « Failed to load resource: the server responded with a status of 413 () api/chat/anthropic »

**Comment by johan456789** [comment]
this can be closed now. #1562 fixed this
