### ISSUE TITLE
Switch GPT model in the middle of a conversation

### ISSUE THREAD

**Issue by jiayao** [mckaywrigley/chatbot-ui#155]
It would be useful to combine the speed and cost-effectiveness of gpt-3.5-turbo and the power of gpt-4 in some conversations.

**Comment by junwatu** [comment]
I think the conversation will lose context.

**Comment by jiayao** [comment]
@junwatu The context is all captured in the list of messages we send to openai.

**Comment by jiayao** [comment]
Implemented.
