### ISSUE TITLE
add Claude Haiku

### ISSUE THREAD

**Issue by johan456789** [mckaywrigley/chatbot-ui#1559]
Haiku is [just available](https://www.anthropic.com/news/claude-3-haiku). I'm creating a pull request for this.

**Comment by spammenotinoz** [comment]
Suggest combining with https://github.com/mckaywrigley/chatbot-ui/pull/1571 to Fix#1543

PS: Haiku is an excellent model, it's now my default as it's a lot cheaper and just as good as GPT-4=Turbo-Preview

**Comment by spammenotinoz** [comment]
Given there is a pull request, and it's a feature shouldn't this be closed?

**Comment by johan456789** [comment]
This will be closed when the PR is merged.
