### ISSUE TITLE
Add images support for Claude 3 Vision

### ISSUE THREAD

**Issue by matiasfnunezdev** [mckaywrigley/chatbot-ui#1563]
- Add images support for Claude 3 Vision

_"The Claude 3 family of models comes with new vision capabilities that allow Claude to understand and analyze images, opening up exciting possibilities for multimodal interaction. With Claude, you can now provide both text and image inputs to enrich your conversations and enable powerful new use cases."_

Reference docs: https://docs.anthropic.com/claude/docs/vision

**Comment by johan456789** [comment]
this can be closed now
