### ISSUE TITLE
LANG function automatic detection 

### ISSUE THREAD

**Issue by Oxp228** [mckaywrigley/chatbot-ui#158]
make it so that the user's preferred language is automatically detected (by detecting from the browser what language it is)

**Comment by oznav2** [comment]
i would suggest to improve this function and add a small button to select language. the idea is to allow user to select his desired language for the conversation so he will be able to conduct a conversation in English and another on French without changing his browser settings each time .

**Comment by Jungley8** [comment]
All you need to do to switch languages is visit https://www.chatbotui.com/fr or https://www.chatbotui.com/zh. Of course, having the option to select the language with a simple click would be even better.
