### ISSUE TITLE
Not correctly displaying Username

### ISSUE THREAD

**Issue by fbec76** [mckaywrigley/chatbot-ui#1596]
When chatting with any model, the Name to be called is not correctly formatted: <br>
<img width="135" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/37416552/a6d79c3f-4bdd-46cc-885c-017eceddd20e">
<p>

A fix would could look like this: <br>
<img width="170" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/37416552/7f2bc579-abc2-4be6-a113-602454bbb15b">

For that you would have to update the `components/messages/message.tsx` in Line 266.

Please consider updating this.
Otherwise, is there any guide on how to contribute to this repo?

**Comment by mckaywrigley** [comment]
Should be fixed!
