### ISSUE TITLE
Can only upload word docs after pull request #1557

### ISSUE THREAD

**Issue by haydenkong** [mckaywrigley/chatbot-ui#1601]
Can't upload other file types except for word docs after: Add file size limit for uploads and fix error handling in file upload #1557 pull request

![image](https://github.com/mckaywrigley/chatbot-ui/assets/115069692/a23a9321-2724-4f36-a0cb-fd85d6fc9413)

Thanks!

**Comment by spammenotinoz** [comment]
Excellent find, bet it works via explorer drag and drop!!
@fkesheh @mckaywrigley  does this help narrow down the file upload issue, when using New File Create\Menu?
Status:
Drag Drop into Chat (working for all file types)
New File Create (appears to be word .docx only), all other types regardless of size return the multiple (nor no) rows returned error.
Previously thought it was all fines but this is getting closer.
Side Node: Upload Images to Claude Haiku works via Mobile (didn't even know this model supports images), but not via PC.

**Comment by haydenkong** [comment]
Yes! So when I drag and drop the file into the chat area, it works fine most of the time(the .csv file failed but I think it's not supported yet). If I upload the files using the sidebar, it returns the error listed above. 

and yes, the only file I can get it to successfully upload using the sidebar is a word .docx file.

**Comment by haydenkong** [comment]
But also good to note that before the pull request. the uploads were perfectly fine. I assume it's something to do with the updates made with pull request #1557.

It is probably because of some change in the following files:

- app/api/retrieval/process/route.ts
- components/chat/chat-hooks/use-select-file-handler.tsx
- db/files.ts
- db/storage/files.ts

**Comment by spammenotinoz** [comment]
I don't think it was pull request #1557, as I rolled this back.  
Can anyone else still confirm the issue after roll-back of #1557 ?

**Comment by mckaywrigley** [comment]
reverted just in case

**Comment by spammenotinoz** [comment]
> reverted just in case

Thanks, tried twice and I was now able to upload fine via the sidebar, new file\create file option.
Thank-you

**Comment by haydenkong** [comment]
Thank you @mckaywrigley and @spammenotinoz. Reverted it and it's working perfectly fine. 

I will close the issue.
Thanks!
