### ISSUE TITLE
Consider using prettier to enable consistent formatting? 

### ISSUE THREAD

**Issue by srsholmes** [mckaywrigley/chatbot-ui#164]
Would you consider using prettier to enable consistent code formatting between contributors?

It would likely reduce unnecessary git diffs once setup and the code base formatted.

I am happy to do a PR if that is something we would be interested in.

**Comment by mckaywrigley** [comment]
Yeah that would probably be good. I've noticed it a lot lately.

**Comment by srsholmes** [comment]
Ok I'll do a PR and reference this issue as soon as I can 🙂
