### ISSUE TITLE
When the AI finishes replying, the content the user is typing is cleared.

### ISSUE THREAD

**Issue by TimchaStudio** [mckaywrigley/chatbot-ui#1683]
website: www.chatbotui.com

![show-error](https://github.com/mckaywrigley/chatbot-ui/assets/65017420/da7ac4a3-a1b6-41d3-8f67-5540e65328bf)

This is not an expected behavior for users. When the AI finishes replying, the content the user is typing should not be cleared.

**Comment by haydenkong** [comment]
Yea ill look into that further

**Comment by ovachiever** [comment]
Wish I was dev-enough to help, but I can confirm this is a major-minor issues for us as well.

**Comment by haydenkong** [comment]
I don't really see any major problem, but the forked version of ChatBotUI (ChatLabs) doesn't have this issue. Maybe try comparing parts of the code?
