### ISSUE TITLE
Messages not sending when pressing enter / clicking the send icon

### ISSUE THREAD

**Issue by taylorsudo** [mckaywrigley/chatbot-ui#1718]
Messages not sending when pressing enter / clicking the send icon -- tried logging in and out, using a different API key, using a different browser and device, but it doesn't work (since the beginning of this month)

**Comment by triforcely** [comment]
I started having the same issue

**Comment by triforcely** [comment]
I noticed that if I start new chat and select a model in top right corner it works. I think I have an obsolete model selected as a default for new chats and that might be the case for you too @taylorsudo

**Comment by taylorsudo** [comment]
> I noticed that if I start new chat and select a model in top right corner it works. I think I have an obsolete model selected as a default for new chats and that might be the case for you too @taylorsudo

This works -- thank you!
