### ISSUE TITLE
Add GPT-4o

### ISSUE THREAD

**Issue by hashmil** [mckaywrigley/chatbot-ui#1726]
Of course this is very new - and looking forward to seeing it being implemented!

**Comment by derpina-ai** [comment]
It's already implemented. 
![image](https://github.com/mckaywrigley/chatbot-ui/assets/153082447/b71298b6-6f2f-41db-8a17-6678291c92fb)

**Comment by danielgrabowski** [comment]
Will you publish a new docker image supporting GPT-4o?

**Comment by derpina-ai** [comment]
Just git pull my friend. This repo doesn’t provide docker images nor are they required except for supabase hosting/migration. You deployed using older code, just redeploy using the latest version, whatever method you used initially

**Comment by danielgrabowski** [comment]
We're deploying on Docker using this: https://github.com/mckaywrigley/chatbot-ui/pkgs/container/chatbot-ui so you ARE providing something :) So to make it clear - you will not update the linked docker image to support new models?

**Comment by derpina-ai** [comment]
First of all @danielgrabowski I'm not a maintainer or repo owner here, just a dude in case you didn't realize. 
Secondly that thing is 4 months old, it's probably missing half the commits on this repo.  
It doesn't say anywhere on github that the end product of this repo is anything but the open-source source code. Whatever you found there  may or may not ever be updated. 
Good luck to ya!

**Comment by codehopper-uk** [comment]
@danielgrabowski same disclaimer as @derpina-ai - I'm not a maintainer or affiliated, so can't support much...

but, try this Dockerfile 

```# ---- Base Node ----
FROM node:19 AS base

WORKDIR /app
COPY package*.json ./

# ---- Dependencies ----
FROM base AS dependencies
RUN npm ci

# ---- Build ----
FROM dependencies AS build
COPY . .
RUN npm run build

# ---- Production ----
FROM node:19-alpine AS production

WORKDIR /app
COPY --from=dependencies /app/node_modules ./node_modules
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
COPY --from=build /app/package*.json ./
COPY --from=build /app/next.config.js ./next.config.js
COPY --from=build /app/i18nConfig.js ./i18nConfig.js

# Update the apk package list and install the required libraries.
RUN apk update && apk add g++ make python3 libc6-compat

# Expose the port the app will run on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
```

and build against main branch via

```
docker build -t chatgpt-ui .
docker run -e OPENAI_API_KEY=$OPENAI_API_KEY -p 3000:3000 chatgpt-ui
```

(though I don't see GPT-4o available as an option...)

**Comment by hashmil** [comment]
> It's already implemented. ![image](https://private-user-images.githubusercontent.com/153082447/331567007-b71298b6-6f2f-41db-8a17-6678291c92fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTQ4NDIsIm5iZiI6MTcxNjQ1NDU0MiwicGF0aCI6Ii8xNTMwODI0NDcvMzMxNTY3MDA3LWI3MTI5OGI2LTZmMmYtNDFkYi04YTE3LTY2NzgyOTFjOTJmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwODU1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYmVhMmQ5YmRiNjUyYWQ4Y2Y4NTBkYjlmZGI5NGFkNmQyY2E2ZWY5MWE4YmYzNGI0ZTA5ZDkwMDUzMGFiNzBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PBy5cDqo4tRqPx6FVZltxAhCLw0aLIMQS3kTzVVYVyM)

thank you! i just did a git pull and it seems to be there!
<img width="488" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/4124458/8c89045d-3a62-479c-af3b-df53787d67e0">
