### ISSUE TITLE
Add Google Gemini 1.5 Pro and Gemini Flash

### ISSUE THREAD

**Issue by meetpateltech** [mckaywrigley/chatbot-ui#1728]
Gemini 1.5 Flash is available in public preview with a 1 million token context window in Google AI Studio and Vertex AI.

more detailed information available here:
https://deepmind.google/technologies/gemini/flash/
https://deepmind.google/technologies/gemini/pro/

**Comment by presleygermano** [comment]
Could someone tell me how I can configure Gemini 1.5 in chatbot-ui?

**Comment by meetpateltech** [comment]
You need to modify these files to add Gemini 1.5 in this chatbot-ui: 

1. types/llms.ts
2. lib/models/llm/google-llm-list.ts
3. lib/chat-setting-limits.ts
4. app/api/chat/google/route.ts

**Comment by faraday** [comment]
Done here: https://github.com/mckaywrigley/chatbot-ui/pull/1772

This issue can be closed.

**Comment by meetpateltech** [comment]
Yes, but you added 'Gemini 1.5 Pro' as 'Gemini Flash'. (There is a separate 'Gemini 1.5 Flash' model.)

I have fixed this in #1778

**Comment by faraday** [comment]
@meetpateltech Ah yes, I was using Flash initially. I must have forgot to re-add it the definition back in.
Thanks for fixing.

**Comment by meetpateltech** [comment]
@faraday Thank you! Closing this now.
