### ISSUE TITLE
File upload disregards filename

### ISSUE THREAD

**Issue by gianlucagilardi** [mckaywrigley/chatbot-ui#1734]
Upon uploading a pdf file the system correctly embeds it and adds to the collection but drops the filename (i.e., "whatever.pdf" becomes ".pdf")

Filename can be later edited to restore the original name.

While uploading the file, i see in the console the following error:
_Warning: TT: undefined function: 32_

Dunno if it is related or not.

Update: if you upload the file from the prompt (+ symbol on the left of the input box) everything is fine (filename is kept)

**Comment by housser-apply** [comment]
I'm seeing the same issue. I'm not seeing any client-side errors in the console, but I am seeing that the very first POST request to `supabase/rest/v1/files` already has the `name` attribute set to the file extension, so it seems like it's a client-side transformation that's splitting the filename unexpectedly.
