### ISSUE TITLE
Sonnet 3.5 is still not showing in chatbotui.com

### ISSUE THREAD

**Issue by eoakley** [mckaywrigley/chatbot-ui#1797]
Sonnet 3.5 is still not showing in chatbotui.com

**Comment by meetpateltech** [comment]
The reason Sonnet 3.5 is not showing on chatbotui.com is that the deployment version of the site has not been updated with the latest commit.

You can fork the repo and run it locally or self-host it to see Sonnet 3.5.

**Comment by XTorX** [comment]
Sorry, what is meant by self-host. Can I change the code myself to use it? Thank you very much.

**Comment by eoakley** [comment]
It's there now. Thanks

**Comment by XTorX** [comment]
With OpenAI everything is fine, but I get an error with the Antropic API. I don't understand why. I tried everything.

**Comment by meetpateltech** [comment]
@XTorX 
> Sorry, what is meant by self-host. Can I change the code myself to use it? Thank you very much.

Self-host means that you run the code on your own system, either locally or on a server, and you typically do not need to change the code (except environment variable)

> With OpenAI everything is fine, but I get an error with the Antropic API. I don't understand why. I tried everything.

What is the exact error message that you are seeing with the Antropic API?

**Comment by XTorX** [comment]
Thanks for your answer. I get the error: "Custom api key is incorrect. Please fix it in your profil setting."
The API works fine in my own script. I tried everything, with " and ' before and after the api-key, in the profil, in .env_local, in the model , but I still get these error. What do I am wrong? Thank you very much
