### ISSUE TITLE
Add MongoDB database support for ChatBOT UI app

### ISSUE THREAD

**Issue by KutiBond** [mckaywrigley/chatbot-ui#182]
Currently, the ChatBOT UI app uses local storage to store chat messages. While this works fine for small-scale testing, it is not a scalable solution for real-world use cases. It would be great if the app could be updated to use a more robust and scalable database like MongoDB.

Adding support for MongoDB would not only improve the app's performance and reliability but also make it more attractive to users who need to store large volumes of chat messages. MongoDB is a popular choice for many web applications due to its scalability and flexibility, and it would be a valuable addition to the ChatBOT UI app.

**Comment by oznav2** [comment]
i agree. very much the same way as implementing such a functionality based on google firebase and firestore can be very useful and allow both google Auth login and scalable firestore DB.

**Comment by KutiBond** [comment]
I have already tried to do a realtime chat app with firebase but it is not scalable, so I would recommend MongoDB Stitch

**Comment by jfgonsalves** [comment]
I second this. My use case is very simple - I'm a single user with no requirement for concurrency at all. I'd even entertain storing history in a flat JSON file but I imagine that would get unwieldy quickly. SQLite/MongoDB or some other database solution might be the most flexible.

**Comment by jorge-menjivar** [comment]
Would anyone be interested in a PostgreSQL solution? I have a side project a bit similar to this, but focusing on education. It saves the conversations on PostgreSQL, and links it to the user's account. This code is currently in python, but I can quickly port it here if there is enough interest. Hosting PostgreSQL databases is not cheap either, so I want to make sure there will be a use for its support.

**Comment by Wingzzzzz** [comment]
@jorge-menjivar +1 doing quite the same thing.
user database, conversion (if enable), token control in RDBMS

**Comment by jorge-menjivar** [comment]
@Wingzzzzz do you mean you are already working on bringing RDBMS storage to this project? Or do you mean you are working on something similar to my side project? Thanks!

**Comment by Wingzzzzz** [comment]
@jorge-menjivar adding a membership system with probably user, usage table

**Comment by dotneet** [comment]
I've added MongoDB support at fork repo.
https://github.com/dotneet/smart-chatbot-ui

It may be difficult to merge into this repository because of the many other fixes, but it would be helpful if anyone intends to implement MongoDB support in this repo.
