### ISSUE TITLE
Error on login page: relation "public.workspaces" does not exist

### ISSUE THREAD

**Issue by AumCoin** [mckaywrigley/chatbot-ui#1834]
I followed the directions to install the project.  On the login page I put username "myname@local" and a password.  I clicked login and got some error indicating my username was invalid.  Then I clicked "Sign up" and received this error on http://myserver:3000/login:

![image](https://github.com/user-attachments/assets/9e0fa12e-cf89-4791-b722-2dcdf6aa6631)

I tried various thing but could not resolve this error.  I wiped out the entire project folder and started over, but still I receive this error whenever the **/login** URL is visited.  I searched and could not find a similar report.  Any help is appreciated.

**Comment by AumCoin** [comment]
I used an unofficial Docker container instead and will not be following up on this issue.   Closing.

**Comment by tangmc0210** [comment]
Hi, I met with the same problem and am wondering how you solve this problem. Can you share with me some ideas?
