### ISSUE TITLE
.overflow-scroll

### ISSUE THREAD

**Issue by seanchito** [mckaywrigley/chatbot-ui#184]
Really enjoying this project!

CSS .overflow-scroll style creates an ugly mid-page scrollbar in Firefox.  Removing the style fixes it, without any apparent ill-effects.

**Comment by Abh3201** [comment]
It also happening in chrome.

**Comment by Abh3201** [comment]
But by removing it added a vertical and horizontal scroll to the full page.

**Comment by igorhbs** [comment]
Is this why scrolling is suddenly so slow (Chrome desktop)?

**Comment by seanchito** [comment]
Ah, I see it now.   Simply removing overflow:scroll breaks the page once a long response has been generated.   A quick fix for the ugly horizontal scrollbar would be to change overflow:scroll to overflow-y:scroll.   That at least removes the pointless page-splitting horizontal scrollbar visible before responses are generated.  The initial vertical scrollbar isn't as noticeable. 

On my W10 laptop I only see the horizontal scroll page split in Firefox, not in Chrome or Edge.

**Comment by thomasleveil** [comment]
@seanchito can you test if the following change does the trick for you ?
![image](https://user-images.githubusercontent.com/42300/227799095-b41372f9-90bf-4d0b-9958-be177d33aa0b.png)

**Comment by seanchito** [comment]
@thomasleveil Yep that's the stuff.  x-overflow: hidden FTW.    Perfect now -- scrollbar when you want it, no extra scrollbars when you don't.   Looks good in Firefox, Chrome and Edge.  Nice

**Comment by thomasleveil** [comment]
Thank you for confirming the fix. This is included in #174

**Comment by thomasleveil** [comment]
#174 is now merged.
