### ISSUE TITLE
Signup issue

### ISSUE THREAD

**Issue by saidi59** [mckaywrigley/chatbot-ui#1864]
I'm getting this error when try to sign up.
please someone help me to fix this.

Thanks.

<img width="1440" alt="Screenshot 2024-10-12 at 5 41 49 PM" src="https://github.com/user-attachments/assets/22d5255d-0fd3-449d-97ba-5852f036a4d3">
<img width="477" alt="Screenshot 2024-10-12 at 5 41 54 PM" src="https://github.com/user-attachments/assets/32b9f1b8-6c81-4b41-bbbc-fa3354082d9f">

**Comment by Davitcoin** [comment]
Do you setup your DB correctly?

**Comment by slliland** [comment]
You may need to set NEXT_PUBLIC_SUPABASE_URL, etc in your vercel's environment variables according to your own db's url.

**Comment by saidi59** [comment]
> Do you setup your DB correctly?

Yes

**Comment by saidi59** [comment]
> You may need to set NEXT_PUBLIC_SUPABASE_URL, etc in your vercel's environment variables according to your own db's url.

Thank you so much, brother. It's working now.
