### ISSUE TITLE
activate gpt-4

### ISSUE THREAD

**Issue by thomasleveil** [mckaywrigley/chatbot-ui#19]
My api key gives me access to model `gpt-4` and un-commenting  https://github.com/mckaywrigley/chatbot-ui/blob/c40f755cac7663589ae8399f0b1a9e8ab8ca0b0a/types/index.ts#L4 and https://github.com/mckaywrigley/chatbot-ui/blob/c40f755cac7663589ae8399f0b1a9e8ab8ca0b0a/types/index.ts#L10, I could verify that everything works.

Now, I guess you kept it commented in order to avoid being flooded with issues saying that GPT 4 is producing errors from people with no `gpt-4` access.

I wrote the following api route that provides a list a supported available models given an api key, but I'm not familiar with next.js and I see issues with spamming openai again and again for just checking the available models. Caching should be used.  Anyway, here's the endpoint code in case part of it can be useful (maybe with getServerSideProps ?)

```typescript
// api/models.ts
import { OpenAIModel } from '@/types';

export const config = {
  runtime: "edge"
};

type Model = {
  id: string;
};

type ModelsData = {
  data: Model[];
}



const handler = async (req: Request): Promise<Response> => {
  try {
    let key: string | null = null;
    try {
      key = (await req.json())?.key;
    } catch (e) { }

    const res = await fetch("https://api.openai.com/v1/models", {
      headers: {
        Authorization: `Bearer ${key ? key : process.env.OPENAI_API_KEY}`
      },
    });

    if (res.status !== 200) {
      throw new Error(`OpenAI API returned an error ${res.status} : ${await res.text()}`);
    }

    const { data } = await res.json() as ModelsData;
    const availableModelIds = data.map((model: Model) => model.id)
    const supportedModels = availableModelIds.filter(
      x => (Object.values(OpenAIModel) as String[]).includes(x)
    )
    return new Response(
      JSON.stringify(supportedModels),
      {
        status: 200,
        headers: {
          'content-type': 'application/json',
        },
      }
    );
  } catch (error) {
    console.error(error);
    return new Response("Error", { status: 500 });
  }
};

export default handler;

```

**Comment by mckaywrigley** [comment]
Keeping it "off" by default was mostly to avoid the headache of people getting confused why it wasn't working if they didn't have access yet.

This is a smart way to handle the problem. I'll go ahead and use this to help implement GPT-4 tomorrow.

Thanks for this!

**Comment by mckaywrigley** [comment]
About to add support so closing this. Thanks again for the idea - fully implemented!
