### ISSUE TITLE
How to enable GPT-4

### ISSUE THREAD

**Issue by wangweiX** [mckaywrigley/chatbot-ui#193]
Hello, I love this project. I deploy it. but i can't find GPT-4 mode.

**Comment by HaiwangTT** [comment]
GPT4 is required for your API support

**Comment by rsaisankalp2** [comment]
how to enable it
if we have api access for gpt4

**Comment by defining** [comment]
same problem here. I have access to GPT4 but impossible to enable it in the chatbot UI
