### ISSUE TITLE
Feature Request: Support ChatGPT Plugins

### ISSUE THREAD

**Issue by jiayao** [mckaywrigley/chatbot-ui#207]
As a starting point, you could equip ChatBot with a memory of past conversations by integrating https://github.com/openai/chatgpt-retrieval-plugin/tree/main/examples/memory

**Comment by kaaboaye** [comment]
LangChain has already created working plugins implementation. It could be used to inspire ChatBot's implementation.

https://python.langchain.com/en/latest/modules/agents/tools/examples/chatgpt_plugins.html
