### ISSUE TITLE
LangChain Wrapper

### ISSUE THREAD

**Issue by slavakurilyak** [mckaywrigley/chatbot-ui#208]
Given the fast development pace of large language models (LLMs) and foundation models, it would be great to see a wrapper around LangChain.

Here is the JS/TS library: [langchainjs](https://github.com/hwchase17/langchainjs) by @hwchase17
Here is the Python library: [langchain](https://github.com/hwchase17/langchain) by @hwchase17

Here are the current LangChain features: [langchain.com/features.html](https://langchain.com/features.html)
Here are the current LangChain integrations: [langchain.com/integrations.html](https://langchain.com/integrations.html)

Here are the general docs: [docs.langchain.com](https://docs.langchain.com/docs)
Here are the Python docs: [python.langchain.com](https://python.langchain.com)
Here are the JavaScript/TypeScript docs: [js.langchain.com/docs](https://js.langchain.com/docs)

Here are the related issues: https://github.com/mckaywrigley/chatbot-ui/issues/149 and https://github.com/mckaywrigley/chatbot-ui/issues/123

**Comment by tatsu-i** [comment]
> Given the fast development pace of large language models (LLMs) and foundation models, it would be great to see a wrapper around LangChain.
> 
> Here is the JS/TS library: [langchainjs](https://github.com/hwchase17/langchainjs) by @hwchase17 Here is the Python library: [langchain](https://github.com/hwchase17/langchain) by @hwchase17
> 
> Here are the current LangChain features: [langchain.com/features.html](https://langchain.com/features.html) Here are the current LangChain integrations: [langchain.com/integrations.html](https://langchain.com/integrations.html)
> 
> Here are the related issues: #149 and #123

The following is a sample implementation of Langchain's agent API as a proxy server following the openai API specification.

By doing so, the langchain agent can be invoked and the results returned to the front end when a request is made in the same way as for OAI.

https://github.com/tatsu-i/chatbot-sample

**Comment by tatsu-i** [comment]
A UI for langchain already exists, such as [langchain-ui](https://github.com/homanp/langchain-ui), and we think it would be better to implement it as a backend compatible with OpenAI's API specification for future extensibility.
