### ISSUE TITLE
Feature request: Speech2Text (Whisper) as chat input

### ISSUE THREAD

**Issue by markusstrasser** [mckaywrigley/chatbot-ui#21]
Use OpenAI Whisper API to transcribe user voice to input into the chat field (OS native transcription is inaccurate). There could be a passphrase like ("over out" or whatever) that functions as [Enter] command and send the query.

I could try to develop this feature if it's deemed valuable

**Comment by mckaywrigley** [comment]
I really like this idea. The only issue I see with it is that Whisper usage costs might add up pretty quickly for the user. I'll add this to my list and look into it some more. I've worked with the Whisper API so I could get it done quite quickly.

**Comment by markusstrasser** [comment]
Good point. At 0.006$/minute transcribed I estimate it to be around 3-15 cents per hour of active chatbot usage, depending on the type of convo. Maybe we can display 'minutes transcribed' and 'costs', possibly set a maximum budget per session/day etc. to clip the downside.

Would be great since it improves user's speaking ability as a freebie (whereas typing won't improve any further)

**Comment by mckaywrigley** [comment]
Good call. I think with that type of UX it would be great. I plan on making token usage visible, and adding Whisper hours to that would be pretty easy. I'll work on this - really like the idea.

**Comment by mckaywrigley** [comment]
I could add it as an option. I think @markusstrasser is advocating for Whisper due to its performance. Extremely accurate.

**Comment by dillchen** [comment]
One option could be to allow users to directly run the Whisper Model directly on their laptops, it would be for power users only, likely

**Comment by tisfeng** [comment]
Sounds great, looking forward to this feature!

**Comment by KutiBond** [comment]
> I could add it as an option. I think @markusstrasser is advocating for Whisper due to its performance. Extremely accurate.

This extension might be helpful: https://github.com/C-Nedelcu/talk-to-chatgpt/pull/45

**Comment by Laurian** [comment]
Whisper.cpp has also a WebAssembly version that works in the browser alone https://github.com/ggerganov/whisper.cpp/tree/master/examples/whisper.wasm

**Comment by hellola** [comment]
I don't mind running whisper locally, not too much to setup, could we do a config setting for to and from speech endpoints, i would probably be looking at running https://github.com/askrella/speech-rest-api or something similar
I'd be happy to collaborate on a PR if this, or even an option for openapi whisper as well, I'm not sure how often I choose to use speech, but probably less if i'm weary of api costs

**Comment by jralduaveuthey** [comment]
is this integrated? in the hosted version I do not see any microphone button for doing STT?
