### ISSUE TITLE
firefox cannot type chinese in the message bar

### ISSUE THREAD

**Issue by MoXuanSun** [mckaywrigley/chatbot-ui#218]

**Comment by d3vw** [comment]
Me too

**Comment by ryanhex53** [comment]
The same goes for me, whether it's the desktop version of Firefox or on my phone, I can't input Chinese characters.

**Comment by ryanhex53** [comment]
I'm trying to fix this.

**Comment by ryanhex53** [comment]
PR #505 Fixed this issue

**Comment by ryanhex53** [comment]
@MoXuanSun The issue has been resolved in [my fork](https://github.com/ryanhex53/chatbot-ui), but the pull request has not yet been merged into this repository.
