### ISSUE TITLE
connect timeout error 

### ISSUE THREAD

**Issue by twoheartliu** [mckaywrigley/chatbot-ui#231]
Why do I get a connect timeout error when running your project locally and accessing api/models? Should I use Nginx to proxy port 3000 to openai on my local machine? Or is there something else wrong?

**Comment by SyedMuzamilM** [comment]
Can you share the response you are getting back here

**Comment by twoheartliu** [comment]
Thank you for your response. I tried again at the company and it seems to be a network issue in mainland China, rather than a code defect. I will have to find a solution myself. Thank you again.

**Comment by g8up** [comment]
I met the same issue.

I try to set a proxy to the container ,but not work:
> docker run --env ALL_PROXY=socks5://host.docker.internal:7890 -p 3000:3000 -p 7890:7890 chatgpt-u

**Comment by sammichenVV** [comment]
> 
ME TOO.how to fix it ?
