### ISSUE TITLE
Hello Sir.

### ISSUE THREAD

**Issue by Pocker88** [mckaywrigley/chatbot-ui#235]
Can you help pls... I didn't understand how use your program.. can you explain me pls?!

**Comment by atharvashukla** [comment]
Do you have an OpenAI API key. You need that to run the program.

**Comment by phrazzld** [comment]
My understanding is that chatbot-ui intends to be be a cleaner and more powerful UX for ChatGPT.

You have to use your own OpenAI API key, but you can save and organize and search your conversations and prompts more easily, customize the system prompt for each conversation (and soon other model parameters), import and export conversations, and more.

You can access the hosted version of the app on https://www.chatbotui.com/ or you can run it yourself following the instructions in the README.
