### ISSUE TITLE
Deploy against Azure OpenAI Studio fails for ChatGPT API incompabilities

### ISSUE THREAD

**Issue by marcellodesales** [mckaywrigley/chatbot-ui#243]
# 🤖 Service

* We have an Azure subscription with ChatGPT-3 and ChatGPT-4...
  * Cognitive Services -> Azure OpenAI Studio 
* We need to set the API URL to a different one

# 👽 API Differences

* HTTP Header for API KEY
* Message structure

# 🐛 Bugs

* We can't provide a different HOST, through Env Vars
* The API is hard-coded and, as a result, it can't be changed to a different set of URLs

> **NOTE**: The Azure OpenAI Studio completely broke the API contract defined by the official openai and so multiple changes are needed for `chat` and `model` APIs.
> * `Models API`: https://learn.microsoft.com/en-us/rest/api/cognitiveservices/azureopenaistable/deployments/list?tabs=HTTP#code-try-0
> * `Chat API`: couldn't find a reference, but it belongs to a given deployment as well

**Comment by marcellodesales** [comment]
Found

https://github.com/mckaywrigley/chatbot-ui/blob/main/utils/server/index.ts#L8-L19

**Comment by marcellodesales** [comment]
# 📸  Solution for Azure OpenAI API - Screenshots

<img width="1725" alt="Screenshot 2023-03-29 at 2 36 28 AM" src="https://user-images.githubusercontent.com/131457/228497954-796364e4-943f-4cd7-b046-4ec5d7b9da83.png">
<img width="1728" alt="Screenshot 2023-03-29 at 2 42 32 AM" src="https://user-images.githubusercontent.com/131457/228497965-b2c2a207-bc72-4202-95c7-efec1a064df7.png">

# 🛠️  Got it to work with Azure's OpenAI API

* Env var is not being properly passed from the docker-compose to Dockerfile to NextJS env vars.
* Azure's OpenAI API breaks the contract from the openai APIs
* The interface to send and receive messages is broken and needs to be changed
* HTTP Header for the API KEY is completely different from the openai version's

```console
$ git status
On branch feature/#243/use-azure-openai-studio
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   Dockerfile
        modified:   components/Chat/Chat.tsx
        modified:   components/Chat/ChatLoader.tsx
        modified:   components/Chat/ChatMessage.tsx
        modified:   docker-compose.yml
        modified:   next.config.js
        modified:   pages/api/chat.ts
        modified:   pages/api/models.ts
        modified:   pages/index.tsx
        modified:   utils/app/const.ts
        modified:   utils/server/index.ts
```

I would suggest creating a Handler for API Servers that are NOT the official public version of chat GPT... If there's an interest, I can push the PR changes to support azure...

**Comment by JonAtDocuWare** [comment]
`If there's an interest, I can push the PR changes to support azure...`

Yes, please! @marcellodesales I can't wait to use this!

**Comment by kiwizznz** [comment]
Another yes please from me.

**Comment by tao12345666333** [comment]
Thanks, I have some suggestions for you to look over.

* You can use the `chat/completions` API with `api-version=2023-03-15-preview`, It is compatible with OpenAI's API without additional modifications.
* The only difference is that you need to configure a different request path.
* For Azure OpenAI Service, the model used for each deployment is determined at the time of deployment and cannot be adjusted through API. Therefore, you can ignore it directly. For example, adding a parameter for Provider to hide these configurations when `Provider == Azure`.

**Comment by marcellodesales** [comment]
@tao12345666333 Thank you for your suggestions! 🎉 

Yeah, I'm not sure if they were working that way... I'm now loading the Deployments directly and we have ideas for the load... I've added an env var `OPENAI_API_PATH` to keep it simpler! I'm using the `/openai/deployments` while the original stays as `/v1`... However, I had to add another env `OPENAI_API_VERSION` and so when I set up the handler, I just construct the URL for it... 

```typescript
export const fetchAzureChats = async (apiKey: string, chatBody: AzureChatBody, signal: AbortSignal, currentModel: OpenAIModel): Promise<Response> => {
  // @ts-ignore
  const query_params = new URLSearchParams({
    'api-version': OPENAI_API_VERSION,
  });

  // The URL is based on the deployment id provided from the list of models (deployments)
  const apiUrl = `${OPENAI_API_HOST}${OPENAI_API_PATH}/${currentModel.id}/chat/completions?${query_params}`;

  const keyKey = OPENAI_API_KEY || ""
  return await fetch(apiUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'api-key': keyKey,
    },
    signal: signal,
    body: JSON.stringify(chatBody),
  });
}
```

# Handling Errors from Azure

* I decided to add another `message.role=provider` and so if I get any message with that role, after handling the exceptions, I can just display the error message...

<img width="858" alt="Screenshot 2023-03-30 at 9 21 36 PM" src="https://user-images.githubusercontent.com/131457/229022284-a13ebc95-1128-4edf-8955-2e320b15822d.png">

I'm mostly trying to get the basis as the UI will be used by multiple teams using their service... I won't have control...

**Comment by tao12345666333** [comment]
@marcellodesales 

You can refer to my previous approach.

* https://github.com/yetone/openai-translator/pull/178
* https://github.com/yetone/openai-translator/pull/506

Add a configuration item for an API URL path, allowing the addition of the complete path `/openai/deployments/{deploymentID}/chat/completions?api-version=2023-03-15-preview`


This will be very simple and can be quickly implemented.

Also, are you planning to submit a PR to implement it?

**Comment by marcellodesales** [comment]
@tao12345666333 yeah I'm working with my team on a branding story and it's been 2 days... I have a presentation on this tomorrow and It would take another day or so... if you guys want to wait I can send what I have and you guys can review it!!!!

Thank you so much for putting those on the other repo!

Any plans to support non Conversational models?

**Comment by tao12345666333** [comment]
@marcellodesales Great! You can submit a PR. Let's finish it together.





> Any plans to support non Conversational models?

Not yet, do you need these functions?

**Comment by eugenesiow** [comment]
To get the `/chat/completions` to stop generating, I added the following code to `utils/server/index.ts`:

```typescript
try {
    const json = JSON.parse(data);
    if (json.choices[0].finish_reason === 'stop') {
        controller.close();
        return;
    }
    const text = json.choices[0].delta.content;
    const queue = encoder.encode(text);
    controller.enqueue(queue);
} catch (e) {
    controller.error(e);
}
```

**Comment by marcellodesales** [comment]
> @marcellodesales Great! You can submit a PR. Let's finish it together.
> 
> > Any plans to support non Conversational models?
> 
> Not yet, do you need these functions?

@tao12345666333 I think it would be interesting for the UI to have a non-conversational UI option! That would be fantastic if we can get that!

**Comment by tao12345666333** [comment]
yeah

**Comment by marcellodesales** [comment]
@mckaywrigley thank you... @itbm Thank you!
