### ISSUE TITLE
Feature request: would it be possible to add a password feature to the webpage

### ISSUE THREAD

**Issue by yanbook** [mckaywrigley/chatbot-ui#244]
Hello, would it be possible to add a password feature to the webpage? When I deployed the website following your deployment process, I directly included my API key in it. One advantage of this is that my friends and I can use the website conveniently from any device simply by entering the website address.However, if a stranger found out my website address, they could quickly use up my resources. Therefore, having to enter a password to access the website could make it more secure. Thank you!

**Comment by yanbook** [comment]
A simple access password will suffice for now, without the need for a complex username and password system.

**Comment by soumendra** [comment]
While you wait for the feature to land, you can use nginx as reverse proxy to password protect your page. [1](https://www.unixtutorial.org/project-password-protect-a-website-with-nginx/), [2](https://www.howtogeek.com/devops/how-to-setup-basic-http-authentication-on-nginx/), [3 - with docker and docker-compose, recommended](https://medium.com/pernod-ricard-tech/adding-basic-authentication-with-nginx-as-a-reverse-proxy-a229f9d12b73)

**Comment by soumendra** [comment]
The feature [is coming](https://github.com/mckaywrigley/chatbot-ui/pull/215).

**Comment by yanbook** [comment]
> While you wait for the feature to land, you can use nginx as reverse proxy to password protect your page. [1](https://www.unixtutorial.org/project-password-protect-a-website-with-nginx/), [2](https://www.howtogeek.com/devops/how-to-setup-basic-http-authentication-on-nginx/), [3 - with docker and docker-compose, recommended](https://medium.com/pernod-ricard-tech/adding-basic-authentication-with-nginx-as-a-reverse-proxy-a229f9d12b73)

Thank you, the method you recommended is simple, effective, and completely meets my requirements. I really appreciate it.
