### ISSUE TITLE
error getting model

### ISSUE THREAD

**Issue by while999** [mckaywrigley/chatbot-ui#250]
![image](https://user-images.githubusercontent.com/48550880/228114768-31c313bf-c15a-427b-ab05-722cd9ac3708.png)

**Comment by junior-coder-wll** [comment]
same error,

**Comment by while999** [comment]
> 
因为这个部署到本地访问不了chatgpt。除非部署到国外服务器，或者给服务器加了反向代理， 或者直接部署在vercel托管平台就可以， 可以参考我仓库的 那个 Chat-gpt-next-web
