### ISSUE TITLE
Using the forward slash causes an immediate crash

### ISSUE THREAD

**Issue by cgbur** [mckaywrigley/chatbot-ui#252]
The application crashes immediately after typing anything following a forward slash. No popup or additional information is provided. The console error messages are as follows:
```
Uncaught TypeError: e is undefined
    NextJS 49
index-7302dbfd76d8310a.js:1:5780
TypeError: e is undefined
    NextJS 67
framework-73b8966a3c579ab0.js:9:69816
TypeError: e is undefined
    NextJS 67
```

### Steps to reproduce:
1. Open the chat
2. Type a forward slash followed by any additional text (e.g., `/test`)

Are there any instructions on what this is supposed to show?

**Comment by cgbur** [comment]
Just realized you need to make prompts on the side for this to work. 

Btw it is a neat feature. It would be nice if this could set the system prompt as well. Maybe include some default variables like date etc.

**Comment by SyedMuzamilM** [comment]
In the system prompt if you type / you will see the popup and you can choose the prompt you want in there as well.
