### ISSUE TITLE
When using Chinese input method mix input English word will cause submit

### ISSUE THREAD

**Issue by yuhr123** [mckaywrigley/chatbot-ui#255]
When using a Chinese input method to mix input English words in a chat window, pressing the enter key to confirm the select word will cause the entered content to be submitted directly. For exmaple, when I input "我有一台 Linux", press enter key to confirm the first word, but it will cause submit action.

Is it possible to add an additional judgment that prevents the default behavior of the Enter key when the input method candidate box exists and allows the Enter key to submit when it doesn't exist?

**Comment by yuhr123** [comment]
![截屏2023-03-28 16 52 02](https://user-images.githubusercontent.com/3388604/228183029-a2217de6-674a-49ee-90d8-ee3a2d9aa0e8.png)

**Comment by nauxliu** [comment]
It has been fixed in #253

**Comment by yuhr123** [comment]
🎉
