### ISSUE TITLE
Feature Request: Wrap code blocks to fit mobile viewport

### ISSUE THREAD

**Issue by TiancongLx** [mckaywrigley/chatbot-ui#265]

**Comment by TiancongLx** [comment]
@SyedMuzamilM 
Good:

![image](https://user-images.githubusercontent.com/16542902/228312997-b3ad98de-75be-4ffe-b3ba-9e9107af7dfd.jpeg)

But:

![image](https://user-images.githubusercontent.com/16542902/228313107-3862e2c4-ba24-4a6a-a25f-81b07d037310.jpeg)

We have to horizontal scroll to see all contents

**Comment by TiancongLx** [comment]
@SyedMuzamilM Edge in iPhone12 mini

**Comment by SyedMuzamilM** [comment]
Thanks. Will check soon and get back to you. 
In the meantime can you check if you will get the same issue here Chatify.BlackKalu.com

**Comment by SyedMuzamilM** [comment]
@TiancongLx this is how I get the code blocks on my phone. Try to refresh and see if it works. 

![image](https://user-images.githubusercontent.com/38078427/228319847-88f96e37-3602-4b5d-8f69-79b21c24598f.png)

**Comment by TiancongLx** [comment]
@SyedMuzamilM Sorry I used last version and I pull current code and found that the issue has been solved! Thanks for building such a wonderful ChatGPT web client!

**Comment by SyedMuzamilM** [comment]
Great. You can close the issue now.
