### ISSUE TITLE
Feature Request: add scroll to top and to bottom button

### ISSUE THREAD

**Issue by TiancongLx** [mckaywrigley/chatbot-ui#266]

**Comment by phrazzld** [comment]
Note: there is already a button for scrolling to the bottom of the screen. 

![Screenshot 2023-03-30 at 08 12 45](https://user-images.githubusercontent.com/788415/228847136-79b3bd61-983e-404d-8832-a929747aec7a.png)

**Comment by TiancongLx** [comment]
> Note: there is already a button for scrolling to the bottom of the screen. 
> 
> 
> 
> ![Screenshot 2023-03-30 at 08 12 45](https://user-images.githubusercontent.com/788415/228847136-79b3bd61-983e-404d-8832-a929747aec7a.png)
> 
> 

Yes, I've seen it. Do you think It is necessary to add a scroll to top button?

**Comment by phrazzld** [comment]
I think it's far rarer to need to scroll to the top than the bottom, but could still occasionally be useful
