### ISSUE TITLE
[Error: OpenAI API returned an error: Bad Request]

### ISSUE THREAD

**Issue by foxfog** [mckaywrigley/chatbot-ui#269]
![Screenshot_1](https://user-images.githubusercontent.com/11442544/228289624-123b40e4-3ca1-44df-bbeb-4e3cbc8af27a.jpg)

When a certain number of messages in the dialog is reached, the bot stops responding. If I start a new dialogue, the answers come in it. If I delete several messages in the current dialog, then the bot replies the same number of times and stops again.

**Comment by foxfog** [comment]
If I export the dialogue, then remove the first part of the dialogue from it and leave the last phrases, then the dialogue continues to work correctly for a while. It turns out that the application sends the entire dialog to the server every time? How to get around this limitation?

**Comment by N1q** [comment]
I was getting the same error, here's a more detailed instruction in case the "Clear conversations" button didn't help. You can clear cookies and site data, or more specifically: F12 - Storage - Local Storage - Delete the row with the key "conversationHistory" - Ctrl+F5

**Comment by foxfog** [comment]
> I was getting the same error, here's a more detailed instruction in case the "Clear conversations" button didn't help. You can clear cookies and site data, or more specifically: F12 - Storage - Local Storage - Delete the row with the key "conversationHistory" - Ctrl+F5

I don't want to lose the dialog every time the limit is reached (. The ideal option would be to implement something similar, to simulate "long memory".

<iframe width="560" height="315" src="https://www.youtube.com/embed/_vetq4G0Gsc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

**Comment by tisfeng** [comment]
I have also encountered this problem, and there is no hint at all, which is very annoying.

In this case, the problem should be solved by summarizing the previous conversation through compression.

**Comment by marcusquinn** [comment]
Same issue. happening with long super-prompt conversations. Could do with an elegant solution, because the nature of the long conversations is that they are reliant on the history for each further message to be meaningful.
