### ISSUE TITLE
Feature Request: include awesome-chatgpt-prompts

### ISSUE THREAD

**Issue by tatsu-i** [mckaywrigley/chatbot-ui#271]
Is it possible to read a CSV file of prompts from "awesome-chatgpt-prompts" and implement a search and recommendation feature for prompts?

* https://github.com/f/awesome-chatgpt-prompts/blob/main/prompts.csv

**Comment by SyedMuzamilM** [comment]
@mckaywrigley I think this feature might be useful. And we should provide a prompt library that would have some of the popular prompts included in the prompt bar which would be a separate tab there. 

What do you think about this, let me know then I would try to work on this.

**Comment by SyedMuzamilM** [comment]
@tatsu-i  check out https://chatify.blackkalu.com and let me know if this is how you want the prompt library to be.

**Comment by oznav2** [comment]
![Screen Shot 2023-03-30 at 11 03 24](https://user-images.githubusercontent.com/92755196/228770677-c7c42ee4-f0d3-44fa-ba0c-6ad88d50e9d7.png)

**Comment by SyedMuzamilM** [comment]
Yes it could be done. I will implement that functionality in my repo and will let you know. Or you can keep checking that.

**Comment by tatsu-i** [comment]
Below is an example of a Dockerfile for this functionality.

```dockerfile
# ---- Base Node ----
FROM node:19-alpine AS base
WORKDIR /app
COPY package*.json ./

# ---- Dependencies ----
FROM base AS dependencies
RUN npm ci

# ---- Build ----
FROM dependencies AS build
COPY . .
RUN npm run build

# ---- Production ----
FROM node:19-alpine AS production
WORKDIR /app
COPY --from=dependencies /app/node_modules ./node_modules
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
COPY --from=build /app/package*.json ./
COPY --from=build /app/next.config.js ./next.config.js
COPY --from=build /app/next-i18next.config.js ./next-i18next.config.js

# Prompt template
ENV PROMPT_CSV=/app/prompts.csv
ADD https://raw.githubusercontent.com/f/awesome-chatgpt-prompts/main/prompts.csv /app/prompts.csv
# Expose the port the app will run on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
```

**Comment by SyedMuzamilM** [comment]
> Below is an example of a Dockerfile for this functionality.
> 
> ```dockerfile
> # ---- Base Node ----
> FROM node:19-alpine AS base
> WORKDIR /app
> COPY package*.json ./
> 
> # ---- Dependencies ----
> FROM base AS dependencies
> RUN npm ci
> 
> # ---- Build ----
> FROM dependencies AS build
> COPY . .
> RUN npm run build
> 
> # ---- Production ----
> FROM node:19-alpine AS production
> WORKDIR /app
> COPY --from=dependencies /app/node_modules ./node_modules
> COPY --from=build /app/.next ./.next
> COPY --from=build /app/public ./public
> COPY --from=build /app/package*.json ./
> COPY --from=build /app/next.config.js ./next.config.js
> COPY --from=build /app/next-i18next.config.js ./next-i18next.config.js
> 
> # Prompt template
> ENV PROMPT_CSV=/app/prompts.csv
> ADD https://raw.githubusercontent.com/f/awesome-chatgpt-prompts/main/prompts.csv /app/prompts.csv
> # Expose the port the app will run on
> EXPOSE 3000
> 
> # Start the application
> CMD ["npm", "start"]
> ```

will check it once it is done you check check the repo or website

**Comment by stephanexenos** [comment]
Hello, I just find this post and I would like to ask you if anybody finally have a working solution for this ? 

Thankx in advance,

Stephane
