### ISSUE TITLE
Feature Request: End response

### ISSUE THREAD

**Issue by myst10py** [mckaywrigley/chatbot-ui#277]
As a user it would be nice to cancel the current output of an answer and end the response.
A simple UI button that appears when an answer is in the process of generating a response that handles the cancel functionality so the user can submit a new prompt again.

**Comment by thomasleveil** [comment]
This ?
![image](https://user-images.githubusercontent.com/42300/228450390-79f34109-dad6-463f-9f6f-658a3b87f521.png)

**Comment by myst10py** [comment]
Oddly enough this button is not showing up on my front end client, maybe I need to repull?

**Comment by myst10py** [comment]
Yes I just saw the updated feature, I just needed to repull for those that don't see the stop generating button in their client. Closing as the feature is there in the main branch.
