### ISSUE TITLE
Hello, may I know what error this is? I'm not sure where I went wrong. I've filled in the key for both places.

### ISSUE THREAD

**Issue by alanjustalan** [mckaywrigley/chatbot-ui#28]
Hello, may I know what error this is? I'm not sure where I went wrong. I've filled in the key for both places.
![image](https://user-images.githubusercontent.com/42884681/226367062-6147446d-95c9-4242-8976-f2ec94c6827e.png)
![image](https://user-images.githubusercontent.com/42884681/226368518-6abb2fa0-4539-4262-900b-ad7f563051cb.png)

**Comment by mckaywrigley** [comment]
Can you confirm the api key works elsewhere?

**Comment by wayne3602** [comment]
i also encountered this problem

**Comment by c2w570063013** [comment]
the same

**Comment by seanchito** [comment]
I can run it but I have to enter the key in the web app every time

**Comment by mckaywrigley** [comment]
Likely a key issue. Make sure it's set correctly in either .env.local or the app (you need to refresh after setting key). Have had this happen to quite a few people and this has always been the issue, with a few cases of invalid keys (generate a new one via OpenAI).
