### ISSUE TITLE
docker image does not have 4.0

### ISSUE THREAD

**Issue by grosser** [mckaywrigley/chatbot-ui#282]
not just not the default but completely missing ...
```
docker run --platform linux/amd64 -e DEFAULT_MODEL=gpt-4.0 -e OPENAI_API_KEY=X -p 3000:3000 ghcr.io/mckaywrigley/chatbot-ui:main
```

<img width="608" alt="image" src="https://user-images.githubusercontent.com/11367/228420017-3307e5a0-419e-4f42-bd9f-39d574327196.png">

**Comment by SyedMuzamilM** [comment]
Do you have access to GPT-4.

**Comment by grosser** [comment]
yes in the regular UI it works

**Comment by grosser** [comment]
... maybe api is different, not sure
<img width="426" alt="image" src="https://user-images.githubusercontent.com/11367/228425062-db564a01-4978-4aab-8728-6eb2af80b262.png">

**Comment by SyedMuzamilM** [comment]
Try to check if the default model you are setting is correct GPT-4.0 or GPT-4

**Comment by grosser** [comment]
no change, only model available is 3.5

![SCR-20230328-un2](https://user-images.githubusercontent.com/11367/228431762-4d03ca39-1c35-4d8d-9feb-fd6dd0a2ed4f.png)

once I ask a question it switches to 4 though
![SCR-20230328-un5](https://user-images.githubusercontent.com/11367/228431801-c2d1c728-d25e-4f63-92a9-7bf8cb3fe822.png)

and stdout shows `[Error: OpenAI API returned an error: Not Found]` 🤷

**Comment by grosser** [comment]
UI shows that a key is entered
![SCR-20230328-uoo](https://user-images.githubusercontent.com/11367/228432005-8436947b-7886-4a8f-90d4-a1cbd3dcbed2.png)

**Comment by SyedMuzamilM** [comment]
Can you confirm if you have access to gpt-4 then I will take a look into the issue?

**Comment by grosser** [comment]
as I said before and attached screenshot I have access to gpt-4

**Comment by grosser** [comment]
but I'd say main problem might be that it does not work at all since even 3.5 does not respond

**Comment by grosser** [comment]
ah it finally decided to work with 3.5 🤷 
... still not showing 4

**Comment by grosser** [comment]
FYI also built locally now from latest and same issue

**Comment by SyedMuzamilM** [comment]
Thanks for confirming Will have a look into it.

**Comment by DerMahlus** [comment]
same here!

**Comment by SyedMuzamilM** [comment]
I ran the same thing it worked fine for me. Make sure you have access to GPT-4 and then you can run this command and it should work fine.

Try to pull the docker image locally and then run from there if this won't work. Also make sure to put the DEFULT_MODE=gpt-4 if you have access.

`docker run --platform linux/amd64 -e DEFAULT_MODEL=gpt-4 -e OPENAI_API_KEY="sk-xxxxxxxxxxxxxxxxxxxxxxxx" -p 3000:3000 ghcr.io/mckaywrigley/chatbot-ui:main`

Change the OPENAI_API_KEY inside the quotes. Hopefully it should work.

**Comment by grosser** [comment]
Thx, but it does not work for me.
I have GPT-4 in the official UI.
Maybe it's something that goes wrong during startup, I imagine the code
tries to determine what is available somehow and if that call goes wrong I
end up with 3.5 only. Would be nice to have a debug option for this or to
show an error when the requested default is not in the returned list.

**Comment by SyedMuzamilM** [comment]
Let me know if we can meet and check the issue. So that it could be resolved. Thanks.

**Comment by grosser** [comment]
Can you give instruction Ms on what you want to check or make a branch with
debug statements so we can do this async ?

**Comment by SyedMuzamilM** [comment]
Can you screen record how you are running this are what you are getting. After that I will see what could be done.

**Comment by grosser** [comment]
```
docker run --platform linux/amd64 -e DEFAULT_MODEL=gpt-4 -e OPENAI_API_KEY="sk-X" -p 3000:3000 ghcr.io/mckaywrigley/chatbot-ui:main
> ai-chatbot-starter@0.1.0 start
> next start

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
```

then go there
![SCR-20230330-nk4](https://user-images.githubusercontent.com/11367/228990108-b45d5219-a657-41bf-b005-a9f6586ce8ff.png)
![SCR-20230330-nk0](https://user-images.githubusercontent.com/11367/228990110-47c7c8ce-923a-4a1c-9e05-c30e518856c0.png)
![SCR-20230330-njv](https://user-images.githubusercontent.com/11367/228990112-a3f0dc79-1d63-47db-94ac-351a89de0e25.png)

**Comment by SyedMuzamilM** [comment]
> ```
> 
> docker run --platform linux/amd64 -e DEFAULT_MODEL=gpt-4 -e OPENAI_API_KEY="sk-X" -p 3000:3000 ghcr.io/mckaywrigley/chatbot-ui:main
> 

Are you not adding the key directly in the env.

**Comment by grosser** [comment]
that's what `-e OPENAI_API_KEY="sk-X"` does right ?

**Comment by grosser** [comment]
also it shows in the UI so I think that part works

**Comment by grosser** [comment]
ah it also shows when not entering a key ...

**Comment by grosser** [comment]
... but it's what the readme says to do 🤷 
if the api key is missing or invalid then I'd expect some kind of error message

**Comment by grosser** [comment]
sk-X being my key, just omitted the full key

**Comment by SyedMuzamilM** [comment]
Will check what could be done to fix this issue.

**Comment by SyedMuzamilM** [comment]
Will see what could be done to fix this issue.

**Comment by jonhill7** [comment]
There may be confusion here between ChatGPT Plus and GPT4 API access.

**Comment by grosser** [comment]
ah yes that could be it, the official UI shows "GPT4" and also "ChatGPT Plus" so I assumed they are the same.

**Comment by doroved** [comment]
> > ```
> > 
> > docker run --platform linux/amd64 -e DEFAULT_MODEL=gpt-4 -e OPENAI_API_KEY="sk-X" -p 3000:3000 ghcr.io/mckaywrigley/chatbot-ui:main
> > ```
> 
> Are you not adding the key directly in the env.

`docker run --platform linux/amd64 -e OPENAI_API_KEY="sk-X" -p 3333:3333 ghcr.io/mckaywrigley/chatbot-ui:main`

I try to run it this way, but the application is not available at http://localhost:3333
What to do?
I have a macbook pro 14

**And in the docker there is this information**
<img width="294" alt="image" src="https://user-images.githubusercontent.com/30116541/229935210-1bdd816b-6749-4a6e-a578-2842b273359b.png">

**Comment by grosser** [comment]
... I found the issue

openai gives out api keys even if you are not on a paid plan
and their monthly subscription does not cover api access 🤦 

so ideally there should be a message explaining that "requested mode X was not available, make sure you are on a paid API plan, see https://platform.openai.com/account/billing/payment-methods"

**Comment by grosser** [comment]
🤦 still does not work ... configured a payment method but the UI is still the same

**Comment by mosaiker** [comment]
> 🤦 still does not work ... configured a payment method but the UI is still the same

maybe you should join the gpt-4 api waitlist first
[https://openai.com/waitlist/gpt-4-api](url)

**Comment by mosaiker** [comment]
to check if you have the access to gpt-4, you can execute this command to see models you can access
``` bash
curl https://api.openai.com/v1/models \
  -H "Authorization: Bearer $OPENAI_API_KEY"
```

**Comment by grosser** [comment]
yeah that's it :)
... that should be in some error message/warning when trying to set gpt-4

**Comment by alphaDev23** [comment]
Is this application limited to 1 AI model per docker instance or does it allow the ability to select?  There is a drop down but I do not see the ability to set the other options.
