### ISSUE TITLE
Response does not display?

### ISSUE THREAD

**Issue by will-zhang** [mckaywrigley/chatbot-ui#284]
<img width="859" alt="image" src="https://user-images.githubusercontent.com/4956884/228421980-6f4f6200-92a7-4ce4-82d4-15e5425e8c08.png">

**Comment by ryanhex53** [comment]
The reason is that when sending a POST request to `/api/chat`, a 400 error occurs. Sometimes the model parameter was missing and the origin API in PR #295 you can see the error.

However, you can temporarily solve this problem by pressing the **Clear conversation** button.

**Comment by jplopezmolinari** [comment]
Same problema here
