### ISSUE TITLE
ERROR Fetching Models, unknown scheme

### ISSUE THREAD

**Issue by zpeng2022** [mckaywrigley/chatbot-ui#290]
## logs: unknown scheme
- 
![image](https://user-images.githubusercontent.com/101320682/228470850-91ad7344-bf93-4f7b-9fc2-0b3268b816ed.png)

## UI error messages
- 
![image](https://user-images.githubusercontent.com/101320682/228471025-ef4267c7-b3c5-4be4-aae9-85227bf3325d.png)

## ENV
- I set OPENAI_API_KEY & OPENAI_API_HOST & DEFAULT_MODEL in the `.env.local` file

can anyone fix this.

**Comment by zpeng2022** [comment]
```
socks5://192.168.137.170:21881
```

**Comment by zpeng2022** [comment]
well, I misunderstood. I set `OPENAI_API_HOST` with wrong value. sorry

**Comment by zpeng2022** [comment]
FINALLY!, I use `proxychain4` instead of `proxychains` to make it works.
![image](https://user-images.githubusercontent.com/101320682/228532665-aff2d70f-d75c-41c5-9fc1-55c1b7327c41.png)

- commands
```
proxychains npm run dev
```

**Comment by palaklive** [comment]
What is the right `OPENAI_API_HOST`?
