### ISSUE TITLE
Wrong request path

### ISSUE THREAD

**Issue by Jinxishihenian** [mckaywrigley/chatbot-ui#294]
<img width="667" alt="Snipaste_2023-03-30_00-42-21" src="https://user-images.githubusercontent.com/44466363/228609326-ad754f2c-3408-4cf1-b821-7093df9a8952.png">
Is the request made correctly? He caused me to have the following problems.
<img width="889" alt="Snipaste_2023-03-30_00-43-54" src="https://user-images.githubusercontent.com/44466363/228609558-112095b4-6eec-47f9-a83d-818adfe7e215.png">

**Comment by thomasleveil** [comment]
what error message can you see on the server console?

**Comment by Emlembow** [comment]
```
/api/chat:1          Failed to load resource: the server responded with a status of 500 ()
index-c2f72dd62e2294af.js:1          POST https://www.myepicportfolio.com/api/chat 500
```

**Comment by Emlembow** [comment]
```
/api/chat:1          Failed to load resource: the server responded with a status of 500 ()
index-c2f72dd62e2294af.js:1          POST https://www.exampledomain.com/api/chat 500
```

**Comment by thomasleveil** [comment]
since #295 was merged 2h ago, can you upgrade your instance and try again. This time the server console should have a more detailed and useful error message

**Comment by ryanhex53** [comment]
I believe this is the same issue as reported in issue #284.
