### ISSUE TITLE
Input box not letting me add accented letters by pressing "´" key

### ISSUE THREAD

**Issue by difigue** [mckaywrigley/chatbot-ui#302]
Hello, when typing in spanish, I can't put accent on vowels (eg. á,ú) by pressing the "´" key. For example, if I want to type "Cuéntame un chiste" the output will be "Cu´ntame un chiste". However, special characters are allowed if I just paste them in the box.

**Comment by mcastillof** [comment]
I had the same problem in Firefox. Chromium (a Chrome based browser) works fine for me.

~I noticed that accents were working fine in other input text like in prompts. I spotted that between the prompts and the chat, "focus:outline-none" class was missing.
Adding it to the <textarea> tag in the chat solved the problem for me.~
