### ISSUE TITLE
Feature request: Add option to store conversations on the disk

### ISSUE THREAD

**Issue by difigue** [mckaywrigley/chatbot-ui#303]
Conversations are stored locally within the browser, so if I want to check or continue them, I have to manually export and import them. It would be nice to access the history from other devices and browsers without the trouble.

**Comment by masonjames** [comment]
How would we solve this? If we automatically export the JSON file locally? I'm not even sure that's possible. It's an interesting problem, but I'm not sure how easily this is solved.

**Comment by vrodriguezf** [comment]
Yeah this would be great, I have the app deployed in one server and it would be great to see the same history of conversations when I access through different devices
