### ISSUE TITLE
Feature request: configurable server-port

### ISSUE THREAD

**Issue by kamil-malinski** [mckaywrigley/chatbot-ui#305]
Hi!

Since on my server port 3000 is already in use I would like to change the port of the chatbot-ui-server. It woule be nice to have the ability to change the server port in the env-file.

Kamil

**Comment by kamil-malinski** [comment]
> (If you use npm run, it will automatically +1 to the server port)

this seems to work only with the dev-version:

```console
npm run start

> ai-chatbot-starter@0.1.0 start
> next start

Error: listen EADDRINUSE: address already in use 0.0.0.0:3000
    at Server.setupListenHandle [as _listen2] (node:net:1774:16)
    at listenInCluster (node:net:1822:12)
    at doListen (node:net:1971:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 3000
}
```

**Comment by PhanTrongGiap** [comment]
No let command:
`npm run dev`

**Comment by PhanTrongGiap** [comment]
So you can add code to package.json:
`"scripts": {
  "dev": "PORT=3001 next start"
}`
3001 = port you want to run

**Comment by kamil-malinski** [comment]
> So you can add code to package.json: `"scripts": { "dev": "PORT=3001 next start" }` 3001 = port you want to run

thanks, this works!

still it would be nice to be able to put the desired port into the env-file, because package.json is under version control

**Comment by nxtreaming** [comment]
pm2 --name chatbot-ui start npm -- start -- --port 3100

**Comment by kamil-malinski** [comment]
thanks a lot!

**Comment by rudolfolah** [comment]
just ran into this issue, I too have an app running on 3000, the docs for Next.js suggest using `PORT` as an environment variable when running the command: https://nextjs.org/docs/api-reference/cli#development


I tried it and here's the output, so it looks like it works 😄 

```shell
$ PORT=4000 npm run dev

> ai-chatbot-starter@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:4000, url: http://localhost:4000
info  - Loaded env from /Users/helloworld/Workspace/chatbot-ui/.env.local
event - compiled client and server successfully in 810 ms (229 modules)
wait  - compiling...
event - compiled successfully in 107 ms (192 modules)

```

**Comment by yuanmouren1hao** [comment]
> ```shell
> PORT=4000
> ```

it works
thank u

**Comment by yuanmouren1hao** [comment]
> just ran into this issue, I too have an app running on 3000, the docs for Next.js suggest using `PORT` as an environment variable when running the command: https://nextjs.org/docs/api-reference/cli#development
> 
> I tried it and here's the output, so it looks like it works 😄
> 
> ```shell
> $ PORT=4000 npm run dev
> 
> > ai-chatbot-starter@0.1.0 dev
> > next dev
> 
> ready - started server on 0.0.0.0:4000, url: http://localhost:4000
> info  - Loaded env from /Users/helloworld/Workspace/chatbot-ui/.env.local
> event - compiled client and server successfully in 810 ms (229 modules)
> wait  - compiling...
> event - compiled successfully in 107 ms (192 modules)
> ```
> 
> @rogerc66 set the `PORT` env var: `docker run -e PORT=3002 ...`

it works
thank u
