### ISSUE TITLE
Markdown tables should look more like ChatGPT.

### ISSUE THREAD

**Issue by atharvashukla** [mckaywrigley/chatbot-ui#31]
Before:

![image](https://user-images.githubusercontent.com/33644308/226471275-32dcdf78-b605-49ff-b195-07d8a396eec8.png)

After:

![image](https://user-images.githubusercontent.com/33644308/226471336-b028597e-926e-4735-be85-6625c275b06c.png)

**Comment by atharvashukla** [comment]
I'm not table to open a pull request but adding this to the react markdown part should do it:

```javascript
table({ children }) {
  return (
    <table className="border-collapse border border-white py-1 px-3 rounded-lg">
      {children}
    </table>
  );
},
th({ children }) {
  return (
    <th className="border border-white break-words py-1 px-3 bg-gray-500">
      {children}
    </th>
  );
},
td({ children }) {
  return (
    <td className="border border-white break-words py-1 px-3">
      {children}
    </td>
  );
},
```

ChatGPT also has rounded corners - which I have not implemented.

**Comment by mckaywrigley** [comment]
added. thanks for the code!
