### ISSUE TITLE
Use custom max_tokens

### ISSUE THREAD

**Issue by EnzoAndree** [mckaywrigley/chatbot-ui#316]
Hello @mckaywrigley!

I liked your work on this UI. I was wondering if the line that sets `max_tokens` to 1000 could be changed in the UI. I believe it would be useful.

https://github.com/mckaywrigley/chatbot-ui/blob/5cdd3e56b7c25a557d4afca3b8c241ef92fec38d/utils/server/index.ts#L34

**Comment by erodactyl** [comment]
Not even in the UI - maybe we could provider an environment variable for this which also has a default value set to 1000?
