### ISSUE TITLE
Style Question

### ISSUE THREAD

**Issue by LuckySpec** [mckaywrigley/chatbot-ui#32]
How can I remove the left sidebars in the page?

![Sin título](https://user-images.githubusercontent.com/62458538/226478525-bc490ab5-f883-40ee-9742-2b2987083db9.png)

**Comment by mckaywrigley** [comment]
May I ask what device/browser you are using? I test on a Mac with Chrome, so I suspect I will need to begin supporting a wider range of options there.

**Comment by mckaywrigley** [comment]
Believe this should be fixed now.
