### ISSUE TITLE
Feature Request: AI chat of other companies such as bing chat, bard or LLaMA.

### ISSUE THREAD

**Issue by sugeflow** [mckaywrigley/chatbot-ui#323]
ChatGPT is most powerful. But it doesn't know thing after 2021, which sometimes is important.

**Comment by pezou45** [comment]
Would be cool to add self hosted llama or gpt4all to the chatbot ui.

**Comment by si-rob** [comment]
Perhaps an integration with LangChain (https://python.langchain.com/en/latest/) could help here, plus extending functionality significantly. By Making chatbot-ui the front end, langchain essentially middleware and LLM the backend model

**Comment by wong2** [comment]
Checkout: https://github.com/chathub-dev/chathub
