### ISSUE TITLE
Bug Report: Nothing generated after a long conversation

### ISSUE THREAD

**Issue by TiancongLx** [mckaywrigley/chatbot-ui#325]
Sometimes It doesn't generate AI reply after a long conversation. Neither the `regenerate` nor re edit works.
However when starting a new conversation It can reply as normal.

**Comment by dennisheiden** [comment]
Here is the error message:
![image](https://user-images.githubusercontent.com/25924499/229140737-fdd1e8a9-2c08-4e2d-beda-7019014f35a8.png)

**Comment by TiancongLx** [comment]
@mckaywrigley

**Comment by takedawilliam** [comment]
I get the same error message. In case of ChatGPT, it seems that they do some tricks behind the scene to slice a long conversation into multiple smaller conversations and feed them into GPT to keep the context. In case of Chatbot UI, it doesn't have this ability and it treats the whole conversation as one big text. Once this conversation exceeds the 4097 token limit, the above error returns
