### ISSUE TITLE
It would be much better than the OFFICIAL one if a SEARCH history can be added

### ISSUE THREAD

**Issue by chaosprint** [mckaywrigley/chatbot-ui#327]

**Comment by SyedMuzamilM** [comment]
Can you explain this more.

**Comment by wirelesstkd** [comment]
I think they're asking for the ability to search chat history. For example, if a user has six folder, each folder containing 15 different chats, they want the ability to search for the term "newtonion physics" and have the search return the three chats that contained that phrase. This feature would make it easier to find a chat you are looking for when you have lots of different chats to look through.

**Comment by SyedMuzamilM** [comment]
But the search feature is already there. You can search for any chat in the sidebar.

**Comment by chaosprint** [comment]
> 

think of any documentation website: there is always a full-text search.

and as @wirelesstkd pointed out, it would be great to filter out other conversations.
