### ISSUE TITLE
Feature request: add optional system role message[s] for each conversation

### ISSUE THREAD

**Issue by jiacheo** [mckaywrigley/chatbot-ui#33]
Most of the time we don't just want a free chat conversation, but a professional one with system role message[s] (or such called prompt prefix) and we can control how many history context (0-any) should be send back to the next message[s].

**Comment by mckaywrigley** [comment]
Custom system prompt up tonight! More settings will follow this week.

**Comment by mckaywrigley** [comment]
Adding this now so closing.

**Comment by jiacheo** [comment]
> Custom system prompt up tonight! More settings will follow this week.

hi @mckaywrigley , many thanks for your great works.  Can System Role Prompts be placed in each conversation and made editable? That is, each conversation has its own System Prompt.

**Comment by dennis-gonzales** [comment]
Was about to ask for a feature request of "System Roles", good thing I searched first.

Anyways as a new user I kinda didn't understand that this icon is for system role, but I got it now.
![image](https://github.com/mckaywrigley/chatbot-ui/assets/43110624/45015344-6505-47bd-b490-604ce4373c11)

Thanks!
