### ISSUE TITLE
Edit message tree like official UI

### ISSUE THREAD

**Issue by SMUsamaShah** [mckaywrigley/chatbot-ui#334]
Official UI keeps your message history like a tree instead of linear. When you edit a message, ChatGPT will generate a new response but previous response will not be erased at any point. You can always scroll back to old message.

This allows going back and branch off the conversation in a different direction from any message.

Can same be done here?

**Comment by SMUsamaShah** [comment]
Example:

![image](https://user-images.githubusercontent.com/385283/229186338-ed258d1f-da1c-4ea6-b80e-ed1383228375.png)
![image](https://user-images.githubusercontent.com/385283/229186442-3f8db061-f2ad-4bc6-aa66-35d284c11f50.png)

**Comment by dwiel** [comment]
this would be super helpful

**Comment by littlemoonstones** [comment]
The issue being discussed is the same as the issue #40.

**Comment by SMUsamaShah** [comment]
PR #339 closes this
