### ISSUE TITLE
Firefox for android issue

### ISSUE THREAD

**Issue by x0aa7i** [mckaywrigley/chatbot-ui#336]
This is the behavior I get when I try to type something using Firefox for android

https://user-images.githubusercontent.com/84672102/229224220-5f4bd251-c013-4653-a013-4977d8aca6d4.mp4

**Comment by grafail** [comment]
Having the same issue with Firefox for Android

**Comment by tapafon** [comment]
Same issue on latest version of Firefox.

**Comment by jerome3o** [comment]
I am also having this issue, whenever a word it autocorrected, the word disappears.

It happens on a few different onscreen keyboards (samsung and microsoft's), and the issue doesn't occur in Chrome.

I am also on Android using firefox
