### ISSUE TITLE
Feature request: Add message button feature

### ISSUE THREAD

**Issue by DelteRT** [mckaywrigley/chatbot-ui#341]
Hello everyone! Thank you very much for making this project possible<3

I would like to submit a feature request to inject editable messages into the AI conversation. Currently, in the original UI from the playground, it is possible to inject blank messages (And you can even choose whether the message is from the user or from the assistant) to create a conversation and make the AI more accurate in its responses.

The proposed feature would allow users to emulate a perfect conversation by injecting editable messages, and the AI would adapt to the previous conversation to provide more accurate responses. This would result in better conversational experiences for users.

This feature is similar to, but not the same as issue #292 

![1](https://user-images.githubusercontent.com/81970381/229267418-23adc1cf-ffc4-4e00-88a9-b0f5eaffa9c0.JPG)

**Comment by NewEpoch2020** [comment]
Agree with this point. Sometimes the response from AI may deviate from our thoughts, and if we need it to be modified, we need to go through one or more rounds of conversation. Editing the AI's response can quickly correct the direction of the conversation.

**Comment by Velora** [comment]
This would be great to have and would make chatbot-ui a powerful tool for prompt writing. Right now the playground functionality allows for writing few shot prompts easily which is not possible in chatbot-ui. 

The downside of the playground is that there is no way to save prompts or organize work in progress. Chatbot-ui does this excellently already, so the ability to add and edit messages would make this one of the best prompt drafting tools.

**Comment by Neurai-ai** [comment]
i would like to be able to edit the ai responses and or delete them
