### ISSUE TITLE
Can I use Azure OpenAI Service

### ISSUE THREAD

**Issue by TiancongLx** [mckaywrigley/chatbot-ui#359]
Using it from unsupported region like CN and HK

**Comment by casaltenburg** [comment]
I think it’s a separate feature , because the API for azure openAI service is a little different.

**Comment by vladiliescu** [comment]
@TiancongLx See [my fork](https://github.com/vladiliescu/azure-chatbot-ui) for this, I'm using it locally but Docker is most likely broken. I'm planning to keep it in sync with the main repo, still figuring out the best way to do this.

**Comment by TiancongLx** [comment]
> I think it’s a separate feature , because the API for azure openAI service is a little different.

An iOS GPT client called OpenCat can customize the API URL, which I think is a wonderful feature since the openai api key will be banned frequently and the account will be suspended with no reason. It is so annoying to using AI service in unsupported regions.

**Comment by leodambrosi** [comment]
@vladiliescu thank you. Does your version still require openai key? I tried to make it run but without openAI won't let me chat. When added, I get a resource error. Thank you

**Comment by vladiliescu** [comment]
@leodambrosi Of course, you will still need an Azure OpenAI key.

**Comment by leodambrosi** [comment]
@vladiliescu thanks. Can you help me understand why "of course"? Azure open AI works independently from OpenAI API. If you have the OpenAI API, why should you use azure api?

**Comment by vladiliescu** [comment]
@leodambrosi Depending on which service you choose to use (OpenAI or Azure OpenAI) you'll need an API key from that respective service. If you're using Azure OpenAI you'll also need a few more things, see [here](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/chatgpt-quickstart?tabs=bash&pivots=rest-api#retrieve-key-and-endpoint) for some details on that.

**Comment by leodambrosi** [comment]
@vladiliescu I have both Azure API an OpenAI API. My question is: why is the OpenAI API still requested on your Azure API based fork?

**Comment by vladiliescu** [comment]
@leodambrosi Cool, take a look at [env.local.example](https://github.com/vladiliescu/azure-chatbot-ui/blob/dev/.env.local.example) to see what you need to configure, the values are referenced in the [readme](https://github.com/vladiliescu/azure-chatbot-ui/tree/dev#configuration) too. You don't need an OpenAI API key, have you filled in `env.local` as per the docs and it still doesn't work for you?

**Comment by leodambrosi** [comment]
@vladiliescu I followed the local installation procedure and unfortunately doesnt work:
<img width="1765" alt="image" src="https://user-images.githubusercontent.com/4950135/229777749-dc1ca0bd-04b5-4baf-ab15-c3e2a3079d3b.png">

**Comment by vladiliescu** [comment]
@leodambrosi Please add this as an issue to my fork, in order to keep the conversation focused. Can you also include what model you're using (gpt-35 or gpt-4), and the structure of your `env.local`?

**Comment by leodambrosi** [comment]
@vladiliescu added https://github.com/vladiliescu/azure-chatbot-ui/issues/1

**Comment by weltonrodrigo** [comment]
Are you willing to receive a pull-request for this?

Are you sure the api is different? Because in the docs, Azure shows usage of the official python openai API, suggesting total compatibility
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/quickstart?tabs=command-line&pivots=programming-language-python#create-a-new-python-application

UPDATE: there is a PR with a running version here: https://github.com/mckaywrigley/chatbot-ui/pull/337
