### ISSUE TITLE
Feature Request - Add NextAuth, SQLite storage, and support for multiple AI models

### ISSUE THREAD

**Issue by kendevco** [mckaywrigley/chatbot-ui#367]
First of all, amazing work on this project. I would like to suggest adding a Discussions tab for better organization and separation from the Issues tab.

I have been working on a similar project, which you can find here: [https://github.com/kendevco/aichat](https://github.com/kendevco/aichat). I've decided to contribute to this project as it is more popular and has better functionality.

I have a few feature requests and suggestions:

1. **NextAuth**: Add support for multiple authentication providers using NextAuth. This would make the project more accessible for users without Google accounts. Here's a link to a great NextAuth tutorial: [https://www.youtube.com/watch?v=t0Fs0NO78X8](https://www.youtube.com/watch?v=t0Fs0NO78X8).

2. **SQLite**: Implement SQLite for storing messages locally on the server. This would provide an option for users who wish to save their chat conversations while respecting privacy considerations. Sonny's project used Firebase (which I faithfully implemented in my own project) but I get it that this project was focused on making a GPT client which is easy to get started with. Thus, if the .env variable is present then the feature would turn on based upon the presence of the configuration variable. Or just serialize the conversations to json like it currently does and saves in the server's conversations\userid\ directory or something like that? 

3. **Mobile View**: Improve the mobile view by making the side tabs collapsible and fixing the missing dismiss icon for the sidebars.

4. **API Timeouts**: Address the issue of API timeouts from OpenAI by setting a timeout parameter on the API function call.

5. Explore support for other models like Bloom, Alpaca, LLaMA, etc. This would make the client more resilient and flexible and prepare for the possible eventuality that there is some form of event that necessitates OpenAI to remove access to GPT4 api. 

6. **Project attribution**: If this project is based on Sonny Songha's tutorial, please mention it in the README to help more people find and contribute to the project.

For more information on running a ChatGPT-like AI on your own machine, check out the LLaMA and Alpaca projects:

- llama.cpp: [https://github.com/ggerganov/llama.cpp](https://github.com/ggerganov/llama.cpp) 
- llama model download: [https://github.com/shawwn/llama-dl](https://github.com/shawwn/llama-dl) 
- alpaca.cpp: [https://github.com/antimatter15/alpaca.cpp](https://github.com/antimatter15/alpaca.cpp) 
- alpaca model download: [https://github.com/tloen/alpaca-lora](https://github.com/tloen/alpaca-lora) 
- Stanford Alpaca: [https://github.com/tatsu-lab/stanford_alpaca](https://github.com/tatsu-lab/stanford_alpaca)

Thank you for considering these suggestions, and I look forward to contributing to this project!

**Comment by pbjorklund** [comment]
Also support for multiple users would be great as I would like to deploy this as our companyChatGPT with individual chats per user, possibility to scan prompts for unsuitable sharing of information/privacy violations of customer data etc, ability to save chats to be accessible company wide, maintain a prompt library that end users can access etc.

Throwing these feature requests in here since thy seem to somewhat align with your issue.

**Comment by jairodriguez** [comment]
I second this request. It'd be huge for Enterprise applications.
