### ISSUE TITLE
Feature request: Installer for Windows.

### ISSUE THREAD

**Issue by discapacidad5** [mckaywrigley/chatbot-ui#381]
Installer for Windows.

I would like to use this program locally but I don't know how to install it. I would like you to create an installer for Windows

**Comment by dornfeld-capital** [comment]
You could try installing it as a PWA.

https://support.google.com/chrome/answer/9658361?hl=en&co=GENIE.Platform%3DDesktop

**Comment by discapacidad5** [comment]
Thank you for responding. Yes, I know I can install it that way, but it still remains in the cloud. I wanted to be able to have the local version installed on Windows with an exe installer
