### ISSUE TITLE
how to use gpt-4-32k

### ISSUE THREAD

**Issue by thecloudgeek** [mckaywrigley/chatbot-ui#382]
Hey all... I'm trying to use gpt-4-32k with this but can't seem to get it to work. I've adjusted the `types/openai.ts` with this:

```
export enum OpenAIModelID {
  ...
  GPT_4_32K = 'gpt-4-32k',
}

export const OpenAIModels: Record<OpenAIModelID, OpenAIModel> = {
  ...
  [OpenAIModelID.GPT_4_32K]: {
    id: OpenAIModelID.GPT_4_32K,
    name: 'GPT-4-32K',
    maxLength: 24000,
    tokenLimit: 26000,
  },
};
```

I still don't see `GPT-4-32K` in the ui though and no console errors... what else am I missing?

**Comment by nythrox** [comment]
GPT-4 isn't available in OpenAI's API yet.

**Comment by gmarko** [comment]
You can apply to https://openai.com/waitlist/gpt-4-api. Regards.
