### ISSUE TITLE
Feature Request: Markdown export 

### ISSUE THREAD

**Issue by Dkeds4MX** [mckaywrigley/chatbot-ui#383]
The option to export conversations to markdown format would be great

**Comment by peterkaminski** [comment]
Another vote for markdown format export.

It should be built in, but for a model of how the UI and export format might look, check out [pionxzh/chatgpt-exporter: Export and Share your ChatGPT conversation history](https://github.com/pionxzh/chatgpt-exporter).  It's a Tampermonkey userscript that installs an export button on the OpenAI ChatGTP web interface.

**Comment by peterkaminski** [comment]
I've submitted PR #684, which adds an "Export Markdown" button that exports conversations in Markdown in a zip file.

**Comment by boozedog** [comment]
@mckaywrigley I just did a pull of this commit https://github.com/mckaywrigley/chatbot-ui/commit/369087057e0d90a38188ef06a6af0d3b685a81ee and started the app, not seeing the option to export to markdown? Any ideas? Thanks!
