### ISSUE TITLE
Maximum Context Length Reached, now what?

### ISSUE THREAD

**Issue by tljstewart** [mckaywrigley/chatbot-ui#386]
<img width="347" alt="image" src="https://user-images.githubusercontent.com/8463038/229409008-711a202c-efd9-4488-8499-d5005ef00951.png">

was solving some cool problems then all of a sudden ran into a context wall, how do I go forward? Do i just start a new chat and lose the previous context?

**Comment by anuragmundhada** [comment]
It seems the ChatGPT interface truncates the older context messages. That would be very useful to have here as well.
Ideal solution would be to summarize the old context and send that?

**Comment by jairodriguez** [comment]
I run into this problem constantly. It makes this model unusable. Looking into a solution by using langchain.

**Comment by jimprince** [comment]
Any progress on this? This is kinda a deal breaker if I can't continue a conversation.

**Comment by ignamiranda** [comment]
This is also any issue for me
