### ISSUE TITLE
DEFAULT_SYSTEM_PROMPT not working

### ISSUE THREAD

**Issue by lzm0** [mckaywrigley/chatbot-ui#388]
I'm using Vercel, and I configured a different system prompt as an environment variable in my project dashboard. However, the system prompt shown in a new chat remains the original.

I would like to know if `DEFAULT_SYSTEM_PROMPT` is working for others.

**Comment by chepidev** [comment]
hi, just wanna know, why is the script wont generate any respon? its still working yesterday

**Comment by jponline77** [comment]
Doesn't work for me.  I've been working with environmental variables all morning and it seems something is broken with the utils/app/const.ts, It seems that the the environmental variables get erased after the client starts.  I was working on creating an environmental variable to change the title and it just won't work.  However, I was also using system prompt and it has the same problem.

**Comment by jponline77** [comment]
I root caused the issue as an issue with environmental variables not being visible at runtime in Next.  I created a pull request to fix the issue.
