### ISSUE TITLE
GPT-4 support (access required) (3/20/23)

### ISSUE THREAD

**Issue by Sam-Si** [mckaywrigley/chatbot-ui#397]
I read the update. How can I access GPT-4 using chatbot-ui?
In the drop-down, I don't get an option

I have the API key for a premium account.

**Comment by thomasleveil** [comment]
First, you want to check if OpenAI effectively gives you access to the `gpt-4` model by making a HTTP request as described [here](https://platform.openai.com/docs/api-reference/models/list)

**Comment by Sam-Si** [comment]
Thanks, @thomasleveil having access to GPT-4 because you bought the sub has nothing to do with getting the API for GPT-4.
```
    "id": "gpt-3.5-turbo-0301",
      "root": "gpt-3.5-turbo-0301",
      "id": "gpt-3.5-turbo",
      "root": "gpt-3.5-turbo",
```
These are the models I have access to.
