### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by NextGenGk** [mckaywrigley/chatbot-ui#398]
How can we deployed this site on production? help!

**Comment by Alex-Mc** [comment]
go to project. select project 
![4895F460-AFBE-4165-A8AB-01D9A2C6C9B0](https://user-images.githubusercontent.com/30066368/229686336-2e52fa1a-b008-460e-ab2c-90a682e4bd57.jpeg)
click Promote to Production
![CB36F960-6FF0-4C98-AEEC-1BA6DB61B26B](https://user-images.githubusercontent.com/30066368/229686445-6bc488cf-3284-488a-918a-a4f58ec79d8d.jpeg)


i hope it's help .
