### ISSUE TITLE
Feature request: Tree-like message history

### ISSUE THREAD

**Issue by littlemoonstones** [mckaywrigley/chatbot-ui#40]
Hello, I recently built a tree-like message history feature ([link](https://github.com/littlemoonstones/ChatGPT-conversation)) and I would like to develop it further to make it more similar to a real ChatGPT conversation. However, implementing this feature would require refactoring the current structure of the conversation. I'm wondering if this is worth doing?

**Comment by mckaywrigley** [comment]
This is a really great idea. I've got a few things that are priority this week, but will keep this open and revisit once those are done. I think this could be really cool.

**Comment by atharvashukla** [comment]
+1 This would be really useful with the 32k version

**Comment by littlemoonstones** [comment]
I did it.(#339)

**Comment by jmpaz** [comment]
awesome work! haven't given it a try yet but curious as to whether the entire tree is included in exports

**Comment by littlemoonstones** [comment]
> awesome work! haven't given it a try yet but curious as to whether the entire tree is included in exports

Each conversation is like a tree. When you click the export button, it exports all the trees as a JSON file.
