### ISSUE TITLE
chatbot possible memory leak

### ISSUE THREAD

**Issue by superman66** [mckaywrigley/chatbot-ui#408]
When chatbot is open for a long time, memory usage will be particularly high. 
It may be due to a memory leak.

**Comment by dee1024** [comment]
I have also encountered this. I suspect it's caused by running the command `npm run dev.` Every time I run it, the memory within 500MB is exhausted, and it gets stuck.

**Comment by gujun4990** [comment]
I have same phenomenon to lead container exit. The [link](https://github.com/mckaywrigley/chatbot-ui/issues/404) display more information.

**Comment by thomasleveil** [comment]
@superman66 how are you starting the app ? 
- `npm run dev`
- with docker
- other ?

**Comment by doroved** [comment]
I will have to write my own solution. This application has a very serious memory leak! Too bad

**Comment by doroved** [comment]
Very nice
<img width="392" alt="image" src="https://user-images.githubusercontent.com/30116541/229946160-5a903c51-e258-4b9b-a6ae-2e1d39271276.png">

**Comment by superman66** [comment]
@thomasleveil  I am deploying on Vercel and using the default start command, which I guess is "npm run start".

**Comment by doroved** [comment]
<img width="361" alt="image" src="https://user-images.githubusercontent.com/30116541/230705542-e368fa92-86be-46c0-9da6-6c4e19c39faf.png">

**Comment by doroved** [comment]
)) record so far
<img width="357" alt="image" src="https://user-images.githubusercontent.com/30116541/231298351-62239ba1-8b0d-4897-99dd-3c20dd3ea5a1.png">

**Comment by AndreLCanada** [comment]
Have we sorted a solution for this yet?

**Comment by doroved** [comment]
> Have we sorted a solution for this yet?

<img width="317" alt="image" src="https://user-images.githubusercontent.com/30116541/232168043-fa29eb82-6f15-494a-b175-b19e6ffa2c17.png">
