### ISSUE TITLE
You exceeded your current quota

### ISSUE THREAD

**Issue by ArchDuran** [mckaywrigley/chatbot-ui#409]
Greetings! I receive a message:
"You exceeded your current quota, please check your plan and billing details"
Even though I'm maxed out at $4.47/$18
I also used the API key from the second account - the same problem. Can you help me, or just tell me what could be wrong?

**Comment by jponline77** [comment]
Not something that will be able to be answered here.  You will need to work that out with OpenAI.

**Comment by kornatskyi** [comment]
I think quotas are given also for limited amount of time, so you might not exceeded it in value, but it's just expired 
![image](https://user-images.githubusercontent.com/62629228/230272848-4ed555e6-9f1e-464b-a7ff-04d780ebe62c.png)

**Comment by travahacker** [comment]
here is the answer in detail

https://stackoverflow.com/questions/75898276/openai-chatgpt-gpt-3-5-api-error-429-you-exceeded-your-current-quota-please
