### ISSUE TITLE
Merge the answer together if the user's prompt is `continue`

### ISSUE THREAD

**Issue by chunrapeepat** [mckaywrigley/chatbot-ui#411]
I'm running into these cases all the time where I need to prompt `continue` to get further answers. I'm not sure Is there a way to design the UI to make this easier? for example, merge the answer together if the user's prompt is `continue,` create a merge answer button, etc.

Love to hear your ideas.

<img width="860" alt="CleanShot 2566-04-04 at 19 19 52@2x" src="https://user-images.githubusercontent.com/8079099/229789546-a4e2eadc-f6cc-41a7-9d8b-6760dafd00b3.png">

**Comment by dee1024** [comment]
> I'm running into these cases all the time where I need to prompt `continue` to get further answers. I'm not sure Is there a way to design the UI to make this easier? for example, merge the answer together if the user's prompt is `continue,` create a merge answer button, etc.
> 
> Love to hear your ideas.

Very good idea, especially in the scenario of code output 。

**Comment by chunrapeepat** [comment]
@dee1024, maybe I'll open the pull request this weekend.

**Comment by Vheissu** [comment]
Interestingly, ChatGPT has this feature now where a button appears "Continue Generating", and it continues and merges the prompt. Presumably, we just need to detect an incomplete response and then show the button.
