### ISSUE TITLE
Why does GPT-4 perform worse than GPT-3.5 which is on the official site.

### ISSUE THREAD

**Issue by foryura** [mckaywrigley/chatbot-ui#412]
![image](https://user-images.githubusercontent.com/91335687/229792510-b63a8d21-9a3f-433f-b186-b461306cea43.png)
![image](https://user-images.githubusercontent.com/91335687/229792653-e2ab9541-1b49-4009-aa7c-2d81154336b1.png)
Please don't mind that the text looks like it has been pasted, I have deliberately translated it into the right comfortable language.

Just wondering why this happens all of a sudden you know.
Putin is 70. I hope this question did not offend anyone.
It's just not the first time I noticed it, only in my own experiments with the API GPT.

**Comment by jponline77** [comment]
Put todays date in system prompt and try again (chatgpt website puts todays date in the system prompt).
