### ISSUE TITLE
"Copy code" button not appearing on codeblocks

### ISSUE THREAD

**Issue by alnandr** [mckaywrigley/chatbot-ui#416]
I noticed that the "Copy code" button for generated codeblocks is not appearing. I've tried multiple instances of asking the AI to generate code and it won't appear no matter what I try, this is both in a local build and in live production (Vercel) as of the latest commit.

![image](https://user-images.githubusercontent.com/65328/229860438-4024008e-0fdc-420e-8a71-7ab999ae258c.png)

**Comment by thomasleveil** [comment]
I can reproduce this on d5ce8e3 by asking "write 5 random lines in a code block"

![image](https://user-images.githubusercontent.com/42300/229938826-2be39345-4107-453f-96fa-737e1e2f128a.png)
