### ISSUE TITLE
Chatbot not responding after adding API key

### ISSUE THREAD

**Issue by Ismail01Hub** [mckaywrigley/chatbot-ui#420]
Chatbot not responding after adding API key. What am I doing wrong?

**Comment by caseycarpenter** [comment]
Same issue

**Comment by dornfeld-capital** [comment]
Try creating a new key here: https://platform.openai.com/account/api-keys

**Comment by Ismail01Hub** [comment]
> Try creating a new key here: https://platform.openai.com/account/api-keys

Same. It didn't work

**Comment by jupediaz** [comment]
Same for me 
<img width="1106" alt="Captura de Pantalla 2023-04-06 a las 11 13 52" src="https://user-images.githubusercontent.com/127509/230331387-adc43e48-16ea-4830-8d03-e27f91aff8b5.png">
and by the way, the API key I have in my .env.local starts with "sk-gvU0V" ends with "KWm" so I don't understand from where is getting that API key that says that doesn't work.

**Comment by s10mcow** [comment]
You need to upgrade your free plan to a paid one - just add a credit card - and then it worked for me...

**Comment by Huowuge** [comment]
Same issue. I have tried several times, including change api-key, redeploy on vercel etc. It still doesn't work.
BTW, without env.local config, it works. However, my use case doesn't require api-key from users.

**Comment by afafw** [comment]
If you are using vercel, better use environment variable instead of modifing files, not sure why it happens.
