### ISSUE TITLE
Support for connecting to custom fine-tuned models

### ISSUE THREAD

**Issue by bingoko** [mckaywrigley/chatbot-ui#425]
I have fine-tuned an LLM chat model specifically and would like to use it with the Chatbot UI. Currently, the Chatbot UI only supports default OpenAI models with API Key, but I'd like to request a new feature that allows connecting to custom fine-tuned models.

**Comment by thomasleveil** [comment]
Can you please comment with the output of the query described [here](https://platform.openai.com/docs/api-reference/models/list)

**Comment by jpzhangvincent** [comment]
Ya I think this feature will be a great integration with another project - https://github.com/alexanderatallah/window.ai

**Comment by hexacat42** [comment]
I would appreciate this feature - using private fine-tuned models from OpenAI - as well

**Comment by tediknaak** [comment]
I see this is closed as completed but how do we use this feature? Where in the UI or back-end config can we connect to a personal fine-tuned gpt model?
