### ISSUE TITLE
Bug: Google Search plugin "regenerate response" doesn't use plugin second time

### ISSUE THREAD

**Issue by gchenfc** [mckaywrigley/chatbot-ui#433]
I suspect the "regenerate response" isn't using the same plugin as the original message query.  So e.g.

User, w/ Google Search plugin:
> "What's the weather in SF?"

ChatbotUI:
> Wednesday, April 5, in San Francisco is expected to have partly cloudy skies during the day with a high of 56F and winds increasing to 10 to 20 mph from the NNE to W. At night, partly cloudy skies with a low of 46F and winds WNW at 10 to 15 mph. [[1]](https://weather.com/weather/tenday/l/San+Francisco+CA+USCA0987:1:US) [[2]](https://weather.com/weather/tenday/l/69bedc6a5b6e977993fb3e5344e3c06d8bc36a1fb6754c3ddfb5310a3c6d6c87) [[3]](https://www.wunderground.com/weather/us/ca/san-francisco) [[4]](https://weather.com/weather/hourbyhour/l/6ceaa33cf03fa585f14f1049c4114203a0689d0c82546b1ca35e76197a1731d3)

ChatbotUI, Regenerate response:
> I'm sorry, as an AI language model I don't have access to real-time weather updates. However, you can easily check the current weather in San Francisco by searching the internet or using a weather app on your phone or computer.

**Comment by MarioGiancini** [comment]
@gchenfc this is because in it's current beta, it sets the plugin to `null` after every send.

See `handleSend` in https://github.com/mckaywrigley/chatbot-ui/blob/main/components/Chat/ChatInput.tsx#L95.
