### ISSUE TITLE
Feature suggestion: retrieval of external documents using embeddings

### ISSUE THREAD

**Issue by ghost** [mckaywrigley/chatbot-ui#434]
Retrieving the best ranking snippets from semantic search on external documents for QA and etc.

**Comment by tychotdeback** [comment]
Seconded, that would be really useful!

**Comment by jairodriguez** [comment]
I consider this absolutely crucial.

**Comment by mfieschko** [comment]
@mckaywrigley Is this actually implemented or was it closed to get it out of the open issues list?
