### ISSUE TITLE
How to hide the user input key button?

### ISSUE THREAD

**Issue by china-zhoujie** [mckaywrigley/chatbot-ui#438]
How to hide the user input key button?

**Comment by dornfeld-capital** [comment]
What do you mean? Can you provide a screenshot?

**Comment by china-zhoujie** [comment]
Hello, it is the place where you enter the key in the lower left corner of the page. Can you customize the setting to hide it?
![image](https://user-images.githubusercontent.com/68981680/230523548-3f3a21a0-387f-430c-8c6e-dea825bb2e30.png)
