### ISSUE TITLE
Add ENV Password

### ISSUE THREAD

**Issue by rossman22590** [mckaywrigley/chatbot-ui#439]
Can we have a password Variable to prevent bad usage

**Comment by dornfeld-capital** [comment]
How do you envision this implementation?

**Comment by rossman22590** [comment]
in the ENV , we have an entry like **APP_PASSWORD= PASSWORD** , if left empty, no password is on the site and anyone can access and if filled in a password is needed I will make mockup later on.

**Comment by dnlmrls** [comment]
Very good idea, I would be glad to see some protection the GUI in a way of login form.

**Comment by masonjames** [comment]
There are steps for doing this available in [this PR](https://github.com/mckaywrigley/chatbot-ui/pull/215).

**Comment by jschuur** [comment]
Came here looking for this too, because if you deploy via the Vercel template, you end up hosted at a predictable URL (https://projectname-username.vercel.app) and anyone who guesses that can use your API key.

**Comment by masonjames** [comment]
Just to be clear, the .env.local and .env files is where any API keys should be stored. However, if you're deploying to Vercel you can skip both of these files altogether and add your keys via an [environmental variable setting](https://vercel.com/guides/how-to-add-vercel-environment-variables) for each project. Cheers!

**Comment by Nimdy** [comment]
https://github.com/mckaywrigley/chatbot-ui/pull/541

I updated the login form for the feature I am trying to get mckaywrigley's input on.

**Comment by anphex** [comment]
Any update on this? Or is there a fork that can handle a password?
