### ISSUE TITLE
Keep focus on the chat input box after sending a message

### ISSUE THREAD

**Issue by solidSpoon** [mckaywrigley/chatbot-ui#44]
First of all, I'd like to thank you for creating and maintaining this wonderful project. I have been using it and find it very helpful.

However, I noticed that the chat input box loses focus after sending a message. This requires users to click on the input box again with the mouse before they can type another message, which can be a bit inconvenient.

I would like to request a feature that keeps the focus on the chat input box after sending a message. This would allow users to continue typing and sending messages more efficiently, without having to manually click on the input box each time.

Best regards

**Comment by mckaywrigley** [comment]
Great idea. Will implement.

**Comment by mckaywrigley** [comment]
Fixed!
