### ISSUE TITLE
Gateway timeout

### ISSUE THREAD

**Issue by poppinpixels** [mckaywrigley/chatbot-ui#443]
![image](https://user-images.githubusercontent.com/113057992/230051191-5abc422f-2791-4374-a506-e92ddfa1aa72.png)
After applying OpenAI, CSE ID and Google API, I get a Gateway Timeout instead of an answer. Works just fine when plugin is not activated in the prompt line.
The API's should be fine.

**Comment by jjfantini** [comment]
I am also experiencing this issue when setting up Google Keys the way suggested in docs. Keys are currently in env vars in vercel, available to the deployment.

I wonder if I need to set something up on google side to get the plugin working correctly?

**Comment by usamasaleem1** [comment]
Same here, google does not work using vercel deployment.

**Comment by joshfryart** [comment]
Same issue :)

**Comment by dkowitz** [comment]
It worked for the first 3 or 4 searches, then stopped working altogether.  Been trying to use GPT-4 to debug it, so far no luck.

**Comment by jairodriguez** [comment]
I've experienced the same problem on Vercel deployment. Using google api creds in vercel env, also added them through the interface, logs show a timeout. However the google search does work fine at localhost.

https://user-images.githubusercontent.com/73152066/230486647-24affc61-32b8-4212-ac18-0f37e3d45757.mov

**Comment by Designdocs** [comment]
Same issue :) +1

**Comment by digitaldesaster** [comment]
I get an empty error message using the google search , deployed on vercel, api key / search id are working in on the google testing site
