### ISSUE TITLE
In readme.md the google api and cse link's are not valid

### ISSUE THREAD

**Issue by bigsk1** [mckaywrigley/chatbot-ui#444]
GOOGLE_API_KEY |   | See Custom Search JSON API documentation
-- | -- | --
GOOGLE_CSE_ID |   | See Custom Search JSON API documentation

</body>
</html>GOOGLE_API_KEY 		See [Custom Search JSON API documentation](https://developers.google.com/custom-search/v1/overview)
GOOGLE_CSE_ID 		See [Custom Search JSON API documentation](https://developers.google.com/custom-search/v1/overview)

**Comment by dornfeld-capital** [comment]
Follow this prompt to set `GOOGLE_API_KEY ` and `GOOGLE_CSE_ID `.

https://github.com/mckaywrigley/chatbot-ui/blob/main/docs/google_search.md
