### ISSUE TITLE
Does the copy button not work?

### ISSUE THREAD

**Issue by dee1024** [mckaywrigley/chatbot-ui#457]
When I click the copy button or copy the code, it doesn't work.

**Comment by dornfeld-capital** [comment]
Works for me. Do you have steps to reproduce?

**Comment by kornatskyi** [comment]
Doesn't work while code ouput is still going  
![Peek 2023-04-06 19-30](https://user-images.githubusercontent.com/62629228/230528730-048e304e-7453-4850-8443-e8efa4cdc9d0.gif)

**Comment by dornfeld-capital** [comment]
I see. We should render the copy button after the text has finished streaming.

**Comment by kornatskyi** [comment]
I've been using the project for several days, I can try to make a PR for this fix. I would be happy to contribute @dornfeld-capital

**Comment by dornfeld-capital** [comment]
@kornatskyi  That would be great.

**Comment by dee1024** [comment]
> 

When I run on my local computer, the copy function works fine, but when I deploy to my Azure server via docker, the copy problem keeps appearing. In my environment, this is a necessary question.

<img width="979" alt="image" src="https://user-images.githubusercontent.com/35425156/230620743-c4984cf2-0837-4a5e-b056-b419ade96c98.png">

**Comment by dee1024** [comment]
When I debug the code, I find that the value "navigator.clipboard" in ChatMessage.tsx is false. But i don't know how to fix it.

<img width="873" alt="image" src="https://user-images.githubusercontent.com/35425156/230714019-630d4bc9-6376-4897-82e5-7cee95e87f72.png">

**Comment by dee1024** [comment]
When I use an SSL certificate to access my website, everything works fine.

**Comment by kornatskyi** [comment]
I've been looking into this issue, and it seems like it has two parts to it. First is what @dee1024  mentioned. And another is that you can't copy code because `CodeBlock` component is being constantly re-rendered by `MemoizedReactMarkdown`
![image](https://user-images.githubusercontent.com/62629228/230731480-283d8959-bd1f-4f64-9efc-43eaff123fb5.png)

So copy button works intermittently, if there are enough time between re-rendering, you can copy more easily when GPT4 responding, because it prints tokens slower. Also each update resets selection, so it's hard to select and copy when code is still rendering
![cantcopy](https://user-images.githubusercontent.com/62629228/230732082-79bbfe7c-01b9-4f74-861c-d41617804d22.gif)

**Comment by YIKAILucas** [comment]
How to fix the problem?

**Comment by HunterGerlach** [comment]
Even though this is closed, here's a working solution for anyone who stumbles on this in the future....

Replace the copyToCliboard method with the following in CodeBlock.tsx:
```
const copyToClipboard = () => {
    console.log('Attempting to copy to clipboard:', value);

    if (!navigator.clipboard || !navigator.clipboard.writeText) {
      console.error('Clipboard API not available.');
      copyToClipboardFallback(value);
      return;
    }

    navigator.clipboard
      .writeText(value)
      .then(() => {
        console.log('Copy successful');
        setIsCopied(true);
        setTimeout(() => setIsCopied(false), 2000);
      })
      .catch((err) => console.error('Copy failed', err));
  };

  const copyToClipboardFallback = (textToCopy: string) => {
    const textArea = document.createElement('textarea');
    textArea.value = textToCopy;
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    try {
      const successful = document.execCommand('copy');
      const msg = successful ? 'successful' : 'unsuccessful';
      console.log('Fallback: Copying text command was ' + msg);
    } catch (err) {
      console.error('Fallback: Oops, unable to copy', err);
    }
    document.body.removeChild(textArea);
  };
  ```

**Comment by decolygs** [comment]
> When I use an SSL certificate to access my website, everything works fine.

This is very interesting, please let me know.

What is WebServer with SSL,
・Next.js with HTTPS?
or
・Did you build a separate Web Server (Nginx, Cadyy, etc.)?
Which is it?
