### ISSUE TITLE
Implement persistent database storage for chat history and properties

### ISSUE THREAD

**Issue by kornatskyi** [mckaywrigley/chatbot-ui#461]
Currently, chat history and properties are stored in the browser's local storage, which means they are not shared between devices and may be lost if the browser's cache is cleared.
I suggest implementing a persistent database to store chat history and things such as custom prompts and future configurations, so that users can access their data across multiple devices, and the data is not lost when the browser's cache is cleared.
Export and Import data manually is a nice feature  but this is not as user-friendly and convenient a database.
Please let me know your thoughts on this idea, and if you would be open to implementing it or accepting a pull request for this feature.

**Comment by miglor-bcn** [comment]
The "Export data" works, but the "Import data" only brings the conversation name title, but not the content. 

I'm using:
- Safari in macOS Big Sur 11.7.5 
- Local hosted in ubuntu 18.04 virtual machine.
- NodeJs version 16.15.1
- I also tried in Firefox with the same behaviour.

Thanks

**Comment by kornatskyi** [comment]
Import works for me just fine on local hosted version in Fedora 37
And I also can import chats history to the demo website [https://www.chatbotui.com/](https://www.chatbotui.com/)
I'm using Mozilla Firefox 111.0.1
But also works in Chrome

Edit:Have the same problem with importing as @miglor-bcn has when running application in a container.

**Comment by Maatteogekko** [comment]
It would also be really useful if every chat had its unique url, so that it could easily be referenced.
