### ISSUE TITLE
How can I change it to stream output mode

### ISSUE THREAD

**Issue by LegendsGoneDie** [mckaywrigley/chatbot-ui#463]
Has the previous stream output mode been modified? The current overall response output has a long waiting time. Would you please tell me what parameters to modify to revert it back?

**Comment by magickio** [comment]
If you are using Nginx as a reverse proxy, you need to add the parameter `proxy_buffering off;` to the configuration

**Comment by Telosmos** [comment]
> If you are using Nginx as a reverse proxy, you need to add the parameter `proxy_buffering off;` to the configuration

In which file do I add this?

**Comment by seanchito** [comment]
There is also still an issue with some browsers (eg Firefox) where streaming is delayed due to an absent server response header when the chatbot answers.  Described here:

https://github.com/mckaywrigley/chatbot-ui/issues/343

> In which file do I add this?

In the nginx configuration file containing the server block that controls the app.   The main nginx config is frequently /etc/nginx/nginx.conf

**Comment by Telosmos** [comment]
> There is also still an issue with some browsers (eg Firefox) where streaming is delayed due to an absent server response header when the chatbot answers. Described here:

Ah, I noticed this, as I use LibreWolf which is a fork of Firefox. Had me so confused.

> In the nginx configuration file containing the server block that controls the app. The main nginx config is frequently /etc/nginx/nginx.conf

Oh, does it have to be a system-wide configuration, rather than having the stream output only for the chatbotui app? My apologies as I haven't been exposed to Nginx much before these last few days.

**Comment by seanchito** [comment]
> > There is also still an issue with some browsers (eg Firefox) where streaming is delayed due to an absent server response header when the chatbot answers. Described here:
> 
> Ah, I noticed this, as I use LibreWolf which is a fork of Firefox. Had me so confused.
> 
> > In the nginx configuration file containing the server block that controls the app. The main nginx config is frequently /etc/nginx/nginx.conf
> 
> Oh, does it have to be a system-wide configuration, rather than having the stream output only for the chatbotui app? My apologies as I haven't been exposed to Nginx much before these last few days.

Well, there are two separate issues.  Nginx buffering will prevent any streaming, while the missing server response header (for me anyway) caused Firefox to buffer a certain amount of text and then begin to stream.

I'm a total JS and nginx newb, so not the best source of advice.   Ask the bot!   With GPT assist I was able to fix both issues.  The code I posted on the other thread works to fix Firefox.  For nginx I think I ended up disabling buffering globally on my server.   Didn't notice any bad effects.

**Comment by huedaya** [comment]
I think it necessary to put a `stream` toggle options, since more comfortable and less buggy (especially when outputting code) with `stream` turned false.
