### ISSUE TITLE
Little Prolems In AI response pausing and input deletion on multiple regenerations

### ISSUE THREAD

**Issue by Mozartismee** [mckaywrigley/chatbot-ui#466]
I found a little problem in the chatgpt UI that may need to be addressed. After a few rounds of conversation, the AI stops responding completely and deletes the input I entered when I use the "regenerate" button multiple times. While this is a minor issue, I think it would be beneficial to fix it for a smoother user experience. Can you please investigate and provide a solution? Thank you.

**Comment by rt3722** [comment]
same error, after long chat, the UI basically refuses any more prompts all you get is small pop up with red X mark and if you click regenerate it deletes the previous cell. i am using this UI through vercel

**Comment by seanchito** [comment]
It's probably the  api context limit -- 4000 tokens for gpt-3.5 and 8000 for gpt-4   After the dialog reaches a certain size, it's too big to continue.   It would be nice to have a more descriptive error.   And the ability to trim the conversation down so it can continue.  Trimming would also save a lot of money over time, as over 50% of the back and forth is the bot apologizing or other fluff. The only solution now if you hit the limit is to start a new conversation.
