### ISSUE TITLE
It only shows Default GPT-3.5, although I have GPT-4 subscription

### ISSUE THREAD

**Issue by softcoder2020** [mckaywrigley/chatbot-ui#467]
Показывает только Default GPT-3.5, хотя у меня подписка GPT-4.
Tried in different browsers.

**Comment by geekbb** [comment]
I am in the same situation as well

**Comment by nxtreaming** [comment]
Because you do not have a GPT-4 apikey,

**Comment by huedaya** [comment]
This app is not dependent on your GPT-4 subscription, instead using API Key, which needs approval.

Check it here https://platform.openai.com/account/api-keys

**Comment by softcoder2020** [comment]
> This application does not depend on your GPT-4 subscription, instead it uses an API key that needs to be approved.
> 
> Check it out here [https://platform.openai.com/account/api-keys ](https://platform.openai.com/account/api-keys)

The key is present and active. 
After all, for GPT-3.5 it is in the application.

**Comment by huedaya** [comment]
As far I know GPT-4 API also requires additional application in here https://openai.com/waitlist/gpt-4-api
