### ISSUE TITLE
http://localhost:3000/api/models  -->>500

### ISSUE THREAD

**Issue by zhaoyuan020** [mckaywrigley/chatbot-ui#470]
为什么我的这个接口报500了？谁能告诉我。。

**Comment by zhaoyuan020** [comment]
> 为什么我的这个接口报500了？谁能告诉我。。

那是因为你在本地部署的时候，本地无法直连api.openai.com导致的

**Comment by zhaoyuan020** [comment]
> > 为什么我的这个接口报500了？谁能告诉我。。
> 
> 那是因为你在本地部署的时候，本地无法直连api.openai.com导致的

可是我本地已经开了vpn了呀，在浏览器里可以访问openai.com的，有什么解决方案吗？难道一定要把项目部署在国外的服务器上吗？

**Comment by huadongxiao** [comment]
问题解决了么？我也遇到了同样的错误，我已经链接VPN了，但是一直报错500

**Comment by zhaoyuan020** [comment]
没有解决，最后选择部署在国外服务器上😂发自我的 iPhone在 2023年4月13日，17:24，huadongxiao ***@***.***> 写道：﻿
问题解决了么？我也遇到了同样的错误，我已经链接VPN了，但是一直报错500

**Comment by huadongxiao** [comment]
那你二开是怎么二开的，盲写然后再部署嘛

**Comment by zhaoyuan020** [comment]
没有二开，按教程一键部署就可以用了。。。

从 Windows 版邮件发送

发件人: huadongxiao
发送时间: 2023年4月13日 18:01
收件人: mckaywrigley/chatbot-ui
抄送: zhaoyuan020; Author
主题: Re: [mckaywrigley/chatbot-ui] http://localhost:3000/api/models -->>500 (Issue #470)

那你二开是怎么二开的，盲写然后再部署嘛

**Comment by xiaoshuaishuai** [comment]
your vpn ip banned， update /etc/hosts such as 104.18.6.192 api.openai.com, IP被封了，修改本地hosts文件，实测可用

**Comment by zhaoyuan020** [comment]
有时间我也试试👌发自我的 iPhone在 2023年5月9日，16:54，xiaoshuaishuai ***@***.***> 写道：﻿
your vpn ip banned， update /etc/hosts such as 104.18.6.192 api.openai.com, IP被封了，修改本地hosts文件，实测可用

**Comment by NUAAwanghe** [comment]
我也遇到这个问题了，国内的服务器，老版本chatgpt-mirror是没问题的，但是这个就是提示获取服务模型失败，代理也没问题

**Comment by zhaoyuan020** [comment]
尝试一下上边兄弟提出的修改host的方法吧，我还没来得及测试，不知道行不行发自我的 iPhone在 2023年5月12日，10:48，NUAA王鹤 ***@***.***> 写道：﻿
我也遇到这个问题了，国内的服务器，老版本chatgpt-mirror是没问题的，但是这个就是提示获取服务模型失败，代理也没问题

**Comment by NUAAwanghe** [comment]
没用，这个国内不行，chatgpt-web更好用

**Comment by zhaoyuan020** [comment]
chatgpt-web是什么项目？发自我的 iPhone在 2023年5月12日，15:15，NUAA王鹤 ***@***.***> 写道：﻿
没用，这个国内不行，chatgpt-web更好用

**Comment by NUAAwanghe** [comment]
> chatgpt-web是什么项目？发自我的 iPhone在 2023年5月12日，15:15，NUAA王鹤 ***@***.***> 写道：﻿ 没用，这个国内不行，chatgpt-web更好用 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

也是github上一个开源chatgpt页面，国内服务器我用那个搭可以用

**Comment by zhaoyuan020** [comment]
地址给我一下吧，我也想试试国内的😂发自我的 iPhone在 2023年5月13日，16:30，NUAA王鹤 ***@***.***> 写道：﻿

chatgpt-web是什么项目？发自我的 iPhone在 2023年5月12日，15:15，NUAA王鹤 @.> 写道：﻿ 没用，这个国内不行，chatgpt-web更好用 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.>

也是github上一个开源chatgpt页面，国内服务器我用那个搭可以用

**Comment by NUAAwanghe** [comment]
> 地址给我一下吧，我也想试试国内的😂发自我的 iPhone在 2023年5月13日，16:30，NUAA王鹤 ***@***.***> 写道：﻿ chatgpt-web是什么项目？发自我的 iPhone在 2023年5月12日，15:15，NUAA王鹤 @.> 写道：﻿ 没用，这个国内不行，chatgpt-web更好用 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.> 也是github上一个开源chatgpt页面，国内服务器我用那个搭可以用 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

https://github.com/Chanzhaoyu/chatgpt-web

**Comment by zhaoyuan020** [comment]
Railway是一个云开发平台，旨在简化Web应用程序的开发流程。用户可以使用Railway来轻松部署和管理他们的应用程序，而无需关心服务器端的架构和配置，以及其他与服务器管理相关的细节。此外，该平台为开发者提供了各种工具和功能，例如应用程序部署、数据存储和身份验证，以帮助他们在开发Web应用程序时提高效率和减轻工作负担。Railway主要适用于中小型Web应用程序的开发，包括网站、API服务和移动应用后端。

这个平台，我的的GitHub账号不能用，你知道怎么办嘛？

报错如下：
Verify your identity
Railway is a platform for good actors to build great products. We're sorry for this safety-check inconvenience; we aim to keep things cool for everybody. Thank you.


从 Windows 版邮件发送

发件人: NUAA王鹤
发送时间: 2023年5月14日 10:53
收件人: mckaywrigley/chatbot-ui
抄送: zhaoyuan020; Author
主题: Re: [mckaywrigley/chatbot-ui] http://localhost:3000/api/models -->>500 (Issue #470)

地址给我一下吧，我也想试试国内的😂发自我的 iPhone在 2023年5月13日，16:30，NUAA王鹤 @.> 写道：﻿ chatgpt-web是什么项目？发自我的 iPhone在 2023年5月12日，15:15，NUAA王鹤 @.> 写道：﻿ 没用，这个国内不行，chatgpt-web更好用 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.> 也是github上一个开源chatgpt页面，国内服务器我用那个搭可以用 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.>
https://github.com/Chanzhaoyu/chatgpt-web

**Comment by NUAAwanghe** [comment]
> Railway

一般对于国外的网站，我推荐使用gmail注册，一般没有问题

**Comment by zhaoyuan020** [comment]
好的，我重新注册一个账号👌发自我的 iPhone在 2023年5月15日，12:26，NUAA王鹤 ***@***.***> 写道：﻿

Railway

一般对于国外的网站，我推荐使用gmail注册，一般没有问题

**Comment by zhaoyuan020** [comment]
你不会部署在本地了吧？发自我的 iPhone在 2023年5月15日，12:26，NUAA王鹤 ***@***.***> 写道：﻿

Railway

一般对于国外的网站，我推荐使用gmail注册，一般没有问题

**Comment by zhaoyuan020** [comment]
Unverified GitHub account
Unfortunately, the attached GitHub account does not meet our good actor criteria.
我重新用gmail注册的账号也不行。。。你部署好的地址给我用一下呗，我体验一下，用我自己的api key。。。

从 Windows 版邮件发送

发件人: NUAA王鹤
发送时间: 2023年5月15日 12:26
收件人: mckaywrigley/chatbot-ui
抄送: zhaoyuan020; Author
主题: Re: [mckaywrigley/chatbot-ui] http://localhost:3000/api/models -->>500 (Issue #470)

Railway
一般对于国外的网站，我推荐使用gmail注册，一般没有问题

**Comment by Ading163** [comment]
![image](https://github.com/mckaywrigley/chatbot-ui/assets/94432082/1edc7e2e-917b-49cd-8b40-274fce8cbf2a)
修改主机地址实测无效

**Comment by zhaoyuan020** [comment]
。。。发自我的 iPhone在 2023年5月21日，09:39，Ading163 ***@***.***> 写道：﻿

修改主机地址实测无效

**Comment by yunjun199321** [comment]
我在本地电脑，开了VPN。按文档说的用docker跑可以，直接node跑跟你一样报错。感觉跟VPN无关。

**Comment by liusome** [comment]
在.env.local中设置OPENAI_API_HOST=https://open.aiproxy.xyz就可以了，亲测可用 参考https://www.v2ex.com/t/921689
