### ISSUE TITLE
Show Plugin In Dropdown Only If API Keys Are Given

### ISSUE THREAD

**Issue by MarioGiancini** [mckaywrigley/chatbot-ui#476]
### Overview

Currently, the first plugin was for Google search and is in beta via #414. 

We should update the components to only show the plugins in the dropdown if we've set our `.env` keys for them, in this case the Google API plugin.

**Comment by kornatskyi** [comment]
I see a drop-down with Google Plugin even when I don't specify google API key in `.env`
![image](https://user-images.githubusercontent.com/62629228/230732427-4f590946-5749-4782-af40-4050dce3023b.png)

**Comment by MarioGiancini** [comment]
@kornatskyi yep, same for me.

[I completely missed the the `BoltIcon` was the trigger](https://github.com/mckaywrigley/chatbot-ui/pull/477#issuecomment-1500929792) to show the plugin list.

So perhaps this issue should be updated to only show the Google Search plugin if `.env` keys are given.
