### ISSUE TITLE
Error "Sorry, there was an error."

### ISSUE THREAD

**Issue by seblavoie** [mckaywrigley/chatbot-ui#48]
I'm trying to get things running locally. I've cloned the repo, installed dependencies, provided my api key, but I keep receiving the message: `Sorry, there was an error.` 

I've tried creating a new api key and it doesn't fix the issue. Although I can see on OpenAI's site that it updates my API key "last used" to today, so it does hit it. 

I've also searched for an error log file but couldn't find it. Any help would be appreciated thanks! (Great work by the way!) 

<img width="1595" alt="Screenshot 2023-03-21 at 11 54 57" src="https://user-images.githubusercontent.com/950207/226666934-b1b88af2-3bf6-4f06-b178-b1e52d485778.png">

**Comment by igorhbs** [comment]
If you had installed the a previous release, run `npm i `in the app directory again to install a new package that was added to the last release and try running the application again.

**Comment by seblavoie** [comment]
Thanks for the quick response, but I did already try to update the repo and run `npm i`. I also deleted `node_modules` and rerun it to be sure. Still same error. 

In the terminal I get `[Error: OpenAI API returned an error]`

**Comment by mckaywrigley** [comment]
Likely a key issue. Have yet to run into this error without it being one. Double check the API key being set correctly, OpenAI being up, and the key working elsewhere.

**Comment by hemaaanth** [comment]
You probably want to check for trailing spaces or newlines in your .env.local file!
