### ISSUE TITLE
Feature Suggestion: Make it a PWA

### ISSUE THREAD

**Issue by TiancongLx** [mckaywrigley/chatbot-ui#482]

**Comment by geekbb** [comment]
I strongly agree, this will better serve my iPad and iPhone.

**Comment by TiancongLx** [comment]
> I strongly agree, this will better serve my iPad and iPhone.

Yeah, No need to open the webpage in browser and no need to refresh the webpage every time.

**Comment by dominiksipowicz** [comment]
I created PR to add it to todo list 🤣 for visibility 

https://github.com/mckaywrigley/chatbot-ui/pull/549

**Comment by dominiksipowicz** [comment]
Also if anyone wants to bump up the reach here is the tweet:
https://twitter.com/dom_sipowicz/status/1646847236024705024

**Comment by tobi** [comment]
Nicer install dialogs are rolling out: https://developer.chrome.com/blog/richer-install-ui-desktop/
