### ISSUE TITLE
Post error msg to ui

### ISSUE THREAD

**Issue by pccai** [mckaywrigley/chatbot-ui#487]
When server error，UI has no message：

 [OpenAIError: That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 2953c0dd52959dc19709f91ee62b61c0 in your message.)] {
  name: 'OpenAIError',
  type: 'server_error',
  param: null,
  code: null
}

**Comment by shrwnsan** [comment]
+1

**Comment by adamshand** [comment]
Ran into this today, confused me for a few minutes until I figured out what was going on.

Would be great if error messages were shown in the UI somewhere so the user isn't left hanging wondering what's going on.
