### ISSUE TITLE
Copy function from a coding window not working

### ISSUE THREAD

**Issue by jdeesy411** [mckaywrigley/chatbot-ui#489]
The copy button used to copy code the AI has written for you does not work.  The mouse cursor turns to a finger when hovered over the copy button, but the contents of the window does not copy to the clipboard.

**Comment by BouarfaMahi** [comment]
same issue on android  with select and copy/paste.

**Comment by liharryboy** [comment]
When executing navigator.clipboard in Chrome's DevTools console, it returns undefined. Upon further research, it was found that the browser has disabled the navigator.clipboard object for non-secure domains. Which addresses are considered secure?
Secure domains include locally accessed addresses and those with TLS security certification, such as addresses using the https protocol, 127.0.0.1, or localhost.

when navigator.clipboard.writeText is false, you can try to use [ document.execCommand('copy')  ] to workaround it.

**Comment by Cornoualis** [comment]
Same issue for me.
The "copy code" seems to be a dummy button. Absoluterly nothing happens when I click on it, even in the JS console.

**Comment by liharryboy** [comment]
try use these code, in 
```
#ChatMessage.tsx, 
if (!navigator.clipboard || !navigator.clipboard.writeText) {
  const textArea = document.createElement('textarea');
  textArea.value = message.content;
  document.body.appendChild(textArea);
  textArea.focus();
  textArea.select();
  document.execCommand('copy');
  textArea.remove();
  setMessageCopied(true);

  setTimeout(() => {
    setMessageCopied(false);
  }, 2000);
  return;
}
```

```
#CodeBlock.tsx
if (!navigator.clipboard || !navigator.clipboard.writeText) {
  const textArea = document.createElement('textarea');
  textArea.value = value;
  document.body.appendChild(textArea);
  textArea.focus();
  textArea.select();
  document.execCommand('copy');
  textArea.remove();
  setMessageCopied(true);

  setTimeout(() => {
    setMessageCopied(false);
  }, 2000);
  return;
}
```
