### ISSUE TITLE
Error message "The API deployment for this resource does not exist" when using Azure OpenAI Service

### ISSUE THREAD

**Issue by jony4** [mckaywrigley/chatbot-ui#498]
```
The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.
```

**Comment by jony4** [comment]
Actually, I have deployed the OpenAI model and service already.

**Comment by jony4** [comment]
Perhaps this parameter was omitted.

reference -> https://github.com/sashabaranov/go-openai/blob/master/config.go#L60

**Comment by gchust** [comment]
I was facing the same error, I fixed it by setting the following environment var for azure

```diff
DEFAULT_MODEL | gpt-3.5-turbo | The default model to use on new conversations, for Azure use gpt-35-turbo

---gpt-3.5-trubo
+++gpt-35-turbo

```

Azure should use **gpt-35-turbo**

**Comment by jony4** [comment]
no, this is deployment id is from here: https://learn.microsoft.com/zh-cn/azure/cognitive-services/openai/reference#completions which input by yourself

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/13718575/231163751-d129fa8a-ca01-462c-9d63-e076fceb189b.png">

I just test with "gpt35", and no more error message. lol

**Comment by jony4** [comment]
pr https://github.com/mckaywrigley/chatbot-ui/pull/499

**Comment by gchust** [comment]
> no, this is deployment id is from here: https://learn.microsoft.com/zh-cn/azure/cognitive-services/openai/reference#completions which input by yourself
> 
> <img alt="image" width="1328" src="https://user-images.githubusercontent.com/13718575/231163751-d129fa8a-ca01-462c-9d63-e076fceb189b.png">
> 
> I just test with "gpt35", and no more error message. lol

You're right, I have renamed the deployment name same as the model name lol...

**Comment by itbm** [comment]
@jony4 @mckaywrigley PR #499 isn't required and adds complexity. The existing solution automatically translates `gpt-35-turbo` / `gpt-4` / `gpt-4-32k` to your deployment name. See https://github.com/mckaywrigley/chatbot-ui/blob/main/pages/api/models.ts#L53.

If you opened the web UI before setting `DEFAULT_MODEL=gpt-35-turbo` it may have cached `gpt-3.5-turbo` in your conversations. Exporting your data, fixing the JSON file, clearing your cache and re-importing data will probably solve it _(or just clear your cache if you don't want to keep conversations)_. The exported JSON should have:

```
// ...
  "model": {
    "id": "<deployment_name>",
    // ...
  },
// ...
```

**Comment by jony4** [comment]
the /api/models api returns this response
```
[{"id":"gpt35","name":"GPT-3.5"}]
```
but seems the response's id field isn't used by [index.ts#L34](https://github.com/mckaywrigley/chatbot-ui/blob/main/utils/server/index.ts#L34) correctly.

`/openai/deployments/gpt35/chat/completions?api-version=` will works.

**Comment by jony4** [comment]
here's my demo, you can check it. https://azure.chat.jony4.vip

**Comment by vladiliescu** [comment]
@jony4 I think you may want to shut that down, at the moment anyone can make calls to Azure OpenAI using your keys (so you will get billed for it).

**Comment by Quetzalcohuatl** [comment]
Removing the period from 3.5 fixed it on my end too. Thanks random github issue!
