### ISSUE TITLE
I encountered an error, but I don't know how to solve it.

### ISSUE THREAD

**Issue by alanjustalan** [mckaywrigley/chatbot-ui#5]
![image](https://user-images.githubusercontent.com/42884681/226100160-cc49b797-3c54-440a-ba3a-5779a5c9d5c3.png)
Can you tell me how to solve this error? Thank you very much!

**Comment by mckaywrigley** [comment]
@alanjustalan Do you have your OpenAI API key in a .env.local file?

**Comment by alanjustalan** [comment]
是的，my OpenAI API in .env.local file
![image](https://user-images.githubusercontent.com/42884681/226104546-33ab1a4f-0c3c-42e0-b15c-facd61b84bc5.png)
![image](https://user-images.githubusercontent.com/42884681/226104561-b4e1ce5a-db15-4d00-9765-8e2f2bf1e787.png)

**Comment by mckaywrigley** [comment]
Ah I see! Get rid of the < and >. Sorry for the confusion there. That should fix it!

**Comment by alanjustalan** [comment]
thanks~

**Comment by kevinlyliu** [comment]
"Get rid of the < and >" what does that mean? Please open mind, there's first day python learner here, haha. Please elaborate, thanks.
