### ISSUE TITLE
Give ability for users to use their own models

### ISSUE THREAD

**Issue by dillchen** [mckaywrigley/chatbot-ui#50]
Instead of using the OpenAPI, for example, a user could use the Stanford Alpaca Models [training weights](https://github.com/tatsu-lab/stanford_alpaca), if they were to obtain these.

**Comment by mckaywrigley** [comment]
Will support this eventually. Keeping my eye on this, but not ready for it yet (someone else could potentially work on it sooner if interested).

**Comment by mkellerman** [comment]
This is how i got it working: https://github.com/mkellerman/gpt4all-ui
