### ISSUE TITLE
Where should I put OPENAI_API_KEY to host my own Vercel?

### ISSUE THREAD

**Issue by Gaozhongpai** [mckaywrigley/chatbot-ui#501]
The title says it all. Thanks

**Comment by jairodriguez** [comment]
Under settings

<img width="1095" alt="Screenshot 2023-04-11 at 14 04 30" src="https://user-images.githubusercontent.com/73152066/231276315-92c25e80-a75f-414c-a3b3-4bb3f02b363c.png">

<img width="1319" alt="Screenshot 2023-04-11 at 14 05 03" src="https://user-images.githubusercontent.com/73152066/231276308-41a6e139-6c0c-4b03-ade9-293518bceb17.png">

**Comment by Itangalo** [comment]
Also, you might want to redeploy to get new settings out. (At least I had to, but that might have been because I didn't wait for some automatic deploy.)

![image](https://github.com/mckaywrigley/chatbot-ui/assets/262940/6d078ba6-09eb-4523-b525-cabc686718c7)
