### ISSUE TITLE
[Plugin Keys]Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by Designdocs** [mckaywrigley/chatbot-ui#502]
Hello, I just updated the latest code, but when clicking on [Plugin Keys], the screen prompts: 

`Application error: a client-side exception has occurred (see the browser console for more information).`

The tested browsers include：Google/Firefox/safair
Does anyone have a similar situation? How should I fix it? Thank you!

**Browser console error prompt：**

```
3DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
framework-73b8966a3c579ab0.js:1 
TypeError: n.find is not a function
    at eR (index-0010ba8666107666.js:1:46157)
    at ab (framework-73b8966a3c579ab0.js:1:61011)
    at ud (framework-73b8966a3c579ab0.js:1:72897)
    at i (framework-73b8966a3c579ab0.js:1:120465)
    at oO (framework-73b8966a3c579ab0.js:1:99207)
    at framework-73b8966a3c579ab0.js:1:99074
    at oF (framework-73b8966a3c579ab0.js:1:99081)
    at ox (framework-73b8966a3c579ab0.js:1:95833)
    at oC (framework-73b8966a3c579ab0.js:1:96222)
    at r4 (framework-73b8966a3c579ab0.js:1:44872)
 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

**Comment by leoli-dev** [comment]
same here:

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/1598600/231751217-15d2559f-f7d9-4d76-ba9d-0008800b529c.png">

To eliminate the error, I need to manually delete the `pluginKeys` from the local storage.

**Comment by Designdocs** [comment]
> 同样在这里：
> 
> <img alt="图像" width="1670" src="https://user-images.githubusercontent.com/1598600/231751217-15d2559f-f7d9-4d76-ba9d-0008800b529c.png">
> 
> 为了消除错误，我需要`pluginKeys`从本地存储中手动删除。

**This method is effective, it worked normally. Thank you for your help.**
