### ISSUE TITLE
Configuration In which file is it modified?

### ISSUE THREAD

**Issue by shexiaobin** [mckaywrigley/chatbot-ui#504]
i want to use azure openai, but i don't how to  Configuration

<img width="885" alt="image" src="https://user-images.githubusercontent.com/26622879/231208931-15a3a94c-f750-46ff-8f93-73163be34f15.png">

**Comment by SyedMuzamilM** [comment]
You can add these in environmen file. `.env` and then set the values for these variables.

**Comment by shexiaobin** [comment]
Modify this file directly, right?
![image](https://user-images.githubusercontent.com/26622879/231356073-5fc0e678-dbc9-4b1d-8abb-ab8ece79af67.png)

**Comment by SyedMuzamilM** [comment]
You need to copy this file into `.env` and then modify that. Not `.env.example`

**Comment by SyedMuzamilM** [comment]
I think you can close this issue.
