### ISSUE TITLE
How is dark/light theme handled?

### ISSUE THREAD

**Issue by shep920** [mckaywrigley/chatbot-ui#506]
Apologies for the basic issue, but i've been running my head against a wall trying to figure out how the theming works. In home.tsx, we can find the effect:
```
const theme = localStorage.getItem('theme');
    if (theme) {
      dispatch({ field: 'lightMode', value: theme as 'dark' | 'light' });
    }
```

Which is used in a couple places like this
```
<main
          className={`flex h-screen w-screen flex-col text-sm text-white dark:text-white ${lightMode}`}>
 ```
 
 But when checking tailwind's config, i dont see anything about it except just darkMode: 'class', and there is nothing about it in the global styles. Anyone know how you could implement the themes in say, other routes/components?

**Comment by zxhmike** [comment]
@shep920 Check this out: https://tailwindcss.com/docs/dark-mode
