### ISSUE TITLE
[docker] Add support to platform linux/arm64

### ISSUE THREAD

**Issue by fox91** [mckaywrigley/chatbot-ui#518]
Actually docker images are built only for platform `linux/amd64`.
Is it possible to add support to `linux/arm64` and release it as a multi-platform image?

**Comment by mkellerman** [comment]
@mckaywrigley please dont close until the PR is merged.

**Comment by fox91** [comment]
PR #519 was merged and issue closed, why not?
Probably it need to close #424.

I've already tested the new arm64 image on a raspberry and works perfectly.

**Comment by mkellerman** [comment]
Yes, was referring to #424.

`<insert meme of homer backing into the bushes>`
