### ISSUE TITLE
"Enter" key on prompt list selection does not open a modal with correct title and description

### ISSUE THREAD

**Issue by morleyabbott** [mckaywrigley/chatbot-ui#523]
To reproduce:

1. Create 2 or 3 prompts that have variables. 
2. Start typing in chat with `/` and the name of the 2nd or 3rd prompt
3. Hit 'enter' to select the prompt.
4. The modal opens, but has the name and description of the *first* prompt rather than the one chosen. 

Does not happen if you click on the prompt name. 

I believe this is because clicking triggers line 38 of `components/Chat/PromptList.tsx` which in turn calls the callback sent in `components/Chat/ChatInput.tsx#L350`, which is `setActivePromptIndex`. But in `components/Chat/ChatInput.tsx#L151` we don't do the same thing when someone hits enter- it simply opens the modal and presumes the index is correct.

Might take a look at going after this myself if I get some time later this week, but I suspect someone with deeper knowledge of the codebase will be much faster at solving the problem.

**Comment by geekbb** [comment]
I also encountered this problem, I thought it was the browser's error.
