### ISSUE TITLE
Error fetching models on Vercel

### ISSUE THREAD

**Issue by Klaudioz** [mckaywrigley/chatbot-ui#526]
I'm seeing this error intermittently on Vercel often:

![image](https://user-images.githubusercontent.com/632625/231544482-88314815-db54-47cb-94cf-117cc450753d.png)

Looking Vercel logs I can see:

```
Level: Error
Cache: MISS
Type: Edge Function
Function: /api/models
[POST] /api/models status=500
```

![image](https://user-images.githubusercontent.com/632625/231545167-6944c478-1330-452a-b5fa-f7c4dfcb1674.png)

I think it's hitting the [Edge Function size limitations](https://vercel.com/docs/concepts/limits/overview#edge-middleware-and-edge-functions-size). I'm not expert on Vercel serverless but the cache MISS happened to me before on a NextJS project.

So this template was released on the Vercel Templates officially: https://vercel.com/templates/next.js/chatbot-ui so I guess more people with have this issue.

I've recorded a video as well showing it comes and goes: https://cln.sh/833RksHwXQXBHr9Zj0N0/download
Maybe this project is too heavy for Vercel Hobby but Actually I'm using a PRO account.

**Comment by steven-tey** [comment]
Can repro on https://www.chatbotui.com/ as well, and I suspect that you might be right @Klaudioz!

@mckaywrigley what are the sizes of the models you're fetching in `/api/models`?

**Comment by Klaudioz** [comment]
Anybody can help with this issue?.

Thanks.

**Comment by Klaudioz** [comment]
Can you please check on this @mckaywrigley.

I think it's an important issue after the Vercel announcement.

Thank you.

**Comment by SDcodeman** [comment]
Same issue

**Comment by yimouleng** [comment]
My guess is that openai has banned Vercel's IP

**Comment by Husky931** [comment]
i am having the same issue

**Comment by skarlekar** [comment]
I am having the same issue running it locally from my laptop connected to the internet. I repeat this is not through Vercel. Any pointers will be appreciated!

I am getting the following error on my console:

error - Class extends value undefined is not a constructor or null

This might be caused by a React Class Component being rendered in a Server Component, React Class Components only works in Client Components. Read more: https://nextjs.org/docs/messages/class-component-in-server-component
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/file.js (evalmachine.<anonymous>:5724:19)
    at __require (evalmachine.<anonymous>:14:50)
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/formdata.js (evalmachine.<anonymous>:5881:49)
    at __require (evalmachine.<anonymous>:14:50)
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/body.js (evalmachine.<anonymous>:6094:35)
    at __require (evalmachine.<anonymous>:14:50)
    at ../../node_modules/.pnpm/undici@5.11.0/node_modules/undici/lib/fetch/response.js (evalmachine.<anonymous>:6510:49)
    at __require (evalmachine.<anonymous>:14:50)
    at <unknown> (evalmachine.<anonymous>:11635:30)
    at requireFn (file:///Users/skarlekar/Documents/theWorks/chatbot-ui/node_modules/next/dist/compiled/edge-runtime/index.js:1:7079) {
  name: 'TypeError'

**Comment by skarlekar** [comment]
Interestingly, the above error (Error fetching models) does not manifest if I build and run it in Docker. The docker version runs fine.

**Comment by skarlekar** [comment]
FYI. The error disappeared on my local machine after I upgraded to the latest version of Node and NPM. My current version after upgrading is as follows:
(base) Srini-13-MacBook-Pro-1844:~ skarlekar$ node -v
v19.9.0
(base) Srini-13-MacBook-Pro-1844:~ skarlekar$ npm -v
9.6.4
(base) Srini-13-MacBook-Pro-1844:~ skarlekar$

**Comment by arudaev** [comment]
@mckaywrigley 
I think I found the issue for this error, and it prob needs fixing.
> OpenAIError: This model's maximum context length is 4097 tokens. However, you requested 4211 tokens (3211 in the messages, 1000 in the completion). Please reduce the length of the messages or completion.
    at (utils/server/index.ts:72:12)
    at (pages/api/chat.ts:55:19)
    at (node_modules/next/dist/esm/server/web/adapter.js:103:0) {
  name: 'OpenAIError',
  type: 'invalid_request_error',
  param: 'messages',
  code: 'context_length_exceeded'
}

![image](https://user-images.githubusercontent.com/66517969/235119545-0b69355b-81d3-4487-8077-f9fb603ee46f.png)

**Comment by hexacat42** [comment]
@mckaywrigley
In my case, the issue exists only, if I use the `OPENAI_API_KEY=<KEY>` in .env.local
If I provide the OpenAI key within chatbot-ui (left bottom corner), it works for me.

**Comment by harshv1t** [comment]
> (base) Srini-13-MacBook-Pro-1844:~ skarlekar$ npm -v

This worked for me

**Comment by codsec** [comment]
Im having the same issue, any idea?
