### ISSUE TITLE
Google Search Plugin returns 500

### ISSUE THREAD

**Issue by hooman-bayer** [mckaywrigley/chatbot-ui#528]
It seems like the google plugin is not functional anymore. After entering the google api keys in the demo frontend, it only returns 500

**Comment by rossman22590** [comment]
same here

**Comment by kevinpardo** [comment]
Same here :
Failed to load resource: the server responded with a status of 504 ()

**Comment by rossman22590** [comment]
i rolled back and it worked

**Comment by kevinpardo** [comment]
Running it locally I get this error : 

TypeError: Cannot read properties of undefined (reading 'length')
components/Chat/Chat.tsx (397:44) @ length

When I refresh the page I have the answer in the chat, but the prompt switched to ChatGPT.

**Comment by RoskiDeluge** [comment]
#536 fixed the issue for me.

**Comment by kevinpardo** [comment]
I still have the issue here.
EDIT : Nevermind I made a mistake, #536 worked out for me too !

**Comment by masonjames** [comment]
The 500 error happens for me when I am only using the environmental variables. Adding them via the interface resolves it. For my use case, I'd like to define the variables and hide the interface entirely, same as the OpenAI key.

**Comment by kevinpardo** [comment]
Hmm... Seems like everything works in local, but not once deployed on Vercel. I checked my environment variables, everything is good.

I get a 504 on Vercel while I get the correct answer from Google on Local.

I tried adding the 2 Google variables via the interface too but it didn't change anything for me @masonjames

**Comment by hooman-bayer** [comment]
#536 fixed it for me too (both local and deployed)
