### ISSUE TITLE
Suggestion:  cleaner UI

### ISSUE THREAD

**Issue by seanchito** [mckaywrigley/chatbot-ui#540]
With the new temperature setting there are now 4 settings in a large window front and center every time a new chat is started.  It seems like this entire div could be hidden so we get a less cluttered page for each new chat.   Maybe a convenient and subtle modal button to open and hide this window?   Wouldn't it look clean and nice with only the app title and the input form?

**Comment by ghost** [comment]
I agree. I think the temperature parameter is definitely useful, but could be hidden in an elegant manner.

Also, a setting for **default temperature** would be very useful.
