### ISSUE TITLE
Update UI 

### ISSUE THREAD

**Issue by clevermiraz** [mckaywrigley/chatbot-ui#545]
What About I'm Thinking The UI Should Be Good Looking.

Now What UI On The Chatbot-ui is good?

But If We Update The UI More modern It Will Look Fantastic.

What Did You think Just Comment on It Out. Let Me Know

**Comment by upasch** [comment]
I did it after I forked the project. But to not loose the possibility to merge new functions or other updates, I didnt change the structure. Therefore I'm still able to merge new commits in my own project ;)

**Comment by clevermiraz** [comment]
Ok.

**Comment by clevermiraz** [comment]
We Can Work With Small Pieces of Code.
