### ISSUE TITLE
I use paid API but only have the option of GPT-3.5 

### ISSUE THREAD

**Issue by nostitos** [mckaywrigley/chatbot-ui#550]
?

![image](https://user-images.githubusercontent.com/48504624/232052905-670b507b-c9a9-4eb2-9bdc-6a9a8be54708.png)

Odd to have a selection with one option

**Comment by clevermiraz** [comment]
GPT-4 Is Not Publicly released yet.

If You Want To use Then You Should contact With OpenAI Support Team

**Comment by upasch** [comment]
I guess you pay for ChatGPT Plus, but this Product does not include GPT-4 API Support. You have to request for the GPT-4 from their Website. You will find the form here: https://openai.com/waitlist/gpt-4-api
