### ISSUE TITLE
Feature Request: Multi-line input

### ISSUE THREAD

**Issue by j4shu** [mckaywrigley/chatbot-ui#566]
Wondering if a way to toggle explicitly single line + multi line would be possible, i.e. like slack. Ctrl/Cmd + enter to send message in multi-line mode

**Comment by KhanKudo** [comment]
You can always use Shift + Enter to create a new line, without sending the message.
But a specific mode toggle like a button is something I personally have never seen, would be odd.
Changing it to default Enter as new-line and Ctrl+Enter as send could be confusing and unnecessary for most users.
If you have a suggestion on what this would look, I'd be happy to create a PR.

**Comment by j4shu** [comment]
It is a pretty common practice, i.e. in Slack: https://slack.com/help/articles/115005523006-Set-your-Enter-key-preference and Microsoft Teams: https://camerondwyer.com/2018/12/22/do-you-hit-enter-in-microsoft-teams-for-a-new-line-and-accidentally-post-partial-message-try-this-hack/. It's usually a setting instead of default so it wouldn't affect most users.

**Comment by KhanKudo** [comment]
I see what you mean. I'll take a closer look at it. I have a possible implementation in mind.

**Comment by KhanKudo** [comment]
I believe this #581 is what you are looking for.
If it's not correct, I am happy to make any adjustments.
