### ISSUE TITLE
Error occurs when importing the data

### ISSUE THREAD

**Issue by vaghawan** [mckaywrigley/chatbot-ui#572]
Since there was no clear documentation on the Importing data or even what does it mean, I uploaded a random json data and Chatbot-UI stopped working, it throws the following error, 

1 of 2 unhandled errors

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'length')

Source

```
components/Chat/Chat.tsx (399:44) @ length

  397 |   onScroll={handleScroll}
  398 | >
> 399 |   {selectedConversation?.messages.length === 0 ? (
      |                                  ^
  400 |     <>
  401 |       <div className="mx-auto flex w-[350px] flex-col space-y-10 pt-12 sm:w-[600px]">
  402 |         <div className="text-center text-3xl font-semibold text-gray-800 dark:text-gray-100">
```

It throws the same error even after restarting the server.

**Comment by vaghawan** [comment]
So, I had to hack a little bit, since I am just started with this project, I did the following: 

set at line 62 of ChatInput.tsx: 

`selectedConversation.messages = [];`

Then the UI will come back, then I did clear conversation, it cleared everything from that random data, then I commented the line 62, and it started working. I know this is not the solution, there must be a better way to check if the imported data is valid or not when the import is being performed. 

I think, we could do something here in the Import.txs

```
export const Import: FC<Props> = ({ onImport }) => {
  const { t } = useTranslation('sidebar');
  return (
    <>
      <input
        id="import-file"
        className="sr-only"
        tabIndex={-1}
        type="file"
        accept=".json"
        onChange={(e) => {
          if (!e.target.files?.length) return;

          const file = e.target.files[0];
          const reader = new FileReader();
          reader.onload = (e) => {
            let json = JSON.parse(e.target?.result as string);
            onImport(json);
          };
          reader.readAsText(file);
        }}
      />

```

If there is any example conversation import data example format, then it would be easy to check, if the file being uploaded is valid. If you could provide the example, I could probably fix the issue and submit a PR. 

Anyway, thank you for this awesome project.

**Comment by KhanKudo** [comment]
For anyone else encountering this error, that doesn't have programming knowledge:

Open the dev-tools (F12-key) in chrome (or any other browser),
goto the application tab on the top,
expand the "Local Storage" submenu on the left,
select the first (and only) option,
select "selectedConversation" in the primary view,
hit the "Del" key, or right-click then Delete.

This will allow you to load the website without any errors or losing any data

Unfortunately the UI doesn't allow deleting chats without first selecting them, so you can either:
Clear all conversations
or
in the devtools, edit "conversationHistory" and remove the conversations causing issues.
Best if you copy the value into a text-editor to change it, then paste it back in.

Here is what that would look like:

![image](https://user-images.githubusercontent.com/37520008/232287474-04eb06fc-b63b-45f3-9f21-2cc3d4accaf0.png)

edit:
I have submitted a PR #579 that no longer displays those errors and allows the user to delete individual conversations causing issues, instead of having to clear all conversations.

**Comment by KhanKudo** [comment]
Also @vaghawan here is an example of a valid conversation object

Note that folderId can be null

``` json
{
    "id": "*************************************",
    "name": "Hello World",
    "messages": [
      {
        "role": "user",
        "content": "Hello World"
      },
      {
        "role": "assistant",
        "content": "Hello! How can I assist you today?"
      }
    ],
    "model": {
      "id": "gpt-3.5-turbo",
      "name": "GPT-3.5",
      "maxLength": 12000,
      "tokenLimit": 4000
    },
    "prompt": "You are ChatGPT, a large language model trained by OpenAI. Follow the user's instructions carefully. Respond using markdown.",
    "temperature": 1,
    "folderId": "*********************************************"
  }
```

**Comment by vaghawan** [comment]
Thank you @KhanKudo , and also thank you for the permanent fixes.

**Comment by KhanKudo** [comment]
The PR fixing the errors was just merged.
Whilst there are no checks for validity when importing json, the specific error mentioned in this issue has been resolved. If you feel that that is enough, feel free to close it.

**Comment by vaghawan** [comment]
Thank you, this should do it, but if you think the validation is needed as well, we could probably work on another issue.

**Comment by KhanKudo** [comment]
Whilst in the future it may be a good idea to let the user know the json is not valid, for now I do believe that preventing the major errors is enough.

**Comment by vaghawan** [comment]
> Whilst in the future it may be a good idea to let the user know the json is not valid, for now I do believe that preventing the major errors is enough.

Alright, I will try to work on the validation

**Comment by vaghawan** [comment]
Hi @KhanKudo , I sent a pull request [Import validation Added #668
](https://github.com/mckaywrigley/chatbot-ui/pull/668) , where I've added the needful validation and done some manual tests. 

Thanks

**Comment by KhanKudo** [comment]
Looks good @vaghawan

**Comment by ambareesh-jayakumari** [comment]
@vaghawan How does the import document work though?

**Comment by ambareesh-jayakumari** [comment]
How does one use the import data though? I wasn't even able to upload a legit json file (and it doesn't accept txt files)

**Comment by vaghawan** [comment]
the data that you need to import has to exactly similar with the data that you get when you export you data, so what I would suggest it, first export your histories, then do import. It should work. It should be a json file.
