### ISSUE TITLE
import document

### ISSUE THREAD

**Issue by Bitbitti** [mckaywrigley/chatbot-ui#573]
hello,
how do i upload a file so that gpt chat can use it as data?

**Comment by nattyraz** [comment]
> hello, how do i upload a file so that gpt chat can use it as data?

that a good question !!

**Comment by MJE43** [comment]
Langchain

**Comment by tobyarnett** [comment]
is there any more info about that? Langchain is very generic. Has this not been done where there is a guide or more info to how to incorporate that into this program? It seems having a function of ingesting files would be a given for a private server

**Comment by yayashuxue** [comment]
Any update on this? @MJE43 @tobyarnett
