### ISSUE TITLE
Chat history disappears after editing the initial message and submitting it.

### ISSUE THREAD

**Issue by ghost** [mckaywrigley/chatbot-ui#574]
https://user-images.githubusercontent.com/46987492/232258337-704f3262-ddbc-4393-b027-3e6eb4442cc4.mp4

**Comment by renatocron** [comment]
+1 

I just docker pulled to see if this was fixed, lost my text twice now, it's consistent behavior (at least when you edit while the text is still generating)

**Comment by yourbuddyconner** [comment]
This has been really annoying me, looks like @shemarlindie has a PR that addresses this!

**Comment by ghost** [comment]
PR #575 works good! @shemarlindie 👏
