### ISSUE TITLE
SyntaxError: Unexpected token D in JSON at position 1

### ISSUE THREAD

**Issue by hishtadlut** [mckaywrigley/chatbot-ui#580]
### Description
I'm getting a "SyntaxError: Unexpected token D in JSON at position 1" error while trying to parse JSON in my project. Upon investigating, I found that the issue is with the string "[DONE]" not being able to be parsed by `JSON.parse()`. To fix this, I added an if statement to handle this specific case.

### Steps To Reproduce
1. Attempt to parse the string "[DONE]" using `JSON.parse()`.
2. Check for syntax errors and observe the "SyntaxError: Unexpected token D in JSON at position 1" error.

### Proposed Solution
Handle this exception case in the code using an if statement before attempting to parse it: 
```
if (data === '[DONE]') {
    console.log('data', data);
} else {
    // normal parsing code
}
```

### Additional Information
I am behind a proxy server, which may potentially be causing this issue.

**Comment by andrezaycev** [comment]
+1 - also use api-gateway for api.openai

**Comment by moecly** [comment]
+1

**Comment by houyongsheng** [comment]
how to fix this?

**Comment by hishtadlut** [comment]
To fix this issue, update the `ReadableStream` in `utils/server`. Locate `const stream = new ReadableStream({` and add the condition `if (data !== '[DONE]')` before the `try-catch` block:

```javascript
const stream = new ReadableStream({
    async start(controller) {
      const onParse = (event) => {
        if (event.type === 'event') {
          const data = event.data;
          if (data !== '[DONE]') {
            try { /* original try-catch block */ } catch (e) {}
          }
        }
      };
      // ... rest of the code
  });

  return stream;
};
```

**Comment by pierrerognion** [comment]
> To fix this issue, update the `ReadableStream` in `utils/server`. Locate `const stream = new ReadableStream({` and add the condition `if (data !== '[DONE]')` before the `try-catch` block:
> 
> ```js
> const stream = new ReadableStream({
>     async start(controller) {
>       const onParse = (event) => {
>         if (event.type === 'event') {
>           const data = event.data;
>           if (data !== '[DONE]') {
>             try { /* original try-catch block */ } catch (e) {}
>           }
>         }
>       };
>       // ... rest of the code
>   });
> 
>   return stream;
> };
> ```

It works perfectly now. Thanks!
