### ISSUE TITLE
High CPU usage (only after upgrade?)

### ISSUE THREAD

**Issue by renatocron** [mckaywrigley/chatbot-ui#588]
Hello, I'm noticing during the responses, chrome start using 100% of cpu and the fans all run up. Were any recent changes to the tech stack that could indicate this behavior? eg: all CHAT being redraw each token received? If there's a way to add throttling to only update the screen a few times per second to save some battery

**Comment by anthonypuppo** [comment]
Was happening to me as well, resolved in #602.
