### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by thegeneth** [mckaywrigley/chatbot-ui#599]
I keep getting error with the main branch when I do google searches.

**Comment by agileben** [comment]
Digging into this a bit more it seems after using the google plugin the selectedConversation is set to an incorrect value somewhere. 
Some console logging in Chat.tsx shows it gets set to something crazy at some point but my react is not good enough to debug where this incorrect value is coming from:

Working:
selected conversation:  {id: '2a98be35-b912-4947-b3dd-1319daa5f005', name: 'New Conversation', messages: Array(3), model: {…}, prompt: 'You are a helpful chatbot. Respond using markdown.', …}

Broken:
selected conversation:  (updatedConversation, allConversations)=>{
    const updatedConversations = allConversations.map((c)=>{
        if (c.id === updatedConversation.id) {
            return updatedConversation;
        …
        
       
<img width="1092" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/306591/42c5f816-7057-4fde-99a0-1cb15db400f7">

**Comment by bartholomewbartkowski** [comment]
I've run a pull request, have a fresh setup, but I keep running into
`selectedConversation?.messages.length === 0`
chatbotui.com:
<img width="771" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/107932776/6adbfa18-2a05-45f5-9793-a9185b22f31e">
<img width="598" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/107932776/ad601d01-d02f-4344-8dd8-462821789c17">
and locally:
<img width="996" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/107932776/0b573b67-63a7-429c-943a-14ed856547f9">
<img width="977" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/107932776/11415a35-28d5-4948-8f70-24b938c8032e">
