### ISSUE TITLE
Table not displaying correctly

### ISSUE THREAD

**Issue by Ilanbeebey** [mckaywrigley/chatbot-ui#6]
Hello ! I tried to do a table by asking ChatGPT but it doesn't display the table, it displays the data. Look at the picture to see what I'm talking about. Thanks you !
![image_2023-03-18_141951573](https://user-images.githubusercontent.com/36510184/226108734-352fa6ee-3572-4945-b817-0311890ffef3.png)

**Comment by mckaywrigley** [comment]
Just to confirm, is that valid markdown syntax?

if it is it’s possible that I need to build a custom table component to render it correctly and will add it to the list.

How does it show up in regular ChatGPT?

**Comment by Ilanbeebey** [comment]
Thanks for the fast answer !
Here's what it should looks like :
![image_2023-03-18_142643346](https://user-images.githubusercontent.com/36510184/226109053-c8e1a1aa-3163-4e5a-895e-414ca8f5b1f8.png)

I went to [markdown doc](https://www.markdownguide.org/extended-syntax/) and saw that yes, it's a valid markdown syntax.

**Comment by mckaywrigley** [comment]
Thanks for sharing this. Very helpful.

I’ll add table support to my list and report back when it’s done.

**Comment by mckaywrigley** [comment]
Okay if you pull now it should a table showing correctly. I will look into better styling if it's not good enough.

**Comment by Ilanbeebey** [comment]
It's working ! It's good like that but if you want a better styling then just put borders and first row background color. Thanks you for your fast answer and push !
