### ISSUE TITLE
Any way to set proxy?

### ISSUE THREAD

**Issue by kilasuelika** [mckaywrigley/chatbot-ui#60]
I have a networking problem and it seems that I have to set a proxy. Message:

```
 [TypeError: fetch failed] {
  cause:  [ConnectTimeoutError: Connect Timeout Error] {
  name: 'ConnectTimeoutError',
  code: 'UND_ERR_CONNECT_TIMEOUT',
  message: 'Connect Timeout Error'
}
```

**Comment by mckaywrigley** [comment]
Unsure how to fix this. I’ll leave this open to see if someone else has any tips.

**Comment by wushuanger** [comment]
have the same problem

**Comment by frogchou** [comment]
docker logs show this problem

**Comment by gaoshilei** [comment]
I also encountered the same problem. The project is deployed on Linux and has already set up an HTTP proxy http://127.0.0.1:7890/, but the project still reports an error. Can I provide a proxy setting function in the project?

**Comment by gaoshilei** [comment]
I've encountered the same issue. The project is deployed on Linux and the http proxy http://127.0.0.1:7890 has already been set up. However, errors still occur. Does the project have a function for proxy settings?

**Comment by LiuCao** [comment]
I have the same needs

**Comment by ryanhex53** [comment]
This is happening because the client is attempting to fetch `/api/models`, but as far as I am aware, there is no corresponding server-side code to handle the request.

**Comment by ryanhex53** [comment]
This will cause all HTTP and HTTPS requests to go through the specified proxy server.

In Linux and macOS systems, you can set these environment variables using the following command:

```bash
export HTTP_PROXY=http://your-proxy-url:port
export HTTPS_PROXY=http://your-proxy-url:port
```

On Windows systems, you can set these environment variables using the following command:

```batch
set HTTP_PROXY=http://your-proxy-url:port
set HTTPS_PROXY=http://your-proxy-url:port
```

Replace `your-proxy-url` and `port` with your actual proxy server address and port.

After setting the environment variables, all HTTP and HTTPS requests in the Node.js runtime environment will go through the proxy server. It is worth noting that this approach can also be used in other languages and tools such as Python, Curl, etc.

**Comment by ryanhex53** [comment]
Doing this Before you run the server

Set Node.js behind a proxy

```bash
$ npm config set proxy http://localhost:3128
$ npm config set https-proxy http://localhost:3128
```

Delete proxy settings
```bash
$ npm config delete http-proxy
$ npm config delete https-proxy
```

**Comment by Jungley8** [comment]
Using the Docker environment variable OPENAI_API_HOST can help you.

**Comment by ryanhex53** [comment]
Setup a proxy server by using the following code:
```javascript
const http = require('http');
const https = require('https');
const { URL } = require('url');

const serverPort = process.env.PORT || 80;
const proxyURL = process.env.PROXY_URL || 'https://api.openai.com';

// Create an HTTP proxy server and handle client requests
const server = http.createServer((req, res) => {
  const url = new URL(proxyURL);
  req.headers.host = url.hostname;
  // Create a request to the actual target server
  const options = {
    host: url.hostname,
    port: url.port,
    path: req.url,
    method: req.method,
    headers: req.headers
  };

  // Choose HTTP or HTTPS protocol based on the URL protocol
  const protocol = (url.protocol == 'http:') ? http : https;
  const proxyReq = protocol.request(options, (proxyRes) => {
    // Forward the response received by proxy server to the client
    res.writeHead(proxyRes.statusCode, proxyRes.headers);
    proxyRes.pipe(res);
  });

  // Listen to the response from the target server connected by the proxy server and return it to the client
  req.pipe(proxyReq);
});

// Listen to the port of the proxy server
server.listen(serverPort, () => {
  console.log(`Proxy server is listening on port ${serverPort}`);
});
```
Then set environment variable OPENAI_API_HOST to `http://<your-proxy-server-ip>`

**Comment by LiuCao** [comment]
> Using the Docker environment variable OPENAI_API_HOST can help you.
源码全局一搜索，里有还真有这个环境变量。 👍 👍 👍 👍

**Comment by outp1** [comment]
I could try to add a connection through the proxy server function using pull request. It would be more convenient than the solutions above.

**Comment by yuhr123** [comment]
Here is a simple method to configure a reverse proxy for `https://api.openai.com` using [Caddy](https://github.com/caddyserver/caddy). First, install Caddy on your cloud server and bind a domain name to the server, such as `example.com`. Then add the following configuration to the Caddyfile:

```
example.com {
  reverse_proxy /* https://api.openai.com {
    header_up Host api.openai.com
    header_up X-Forwarded-Proto {scheme}
    header_up X-Forwarded-For {remote}
  }
}
```

Restart Caddy service, you can use `https://example.com` to send requests to the OpenAI API.  As for Chatbot-UI, you can add `OPENAI_API_HOST=https://example.com` in the `.env.local` file to set up it.

**Comment by windysnows** [comment]
> Setup a proxy server by using the [this code](https://gist.github.com/ryanhex53/665588cd45ade46683c1ad2a27084592):
> 
> Then set environment variable OPENAI_API_HOST to `http://<your-proxy-server-ip>`

how to use this proxy.js,which releative path can set it?

**Comment by DengFist** [comment]
Have you solved it yet?

**Comment by frogchou** [comment]
I deployed this project using Docker. I accessed the OpenAI API from a server in the United States while I was in mainland China. Before that, I tried to use an HTTP proxy on my Linux server in China, but it failed. So, I used Nginx to configure a reverse proxy on my server in the United States. Therefore, I did not directly use https://api.openai.com/, but instead used my own server's domain, http://mydomain.com/.

First, I built a local image using the command "docker build chatgpt-ui:4.12 .". Then, I created a container using the command "docker run -itd -e OPENAI_API_KEY=skXXXXXXXXX -e OPENAI_API_HOST=http://mydomain.com/ -p 3100:3000 --name openai-chat chatgpt-ui:4.12". However, it still did not work. When I entered a question in the chat interface, there was no response.

So, I used the command "docker exec -it openai-chat sh" to enter the container and searched for all content related to https://api.openai.com/ in the project. I replaced them all with http://mydomain.com/ and then restarted the container. It worked properly after that. I am not familiar with script languages, so I had to make these changes in a rough way. However, there are still many issues in the project, and I am looking forward to the author's improvements.
