### ISSUE TITLE
chatbot-ui not working 

### ISSUE THREAD

**Issue by HMMubashar** [mckaywrigley/chatbot-ui#604]
I deploy live version on vercel and using it from one month , but from yesterday chatbot-ui is not working , showing an popup of red-cross like this
![image](https://user-images.githubusercontent.com/48956846/232931439-3f974608-8b46-4455-8856-a627e40fcda0.png)
even i change the Api key , i again deploy the new version ,, Also Temprature line is not working..

what is the solution?

**Comment by andy7076** [comment]
+1

**Comment by johnnyhaggs** [comment]
+1, although it is my first time deploying so I wasn't sure if it was user error or not.
