### ISSUE TITLE
Is it possible to add Google analytics to facilitate viewing of page usage

### ISSUE THREAD

**Issue by mindcont** [mckaywrigley/chatbot-ui#608]

**Comment by solid-pixel** [comment]
Can't you just add your GA script to the `<head>` yourself?

**Comment by Designdocs** [comment]
Please refer to Google Docs to add yourself.

**Comment by mindcont** [comment]
Thanks for the reply, I'm a rookie, I've only reached the level of application deployment, I don't know how to make changes on that page, let me try it, forget about it
