### ISSUE TITLE
Code block copy button obscuring code.

### ISSUE THREAD

**Issue by Maxiviper117** [mckaywrigley/chatbot-ui#61]
![image](https://user-images.githubusercontent.com/11472492/226879238-0260ff4c-f43b-47ea-a089-b554ac357382.png)

**Comment by mckaywrigley** [comment]
Will fix.

**Comment by saliksik** [comment]
> Will fix.

Please also include a copy button on the mermaid codes. Thank you!
![Screenshot (273)](https://user-images.githubusercontent.com/122975898/226902856-c00b1da2-d974-45cb-a69b-738762210a9b.png)

**Comment by mckaywrigley** [comment]
Fixed.
