### ISSUE TITLE
ChatGPT 4 not working?

### ISSUE THREAD

**Issue by afern247** [mckaywrigley/chatbot-ui#611]
![image](https://user-images.githubusercontent.com/34192856/233079736-06ca3f99-e11d-4d9a-8140-c6cc4b581b5f.png)

**Comment by afern247** [comment]
How can I check if the api key is for chatgp4? I remember getting access to the 4

**Comment by jonatansberg** [comment]
I'm seeing the same type of responses in the playground as well. Sometimes it says 3, other times 3.5-turbo.

<img width="1403" alt="Screenshot 2023-04-19 at 15 30 05" src="https://user-images.githubusercontent.com/58557/233090453-a1f92af6-c678-4bd3-9c8b-d5055f80aab4.png">

**Comment by afern247** [comment]
oh that's interesting. Yeah it just gave me an answer that gpt3 would not do. Thanks for confirming.
