### ISSUE TITLE
High Cost

### ISSUE THREAD

**Issue by afern247** [mckaywrigley/chatbot-ui#613]
Am I the only one that notices a high cost in this? I used the other day an auto-agent and it was not nearly as expensive as this one. I've executed with chatbot-ui like 20 requests and it's already in $1.46. Is this normal? I wonder if there are more requests under the hood happening.

**Comment by MalTarDesigns** [comment]
Yes, I am feeling the same way. I was working with another app doing to same level of testing with gpt 3 and the cost seems higher when I started working on this app. We should look into this to try to reduce cost.

**Comment by ghost** [comment]
You can estimate the total token for any given chat completion request using [Tokenizer ](https://platform.openai.com/tokenizer) and compare it with data from [API usage breakdown](https://platform.openai.com/account/usage), they should be roughly the same.

Or even better: send the same content through [OpenAI Playground](https://platform.openai.com/playground) and through Chatbot-UI and then compare each request usage breakdown.

**Comment by MikeBirdTech** [comment]
After a relatively short conversation, I was receiving an error for exceeding the ~8k token limit. The most recent message was quite short, maybe the entire conversation in the prompt?

**Comment by ghost** [comment]
Yes, the entire conversation is part of the prompt. this is expected.
