### ISSUE TITLE
Why My Chat-bot is not working or showing Red cross popup ? Temperature feature also not working. @mckaywrigley

### ISSUE THREAD

**Issue by HMMubashar** [mckaywrigley/chatbot-ui#621]
![image](https://user-images.githubusercontent.com/48956846/233473531-7b7af082-f99e-475b-aaeb-9ce9796acb37.png)
I am using from last month , but from yesterday it is not working , even I deploy new version and put API key, also temperature feature also not working ?  what could be the possible solution? @mckaywrigley please lookup

**Comment by NayyabRajoopt** [comment]
+1

**Comment by binbugs** [comment]
Have you solved this problem yet ？

**Comment by HMMubashar** [comment]
No I tried Different account or different API key but problem did not solved..
Are you facing same issue??

**Comment by binbugs** [comment]
> No I tried Different account or different API key but problem did not solved.. Are you facing same issue??

My problem is exactly the same as yours. I suspect that my account balance is insufficient, but I do not have a foreign credit card to pay. From your situation, it seems that the balance is not insufficient

**Comment by HMMubashar** [comment]
No its not mandatory to have plus account, I create new account with Open AI and Use that key , but the error is same,, One of mine friend still using the old version of Chatbot-Ui and have not pus account , his chatbot is still working fine...but mostly this error is occurring now.

**Comment by SpinnerCode7** [comment]
> No its not mandatory to have plus account, I create new account with Open AI and Use that key , but the error is same,, One of mine friend still using the old version of Chatbot-Ui and have not pus account , his chatbot is still working fine...but mostly this error is occurring now.

how i solve this
