### ISSUE TITLE
editing previous prompt and click "Save & Submit" make prompt disappear and get lost 

### ISSUE THREAD

**Issue by mauga** [mckaywrigley/chatbot-ui#622]
editing previous prompt and click "Save & Submit" make prompt disappear and get lost with no response
chrome on windows 10 with italian locale, published on vercel

**Comment by ghost** [comment]
Have you tried updating to the last release? this issue should have been fixed by now: #575

**Comment by mauga** [comment]
ok, i have updated the deploy with latest commit, the problem is fixed.
