### ISSUE TITLE
Any tutorial for non-tech guys on how to use Chatbot UI? I am getting an error.. video link provided

### ISSUE THREAD

**Issue by viraj21283** [mckaywrigley/chatbot-ui#623]
Hi, any tutorial for non-tech guys on how to use Chatbot UI? I updated the API key but still getting some errors.. https://mega.nz/file/l8cgxZha#MUKFb18Tvd-QDtIyh2JgTHbWz_eDA0BE94pLcEF7oJg

**Comment by seanchito** [comment]
It has to be a problem with the API key.   That site works fine.
