### ISSUE TITLE
[Feature Request]: Set Several Default Prompts on right side panel, cause it's more convinent when using on different Devices

### ISSUE THREAD

**Issue by tiwentichat** [mckaywrigley/chatbot-ui#629]
On the right panel, if there are several  default prompts, that would be better when we using Chatbot-UI indifferent devices, like laptop and iPhone. 

Now, the prompts on right side could only in local memory of browser on lap top or pad and iPhone, every prompt would be added three times...

Wish For Mckay's kindness to add this feature

**Comment by upasch** [comment]
An option to use supabase to authenticate a user (e.g. by using magic link) and store prompts and chats in the PG Database for each user would be cool.
