### ISSUE TITLE
Where and how is the data saved?

### ISSUE THREAD

**Issue by extralsc** [mckaywrigley/chatbot-ui#630]
Just too clarify, where and how is the data saved on handled from api to server?

**Comment by upasch** [comment]
Currently in the local data memory of your browser

**Comment by extralsc** [comment]
> Currently in the local data memory of your browser

Thanks for reply. Could you help me find the file/row number where this is set? Otherwise i will start looking into the code.

**Comment by afern247** [comment]
Wait so if I clean the cookies all my prompts and chats are lost???

**Comment by upasch** [comment]
Export your Chats and Prompts and try it out ;)

**Comment by afern247** [comment]
@upasch exporting the chats means manual intervention and remembering this. Can we save all the stuff in a small db locally? This would be a great feature.

**Comment by upasch** [comment]
The data is saved in the memory of your browse on your harddisk together with a cookie. The export function is saving the data into a json file on your harddisk. To have the data available everywhere, first you need a login function and a database related to the user. I forked the project and implemented a login function using Supabase. Next idea is to save the chats and prompts in a database at Supabase.

**Comment by afern247** [comment]
Can you share your implementation please? I'd love to have this hosted on my own server and pick up the prompts/chat from any device.

**Comment by upasch** [comment]
> Can you share your implementation please? I'd love to have this hosted on my own server and pick up the prompts/chat from any device.

Of course. This one uses Supabase for Authentication. I made it quite simple and used the auth-helpers provided by Supabase. But be aware, this is not the current version of Chatbot-Ui, because McKay restructured the code so you will not be able to merge with the current repo of chatbot-ui! Here you go: https://github.com/upasch/g5-chatbot-ui

**Comment by upasch** [comment]
> Can you share your implementation please? I'd love to have this hosted on my own server and pick up the prompts/chat from any device.

Btw, chat and prompt database is not realized yet!. Currently it only provides the authentication, so you are able to use it with a team or family. 

If you want to use it with Vercel, the first think you should do, is forking the repo into your own repo!
Also you need to provide the keys in the .env.local file with your own values:
OPENAI_ORGANIZATION=
OPENAI_API_KEY=
DEFAULT_MODEL=gpt-3.5-turbo

# SUPABASE Credencials
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=

**Comment by upasch** [comment]
I do not have plenty of time at the moment to work on that project. Also I will try to implement the Supabase auth into the restructured repo of Chatbot-Ui, so one can always merge new functions by merge the projects.

**Comment by afern247** [comment]
Thanks for sharing, I'll wait for when you add the new auth to this one otherwise it'll become a pain to merge new changes. I appreciate it!

**Comment by LanceHaverkamp** [comment]
I see no option to export prompts, at least on the public website.  Is it behind, or ???
