### ISSUE TITLE
Error using the Google Plugin

### ISSUE THREAD

**Issue by upasch** [mckaywrigley/chatbot-ui#631]
I setup the requirements as described in the docs. Also checked via console.log in /components/Chat/Chat.tsx file. Everything' works but as soon I use the Google Plugin I got the following error: 'TypeError: selectedConversation.messages is undefined' in line 399 and an additional error/timeout in the console: 'Error: Request timed out
    at Timeout.eval [as _onTimeout] (webpack-internal:///(api)/./pages/api/google.ts:35:87)' 

Any ideas to solve that problem?

**Comment by aribo** [comment]
I have the same error. 

```
Unhandled Runtime Error

TypeError: selectedConversation.messages is undefined
Source

components/Chat/Chat.tsx (399:13) @ selectedConversation

  397 |   onScroll={handleScroll}
  398 | >
> 399 |   {selectedConversation?.messages.length === 0 ? (
      |   ^
  400 |     <>
  401 |       <div className="mx-auto flex flex-col space-y-5 md:space-y-10 px-3 pt-5 md:pt-12 sm:max-w-[600px]">
  402 |         <div className="text-center text-3xl font-semibold text-gray-800 dark:text-gray-100">
```
I haven't looked at it in detail. A problem with the variable selectedConversation.

**Comment by Jackyxiaocc** [comment]
I have the same error.

**Comment by Designdocs** [comment]
The same similar error will appear when I use it on chatbotui.com.

And the browser console reported an error. #502

**Comment by Jackyxiaocc** [comment]
你好，我已经收到您的邮件了，谢谢。

**Comment by dillchen** [comment]
Same error

**Comment by Jackyxiaocc** [comment]
你好，我已经收到您的邮件了，谢谢。
