### ISSUE TITLE
temperature is lost between sessions 

### ISSUE THREAD

**Issue by mauga** [mckaywrigley/chatbot-ui#633]
setting temperature at start of chat work until browser window is closed, opening new window show last chat, but the temperature is always set to 1 even if it was set to a different value

you can visit the deploy at https://chatbot-ui-mauga.vercel.app/

**Comment by nousolve** [comment]
close this issue to open new, more focused issue

https://github.com/mckaywrigley/chatbot-ui/issues/662

**Comment by mauga** [comment]
closing
