### ISSUE TITLE
how to use plugin？

### ISSUE THREAD

**Issue by houyongsheng** [mckaywrigley/chatbot-ui#635]
I  add the  keys,but nothing happend when I prompted, even errors.

**Comment by rpallas** [comment]
If plugin keys are set, there should be a lightning bolt icon on the left side of the prompt which lets you select between Chat GPT and Google Search.

Be aware there are some open issues relating to it. See #537 #565 and #631

For me, it only works when providing the plugin keys via environment variables

**Comment by UmutAlihan** [comment]
thank you! @rpallas
