### ISSUE TITLE
History doesn’t sync across devices

### ISSUE THREAD

**Issue by trialskid** [mckaywrigley/chatbot-ui#636]
Hello

I am running this on an Unraid server. 

My chat history doesn't sync across my devices. I'm not sure if this is by design or not

if it is by design, would there be any way to have the option to save the history server side?

Thanks

**Comment by SyedMuzamilM** [comment]
Right now all the conversations are stored locally on the browser.  

I am not sure if we will be implementing the syncing feature but that will be an interesting thing to do.

**Comment by KickingAss2024** [comment]
I also use Unraid and was planning to add this. May I know if there is an app you used? Have you discovered a solution to the chat history not syncing?

**Comment by dongphuchaitrieu** [comment]
> Right now all the conversations are stored locally on the browser.  
> 
> I am not sure if we will be implementing the syncing feature but that will be an interesting thing to do. 

Please make it!

**Comment by KickingAss2024** [comment]
Yes please make it

**Comment by jtfidje** [comment]
I would also really like this feature. Maybe it could be a setting that one could toggle on or off?
