### ISSUE TITLE
How to not input API key

### ISSUE THREAD

**Issue by matsu11111111** [mckaywrigley/chatbot-ui#637]
Resolved. Our apologies. Please remove this issue.

**Comment by p-zhan** [comment]
what's PW?

**Comment by shuuuuuuu1111** [comment]
I would like to make the OpenAI APIkey not open, but instead of APIkey, if you enter for example user1, it will be converted to APIkey internally and made available to you.

**Comment by shuuuuuuu1111** [comment]
Resolved. Our apologies. Please remove this issue.

**Comment by SyedMuzamilM** [comment]
You can close the issue yourself.
