### ISSUE TITLE
How to deploy this to a Linux server

### ISSUE THREAD

**Issue by haodaohong** [mckaywrigley/chatbot-ui#639]
Hi all, I'm new to learn this, I just run command "npm run build" and get a '.next' folder, then I put this folder into server, but cannot work, could you help me for this, thanks so much!

**Comment by lameTookan** [comment]
tip: copy and paste the entire readme into chatgpt(or whatever platform that allows you to talk to gpt4). Ask it for a comprehensive step by step guide to get it running on whatever linux distro your server is running. If anything goes wrong ask it and paste in any errors you are getting.

**Comment by haodaohong** [comment]
> tip: copy and paste the entire readme into chatgpt(or whatever platform that allows you to talk to gpt4). Ask it for a comprehensive step by step guide to get it running on whatever linux distro your server is running. If anything goes wrong ask it and paste in any errors you are getting.

thanks for your good suggestion！

**Comment by hubingzhong123** [comment]
I Create a .env.local file in the root of the repo with my OpenAI API Key, I still need to fill in my OpenAI key on the page，what should I do to solve this problem?
