### ISSUE TITLE
Deploy to Vercel button deploys old Chatbot UI Lite

### ISSUE THREAD

**Issue by xoelop** [mckaywrigley/chatbot-ui#64]
How would I deploy the new version? This is what I see when following the Deploy to Vercel button

![image](https://user-images.githubusercontent.com/8508402/226903509-48fc155e-7091-4673-b638-4652dc1e09b0.png)

**Comment by mckaywrigley** [comment]
This bug was fixed recently.

Did you use an old local version of the link?

The one on the readme right now should be correct.
