### ISSUE TITLE
CHAT BOT UI SUPPORTS NOT chat gpt 4

### ISSUE THREAD

**Issue by cybermike3332** [mckaywrigley/chatbot-ui#643]
CHAT BOT UI SUPPORTS NOT chat gpt 4 on umbrel node

**Comment by spullara** [comment]
It does support it:

https://github.com/search?q=repo%3Amckaywrigley%2Fchatbot-ui%20gpt-4&type=code

**Comment by reconrad48** [comment]
can confirm it uses gpt-4, should be a drop down at the top of your gui.

**Comment by cybermike3332** [comment]
Hi there,
in the gui drop down is only 3.5 to choice!

Kind regards / Mit freundlichen Grüßen

Michael Gehrmann-Gacasa

skype: cybermike3332

**Comment by xaperret** [comment]
@cybermike3332 It's probably due to the fact there is still a waitlist. So if you are not in I supposed you don't have the option to select it.
https://openai.com/waitlist/gpt-4-api

**Comment by reconrad48** [comment]
yeah you would think that goes without saying, but apparently maybe not.. if you don't have access to GPT4 API then you will not have access in chatbot ui either
