### ISSUE TITLE
My apologies but I am missing a step here... 

### ISSUE THREAD

**Issue by reconrad48** [mckaywrigley/chatbot-ui#647]
since there isn't a discussion option, guess I'll post here. 

Unfortunately the instructions are really vague, but I know that's from the perspective of someone who isn't a programmer nor have ever used docker. I've used vmware, virtualbox, etc, but not docker. 

Anyway, I can run this just based on the cloned repo... after changing/adding a few variables. However, I assume the objective is to have this run in a docker container, so I started that process, and within Docker, I started the server but can't connect  to it, so I figured I a missing a step. Looked over "pull from ghcr:" and I don't know what "docker run -e OPENAI_API_KEY=xxxxxxxx -p 3000:3000 ghcr.io/mckaywrigley/chatbot-ui:main" means, because the API is already local in the file it's supposed to be.. 

I mean again, I can get this to run without building a docker image... just by running the  npm run dev command... however, is that "one" of the ways to run this? Sounds like that way is far less secure? I already had my openai API hijacked once by one these github projects. What is the best practice for setting this app up locally and contained so that I am not accidently push my api key? Is "Build locally" a prerequisite for "run locally?" 

Also, Visual Studio Code keeps offering to install extensions that appear to supplement the full docket desktop, can VSC basically handle everything through extensions without the need for a full docker install?

_Also, now I am seeing "chatbotui.com" as well... is that meant only for demo, or are we permitted to use it freely?_ 

Thank you in advance

**Comment by mbronze** [comment]
To start the project, first clone the repository. Then, navigate to the **chatbot-ui** folder and run the command:
_sudo docker-compose up -d_
This command will build and start the server. Once it finishes, you can access the application by browsing to http://localhost:3000 in your web browser. The application should be up and running.

**Comment by mbronze** [comment]
Btw don't forget to:
Provide OpenAI API Key
Create a **.env.local** file in the root of the repo with your OpenAI API Key:

OPENAI_API_KEY=YOUR_KEY

**Comment by reconrad48** [comment]
thanks, I think I got it right a while back...
