### ISSUE TITLE
Suggestion: Saveable System prompts

### ISSUE THREAD

**Issue by Maxiviper117** [mckaywrigley/chatbot-ui#65]
Currently, you have a default system prompt that resets with every new chat.

Having the ability to store and utilize our own customized system prompts within the interface would be an extremely valuable addition. This would allow a user to reuse prompts based on the specific behaviour we desire from GPT in a given thread. Instead of re-typing a new system prompt each time.

![image](https://user-images.githubusercontent.com/11472492/226907918-ab8aa297-cbe7-4ca9-83a8-2ca7e5feae22.png)

**Comment by mckaywrigley** [comment]
This weekend will introduce the prompt system. Stay tuned...

**Comment by Maxiviper117** [comment]
#229
