### ISSUE TITLE
openaierror: you most provide a model parameter

### ISSUE THREAD

**Issue by FabsHazard** [mckaywrigley/chatbot-ui#656]
When i ask something it just doesn't work and it says this: event - compiled successfully in 81 ms (53 modules)
 [OpenAIError: you must provide a model parameter] {
  name: 'OpenAIError',
  type: 'invalid_request_error',
  param: null,
  code: null
} 
Help please:)

**Comment by JK-Wang** [comment]
after i update code, i encounter the same problem
i already config `DEFAULT_MODEL=gpt-3.5-turbo` in `.env.local`
need help too :(
