### ISSUE TITLE
Feature Request: scrap urls to get context from it

### ISSUE THREAD

**Issue by fredy-mederos** [mckaywrigley/chatbot-ui#66]
Sample:
While chatting with the bot, the user can add a url for an article or a code on github, the chat-bot could identify there is an url, scrap it and extract the contents and use it as context for the chat.

**Comment by seanchito** [comment]
Someone's got a slackbot doing that.    

https://github.com/alex000kim/slack-gpt-bot

**Comment by thomasleveil** [comment]
could be done with #123

**Comment by mckaywrigley** [comment]
Going to support plugins that will do this in April.
