### ISSUE TITLE
How disable these options from being changed?

### ISSUE THREAD

**Issue by hlayiso** [mckaywrigley/chatbot-ui#663]
Hi how to disable the changing of System promt, model and temperature?

Check this screenshot: https://ibb.co/8Yswf5N

I don't want user to change the settings i want to keep the settings as the ones I've set on .env.local i don't want them to be changed.

**Comment by seanchito** [comment]
the easiest would be to find the div with all those settings in Chat.tsx and hack it out.   Then nobody can change stuff.

**Comment by jmagly** [comment]
the default comes from a config file, look for the string its using and you can wipe it out. Note that in the current version your system prompt is a powerful setup. If you are creating a role or a large line of convo you will want to start in that system prompt as the messages in-chat are all much less effective user prompts.
