### ISSUE TITLE
It seems there's no syntax highlighting for zsh?

### ISSUE THREAD

**Issue by allbutone** [mckaywrigley/chatbot-ui#67]
<img width="784" alt="image" src="https://user-images.githubusercontent.com/4219875/226911153-142bdeb9-9e40-4c67-9e14-2ea3e97e83d8.png">

**Comment by mckaywrigley** [comment]
Our syntax highlighter must not support it. Looking at OpenAI's and it looks like theirs doesn't either.

What would you expect it to look like? Any examples would help! :)

**Comment by Maxiviper117** [comment]
I see you are using Prism, is there maybe not way to create some sort of alias to trick it into looking like another lang, zsh is similar to bash.

Im also noticing this with MQL5 trading lang (based on C++).

**Comment by Maxiviper117** [comment]
This could be useful if combined with my suggestion #65

Where we could prime the system to by telling it to always use a certain markdown code block directive for all code blocks unless otherwise stated.
