### ISSUE TITLE
[Feature Request x2] Place "OpenAI Key and Plugin Key" into settings & Intergrate more Generative AIs

### ISSUE THREAD

**Issue by GamingNerdLeith** [mckaywrigley/chatbot-ui#670]
### **Feature Request: Place "OpenAI Key/Plugin Key" & "Import/Export Data" into settings**
The space for all of the chat is very limited as seen in [Figure 01 - ChatBotUI Interface Design](https://user-images.githubusercontent.com/67237948/235321991-5d293324-cbf5-415b-a4d5-4472da7d5fd9.png) when compared to the OpenAI website as seen in [Figure 2 - OpenAI Interface Design](https://user-images.githubusercontent.com/67237948/235322211-c5d3db8f-0ff6-4801-b3a9-bc55e97d096d.png) if you use ChatBotUI alot (which I do) you will notice that the space for chat is very limited and just with a few chats and folders. This is very bad UI/UX design and it can quickly become tedious (and annoying) constantally scroll up and down, to fix this issue move "OpenAI Key", "Plugin Key", "Import Data" and "Export Data" into settings, this saves alot of space which then can be occupied by the different chats and folder, as shown in [Figure 03 - Showing the amount of space saved](https://user-images.githubusercontent.com/67237948/235322380-dbdd6047-1e18-45ed-80e0-3386201253ef.png) highlighted in green is the amount of area that would've been saved if "OpenAI Key", "Plugin Key", "Import Data" and "Export Data"  were moved into settings. Additionally OpenAI Key/Plugin Key and Import Data/Export Data can be placed into seperate catagories within settings to show the user that these buttons are linked (or do simular things) as seen in [Figure 04 - Potential Catagories within Settings](https://user-images.githubusercontent.com/67237948/235322738-6613e6b6-9277-4a6f-8278-dee7bdab93b7.png) 

### **Feature Request: Intergrate more Generative AIs such as Open Assistance or Google's Bard**
With the emergance of several generative AI technology such as Bard by Google and the truly open source Open Assistance, ChatBot UI can have a huge potental if all of these AI technology gets impleneted into ChatBot UI as it would allow the user to experement with different AI technology in the same tab and with the same UI. Without having to constantally be changing the UI interface when using a different AI model. The user can become familar to the quite good UI interface of ChatBot UI and still enjoy using the other AI models and would make this project truly useful as currently it is kind of useless because you can just use OpenAI interface which is currently superior. 

Edit: Fixed Figure 04 Link as it was incorrect

**Comment by pdgxiaofei** [comment]
I completely agree with your thoughts. The current UI is too complicated and looks oppressive. Since it is a replica of OpenAI, I think it should be consistent with OpenAI. Thank you.

**Comment by jmagly** [comment]
should be done, there needs to be some more cleanup and separation of concern at the UI/Control layer. there are API paths embedded in the files. Once its pulled apart more cleanly; giving a model selector, even on a per-message basis is possible

**Comment by pascalwhoop** [comment]
I support this endeavour, with Claude, PaLM, Cohere and potentially dozens of self hosted models, this could turn into a bit of a low-code IDE for enterprises if the cards are played right. I'd let go of the ChatGPT immitation, no one said the UI needs to be the same as that of OpenAI, they have no authority on having "the right" UI IMO.
