### ISSUE TITLE
Feature Request: Allow to reply to messages to add context to the chat

### ISSUE THREAD

**Issue by fredy-mederos** [mckaywrigley/chatbot-ui#68]
Sample:
When chatting in a long thread, it can happen that we need some clarifications or we have any question about old messages in the same thread, currently we must copy the whole content go down and ask the chat again and paste the copied text.

With a reply feature we can easily click on "reply" and down in the chat we just ask another question adding the replied text content internally and automatically as part of the context.

**Comment by mckaywrigley** [comment]
I have some ideas around this. Currently exploring a tree-like system. Will keep this open and come back with ideas.

**Comment by rsaisankalp2** [comment]
> Something to have in mind here is that with Chat-GPT4 api you probably won't need this as it will handle way larger amounts of text

how to enable gpt4 , there is no option
