### ISSUE TITLE
Google CSE API

### ISSUE THREAD

**Issue by othmanelhoufi** [mckaywrigley/chatbot-ui#683]
Hi all,

Thanks for this amazing UI.
I tried to use the Google API for prompt search, I created both Keys, but I still get a "POST 500 ERROR" from google API, maybe I'm using it wrong.
Can someone please explain how to setup the Google Keys?

**Comment by jorge-menjivar** [comment]
I have a fix in my fork. It is several dozen commits ahead of this repo, so I don't want to make a pull request.

[https://github.com/jorge-menjivar/chatbot-ui/tree/plugin_keys](https://github.com/jorge-menjivar/chatbot-ui/tree/plugin_keys)

**Comment by jairodriguez** [comment]
I

> I have a fix in my fork. It is several dozen commits ahead of this repo, so I don't want to make a pull request.
> 
> https://github.com/jorge-menjivar/chatbot-ui/tree/plugin_keys

I`m running your version in vercel with google API and csd keys in environment variables and still get a 500? Any ideas?

**Comment by jorge-menjivar** [comment]
@jairodriguez Vercel has a 10 seconds timeout for serverless functions in the hobby plan. The google plugin will throw a 504 because it needs more time than that to execute. Are you sure you are getting a 500 and not 504?

[source](https://vercel.com/docs/concepts/limits/overview)

**Comment by jorge-menjivar** [comment]
@jairodriguez If you get a 500 response back in less than 10 seconds, then double check your client id and client key for the plugin.

**Comment by jairodriguez** [comment]
You are correct, it`s a 504, and that makes total sense as search works fine running the local copy, I`ve been banging my head with the lack of search functionality for a while. Thank you for the heads-up and the excellent contributions!

**Comment by walter-grace** [comment]
> @jairodriguez If you get a 500 response back in less than 10 seconds, then double check your client id and client key for the plugin.

How do you find the key for the GSE ID:  I cant tell if my keys arent working or if the plugin takes too long

**Comment by nosehair** [comment]
I have the same problem. Think this has been fixed in one of the pull
requests but doesn't look like anyone plans on maintaining this regularly.
There are other similar repos which get regular updates. Try one of those

**Comment by walter-grace** [comment]
> 

Do you happen to know or Have a link to those ones? It be amazing for someone to create a tutorial on how to use this plugin
