### ISSUE TITLE
issue about not getting reply back from GPT even though before that it was worked perfectly 

### ISSUE THREAD

**Issue by MrAlaminH** [mckaywrigley/chatbot-ui#690]
![image](https://user-images.githubusercontent.com/88797912/235835932-66acb743-9bd4-4816-8daa-249053864c45.png)

check that red error icon. There is no warning message btw

**Comment by MrAlaminH** [comment]
![image](https://user-images.githubusercontent.com/88797912/235837595-880b8484-391a-4da7-9abf-0d82614fca6c.png)


oh i see the problem now, but you guys should add an error message so that users can understand this simply,

**Comment by jorge-menjivar** [comment]
Are you still able to get the response message, status code, etc? This would help us implement the user error message. Thanks

**Comment by Its-Alamin-H** [comment]
I haven't repurchased the API to try again, as my free trial expired. but I believe it would be beneficial if you could add a message in the designated location highlighted by the red arrow, indicating that your API has expired. This would help us identify and troubleshoot the issue more efficiently, or alternatively, if there is any other message that accurately reflects the underlying problem, it would be helpful to include that as well.

**Comment by Its-Alamin-H** [comment]
> Are you still able to get the response message, status code, etc? This would help us implement the user error message. Thanks



> Are you still able to get the response message, status code, etc? This would help us implement the user error message. Thanks

I haven't repurchased the API to try again, as my free trial expired. but I believe it would be beneficial if you could add a message in the designated location highlighted by the red arrow, indicating that your API has expired. This would help us identify and troubleshoot the issue more efficiently, or alternatively, if there is any other message that accurately reflects the underlying problem, it would be helpful to include that as well.

**Comment by MrAlaminH** [comment]
> Are you still able to get the response message, status code, etc? This would help us implement the user error message. Thanks

I haven't repurchased the API to try again, as my free trial expired. but I believe it would be beneficial if you could add a message in the designated location highlighted by the red arrow, indicating that your API has expired. This would help us identify and troubleshoot the issue more efficiently, or alternatively, if there is any other message that accurately reflects the underlying problem, it would be helpful to include that as well.

**Comment by jorge-menjivar** [comment]
It’s even better that you haven’t repurchased. Can you maybe show us what error you get (in the dev console) ? That way I can implement the proper warning on the user side
