### ISSUE TITLE
OPENAI_API_KEY 

### ISSUE THREAD

**Issue by huoshicang** [mckaywrigley/chatbot-ui#692]
I set environment variable: OPENAI_API_KEY when I deploy, when I open the address where the deployment is finished, I still need to set: OPENAI_API_KEY, what should I do when such a problem occurs?

**Comment by xeor** [comment]
You will need to provide more info and some examples. There are many people doing this already, so it might be a configuration error. How do you start chatbot-ui, what output do you get and so on.. As much info as possible.

**Comment by ALXRITR** [comment]
I have the same issue.
i entered the API-Key in "[.env.local.example]" - was this right?
i directly deployed in vercel

**Comment by ALXRITR** [comment]
https://github.com/mckaywrigley/chatbot-ui/issues/501

**Comment by tunganhem2018** [comment]
You need to rename to .env.local
