### ISSUE TITLE
error: maximum context length is 4097 tokens.

### ISSUE THREAD

**Issue by ricardodacosta** [mckaywrigley/chatbot-ui#693]
[Keep getting this error. This model’s maximum context length is 4097 tokens.

**Comment by reconrad48** [comment]
do you have openai access to gpt4?

**Comment by jorge-menjivar** [comment]
Should be fixed by #672. In the meantime, you can use my fork since it is taking a while to merge pull requests here.

**Comment by ricardodacosta** [comment]
Thank you! how do I update to latest version from terminal? 

or do I have re-install using

git clone https://github.com/mckaywrigley/chatbot-ui.git

?

**Comment by ricardodacosta** [comment]
@jorge-menjivar Do I install your fork by using git clone https://github.com/jorge-menjivar/chatbot-ui ? 

If i do so, my guess is I will loose all my conversations/folders I have been using with his the past 30 days or so?

**Comment by jorge-menjivar** [comment]
It would be easier to clone [https://github.com/jorge-menjivar/chatbot-ui/tree/token_limit_fix](https://github.com/jorge-menjivar/chatbot-ui/tree/token_limit_fix) than trying to merge everything. Since my repo is several commits ahead of the original

**Comment by jorge-menjivar** [comment]
You should not lose any information, but I would say export the data before hand

**Comment by jorge-menjivar** [comment]
You can also use the main branch, it is a bit more polished

**Comment by ricardodacosta** [comment]
It says

Cloning into 'token_limit_fix'...
fatal: repository 'https://github.com/jorge-menjivar/chatbot-ui/tree/token_limit_fix/' not found

**Comment by jorge-menjivar** [comment]
Clone the main repo, then switch branches

**Comment by jorge-menjivar** [comment]
Sorry for the confusion

**Comment by ricardodacosta** [comment]
Thank you @jorge-menjivar 
I'm not well verse with git, but I can try!

These are the branches I have/see

  remotes/origin/HEAD -> origin/main
  remotes/origin/google
  remotes/origin/mac
  remotes/origin/main

**Comment by jorge-menjivar** [comment]
Try `git clone --all <repository URL>`

**Comment by ricardodacosta** [comment]
Couldn't figure it out. I will have to wait until @mckaywrigley updates

**Comment by jorge-menjivar** [comment]
Okay, you can always just use the main branch

**Comment by MohamedMohana** [comment]
Thank you it works well

**Comment by copperx** [comment]
If one has access to the 32K tokens version of GPT, does this limit present a problem?

**Comment by jorge-menjivar** [comment]
@copperx The issue affects all models as there is bogus code that does not count tokens accurately. Meaning that it will potentially send more tokens than the API can handle, which would result in OpenAI returning an error instead of a proper response.

#672 should fix this for all models though.

**Comment by rdvo** [comment]
I have 32k access on gpt4 and want to adjust this if possile, whats the latets update people have pushed ?> I know the creator isnt active anymore but i'd like to get this working ? 

Has anyone made a change where it forgets/omits older messages when sending to API as context so you can keep going without hitting a limit?

**Comment by cdelalama** [comment]
> I have 32k access on gpt4 and want to adjust this if possile, whats the latets update people have pushed ?> I know the creator isnt active anymore but i'd like to get this working ?
> 
> Has anyone made a change where it forgets/omits older messages when sending to API as context so you can keep going without hitting a limit?

This would be very useful

**Comment by rdvo** [comment]
any updates here? Would be nice if it just omit the old messages and keopt the max Context as u set
