### ISSUE TITLE
url-parameters and customization

### ISSUE THREAD

**Issue by xeor** [mckaywrigley/chatbot-ui#699]
This is a discussion, I'm not sure what the project thinks about this. But the generic idea is to be able to customize the landing page.

## Example goals

* A simple bookmarkable url for a kid to learn to read. A theme=childish and a system prompt like "Give me small sentences and ask me simple questions, ...."
* A bookmark with prepared system messages to solve a common problem you often have.
* A nativefier app with a much simpler ui made for another household member.

### Basic css theme
It would be nice to have a way for chatbot-ui to include custom css stylesheets based on parameters in the url, example `/?theme=childish`.

The usecase and goal is to create a page that a kid can access and learn using chatgpt using a custom system prompt. For the UI to look intereseting, I was planning on creating a more childish UI.

### Start-message / system message
To land on a page that you can start chatting, it would be useful to have `/?systemprompt=child-learn-read`, to initialize the prompt with a system-message.

**Comment by pbarcadia** [comment]
I would like custom css too
