### ISSUE TITLE
worker with gpt-llama  run "OPENAI_API_HOST=http://localhost:6926 npm run dev" get error like below. the error is very long 

### ISSUE THREAD

**Issue by GitMiaoronghua** [mckaywrigley/chatbot-ui#704]
![image](https://user-images.githubusercontent.com/43289542/236384120-5861733d-07cb-4432-879c-b3dd12747821.png)
![image](https://user-images.githubusercontent.com/43289542/236384331-1eadf880-c8a0-4d4d-8948-1e7731285cc3.png)

**Comment by upasch** [comment]
You can't change the host address an expect that it work with any A.I. Normally the code is specific to use the OpenAI API endpoints. If you want to use Chatbot-UI as Interface for other LLMs, first you need to know if it provides an API, second you need to re-write the code how the API handles the communication to its model and how to format the data.
