### ISSUE TITLE
Use Azure - Chinese Display Issue

### ISSUE THREAD

**Issue by jkfzero** [mckaywrigley/chatbot-ui#721]
I use chatbot-UI deploy on vercel and I used Azure openAI service. There may be garbled characters that appear between some sentences, which only happens in cases where there are long response contents and Chinese prompts. And it doesn't happen every time.

here is the screenshot
<img width="747" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/533077/860f7646-bea1-4b7e-aaa9-ae00e50c9363">

and here is my prompt
```
每当我问你一个知识点，你应该提出三个问题，并且尝试解答这三个问题。  这三个问题按照下面的思路去提问：1. 它从哪里来，这个问题意味着，一个知识的产生，并不是凭空产生的，它必然是为了解决一个问题而诞生。 2. 它是什么，这个问题意味着，一个知识点它本身是什么样的，它对于要解决的问题提出了什么方案。 3. 它到哪里去，这个问题意味着一个知识点本身针对问题的解决存在哪些缺陷，他有什么局限性，未来的发展方向如何。
```
```
一致性哈希
```

I think there might be some bug in stream onParse or in TextDecoder but I'm not sure about that.

**Comment by jkfzero** [comment]
By the way, This also happed if I run it in localhost
<img width="1449" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/533077/d57e2084-fdd4-4302-8eda-30042d657b46">

**Comment by t-koyoyo** [comment]
This problem also occurred in Japanese. I suspect that the chunks may have been cut off in the middle and not processed properly, but the root cause is not known.

<img width="546" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/129861908/8e710df5-d193-4e3f-9c31-46132084475a">

**Comment by t-koyoyo** [comment]
This problem may be related to AOAI and fetch. Is anyone tracking this issue?

**Comment by zkJames** [comment]
Yes, I have also encountered this problem . Do you all have any good solutions?
