### ISSUE TITLE
The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by GorillaDaddy** [mckaywrigley/chatbot-ui#722]
Hi, getting this error, despite not having access to gpt-4 now. Default chatgpt3.5-turbo 

event - compiled successfully in 45 ms (53 modules)
 [OpenAIError: The model: `gpt-4` does not exist] {
  name: 'OpenAIError',
  type: 'invalid_request_error',
  param: null,
  code: 'model_not_found'
}

**Comment by adamshand** [comment]
This probably means that your OpenAI account doesn't yet have access to the GPT-4 model.

**Comment by niks15** [comment]
yes, but it should be able to use the default gpt-3.5-turbo correct? I'm facing the same issue, can't run any queries locally

**Comment by GorillaDaddy** [comment]
Yes, I dropped using it. But it seems to be a bug in that every openAI request is sent as GPT4. This despite setting the model to gpt3.5turbo. This is congruent with the complaints of the high cost.
