### ISSUE TITLE
Importing index from '/pages/api/home/'

### ISSUE THREAD

**Issue by LeoFernandezR** [mckaywrigley/chatbot-ui#723]
Hi, i was looking at the code and notice that you're importing the index page from 'pages/api/home' into 'pages/index.tsx' is there any benefit or reason to do this? i couldn't find any even thought i looked at the refactor PR and there's no comments on this. I'm just curious because i have never seen move this pattern before...

**Comment by pranavmalvawala** [comment]
Same. I'm curious as well

**Comment by pranavmalvawala** [comment]
Reading [this](https://github.com/mckaywrigley/chatbot-ui/issues/169) helped
