### ISSUE TITLE
chatbot-ui return openai 400 error

### ISSUE THREAD

**Issue by NUAAwanghe** [mckaywrigley/chatbot-ui#727]
os： centos7
proxy：v2ray by azure vps
this is error page
![1](https://github.com/mckaywrigley/chatbot-ui/assets/30213716/5933d109-8be8-47ae-ace1-b57ce1cb0b29)

but my proxy is good in windows and i test openai.com by curl also good
![2](https://github.com/mckaywrigley/chatbot-ui/assets/30213716/3f9ac459-7111-4f78-9452-1638f8501fd0)

my enviroment: http_proxy https_proxy  OPENAI_API_HOST OPENAI_API_KEY

**Comment by morriswong** [comment]
Same here, encountered the same issue
