### ISSUE TITLE
DNS issues when using Azure endpoint and deploying on AWS

### ISSUE THREAD

**Issue by nkrumm** [mckaywrigley/chatbot-ui#728]
Hi all,

Leaving this as informational in case others experience the same.

We deployed the docker image on our ECS infrastructure and configured the OPENAI_API_TYPE and OPENAI_API_HOST to use our Azure endpoint. 

This results in application 500 errors that log like this:
```
[TypeError: fetch failed] {

cause: [Error: getaddrinfo ENOTFOUND {REDACTED}.openai.azure.com] {
errno: -3008,
code: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: '{REDACTED}.openai.azure.com'
}
}
```

After investigation the issue stems from a couple of interacting factors:
 * The Azure endpoints have a long (7-8) chain of associated CNAME records
 * The Chatbot-UI docker image is based on alpine/musl, which [does not retry over TCP](https://serverfault.com/a/1073494)
 * The default AWS DNS resolvers utilize a ["UDP then retry with TCP" strategy](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSBehavior.html)

There are a couple of workaround we are testing:
 * updating the resolv.conf file to point to 8.8.8.8 or another TCP-enabled nameserver
 * building the project using debian bullseye or another non-alpine base
 * using /etc/hosts to "skip" entries in the CNAME chain

If others have encountered this, I would appreciate hearing any other ideas on how to resolve this.

**Comment by alex9311** [comment]
I think I'm running into the same error trying to make azure openapi calls from github actions (from docker)

**Comment by nkrumm** [comment]
As an update, we ended up using a non-alpine base to deploy. I also saw that this will be fixed in future versions of musl/alpine: https://news.ycombinator.com/item?id=36933028

**Comment by Stan-Stani** [comment]
I was able to use 

```ps
# script.ps1
Resolve-DnsName -Name https://yoururl.com
``` 
to get another host name to use.

**Comment by jvukasovic** [comment]
I was having the same error with an Azure endpoint but deploying on a container registry of Azure. Building the project using  another non-alpine base worked for me!
