### ISSUE TITLE
Firefox can't type Chinese

### ISSUE THREAD

**Issue by chouch0u** [mckaywrigley/chatbot-ui#729]
On firefox you can't type any Chinese into input field. Not problem on Chrome.

## Firefox
https://github.com/mckaywrigley/chatbot-ui/assets/4880734/6f4ee039-e48a-4bca-9211-eddaebcaf67b

## Chrome
https://github.com/mckaywrigley/chatbot-ui/assets/4880734/47a4fdd9-059b-4480-9240-0e69d3182789

**Comment by Fog3211** [comment]
fixed https://github.com/mckaywrigley/chatbot-ui/pull/731
