### ISSUE TITLE
[Feature Request] Web Browser and Code Interpreter (gpt-4) features and plug ins with these capabilities

### ISSUE THREAD

**Issue by austenamplify** [mckaywrigley/chatbot-ui#733]
Any plugin we can use in ChatGPT UI, we'd like to do in chatbot-ui.
i.e. Wolfram Alpha plug in for math prompts
web browsing enabled plugins that live searches internet and extracts information for prompts
and other useful plug ins with these new web browser and code interpreter capabilities they've rolled out.

**Comment by afern247** [comment]
This would be amazing, I have it in ChatGPT official website and I only use their website for this.

**Comment by copperx** [comment]
I'm assuming that OpenAI will make those available in the API soon. Replicating them without the backend will be costly (e.g., fetching a webpage and then feeding it to GPT as a prompt is possible, but it would be done over several queries). Adding support for other existing API parameters and support for 32k tokens for those with access should be prioritized and would make requests like these possible.

**Comment by myst10py** [comment]
Langchain has some functionality around this we can implement into chatbot-ui.
• https://python.langchain.com/en/latest/modules/agents/tools/examples/chatgpt_plugins.html
• https://python.langchain.com/en/latest/modules/agents/tools/examples/google_serper.html
• https://python.langchain.com/en/latest/modules/agents/tools/examples/wolfram_alpha.html

Code Interpreter might be a bit more lift to implement.

**Comment by myst10py** [comment]
Maybe start with Python REPL for code interpreter and build on from there?
• https://python.langchain.com/en/latest/modules/agents/tools/examples/python.html

**Comment by rdvo** [comment]
YEah anyone ewant to work on integrating langchain into this? so you can sideload langchain plugis, or even upload files and have it store those in memory. We need a discord or a group to get together and grow this, potential is there... Lmk

**Comment by vaghawan** [comment]
> 

I would be interested to work on this.
