### ISSUE TITLE
Generated text is not showing in real time with Cloudflare

### ISSUE THREAD

**Issue by dasunNimantha** [mckaywrigley/chatbot-ui#736]
I hosted this application on an Ubuntu server and made it accessible to the internet through a Cloudflare domain. While all functions are operating effectively, the generated text is not displayed in real-time and instead only appears at the end of the answer. What could be the reason for this delayed display of text?

**Comment by seanchito** [comment]
Nginx reverse proxy messes up the stream.  `proxy buffering off`' in the config server block enables streaming.   Also, firefox has similar issues.

**Comment by dasunNimantha** [comment]
> Nginx reverse proxy messes up the stream. `proxy buffering off`' in the config server block enables streaming. Also, firefox has similar issues.

Yes indeed. I had to add the following configuration to my virtual host.

```
location /api/chat {
    proxy_pass http://127.0.0.1:3000;
    proxy_buffering off;
    proxy_request_buffering off;
}
```

And also configure some page rules on my Cloudflare dashboard because it's also a reverse proxy and uses proxy buffering.

![image](https://github.com/mckaywrigley/chatbot-ui/assets/72796127/272bc1c9-176b-465d-86c1-e67aab6918a9)

**Comment by miteshsawant** [comment]
@dasunNimantha Where did you add the configuration on your virtual host? I have added page rules on cloudflare, but I'm still unable to get the response to stream. I am not using nginx proxy manager, just cloudflare tunnels.

**Comment by dasunNimantha** [comment]
> @dasunNimantha Where did you add the configuration on your virtual host? I have added page rules on cloudflare, but I'm still unable to get the response to stream. I am not using nginx proxy manager, just cloudflare tunnels.

It didn't work with Cloudflare tunnels for me. I had to switch to regular DNS with nginx.

**Comment by wang-h** [comment]
> proxy_buffering off;
>     proxy_request_buffering off;

SOLVED! THX!
