### ISSUE TITLE
Apache Proxypass

### ISSUE THREAD

**Issue by roque-lpgc** [mckaywrigley/chatbot-ui#739]
Defined proxypass under Apache 2.4 with a simple auth. Works fine, but when i try "www.mydomain.com/chat" app redirects to "www.mydomain.com/es" is there a parameter to change this?

chatbot-ui runs in docker (docker run -e OPENAI_API_KEY=****** -p 3000:3000 chatgpt-ui)

```
<Location /chat>
        AuthType Basic
        AuthName "Restricted"
        AuthUserFile /etc/apache/.cbui.pass
        Require valid-user

        ProxyPass http://localhost:3000/
        ProxyPassReverse http://localhost:3000/
</Location>
```

**Comment by hisahisabanbi** [comment]
I have made the same observation.

I managed to resolve it by implementing the following changes.

In my case, I was using nginx.

Here's the configuration for nginx:
```
    location /chat/ {
        proxy_pass http://ipaddress:port/chat/;
    }
```

To address the issue, please modify the following files:

- next.config.js
Set the basePath to '/chat'.
```
module.exports = {
  basePath: '/chat',
};
```

- services/useApiService.ts Line: 30
Remove the leading slashes from the paths.
Change "/api/models" to "api/models".

After applying these changes, remember to rebuild the image.

**Comment by roque-lpgc** [comment]
Hi,

Thanks for the tips. They didnt work for me.

Made the changes hisahisabanbi suggested:

```
next.config.js

const { i18n } = require('./next-i18next.config');

module.exports = {
  basePath: '/chat',
};

/** @type {import('next').NextConfig} */
const nextConfig = {
  i18n,
  reactStrictMode: true,

  webpack(config, { isServer, dev }) {
    config.experiments = {
      asyncWebAssembly: true,
      layers: true,
    };

    return config;
  },
};

module.exports = nextConfig;
```

```
services/useApiService.ts (line 30)
return fetchService.post<GetModelsRequestProps>(`api/models`, {
```

The steps i followed where:

1.- git pull [[update to latest]]
2.- Make suggested changes. [[thanks hisahisabanbi]]
3.- docker images 
4.- docker rmi -f {id} [[step 3 and 4 to delete previous docker image]]
5.- docker build -t chatgpt-ui .
6.- docker run -e OPENAI_API_KEY=xxxxxxxxxxxxxxxxxxxx -p 3000:3000 chatgpt-ui

would be great to have the basePath as a parameter. Anyways, if someone could help with this issue would be great :-)

**Comment by hisahisabanbi** [comment]
You need to add `basePath: '/chat'` to the `nextConfig` as shown below:

```
const nextConfig = {
  basePath: '/chat',
  i18n,
  reactStrictMode: true,

  webpack(config, { isServer, dev }) {
    config.experiments = {
      asyncWebAssembly: true,
      layers: true,
    };

    return config;
  },
};
```
