### ISSUE TITLE
How is CB-UI able to extract Infos from a link's content without scrapping?

### ISSUE THREAD

**Issue by ALXRITR** [mckaywrigley/chatbot-ui#741]
I have a list of attributes that I list in the system prompt. With the request that when a link is posted, to analyse its content and fill in my list of attributes.

Via ChatBot UI the whole thing works (I have given my google api key).

I would like to use this in a script of mine, but I can't get a result like this! I'm supposed to work with beautifulsoup all the time.

Does anyone have any ideas?

![image](https://github.com/mckaywrigley/chatbot-ui/assets/77064641/2036154c-d965-4553-a165-347f19712969)

**Comment by ALXRITR** [comment]
I just dont understand how it works.
is GPT just halucinating?
but the results seeps accurate to me.

**Comment by ALXRITR** [comment]
Got anyone an idea?

**Comment by jdtechsol** [comment]
I have one. If you want your question to be seen, set an appropriate title.

**Comment by ALXRITR** [comment]
spasti
