### ISSUE TITLE
how to use Google Search Plugin

### ISSUE THREAD

**Issue by vawterdada** [mckaywrigley/chatbot-ui#743]

**Comment by adamshand** [comment]
Would also love pointers about this, I'm not sure what the search plugin allows or how to access it!

**Comment by renatosaz** [comment]
same..

**Comment by TomTom101** [comment]
+1

**Comment by adamshand** [comment]
Click the lightning bolt to the left of where you type the prompt.

**Comment by walter-grace** [comment]
> Click the lightning bolt to the left of where you type the prompt.

I keep getting an error when I am running this. Internal Server Error

**Comment by mbronze** [comment]
You have to enter the following on your .env.local


GOOGLE_API_KEY=YOU_GOOGLE_API
GOOGLE_CSE_ID=YOUR_ENGINE_ID

and restart the server.

**Comment by julienlagorsse-loreal** [comment]
It crash but it works when I refresh the page.

**Comment by terryds** [comment]
yes it crashed, any thoughts on how to solve?

**Comment by rursache** [comment]
Get the `GOOGLE_API_KEY` from [here](https://developers.google.com/custom-search/v1/introduction) and the `GOOGLE_CSE_ID` from [here](https://programmablesearchengine.google.com/controlpanel/all)

Then add them to the docker run command:
```
-e GOOGLE_API_KEY=XYZ \
-e GOOGLE_CSE_ID=XYZ \
```

Then click the lightning bolt to the left of where you type the prompt.
