### ISSUE TITLE
does it work with chatgpt4.0?

### ISSUE THREAD

**Issue by yuzhiyuan** [mckaywrigley/chatbot-ui#744]
does it work with chatgpt4.0?

**Comment by Khailz** [comment]
yes

**Comment by benjiqq** [comment]
API v4 is not open yet?

**Comment by Ryan526** [comment]
It does but you need to have GPT-4 API access in order for it to work.

**Comment by ilbuonporto** [comment]
During the gradual rollout of GPT-4, we’re prioritizing API access to developers that contribute exceptional model evaluations to [OpenAI Evals]([](https://github.com/openai/evals)) to learn how we can improve the model for everyone. We are processing requests for the 8K and 32K engines at different rates based on capacity, so you may receive access to them at different times. Researchers studying the societal impact of AI or AI alignment issues can also apply for subsidized access via our [Researcher Access Program]([](https://openai.com/form/researcher-access-program)).

[Read more about GPT-4](https://openai.com/research/gpt-4)


[](https://openai.com/waitlist/gpt-4-api)

[](https://openai.com/form/researcher-access-program)

**Comment by ilbuonporto** [comment]
During the gradual rollout of GPT-4, we’re prioritizing API access to developers that contribute exceptional model evaluations to [OpenAI Evals](https://github.com/openai/evals) to learn how we can improve the model for everyone. We are processing requests for the 8K and 32K engines at different rates based on capacity, so you may receive access to them at different times. Researchers studying the societal impact of AI or AI alignment issues can also apply for subsidized access via our [Researcher Access Program](https://openai.com/form/researcher-access-program).  https://openai.com/waitlist/gpt-4-api
