### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by EienFr** [mckaywrigley/chatbot-ui#746]
Hi

How to secure the container with an https certificate?
Regards

**Comment by fshabashev** [comment]
you can put nginx in front of the container to get the SSL, however I didn't manage to make websockets work properly in this case.

**Comment by yyqangular1** [comment]
I think just need to add these configuration in Nginx:

server {

                listen 443 ssl;
                server_name xxx.xxx.com;

                ## Enable SSL ##
                ssl_certificate   cert/xxxxxx.pem;
                ssl_certificate_key  cert/xxxxxxxx.key;
                ssl_session_timeout 5m;
                ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
                ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
                ssl_prefer_server_ciphers on;

                location / {
                        ## Enable Stream response ##
                        proxy_buffering off;
                        proxy_http_version 1.1;
                        chunked_transfer_encoding on;
                        proxy_pass http://localhost:3000/;
               }
}
