### ISSUE TITLE
[Feature Request] OIDC Single Sign On

### ISSUE THREAD

**Issue by WTIGER001** [mckaywrigley/chatbot-ui#749]
I would like to see a way to restrict who can login to the UI. Whil I can put an Identity aware proxy in the front I wonder if we could add support for OIDC (optional)

**Comment by IMSoley** [comment]
+1

**Comment by djam90** [comment]
+1

**Comment by ei-grad** [comment]
We use Cloudflare Zero Trust tunnel to provide such functionality: 
* run chatgpt-ui in private network
* run `cloudflared access ...` tunnel revers-proxy near it
* configure OIDC Sign-in in Cloudflare Zero Trust console to access it
 
It is free for under 50 users. Works great.
