### ISSUE TITLE
arch package?

### ISSUE THREAD

**Issue by ralyodio** [mckaywrigley/chatbot-ui#751]
Can someone create an aur pacakge for this?

**Comment by peterneutron** [comment]
You can use mine https://github.com/peterneutron/aur-chatbot-ui. I didn't publish it in the AUR because it's still very crude and for testing purposes only so use it at your own risk. The applied patch makes it bind to localhost only, you have to create the user `chatbot` manually.

**Comment by MikeWalrus** [comment]
Check out [chatbot-ui-git](https://aur.archlinux.org/packages/chatbot-ui-git).
