### ISSUE TITLE
ChatGPT is not stopping after stop generation

### ISSUE THREAD

**Issue by berecat** [mckaywrigley/chatbot-ui#752]
util/server/index.ts line 110

```
      for await (const chunk of res.body as any) {
        parser.feed(decoder.decode(chunk));
      }
```

**Comment by microflyer** [comment]
You can fix it by adding controller.close() to the end of start function.
`
      const parser = createParser(onParse);

      for await (const chunk of res.body as any) {
        parser.feed(decoder.decode(chunk));
      }

      controller.close();
`

**Comment by PinkD** [comment]
> `controller.close();`

I tried this but it didn't work.
