### ISSUE TITLE
Stream not displayed when communicating over https.

### ISSUE THREAD

**Issue by decolygs** [mckaywrigley/chatbot-ui#753]
built chatbot-ui on Docker.
After that, I published it externally with Nginx reverse proxy.

- Received reverse proxy (own domain) and assigned to 127.0.0.1:3000.

-With http communication, streaming display = 1-2 words at a time.
However,
-when using https (443), it is not displayed streaming, but is displayed after the full text is retrieved.

What settings are needed? Please let me know.

**Comment by adamshand** [comment]
Streaming works fine for me over HTTPS using Caddy.

I used the prebuilt Docker container and Caddy as a proxy.  Just standard configuration for both.

**Comment by decolygs** [comment]
@adamshand 

Thank you!!

I changed the proxy to Caddy as you suggested and now I can view the stream.

**Comment by yyqangular1** [comment]
@decolygs You just need to add these configuration by Nginx:

```
                        proxy_buffering off;
                        proxy_http_version 1.1;
                        chunked_transfer_encoding on;
                        proxy_pass http://localhost:3000/;

```
