### ISSUE TITLE
Issue with Stream in Azure OpenAI - Is anyone else experiencing this?

### ISSUE THREAD

**Issue by devnjw** [mckaywrigley/chatbot-ui#761]
I have managed to get the stream functionality working in Azure OpenAI, but it seems to be streaming in chunks instead of continuous flow. Is this the intended behavior? I'm curious to know if others are also experiencing this issue and if it is a common problem.

By the way, the GPT API from OpenAI is functioning well. 

https://github.com/mckaywrigley/chatbot-ui/assets/48133047/ec4a87cc-cab5-41a1-ae5a-e221e8d7e3d6

**Comment by bwcgn** [comment]
I have this as well, and I wanted to investigate this further. Happy to collaborate.

**Comment by devnjw** [comment]
@bwcgn Nice.

Have any idea? Even curl command to Azure api gets chunk of words... 
I think it would be better if we put a sleep(0.01sec) between words, but I'm not familiar with typescript so I can't figure it out.

**Comment by rdvo** [comment]
+1 here, want to use this but with azure OpenAI endpoints, has anyone gotten that working with streaming?

**Comment by bwcgn** [comment]
There is some other thread on this issue re https usage.  I have deployed it as docker on an app service and now works fine. Previously it was hosted as static web app

**Comment by leohxj** [comment]
its azure stream mode bug.

**Comment by bwcgn** [comment]
> its azure stream mode bug.

Do you have a reference to that?

**Comment by leohxj** [comment]
> > its azure stream mode bug.↳
> 
> Do you have a reference to that?↳

Not sure accurate, my friend told me...

**Comment by amaanr** [comment]
+1 on this, did anyone figure out how to enable streaming?

**Comment by devnjw** [comment]
> There is some other thread on this issue re https usage. I have deployed it as docker on an app service and now works fine. Previously it was hosted as static web app

Oh.. where can I use that? 🙏🏻

**Comment by bwcgn** [comment]
> > There is some other thread on this issue re https usage. I have deployed it as docker on an app service and now works fine. Previously it was hosted as static web app
> 
> Oh.. where can I use that? 🙏🏻

The repo provides a `Dockerfile` and a `docker-compose.yml` already. Just build your docker, push it to a registry and deploy it. 
I personally use a Azure Container Registry and a App Service to run it. Works fine so far, but there are multiple other ways to run and host a docker container.

**Comment by bwcgn** [comment]
Reference issue for streaming over https is #753

**Comment by leohxj** [comment]
here is a library to proxy azure api, it support buffer the chunks then stream output continuous.

https://github.com/haibbo/cf-openai-azure-proxy/blob/main/cf-openai-azure-proxy.js#L82

**Comment by superpoussin22** [comment]
You can also look at https://github.com/Patrick-Davis-MSFT/chatbot-ui what support APIM

**Comment by iyinchao** [comment]
I'm experiencing this as well, messages seem to be blocked at beginning, and received in batch. Any solution on this?
<img width="269" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/3615672/90bbdef5-e86b-4e31-92c7-9f4459b5c354">

**Comment by bytecod3r** [comment]
Same issue, the messages is receiving in chunks of 20-30 words, instead of word by word.

**Comment by Codefa** [comment]
> Same issue, the messages is receiving in chunks of 20-30 words, instead of word by word.

you can fix it by adding 
```js
await new Promise(resolve => setTimeout(resolve, 80))
```
