### ISSUE TITLE
Tree style tabs with information sharing?

### ISSUE THREAD

**Issue by JordanSabie** [mckaywrigley/chatbot-ui#765]
Can we have tree-style tabs?
You have your top-level labs with little carats that expand sub-level tabs.
I would be happy with that concept alone just for organization and if there could be an information sharing between tabs at the sub-tab level. Could this be achieved by writing the contents of the conversations at the sub-tab level to a document that Chatgpt constantly reads?
A way to insert documents under the top-level tab would be nice too. 
I get so annoyed with chatgpt if I need to analyze like 3000 words or something and If I want to diverge in the conversation or take it down another thread, I have to re-copy all my text over into a new tab. it would be so easy to just upload a document under a top-level tab and then open up a new sub-level conversation and get to work.

sorry if this isn't possible.

**Comment by futurk** [comment]
thread-tree structure. would definitely be a killing feature. i often go back and edit my prompt in chatgpt to ask a different question which is often related to previous prompts and answers. browsing through prompts (i.e. threads) is really tedious.
