### ISSUE TITLE
After startup, the domain name of the request backend is http://localhost:3000/

### ISSUE THREAD

**Issue by zdwork** [mckaywrigley/chatbot-ui#769]
<img width="778" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/24469374/4d7c71f9-335a-4d2e-8b57-f07b7a9e1cbd">

**Comment by amithmkini** [comment]
This is working as intended. It's a Next.js app, and it is calling its API function which is hosted at `/api` endpoint. There are functions there that will in turn use the OpenAI Node SDK to connect to OpenAI servers and get the completion.
