### ISSUE TITLE
Idea: Support OpenAI-compatible API's like LocalAI

### ISSUE THREAD

**Issue by alhafoudh** [mckaywrigley/chatbot-ui#770]
It would be nice if chatbot-ui supported OpenAI-compatible API's like LocalAI. I got it working by naming the models like OpenAI models, but it is a hack.

**Comment by arthur-brainchain** [comment]
Lazy question but asking anyways: Do you know if there is any work to support llama.cpp inference for use in this chatbot-ui repo?

**Comment by EchedelleLR** [comment]
Some extra information: https://github.com/go-skynet/LocalAI/issues/165

**Comment by sammcj** [comment]
This would be incredibly useful.
