### ISSUE TITLE
How to DISABLE latex support?

### ISSUE THREAD

**Issue by Creling** [mckaywrigley/chatbot-ui#775]
Hi,

The Latex support in chatbot-ui is buggy, which causes unexpected line breaks and brings extra difficulties in copying chatgpt's responses. Would it be possible to temporarily disable the Latex support?

![image](https://github.com/mckaywrigley/chatbot-ui/assets/43109504/169e5fd3-e800-41bf-b13e-be2f9b3beab6)

**Comment by dav-ell** [comment]
Weird that this is the only issue on this repo talking about latex. This issue has been bothering me for a long time.

**Comment by atharvashukla** [comment]
You can fork and undo this commit here:

https://github.com/mckaywrigley/chatbot-ui/pull/165

I did some memory profiling and the LaTex integration is the culprit

**Comment by elanzini** [comment]
Anybody has had any luck fixing the rendering to also support inline formulas?
