### ISSUE TITLE
OpenAIError: The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by niks15** [mckaywrigley/chatbot-ui#777]
Even with the default model set to gpt-3.5-turbo, app is trying to use GPT-4 as the model and throws the following error:

 [OpenAIError: The model: `gpt-4` does not exist] {
  name: 'OpenAIError',
  type: 'invalid_request_error',
  param: null,
  code: 'model_not_found'

**Comment by fshabashev** [comment]
It might be because OpenAI didn't provide you the access to GPT4. 
Did you exceed the quota by any chance?

**Comment by vladiliescu** [comment]
@niks15 Yeah, I've noticed the models are not used in a consistent manner across the code. I'm guessing this [pull request](https://github.com/mckaywrigley/chatbot-ui/pull/764) might fix it for you?
