### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by alessbonora** [mckaywrigley/chatbot-ui#778]
Hey I'm opening this Issue because Chatbot UI is giving me "Internal Server Error" when I'm trying to use it, either the version I uploaded by myself either the one at chatbotui.com. I thought it was OpenAI Api fault, but even creating a new one, still gives the same error. It was going fine at start but it's like a month that it gives me this error.

**Comment by sutidor** [comment]
It is false API key error. try to create a new api key / check if it has funds and so on.
@maintainer please handle this error

**Comment by alessbonora** [comment]
@sutidor thank you I think this happened because the ChatGPT api went from free to priced and I didn't notice the change
