### ISSUE TITLE
Results vs chat.openai [Question]

### ISSUE THREAD

**Issue by ICULikeMac** [mckaywrigley/chatbot-ui#795]
Should I expect to see the "same" results between using the official website vs the API key? I understand the text will not be the same but of the same quality responses. My wife is telling me that ChatGPT (OpenAI Website etc) has consistently better responses, is this because ChatGPT is a different model to 3.5 or should we be expecting the same quality from the API?

Thank you so much in advance.

Note: Both NOT using 4.

**Comment by Ryan526** [comment]
Could be your temperature setting when starting a chat. I use '0.2' and get similar results to the website.
