### ISSUE TITLE
为什么最近提问总是报500，有没有兄弟遇见过，有没有解决办法？

### ISSUE THREAD

**Issue by jieshengmu** [mckaywrigley/chatbot-ui#809]
![1a660d81-42b3-4add-8170-d464c52991b4](https://github.com/mckaywrigley/chatbot-ui/assets/29828399/1c14fbc6-0d17-4963-b731-abbbed815c61)

**Comment by myth26** [comment]
我最近也是这样

**Comment by yizhongxunsi** [comment]
me too,help

**Comment by myth26** [comment]
我检查了下应该是赠送的API额度用完了，或者是过期了。可以通过访问https://platform.openai.com查看API调用情况，后续使用需要绑定国外的卡

**Comment by mPaella** [comment]
getting this too, after chatting for a while (35 messages to be exact, the 36th is failing). I have put in my API key, so it should be working

<img width="394" alt="image" src="https://github.com/mckaywrigley/chatbot-ui/assets/93682696/fd9dfe63-43bf-492c-9535-e237baccb6dc">
