### ISSUE TITLE
Context length exceeded - but message is not that long.

### ISSUE THREAD

**Issue by arhyarion** [mckaywrigley/chatbot-ui#820]
I've been having a conversation about Django and PostgreSQL via the GPT4 API in ChatbotUI. I have reached a point where a short message like "my host supports PostgreSQL databases" gives me the error:

This model's maximum context length is 8192 tokens. However, you requested 8554 tokens (7554 in the messages, 1000 in the completion). Please reduce the length of the messages or completion.

the terminal shows:

 [OpenAIError: This model's maximum context length is 8192 tokens. However, you requested 8554 tokens (7554 in the messages, 1000 in the completion). Please reduce the length of the messages or completion.] {
  name: 'OpenAIError',
  type: 'invalid_request_error',
  param: 'messages',
  code: 'context_length_exceeded'
}

**Comment by qraccess** [comment]
I have the same issue.

**Comment by arhyarion** [comment]
I was a noob when I wrote that issue. That's how context windows are supposed to work. At the time I didn't realize context was also the entire conversation history going back and forth each time.
