### ISSUE TITLE
gpt 3.5 supports 16k token

### ISSUE THREAD

**Issue by pdgxiaofei** [mckaywrigley/chatbot-ui#826]
https://openai.com/blog/function-calling-and-other-api-updates
gpt 3.5 supports 16k token

**Comment by Wnine16** [comment]
I just created a pr for this new model [gpt-3.5-16k](https://github.com/mckaywrigley/chatbot-ui/pull/827)

**Comment by benedikt90** [comment]
this repos seems abandoned unfortunately :(
