### ISSUE TITLE
Support for deleting or editing messages

### ISSUE THREAD

**Issue by Guandor** [mckaywrigley/chatbot-ui#84]
I believe the biggest strength of the API is to be able to edit the whole conversation, similar to the openAI playground. It would be great to have edit/delete features.

**Comment by PixelJonas** [comment]
would this be possible for the AI answers as well? would be great to change his answers to the ways I'd like them to be to have them as input for the ongoing conversation

**Comment by mckaywrigley** [comment]
Adding this soon. Early next week probably.

**Comment by mckaywrigley** [comment]
Editing done. Holding on deletion for now.
