### ISSUE TITLE
When will GPT-4 be supported?

### ISSUE THREAD

**Issue by dishengai** [mckaywrigley/chatbot-ui#840]
When will GPT-4 be supported?

**Comment by naporin0624** [comment]
If the api key is able to use gpt-4, it came up in my environment without the need for additional operations.

![367d0f03c0f427cf022922a2cddfe5f1](https://github.com/mckaywrigley/chatbot-ui/assets/32933709/59e87d37-b729-44e1-a6f4-fed0ebcff63e)

**Comment by hhtee** [comment]
It says default 3.5 on chatbot UI, but how can i select 3.5-turbo-16k-0613 or other 3.5 models we have available in playground?
