### ISSUE TITLE
fcp and lcp is poor

### ISSUE THREAD

**Issue by huangganggui** [mckaywrigley/chatbot-ui#843]
This is a very nice project and I deploy it on vercel.com and share to my friends. Nice work.

But I meet problem that fcp and lcp is poor(Speed Insights on  vercel.com ). I dont know why and how to fix it.

![image](https://github.com/mckaywrigley/chatbot-ui/assets/17699452/033a3327-f270-428f-bb0c-f93b8c532929)

**Comment by MrAlaminH** [comment]
Use tools like Google's PageSpeed Insights to measure your performance and identify areas for improvement.
