### ISSUE TITLE
Streaming not working when running locally with NPM

### ISSUE THREAD

**Issue by antyoxydant** [mckaywrigley/chatbot-ui#866]
Mesaage pops up with a big chunk of text content every time, not like the typing effect.

**Comment by luohao123** [comment]
Same issue here, but am normal in local, but server not. Did u solve it

**Comment by langchain4j** [comment]
@antyoxydant @luohao123 this might help:
https://github.com/mckaywrigley/chatbot-ui/issues/753
https://github.com/mckaywrigley/chatbot-ui/issues/736
https://github.com/mckaywrigley/chatbot-ui/issues/463
