### ISSUE TITLE
Feature Request: Add continue button on long chat responses to load more.

### ISSUE THREAD

**Issue by fredy-mederos** [mckaywrigley/chatbot-ui#87]
Add a "Continue" button at the bottom of a generated response that may have been cut due to the length.
this allows to easily ask the chat for more text.

**Comment by dennisheiden** [comment]
Is it possible to detect if a response was cut due network error or char limit? Then it might make sense if the app automatically prompted a "continue" to the API. But a button would be good either way, so that you can push the AI ​​to continue writing stories, etc.

**Comment by vladanpaunovic** [comment]
For what is worth, I realised that if you just type `Continue` it will understand and continue writing

**Comment by dennisheiden** [comment]
Thats correct, but that might lead to weird responses from OpenAI on network errors as far I could see. But yeah, that's what you can do. Typing "continue" also works for continues writing of story chapters instead of "write the next chapter" etc.

**Comment by mckaywrigley** [comment]
Continue seems to be the best way to do this for now.
