### ISSUE TITLE
How do I add a password, my web is under attack

### ISSUE THREAD

**Issue by xiaodou435** [mckaywrigley/chatbot-ui#883]
How do I add a password, my web is under attack

**Comment by xiaodou435** [comment]
$600 was gone yesterday

**Comment by huangganggui** [comment]
maybe you can add a invite code. like this:https://github.com/mckaywrigley/chatbot-ui/commit/192c96fe04ca46badee7ff3cd30d1e7c6f0b5822

**Comment by ghost** [comment]
I think I figure out why this happen. This project is using openai JavaScript library, and on the readme of [official repo](https://github.com/openai/openai-node):
> warning Important note: this library is meant for server-side usage only, as using it in client-side browser code will expose your secret API key. [See here](https://platform.openai.com/docs/api-reference/authentication) for more details.

this project is client side and using official js library. Stop using this project now....

**Comment by petarsrepo** [comment]
@xiaodou435 here's a quick and ez `./pages/_app.tsx` replacement you can use to set up basic password protection. Password is stored as an environment variable with `NEXT_PUBLIC_PASSWORD` as its key, so if you're hosting it on Vercel hop on to your project settings => environment variables and enter `NEXT_PUBLIC_PASSWORD` and `YOUR_PASSWORD_HERE` there to set it. Code-wise just copy and paste the following segment over your current `_app.tsx` code, replacing everything and deploy it. Do note that this fix was compiled in ~1h so it is terribly untested BUT WORKS :D

```
import { Toaster } from 'react-hot-toast';
import { QueryClient, QueryClientProvider } from 'react-query';
import { useEffect, useState } from 'react';
import { appWithTranslation } from 'next-i18next';
import type { AppProps } from 'next/app';
import { Inter } from 'next/font/google';

import '@/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

function App({ Component, pageProps }: AppProps<{}>) {
  const queryClient = new QueryClient();
  const [isAuthenticated, setIsAuthenticated] = useState<boolean | null>(null);

  useEffect(() => {
    const checkAuth = async () => {
      let auth = sessionStorage.getItem("auth");

      if (auth === "true") {
        setIsAuthenticated(true);
        return;
      }

      while (auth !== "true") {
        let pass = prompt("Enter password");

        if (pass === null) { // User clicked cancel
          setIsAuthenticated(false);
          return;
        }
        else if (pass === process.env.NEXT_PUBLIC_PASSWORD) {
          sessionStorage.setItem("auth", "true");
          auth = sessionStorage.getItem("auth");
        } else {
          alert("Wrong password");
        }
      }

      setIsAuthenticated(true);
    };

    checkAuth();
  }, []);

  if (isAuthenticated === null) {
    return <div>Loading...</div>; // Loading state
  }

  if (!isAuthenticated) {
    return <div>Access denied</div>; // If authentication failed
  }

  // If authentication passed
  return (
    <div className={inter.className}>
      <Toaster />
      <QueryClientProvider client={queryClient}>
        <Component {...pageProps} />
      </QueryClientProvider>
    </div>
  );
}

export default appWithTranslation(App);

```

**Comment by AnonymousArthur** [comment]
> I think I figure out why this happen. This project is using openai JavaScript library, and on the readme of [official repo](https://github.com/openai/openai-node):
> 
> > warning Important note: this library is meant for server-side usage only, as using it in client-side browser code will expose your secret API key. [See here](https://platform.openai.com/docs/api-reference/authentication) for more details.
> 
> this project is client side and using official js library. Stop using this project now....

Hey, maybe you should figure out what "client-side" means. This project apparently is running on next.js, which has a backend (the server-side) at the same time.
