### ISSUE TITLE
The response speed is getting slower and slower, whether I turn on the proxy or not

### ISSUE THREAD

**Issue by i-shl** [mckaywrigley/chatbot-ui#888]
The response speed is getting slower and slower, regardless of whether I open the proxy or not, it was very fast at the beginning. This is the link I built [https://chatbot-ui-chi-two.vercel.app/zh](https://chatbot-ui-chi-two.vercel.app/zh). May I ask how to solve this problem

**Comment by MarcoColomb0** [comment]
Yeah, I noticed that the generation is way slower than standard API calls. It's not a huge problem, but it's still annoying. I hope someone will resolve it because the project is really good.

**Comment by colin-plus** [comment]
I have the same issue.
