### ISSUE TITLE
TypeError: no 'finish_reason'

### ISSUE THREAD

**Issue by i207M** [mckaywrigley/chatbot-ui#901]
I deployed chatbot-ui on vercel, and it worked perfectly before. But today I encountered this problem, causing the webpage not showing response. This is the log from vercel

```
TypeError: Cannot read properties of undefined (reading 'finish_reason')
```

Any ideas? Thanks in advance.

**Comment by i207M** [comment]
So, for later reference, this is because the new version of Azure's OpenAI API doesn't include "finish_reason" in responses sometimes (specifically, the first package).

**Comment by vikanirav** [comment]
Hello @i207M,

I guess you are using new azure openai api version. I am also getting same error after updating api version from **'2023-03-15-preview' to '2023-12-01-preview'**.

`TypeError: Cannot read properties of undefined (reading 'finish_reason')`

1. Can you please help me that how did you solve this error?
2. Below Deployment api is not supported in newer version of azure openai api? How did you handle this?

 `https://{host name}.openai.azure.com/openai/deployments?api-version=2023-12-01-preview`
       
Thanks in advance!

**Comment by vikanirav** [comment]
> Hello @i207M,
> 
> I guess you are using new azure openai api version. I am also getting same error after updating api version from **'2023-03-15-preview' to '2023-12-01-preview'**.
> 
> `TypeError: Cannot read properties of undefined (reading 'finish_reason')`
> 
> 1. Can you please help me that how did you solve this error?
> 2. Below Deployment api is not supported in newer version of azure openai api? How did you handle this?
> 
> `https://{host name}.openai.azure.com/openai/deployments?api-version=2023-12-01-preview`
> 
> Thanks in advance!

Hello @i207M,

Can you please give answer of 2 questions? Help will be appreciated.

**Comment by i207M** [comment]
Hello Nirav!

Honestly speaking, I didn't solve it. I keep using the older API version. However, I thought the fix should be straightforward. Are you using a CloudFlare worker to convert Azure API to OpenAI's? If that's the case, please edit the worker's code to include "finish_reason" in every response.

As for the second question, I don't really understand it. Can you further it?

Best
