### ISSUE TITLE
Plugin Development

### ISSUE THREAD

**Issue by necromancergh** [mckaywrigley/chatbot-ui#902]
Hi, all, I've forked repo and created customized chatapp with my own API.
My next plan is to create plugins (maybe langchain plugin first) for this...
How come it is possible for me?

**Comment by necromancergh** [comment]
or any one who can help me on this? (will pay you for sure 😄)

**Comment by chen198328** [comment]
Chatboui can load plugins

**Comment by necromancergh** [comment]
> 

Oh, can you please explain more?

All I see is the plugin key...

And I'd like to know how to
- add my own plugin to the platform
- how to allow developers add their own plugins..

**Comment by GEMTechnologies** [comment]
It does not load plugins apart from the google search key which has bugs like nothing and also for plugin compartibility try to search other alternatives within git
