### ISSUE TITLE
If I use Netlify to deploy this project,How can I config the environment variables

### ISSUE THREAD

**Issue by fredfcx** [mckaywrigley/chatbot-ui#905]
If I use Netlify to deploy this project,How can I config the environment variables

**Comment by petarsrepo** [comment]
Hop on to your netlify account>your site>site configuration>environment variables>add a variable and set it in there.  
![image](https://github.com/mckaywrigley/chatbot-ui/assets/24898023/edb6be6a-3cf2-40fa-81ee-23e7cd1a1f7d)
