### ISSUE TITLE
how to deploy the project in a linux server with node environment

### ISSUE THREAD

**Issue by fuxijun** [mckaywrigley/chatbot-ui#907]
how to deploy the project in a linux server with node environment?

**Comment by noodlescripter** [comment]
well, I tried deploying using pm2, since I did not want to deploy using docker due to some issues with api key being leaked.
Ended up running on win server using services using. Works better!!!

**Comment by fkesheh** [comment]
I didn't do that, but I believe you should mimic what is done for docker
