### ISSUE TITLE
Hello, I deploy this website to server and the typing decoding animation are gone

### ISSUE THREAD

**Issue by luohao123** [mckaywrigley/chatbot-ui#920]
In local, the characters are typing one by one, but when deploy to server, it was gone.

I debugged a little bit, it was because of the /api/chat post not using text-stream,

I don't know why it work in local but not work on server, can u help a little bit?

BTW, really appreciated your work and hoping for your next v2 version !(saw from twitter)

**Comment by DiegoSpinola** [comment]
I've had this issue with nginx as a reverse proxy , replaced it with caddyv2 and it fixed it
