### ISSUE TITLE
有盗取KEY的风险，请谨慎使用

### ISSUE THREAD

**Issue by 5536086** [mckaywrigley/chatbot-ui#923]
目前用过的一个KEY已经被用完额度了，本人未泄露KEY

**Comment by toyo2333** [comment]
自己部署的？

**Comment by BaiMoHan** [comment]
Yes. I have experienced this situation.
When I went to sleep, I was sure that nobody else used it. But when I woke up, I found that all my quota had been used up, and it was all used on GPT-4.

**Comment by BaiMoHan** [comment]
> 自己部署的？

Yes, in a private vpc

**Comment by guoqiao** [comment]
I also deployed this service in my vps, using my chatgpt-4 api key.

I got a unexpected USD $38 bill for api usage in July 9th, mostly used on 1 day, while I was not using chatgpt api at all.
(I set limit to USD $40.) So I revoked that key, and no new issue.

I generated a new key on Auguest 7, and used it for this service again.
Today, on Auguest 10th, I got another bill for about USD 38 again, and mostly used on 8.9 and 8.10.

It's very likely this service leaks my api key.

**Comment by 5536086** [comment]
> 自己部署的？

肯定是自己部署的啊，自己的服务器，使用这个程序，卖家卖完号就销毁记录了，所以只能是被这个程序盗用的，用的docker版

**Comment by 5536086** [comment]
> I also deployed this service in my vps, using my chatgpt-4 api key.
> 
> I got a unexpected USD $38 bill for api usage in July 9th, mostly used on 1 day, while I was not using chatgpt api at all. (I set limit to USD $40.) So I revoked that key, and no new issue.
> 
> I generated a new key on Auguest 7, and used it for this service again. Today, on Auguest 10th, I got another bill for about USD 38 again, and mostly used on 8.9 and 8.10.
> 
> It's very likely this service leaks my api key.

Yeah, same experience.

**Comment by kimtiago** [comment]
same here too

**Comment by yuege613** [comment]
确实，被盗用了两次了

**Comment by yuege613** [comment]
刚生成的apikey，部署上去不一会儿就被盗用了，嘎嘎调用GPT-4

**Comment by guoqiao** [comment]
> I also deployed this service in my vps, using my chatgpt-4 api key.
> 
> I got a unexpected USD $38 bill for api usage in July 9th, mostly used on 1 day, while I was not using chatgpt api at all. (I set limit to USD $40.) So I revoked that key, and no new issue.
> 
> I generated a new key on Auguest 7, and used it for this service again. Today, on Auguest 10th, I got another bill for about USD 38 again, and mostly used on 8.9 and 8.10.
> 
> It's very likely this service leaks my api key.

I get this warning email from openai today:


We are reaching out to you as a user of OpenAI’s API because some of the content in your requests has been flagged by our systems to be in violation of our policies against generating or attempting to generate sexual content.

We request you take action to remediate this activity within two weeks of receiving this message. If remedial action is not taken, please note your API access may be terminated in accordance with our Terms of Use.

**Comment by ctrlbrk42** [comment]
Can someone please recommend another Docker deployable package, to replace this one that seems abandoned and now questionable security.  I like the UI of this app, but security comes first.

**Comment by toyo2333** [comment]
> Can someone please recommend another Docker deployable package, to replace this one that seems abandoned and now questionable security. I like the UI of this app, but security comes first.谁能推荐另一个可在 Docker 上部署的软件包，以取代这个似乎已被遗弃且安全性堪忧的软件包。我喜欢这个应用程序的用户界面，但安全是第一位的。

https://github.com/Yidadaa/ChatGPT-Next-Web

**Comment by toyo2333** [comment]
> 刚生成的apikey，部署上去不一会儿就被盗用了，嘎嘎调用GPT-4

try this https://github.com/Yidadaa/ChatGPT-Next-Web

**Comment by djsiroky** [comment]
For anyone experiencing this issue, did you use `docker push` with this repo? Doing so pushes this image with the .env file to a registry, possibly Docker hub. I see quite a few public images on there named `chatbot-ui` with plenty of downloads.

**Comment by seanchito** [comment]
I cloned the repo directly to my ubuntu server and experienced a key breech incident.   Though I'm not positive that this app was the culprit.

**Comment by guoqiao** [comment]
I updated my key used for this service without pushing new image to docker hub, the key is still leaked. So I don't think it's related to docker hub.

**Comment by seanchito** [comment]
FYI, if you got hit with fraudulent charges, OpenAI will remove them from your bill if you contact them.   It's not easy.   I had luck mailing support@openai.com and the being patient.   Their 'Help Center' is completely worthless.

**Comment by Jisen** [comment]
MD，真的会盗用，之前额度被用完，新生成了一个Key，昨晚又被盗用完了，新的Key只在这个项目上使用。
