### ISSUE TITLE
Using GPT3.5 even if GPT4 is selected (for Azure OpenAI deployment)

### ISSUE THREAD

**Issue by smallbirds3** [mckaywrigley/chatbot-ui#927]
Hey,

I am having this issue that I have a deployment in Azure OpenAI with both gpt-35-turbo (deployment_id. = "chatgpt") and gpt-4 (deployment_id = "gpt-4"). When I start up the chatbot-ui it then also correctly identifies gpt-3.5 and gpt-4 as options when I start a new chat. This is great as it has identified that I have both deployed in Azure.

The problem is however that it chooses gpt-3.5 on azure, no matter if I pick gpt-4 or gpt-3.5 in the dropdown menu. I assume it has to do with the fact that you have to set a deployment_id when using Azure deployment - and I selected AZURE_DEPLOYMENT_ID="chatgpt". But in fact I have to use both "chatgpt" (for gpt-3.5) and "gpt-4" for gpt4. Azure OpenAI does not allow me to choose the same deployment_id for both the gpt-3.5 and 4 model. Is this a bug in the code somehow or what do I do wrong? Is there anything I can do to ensure it will use the right deployment id for the two cases?

**Comment by raedkit** [comment]
I have the same problem.  Even with using ``DEFAULT_MODEL`` as ``gpt-4`` it seems to use gpt-3.5

**Comment by riotrah** [comment]
I just got a (very hacky) fork working locally that supports specifying 2 azure endpoints/deployments/keys. It fetches/merges the list of models from both, and calls the selected one correctly when chatting. 

That's your only option (other than picking a different lib or fork)
