### ISSUE TITLE
Copying code causes an error message.

### ISSUE THREAD

**Issue by schihei** [mckaywrigley/chatbot-ui#93]
I receive an error message when I try to copy the source code to the clipboard.

![CleanShot 2023-03-23 at 08 43 29](https://user-images.githubusercontent.com/6663322/227136247-1b1c29ef-ab7a-452e-ab2b-9370a967ce51.png)

![CleanShot 2023-03-23 at 08 42 47](https://user-images.githubusercontent.com/6663322/227136270-89ef1836-71ae-4f53-bb2f-75e5fbbfa4aa.png)

**Comment by mckaywrigley** [comment]
What browser?

**Comment by quocthinhvo** [comment]
> What browser?

Same problem in Chrome.

**Comment by mckaywrigley** [comment]
I wonder if either of you have anything enabled that controls your clipboard. Any extensions maybe?

**Comment by schihei** [comment]
> I wonder if either of you have anything enabled that controls your clipboard. Any extensions maybe?

Not really. I also checked the Privacy and Security settings. Sites can ask to see text and images on my clipboard. I also tried to add the page explicitly, but without success.

This is the detailed error message.

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'writeText')

Source
components/Markdown/CodeBlock.tsx (17:28) @ writeText

  15 | 
  16 | const copyToClipboard = () => {
> 17 |     navigator.clipboard.writeText(value).then(() => {
     |                        ^
  18 |         setButtonText("Copied!");
  19 | 
  20 |         setTimeout(() => {
Call Stack
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js (4164:0)
Object.invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js (4213:0)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (4277:0)
invokeGuardedCallbackAndCatchFirstError
node_modules/react-dom/cjs/react-dom.development.js (4291:0)
executeDispatch
node_modules/react-dom/cjs/react-dom.development.js (9041:0)
processDispatchQueueItemsInOrder
node_modules/react-dom/cjs/react-dom.development.js (9073:0)
processDispatchQueue
node_modules/react-dom/cjs/react-dom.development.js (9086:0)
dispatchEventsForPlugins
node_modules/react-dom/cjs/react-dom.development.js (9097:0)
eval
node_modules/react-dom/cjs/react-dom.development.js (9288:0)
batchedUpdates$1
node_modules/react-dom/cjs/react-dom.development.js (26140:0)
batchedUpdates
node_modules/react-dom/cjs/react-dom.development.js (3991:0)
dispatchEventForPluginEventSystem
node_modules/react-dom/cjs/react-dom.development.js (9287:0)
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay
node_modules/react-dom/cjs/react-dom.development.js (6465:0)
dispatchEvent
node_modules/react-dom/cjs/react-dom.development.js (6457:0)
dispatchDiscreteEvent
node_modules/react-dom/cjs/react-dom.development.js (6430:0)
Hide collapsed frames

**Comment by mckaywrigley** [comment]
I just pushed a fix that will prevent that error, but it will return the function such that it won't copy.

It appears to be a case where your clipboard api is unaccessible.

**Comment by aweshchoudhary** [comment]
Working Fine in my case.
![image](https://user-images.githubusercontent.com/66569398/227235394-c2f72465-53b1-456c-a171-03ab21ec56a9.png)
OS: Linux
Browser: Chrome (Latest Version)

**Comment by mckaywrigley** [comment]
Quick follow up - was this locally run or from chatbotui.com?

**Comment by aweshchoudhary** [comment]
Working fine on both the local and chatbotui.com servers.
![image](https://user-images.githubusercontent.com/66569398/227238098-001ef682-511b-4c51-bcbc-9392c4f39231.png)

**Comment by schihei** [comment]
When I run it in a Docker container it works perfectly. Could it be an incompatibility with the Node.js version, etc?

**Comment by schihei** [comment]
The problem is somehow my browser setting. I apologise for the inconvenience.

![CleanShot 2023-03-23 at 15 56 03](https://user-images.githubusercontent.com/6663322/227243631-75bd995b-a5c5-46a1-858a-18a446bb4856.png)

**Comment by mindsolve** [comment]
Hi, as far as I understand this, clipboard access is only possible in "secure contexts" - i.e. opened via HTTPS or from localhost. This seems to be the case for Chrome and Firefox.

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard
