### ISSUE TITLE
DEFAULT_MODEL not working when using Azure Models

### ISSUE THREAD

**Issue by pouljensen32** [mckaywrigley/chatbot-ui#935]
Hey,

I love this UI, but I have one problem. I want the default model to be GPT-3.5 every time the user want to start a conversation - no matter which model they used for their previous conversation (e.g., GPT-4). Right now, the default in the drop down bar when starting a new conversation is whatever model you picked from your old conversation.

I tried to play around with DEFAULT_MODEL but somehow does not seem to work for Azure OpenAI model??

I also tried playing around with this code - https://github.com/mckaywrigley/chatbot-ui/blob/main/components/Chat/ModelSelect.tsx - for a long time. I have not found a solution.

Anyone who has found a solution on this? Or an easy fix to ensure default model is the GPT-3.5 from azure, and GPT-4 only is selected if the user actively decide to choose it from the dropdown box (no matter if the users previous conversation was with GPT-4 or nor)

**Comment by superpoussin22** [comment]
open utils/server/index.ts

replace line 35 :
url = `${OPENAI_API_HOST}/openai/deployments/${AZURE_DEPLOYMENT_ID}/chat/completions?api-version=${OPENAI_API_VERSION}`;

with

url = `${OPENAI_API_HOST}/openai/deployments/${model.id}/chat/completions?api-version=${OPENAI_API_VERSION}`;

enjoy
