### ISSUE TITLE
App for custom bot

### ISSUE THREAD

**Issue by amit4aws** [mckaywrigley/chatbot-ui#937]
Is it possible to connect the app to a host rather than openai? I want to try the app on custom bot running on a certain server.

**Comment by anuran-roy** [comment]
Hey @amit4aws, my use case is the same. So these were my observations while digging around the code:

1. Add an environment variable called `OPENAI_API_HOST` pointing to the domain where you have hosted the endpoints. http://localhost:8000 works as well.

2. Add an environment variable called `OPENAI_API_KEY` containing the OpenAI key (or set it to an empty string in case your backend is handling the OpenAI API calls) 

3. To make minimum changes in the codebase, make sure you create the endpoints: 
- `v1/models`: Mimics the same endpoint in api.openai.com, sans the API Key in the headers.
- `v1/chat/completions`: Same as above, with similar input and output. Note that the response has to be a Streaming HTTP Response, else stuff will break.

**Comment by mhy-bsi** [comment]
> Hey @amit4aws, my use case is the same. So these were my observations while digging around the code:
> 
> 1. Add an environment variable called `OPENAI_API_HOST` pointing to the domain where you have hosted the endpoints. http://localhost:8000 works as well.
> 2. Add an environment variable called `OPENAI_API_KEY` containing the OpenAI key (or set it to an empty string in case your backend is handling the OpenAI API calls)
> 3. To make minimum changes in the codebase, make sure you create the endpoints:
> 
> * `v1/models`: Mimics the same endpoint in api.openai.com, sans the API Key in the headers.
> * `v1/chat/completions`: Same as above, with similar input and output. Note that the response has to be a Streaming HTTP Response, else stuff will break.

Hi @anuran-roy, Do you have an example to implement point 3? Thanks.
