### ISSUE TITLE
how to set to GPT-4 model?

### ISSUE THREAD

**Issue by mydoto** [mckaywrigley/chatbot-ui#947]
how to set to GPT-4 model?

**Comment by atnjqt** [comment]
Great question, I am wondering the same

**Comment by 0x-sen** [comment]
+1

**Comment by harumijang** [comment]
1. Make sure your OpenAI API key supports GPT-4
2. Add  `DEFAULT_MODEL=gpt-4` to your .env file
3. Clear existing conversations on the chat bot
