### ISSUE TITLE
Suggestion: Decouple auto scrolling when user manually scrolls during reply streaming.

### ISSUE THREAD

**Issue by Maxiviper117** [mckaywrigley/chatbot-ui#95]
Currently, when your interface GPT writes a reply that exceeds the bottom of the page, it automatically scrolls down to keep the streaming text in view. However, it would be more user-friendly if this feature could be decoupled whenever the user manually scrolls, similar to how the official ChatGPT works. 

Sometimes we want to start reading the top of the reply, before it finishes streaming the reply.

**Comment by mckaywrigley** [comment]
I will fix this today.

**Comment by mckaywrigley** [comment]
Fixed!
