### ISSUE TITLE
.

### ISSUE THREAD

**Issue by bvakili-exelixis** [mckaywrigley/chatbot-ui#954]

**Comment by signalprime** [comment]
what is going on here?

**Comment by Husky931** [comment]
can we get some update if this is about the security leak and how to proceed with it?

**Comment by kyleroberts-ai** [comment]
To clarify the app isn't "Leaking" the API key.

As you can see on docker: `https://hub.docker.com/search?q=chatbot-ui&source=community&sort=updated_at&order=desc`

A total of 91 'Chatbot-ui' repos have been added, many of these have multiple downloads.

This looks like a user error with not protecting the application with authentication or following steps to keep environment variables safe.

**Comment by auxon** [comment]
hey there is a security risk in using api keys in getServerSideProps as used in https://github.com/menloparklab/chatbot-ui/blob/main/pages/api/home/home.tsx.  According to https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props: 
 Note that irrespective of rendering type, any props will be passed to the page component and can be viewed on the client-side in the initial HTML. This is to allow the page to be hydrated correctly. Make sure that you don't pass any sensitive information that shouldn't be available on the client in props.
