### ISSUE TITLE
Leaks API Keys!

### ISSUE THREAD

**Issue by 3even** [mckaywrigley/chatbot-ui#962]
Be advised, If you follow the deployment instructions using Docker and host it remotely IT WILL LEAK your OpenAI API keys.

**Comment by GEMTechnologies** [comment]
@3even  so whats the way out of this

**Comment by noodlescripter** [comment]
what if I do not want to use docker, and run locally on my server using pm2?

**Comment by rudism** [comment]
I can confirm this as well. I had API keys that I only supplied to a privately hosted instance of chatbot-ui via docker environment variables, and had large volumes of unauthorized use of those keys. It hit my OpenAI usage limits within a matter of hours on the first day of the month two months in a row even after deleting and recreating the API key. As soon as I stopped providing the keys to chatbot-ui the unauthorized usage stopped.

Looking through the code I didn't see any obvious vector for how they were leaked, but there is no other explanation.

**Comment by phiiil69** [comment]
> Be advised, If you follow the deployment instructions using Docker and host it remotely IT WILL LEAK your OpenAI API keys.

Hi, this can't happen when running locally, right?

**Comment by rudism** [comment]
@phiiil69 it depends. If the application or one of its npm dependencies has code in it somewhere that's actively detecting and sending the keys to a malicious outside party then it can happen in any environment where there's internet access.

In my case the chatbot-ui website was not exposed to the outside but my keys still got out somehow.

**Comment by mbos2** [comment]
If you suply the key via chatbot ui option, it ends up in localstorage, and we know how secure that is . . . 

Suply your keys via env or even better, secret managers to protect yourself better. 

Don't use ui option to add api key
