### ISSUE TITLE
takeoffchat - new lines issue

### ISSUE THREAD

**Issue by TBS-CL** [mckaywrigley/chatbot-ui#967]
Hi.
For some reason new lines are being eaten by the UI (takeoffchat), which breaks most of the responses where I need to copy paste the result with the list of items for example.

The bug works both ways, when I copy paste from Notepad++ for example, text gets merged into 1 line, and all the replies by AI also getting merged into 1 line, even if I ask it specifically to have it multiple lines..
![vivaldi_September 08 2023_13 09 12 16](https://github.com/mckaywrigley/chatbot-ui/assets/80581735/c7a5b679-f7b4-4466-82aa-f90dbeb5e0f2)
![vivaldi_September 08 2023_13 09 42 11](https://github.com/mckaywrigley/chatbot-ui/assets/80581735/158740fc-06e8-40db-b8b2-46ae6adddb5b)

**Comment by kyleroberts-ai** [comment]
Better reaching him on Twitter, this repo is abandoned and won't see it
