### ISSUE TITLE
Can someone please assist with how to reference the Azure deployments rather than the Model?

### ISSUE THREAD

**Issue by Phantom-309** [mckaywrigley/chatbot-ui#968]
I have 4 deployments of different models in Azure:
![azure_deployments](https://github.com/mckaywrigley/chatbot-ui/assets/65787288/60bd6db9-7555-4772-b466-93b85cf15510)
I'd like to see the deployment name rather than the model (which doesn't actually match up to the deployments from above anyway):
![chatbot-ui_model_selection](https://github.com/mckaywrigley/chatbot-ui/assets/65787288/aaba5b86-e801-4d8b-b33d-97fc0921ed8d)
Can anyone help please?

**Comment by riotrah** [comment]
You'll have to fork it and make those changes yourself. That's what I'm doing for our 2 deployments.

**Comment by standaloneSA** [comment]
I would also really like this.
