### ISSUE TITLE
When I'm using some third-party APIs, how can I add other supported models?

### ISSUE THREAD

**Issue by laogou717** [mckaywrigley/chatbot-ui#979]
When I'm using some third-party APIs, how can I add other supported models such as: gpt-3.5-turbo-0301, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k, and gpt-3.5-turbo-16k-0613?

**Comment by stelterlab** [comment]
Take a look at 

https://github.com/imoneoi/openchat-ui/blob/main/types/openai.ts

The OpenChat devs replaced it with their own models. They have their own OpenAI API compatible server.
