### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by ramicaza** [mckaywrigley/chatbot-ui#991]
I see chatui v2 is out but currently closed source. So does that mean this project has been abandoned and it's time to find new maintainers?

**Comment by ramicaza** [comment]
Also, any timeline for open sourcing v2? It's ok if the plan is to keep that closed source. But would be nice to know to determine whether it's worth finding maintainers for this project or just wait until that is open.

**Comment by henrywithu** [comment]
+1 same question

**Comment by bachittle** [comment]
considering the fact that the owner of this repo has been making commits in private repositories, hasn't been merging any of the PRs or adding new commits besides README promo, I'm afraid so. 

I wonder if there are any forks or new repositories that have more features. For example, the plugins feature could emulate what open-interpreter is doing and we could get code interpreters, web browsers, etc running in a web ui.

**Comment by kyleroberts-ai** [comment]
Hi,

Both of the repositories below are notable mentions:

https://github.com/jorge-menjivar/unSAGED 

https://github.com/dotneet/smart-chatbot-ui

**Comment by josh900** [comment]
Yes it would be very nice to know if v2 is ever coming as a foundation chat tool to build upon or if it is mostly closed source. I'm about done waiting to find out.

**Comment by Bortus-AI** [comment]
I second https://github.com/jorge-menjivar/unSAGED 
Works really well for me

**Comment by enricoros** [comment]
Try something different and fun - and we welcome devs :)
https://github.com/enricoros/big-agi

**Comment by bachittle** [comment]
This issue can be closed now, code has been refactored from the ground up to 2.0 today (all previous commits are gone). Let's hope this version can grow and foster an open-source community 😏

**Comment by VladislavAntonyuk** [comment]
I switched to https://yakgpt.vercel.app/
