### ISSUE TITLE
Message Truncation?

### ISSUE THREAD

**Issue by smallbirds4** [mckaywrigley/chatbot-ui#992]
Hey,

I am using this frontend and it works really well.

Except, it keeps on truncating the message from ChatGPT. I am using the models on Azure. Maybe I am not using the right API version, or something else?

![image](https://github.com/mckaywrigley/chatbot-ui/assets/145565180/3e6178ab-09cc-4d5e-889c-895e7b735c51)

**Comment by smallbirds4** [comment]
Could it maybe be related to the parameter for stream being "True" - and then it sometimes does not manage to complete the full message?

**Comment by dougdellolio** [comment]
this looks to be related to #580 . the fix for it is here: https://github.com/mckaywrigley/chatbot-ui/issues/580#issuecomment-1523023238
